import LeanRV64D
import Std.Tactic.BVDecide

/-!
# Oak's RV64 semantics against the Sail RISC-V model

`Oak.RiscV` (spec/lean/Oak/RiscV.lean) is the verifier's transliteration
of the instructions it decides. The Sail model is the ISA's golden model.
Each theorem below states that, for the register values an instruction
reads, the value the Sail model computes for the destination register (or
the branch decision it takes) is Oak's function of those values. The
generated `execute_*` bodies are `wX_bits rd <value>` around exactly the
expression on the left of each theorem (LeanRV64D/InstsEnd.lean:
`execute_RTYPEW`, `execute_RTYPE`, `execute_BTYPE`, `execute_ITYPE`,
`execute_SHIFTIOP`, `execute_SHIFTIWOP`, `execute_ADDIW`, `execute_MULW`,
`execute_MUL`, `execute_DIV`, `execute_REM`), so the theorems are the data
semantics of the instructions with the monadic register plumbing read off
by inspection. Covered: the register ALU and its W forms, the immediate
forms, the shifts by register and by immediate at both widths, the
comparisons, the six branches, the multiplies (both halves), and the
divisions and remainders with the ISA's totalization — every integer
instruction the verifier's tables decide except the W-form divisions
(`divw`, `divuw`, `remw`, `remuw`), whose Oak side is the 32-bit
totalization the Lean model does not yet state.

Built against the export of sail-riscv 497209b9 (2026-08-19) generated by
Sail from git (sail2 @ dba5f007) under lean-sail v5; see README.md.

The Oak definitions are restated verbatim (the OAK-DEF blocks);
`asm/rv64_sail_bridge_test.go` checks them against the specification's
file, so the two cannot drift.
-/

namespace OakSailBridge

open Sail
open LeanRV64D
open LeanRV64D.Functions

-- OAK-DEF-BEGIN
abbrev X := BitVec 64

/-- Sign-extend a 32-bit result to the register. -/
def sextW (v : BitVec 32) : X := v.signExtend 64

def addw (a b : X) : X := sextW (a.truncate 32 + b.truncate 32)
def subw (a b : X) : X := sextW (a.truncate 32 - b.truncate 32)
def mulw (a b : X) : X := sextW (a.truncate 32 * b.truncate 32)
def sllw (a b : X) : X := sextW (a.truncate 32 <<< (b.truncate 5).toNat)
def srlw (a b : X) : X := sextW (a.truncate 32 >>> (b.truncate 5).toNat)
def sraw (a b : X) : X := sextW ((a.truncate 32).sshiftRight (b.truncate 5).toNat)

def sll (a b : X) : X := a <<< (b.truncate 6).toNat
def srl (a b : X) : X := a >>> (b.truncate 6).toNat
def sra (a b : X) : X := a.sshiftRight (b.truncate 6).toNat

def slt (a b : X) : X := if a.slt b then 1 else 0
def sltu (a b : X) : X := if a.ult b then 1 else 0

/-- The high halves of the 128-bit products (`mulhu`, `mulh`): the operands
    zero- or sign-extended, as the verifier's `umulh`/`smulh` terms compute
    them (`asm/isa_semantics.go`). -/
def mulhu (a b : X) : X := ((a.zeroExtend 128 * b.zeroExtend 128) >>> 64).truncate 64
def mulh (a b : X) : X := ((a.signExtend 128 * b.signExtend 128) >>> 64).truncate 64

def divu (a b : X) : X := if b = 0 then BitVec.allOnes 64 else a / b
def remu (a b : X) : X := if b = 0 then a else a % b
def div (a b : X) : X :=
  if b = 0 then BitVec.allOnes 64
  else if a = BitVec.intMin 64 ∧ b = BitVec.allOnes 64 then a
  else a.sdiv b
def rem (a b : X) : X :=
  if b = 0 then a
  else if a = BitVec.intMin 64 ∧ b = BitVec.allOnes 64 then 0
  else a.srem b

inductive Br where
  | beq | bne | blt | bge | bltu | bgeu
  deriving DecidableEq, Repr

def Br.holds : Br → X → X → Bool
  | .beq, a, b => decide (a = b)
  | .bne, a, b => !decide (a = b)
  | .blt, a, b => a.slt b
  | .bge, a, b => !(a.slt b)
  | .bltu, a, b => a.ult b
  | .bgeu, a, b => !(a.ult b)
-- OAK-DEF-END

/-! ## RTYPEW: `execute_RTYPEW rs2 rs1 rd op` writes
    `sign_extend (m := 64) result` with `rs1_val = extractLsb x1 31 0`. -/

theorem addw_bridge (x1 x2 : X) :
    (sign_extend (m := 64) (Sail.BitVec.extractLsb x1 31 0 + Sail.BitVec.extractLsb x2 31 0)) = addw x1 x2 := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, addw, sextW]
  bv_decide

theorem subw_bridge (x1 x2 : X) :
    (sign_extend (m := 64) (Sail.BitVec.extractLsb x1 31 0 - Sail.BitVec.extractLsb x2 31 0)) = subw x1 x2 := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, subw, sextW]
  bv_decide

theorem sllw_bridge (x1 x2 : X) :
    (sign_extend (m := 64) (shift_bits_left (Sail.BitVec.extractLsb x1 31 0) (Sail.BitVec.extractLsb (Sail.BitVec.extractLsb x2 31 0) 4 0))) = sllw x1 x2 := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, shift_bits_left, sllw, sextW]
  bv_decide

theorem srlw_bridge (x1 x2 : X) :
    (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb x1 31 0) (Sail.BitVec.extractLsb (Sail.BitVec.extractLsb x2 31 0) 4 0))) = srlw x1 x2 := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, shift_bits_right, srlw, sextW]
  bv_decide

theorem sraw_bridge (x1 x2 : X) :
    (sign_extend (m := 64) (shift_bits_right_arith (Sail.BitVec.extractLsb x1 31 0) (Sail.BitVec.extractLsb (Sail.BitVec.extractLsb x2 31 0) 4 0))) = sraw x1 x2 := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, shift_bits_right_arith, Sail.BitVec.toNatInt, Int.toNat, sraw, sextW]
  bv_decide

/-! ## RTYPE: the comparisons write `zero_extend (bool_to_bit (op x1 x2))`. -/

theorem slt_bridge (x1 x2 : X) :
    (zero_extend (m := 64) (bool_to_bit (zopz0zI_s x1 x2))) = slt x1 x2 := by
  simp only [zero_extend, Sail.BitVec.zeroExtend, bool_to_bit, bool_bit_forwards, zopz0zI_s, slt, BitVec.slt]
  by_cases h : x1.toInt < x2.toInt <;> simp [h]

theorem sltu_bridge (x1 x2 : X) :
    (zero_extend (m := 64) (bool_to_bit (zopz0zI_u x1 x2))) = sltu x1 x2 := by
  simp only [zero_extend, Sail.BitVec.zeroExtend, bool_to_bit, bool_bit_forwards, zopz0zI_u, Sail.BitVec.toNatInt, sltu, BitVec.ult]
  by_cases h : x1.toNat < x2.toNat <;> simp [h]

/-! ## BTYPE: `taken` is the comparison; Oak's `Br.holds`. -/

theorem beq_bridge (x1 x2 : X) : (x1 == x2) = Br.holds .beq x1 x2 := rfl

theorem bne_bridge (x1 x2 : X) : (x1 != x2) = Br.holds .bne x1 x2 := rfl

theorem blt_bridge (x1 x2 : X) : zopz0zI_s x1 x2 = Br.holds .blt x1 x2 := by
  simp [zopz0zI_s, Br.holds, BitVec.slt]

theorem bge_bridge (x1 x2 : X) : zopz0zKzJ_s x1 x2 = Br.holds .bge x1 x2 := by
  simp only [zopz0zKzJ_s, Br.holds, BitVec.slt]
  cases h : decide (x1.toInt < x2.toInt) <;> simp_all <;> omega

theorem bltu_bridge (x1 x2 : X) : zopz0zI_u x1 x2 = Br.holds .bltu x1 x2 := by
  simp [zopz0zI_u, Sail.BitVec.toNatInt, Br.holds, BitVec.ult]

theorem bgeu_bridge (x1 x2 : X) : zopz0zKzJ_u x1 x2 = Br.holds .bgeu x1 x2 := by
  simp only [zopz0zKzJ_u, Sail.BitVec.toNatInt, Br.holds, BitVec.ult]
  cases h : decide (x1.toNat < x2.toNat) <;> simp_all <;> omega


/-! ## RTYPE: the register ALU, `execute_RTYPE`'s other arms. The shift
    count is the low `log2_xlen = 6` bits of rs2, as Oak's `sll`/`srl`/`sra`
    truncate it. -/

theorem add_bridge (x1 x2 : X) : (x1 + x2) = x1 + x2 := rfl
theorem sub_bridge (x1 x2 : X) : (x1 - x2) = x1 - x2 := rfl
theorem and_bridge (x1 x2 : X) : (x1 &&& x2) = x1 &&& x2 := rfl
theorem or_bridge (x1 x2 : X) : (x1 ||| x2) = x1 ||| x2 := rfl
theorem xor_bridge (x1 x2 : X) : (x1 ^^^ x2) = x1 ^^^ x2 := rfl

theorem sll_bridge (x1 x2 : X) :
    shift_bits_left x1 (Sail.BitVec.extractLsb x2 (Functions.log2_xlen -i 1) 0) = sll x1 x2 := by
  show shift_bits_left x1 (Sail.BitVec.extractLsb x2 5 0) = sll x1 x2
  simp only [shift_bits_left, Sail.BitVec.extractLsb, sll]
  bv_decide

theorem srl_bridge (x1 x2 : X) :
    shift_bits_right x1 (Sail.BitVec.extractLsb x2 (Functions.log2_xlen -i 1) 0) = srl x1 x2 := by
  show shift_bits_right x1 (Sail.BitVec.extractLsb x2 5 0) = srl x1 x2
  simp only [shift_bits_right, Sail.BitVec.extractLsb, srl]
  bv_decide

theorem sra_bridge (x1 x2 : X) :
    shift_bits_right_arith x1 (Sail.BitVec.extractLsb x2 (Functions.log2_xlen -i 1) 0) = sra x1 x2 := by
  show shift_bits_right_arith x1 (Sail.BitVec.extractLsb x2 5 0) = sra x1 x2
  simp only [shift_bits_right_arith, Sail.BitVec.extractLsb, Sail.BitVec.toNatInt, Int.toNat, sra]
  bv_decide

/-! ## ITYPE: the immediate sign-extended to the register, then the RTYPE
    operation; the verifier's constant term is that sign extension. -/

theorem addi_bridge (x1 : X) (imm : BitVec 12) :
    (x1 + sign_extend (m := 64) imm) = x1 + imm.signExtend 64 := rfl
theorem andi_bridge (x1 : X) (imm : BitVec 12) :
    (x1 &&& sign_extend (m := 64) imm) = x1 &&& imm.signExtend 64 := rfl
theorem ori_bridge (x1 : X) (imm : BitVec 12) :
    (x1 ||| sign_extend (m := 64) imm) = x1 ||| imm.signExtend 64 := rfl
theorem xori_bridge (x1 : X) (imm : BitVec 12) :
    (x1 ^^^ sign_extend (m := 64) imm) = x1 ^^^ imm.signExtend 64 := rfl

theorem slti_bridge (x1 : X) (imm : BitVec 12) :
    (zero_extend (m := 64) (bool_to_bit (zopz0zI_s x1 (sign_extend (m := 64) imm)))) = slt x1 (imm.signExtend 64) :=
  slt_bridge x1 _

theorem sltiu_bridge (x1 : X) (imm : BitVec 12) :
    (zero_extend (m := 64) (bool_to_bit (zopz0zI_u x1 (sign_extend (m := 64) imm)))) = sltu x1 (imm.signExtend 64) :=
  sltu_bridge x1 _

/-! ## SHIFTIOP and SHIFTIWOP: shifts by an immediate count; the count is
    the verifier's constant, zero-extended to the register. -/

theorem slli_bridge (x1 : X) (shamt : BitVec 6) :
    shift_bits_left x1 (Sail.BitVec.extractLsb shamt (Functions.log2_xlen -i 1) 0) = sll x1 (shamt.zeroExtend 64) := by
  show shift_bits_left x1 (Sail.BitVec.extractLsb shamt 5 0) = sll x1 (shamt.zeroExtend 64)
  simp only [shift_bits_left, Sail.BitVec.extractLsb, sll]
  bv_decide

theorem srli_bridge (x1 : X) (shamt : BitVec 6) :
    shift_bits_right x1 (Sail.BitVec.extractLsb shamt (Functions.log2_xlen -i 1) 0) = srl x1 (shamt.zeroExtend 64) := by
  show shift_bits_right x1 (Sail.BitVec.extractLsb shamt 5 0) = srl x1 (shamt.zeroExtend 64)
  simp only [shift_bits_right, Sail.BitVec.extractLsb, srl]
  bv_decide

theorem srai_bridge (x1 : X) (shamt : BitVec 6) :
    shift_bits_right_arith x1 (Sail.BitVec.extractLsb shamt (Functions.log2_xlen -i 1) 0) = sra x1 (shamt.zeroExtend 64) := by
  show shift_bits_right_arith x1 (Sail.BitVec.extractLsb shamt 5 0) = sra x1 (shamt.zeroExtend 64)
  simp only [shift_bits_right_arith, Sail.BitVec.extractLsb, Sail.BitVec.toNatInt, Int.toNat, sra]
  bv_decide

theorem slliw_bridge (x1 : X) (shamt : BitVec 5) :
    (sign_extend (m := 64) (shift_bits_left (Sail.BitVec.extractLsb x1 31 0) shamt)) = sllw x1 (shamt.zeroExtend 64) := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, shift_bits_left, sllw, sextW]
  bv_decide

theorem srliw_bridge (x1 : X) (shamt : BitVec 5) :
    (sign_extend (m := 64) (shift_bits_right (Sail.BitVec.extractLsb x1 31 0) shamt)) = srlw x1 (shamt.zeroExtend 64) := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, shift_bits_right, srlw, sextW]
  bv_decide

theorem sraiw_bridge (x1 : X) (shamt : BitVec 5) :
    (sign_extend (m := 64) (shift_bits_right_arith (Sail.BitVec.extractLsb x1 31 0) shamt)) = sraw x1 (shamt.zeroExtend 64) := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, shift_bits_right_arith, Sail.BitVec.toNatInt, Int.toNat, sraw, sextW]
  bv_decide

/-! ## ADDIW: `addw` with the sign-extended immediate. -/

theorem addiw_bridge (x1 : X) (imm : BitVec 12) :
    (sign_extend (m := 64) (Sail.BitVec.extractLsb (x1 + sign_extend (m := 64) imm) 31 0)) = addw x1 (imm.signExtend 64) := by
  simp only [sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, addw, sextW]
  bv_decide


/-! ## MULW: the model multiplies the 32-bit halves as integers and
    truncates; `BitVec.ofInt` is a ring homomorphism, so that is the 32-bit
    product Oak's `mulw` computes. -/

/-- `to_bits_truncate` at a literal width is `BitVec.ofInt`: the low bits of
    the integer (`get_slice_int` slices a one-bit-wider `ofInt`). -/
theorem to_bits_truncate_32 (n : Int) : to_bits_truncate (l := 32) n = BitVec.ofInt 32 n := by
  apply BitVec.eq_of_toNat_eq
  rw [to_bits_truncate, get_slice_int, BitVec.extractLsb'_toNat, BitVec.toNat_ofInt, BitVec.toNat_ofInt]
  simp only [Nat.shiftRight_zero, Nat.reduceAdd, Nat.reducePow]
  omega

theorem mulw_bridge (x1 x2 : X) :
    (sign_extend (m := 64) (to_bits_truncate (l := 32) ((BitVec.toInt (Sail.BitVec.extractLsb x1 31 0)) *i (BitVec.toInt (Sail.BitVec.extractLsb x2 31 0))))) = mulw x1 x2 := by
  simp only [to_bits_truncate_32, BitVec.ofInt_mul, BitVec.ofInt_toInt, sign_extend, Sail.BitVec.signExtend, Sail.BitVec.extractLsb, mulw, sextW]
  bv_decide


/-! ## MUL: the low half of the 128-bit product of the sign-extended
    operands is the 64-bit product — the verifier's `mul`. -/

theorem to_bits_truncate_128 (n : Int) : to_bits_truncate (l := 128) n = BitVec.ofInt 128 n := by
  apply BitVec.eq_of_toNat_eq
  rw [to_bits_truncate, get_slice_int, BitVec.extractLsb'_toNat, BitVec.toNat_ofInt, BitVec.toNat_ofInt]
  simp only [Nat.shiftRight_zero, Nat.reduceAdd, Nat.reducePow]
  omega

/-- `BitVec.ofInt` at a wider width is the sign extension. -/
theorem ofInt_toInt_128 (x : X) : BitVec.ofInt 128 x.toInt = x.signExtend 128 := by
  apply BitVec.eq_of_toNat_eq
  rw [BitVec.toNat_ofInt, BitVec.toNat_signExtend, BitVec.toInt_eq_msb_cond]
  have := x.isLt
  cases h : x.msb <;> simp only [h, BitVec.toNat_setWidth, Bool.false_eq_true, if_true, if_false, Nat.reducePow] at * <;> omega

theorem low_half (y : BitVec 128) : Sail.BitVec.extractLsb y 63 0 = y.setWidth 64 := by
  simp only [Sail.BitVec.extractLsb]
  bv_decide

theorem mul_bridge (x1 x2 : X) :
    mult_to_bits_half (l := Functions.xlen) .Signed .Signed x1 x2 .Low = x1 * x2 := by
  show Sail.BitVec.extractLsb (to_bits_truncate (l := 128) (x1.toInt * x2.toInt)) 63 0 = x1 * x2
  rw [to_bits_truncate_128, BitVec.ofInt_mul, ofInt_toInt_128, ofInt_toInt_128, low_half,
    BitVec.setWidth_mul _ _ (by decide)]
  have h : ∀ x : X, (x.signExtend 128).setWidth 64 = x := by intro x; bv_decide
  rw [h, h]


/-! ## MULH and MULHU: the high half of the 128-bit product. -/

theorem high_half (y : BitVec 128) : Sail.BitVec.extractLsb y 127 64 = (y >>> 64).truncate 64 := by
  simp only [Sail.BitVec.extractLsb]
  bv_decide

theorem ofNat_toNat_128 (x : X) : BitVec.ofInt 128 (BitVec.toNatInt x) = x.zeroExtend 128 := by
  simp only [Sail.BitVec.toNatInt, Int.ofNat_eq_natCast, BitVec.ofInt_natCast]
  apply BitVec.eq_of_toNat_eq
  simp only [BitVec.toNat_ofNat, BitVec.toNat_setWidth]

theorem mulh_bridge (x1 x2 : X) :
    mult_to_bits_half (l := Functions.xlen) .Signed .Signed x1 x2 .High = mulh x1 x2 := by
  show Sail.BitVec.extractLsb (to_bits_truncate (l := 128) (x1.toInt * x2.toInt)) 127 64 = mulh x1 x2
  rw [to_bits_truncate_128, BitVec.ofInt_mul, ofInt_toInt_128, ofInt_toInt_128, high_half, mulh]

theorem mulhu_bridge (x1 x2 : X) :
    mult_to_bits_half (l := Functions.xlen) .Unsigned .Unsigned x1 x2 .High = mulhu x1 x2 := by
  show Sail.BitVec.extractLsb (to_bits_truncate (l := 128) (BitVec.toNatInt x1 * BitVec.toNatInt x2)) 127 64 = mulhu x1 x2
  rw [to_bits_truncate_128, BitVec.ofInt_mul, ofNat_toNat_128, ofNat_toNat_128, high_half, mulhu]

/-! ## DIV and REM: the model divides on `Int` with the ISA's totalization
    (a zero divisor yields all ones or the dividend; the signed overflow the
    minimum), truncating the result to the register. `sailDiv` and `sailRem`
    are the pure bodies of `execute_DIV` and `execute_REM` after the two
    register reads, with `is_unsigned` the instruction's flag. -/

def sailDiv (is_unsigned : Bool) (rs1_bits rs2_bits : X) : X :=
  let rs1_int :=
    if (is_unsigned : Bool)
    then (BitVec.toNatInt rs1_bits)
    else (BitVec.toInt rs1_bits)
  let rs2_int :=
    if (is_unsigned : Bool)
    then (BitVec.toNatInt rs2_bits)
    else (BitVec.toInt rs2_bits)
  let quotient :=
    if ((rs2_int == 0) : Bool)
    then (Neg.neg 1)
    else (Int.tdiv rs1_int rs2_int)
  let quotient :=
    if (((Functions.not is_unsigned) && (quotient ≥b (2 ^i (Functions.xlen -i 1)))) : Bool)
    then (Neg.neg (2 ^i (Functions.xlen -i 1)))
    else quotient
  to_bits_truncate (l := 64) quotient

def sailRem (is_unsigned : Bool) (rs1_bits rs2_bits : X) : X :=
  let rs1_int :=
    if (is_unsigned : Bool)
    then (BitVec.toNatInt rs1_bits)
    else (BitVec.toInt rs1_bits)
  let rs2_int :=
    if (is_unsigned : Bool)
    then (BitVec.toNatInt rs2_bits)
    else (BitVec.toInt rs2_bits)
  let remainder :=
    if ((rs2_int == 0) : Bool)
    then rs1_int
    else (Int.tmod rs1_int rs2_int)
  to_bits_truncate (l := 64) remainder

theorem to_bits_truncate_64 (n : Int) : to_bits_truncate (l := 64) n = BitVec.ofInt 64 n := by
  apply BitVec.eq_of_toNat_eq
  rw [to_bits_truncate, get_slice_int, BitVec.extractLsb'_toNat, BitVec.toNat_ofInt, BitVec.toNat_ofInt]
  simp only [Nat.shiftRight_zero, Nat.reduceAdd, Nat.reducePow]
  omega

/-- A quotient's balanced residue and the quotient itself name one word. -/
theorem ofInt_bmod_64 (n : Int) : BitVec.ofInt 64 (n.bmod (2 ^ 64)) = BitVec.ofInt 64 n := by
  apply BitVec.eq_of_toNat_eq
  rw [BitVec.toNat_ofInt, BitVec.toNat_ofInt]
  simp only [Nat.reducePow, Int.bmod_emod]

theorem toNat_ne_zero_of_ne (x : X) (h : x ≠ 0) : (x.toNat : Int) ≠ 0 := by
  intro hz; apply h; apply BitVec.eq_of_toNat_eq; simp; omega

theorem toInt_ne_zero_of_ne (x : X) (h : x ≠ 0) : x.toInt ≠ 0 := by
  intro hz; apply h
  have := BitVec.toInt_eq_toNat_cond x
  apply BitVec.eq_of_toNat_eq; simp
  split at this <;> omega

theorem divu_bridge (x1 x2 : X) : sailDiv true x1 x2 = divu x1 x2 := by
  simp only [sailDiv, divu, Functions.not, Bool.not_true, Bool.false_and, Bool.false_eq_true, ↓reduceIte,
    to_bits_truncate_64, Sail.BitVec.toNatInt, Int.ofNat_eq_natCast, beq_iff_eq]
  by_cases h : x2 = 0
  · subst h; simp
  · simp only [h, toNat_ne_zero_of_ne x2 h, ↓reduceIte]
    rw [← Int.ofNat_tdiv, BitVec.ofInt_natCast]
    apply BitVec.eq_of_toNat_eq
    rw [BitVec.toNat_ofNat, BitVec.toNat_udiv]
    exact Nat.mod_eq_of_lt (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) x1.isLt)

theorem remu_bridge (x1 x2 : X) : sailRem true x1 x2 = remu x1 x2 := by
  simp only [sailRem, remu, ↓reduceIte, to_bits_truncate_64, Sail.BitVec.toNatInt, Int.ofNat_eq_natCast, beq_iff_eq]
  by_cases h : x2 = 0
  · subst h; simp
  · simp only [h, toNat_ne_zero_of_ne x2 h, ↓reduceIte]
    rw [← Int.ofNat_tmod, BitVec.ofInt_natCast]
    apply BitVec.eq_of_toNat_eq
    rw [BitVec.toNat_ofNat, BitVec.toNat_umod]
    exact Nat.mod_eq_of_lt (Nat.lt_of_le_of_lt (Nat.mod_le _ _) x1.isLt)

theorem rem_bridge (x1 x2 : X) : sailRem false x1 x2 = rem x1 x2 := by
  simp only [sailRem, rem, Bool.false_eq_true, ↓reduceIte, to_bits_truncate_64, beq_iff_eq]
  by_cases h : x2 = 0
  · subst h; simp
  · simp only [h, toInt_ne_zero_of_ne x2 h, ↓reduceIte]
    by_cases hm : x1 = BitVec.intMin 64 ∧ x2 = BitVec.allOnes 64
    · obtain ⟨h1, h2'⟩ := hm; subst h1; subst h2'; decide
    · simp only [hm, ↓reduceIte]
      rw [← BitVec.toInt_srem, BitVec.ofInt_toInt]

theorem div_bridge (x1 x2 : X) : sailDiv false x1 x2 = div x1 x2 := by
  simp only [sailDiv, div, Functions.not, Bool.not_false, Bool.true_and, Bool.false_eq_true, ↓reduceIte,
    to_bits_truncate_64, beq_iff_eq]
  have hpow : (2 : Int) ^ ((Functions.xlen : Int) - 1) = 9223372036854775808 := by rfl
  simp only [hpow, decide_eq_true_eq]
  by_cases h : x2 = 0
  · subst h; simp
  · simp only [h, toInt_ne_zero_of_ne x2 h, ↓reduceIte]
    by_cases hm : x1 = BitVec.intMin 64 ∧ x2 = BitVec.allOnes 64
    · obtain ⟨h1, h2'⟩ := hm; subst h1; subst h2'; decide
    · simp only [hm, ↓reduceIte]
      have hsdiv : x1.sdiv x2 = BitVec.ofInt 64 (x1.toInt.tdiv x2.toInt) := by
        rw [← ofInt_bmod_64, ← BitVec.toInt_sdiv, BitVec.ofInt_toInt]
      rw [hsdiv]
      have hle := Int.natAbs_tdiv_le_natAbs x1.toInt x2.toInt
      have hlt := BitVec.toInt_lt (x := x1)
      have hge := BitVec.le_toInt (x := x1)
      split
      · rename_i hq
        have hq' : x1.toInt.tdiv x2.toInt = 9223372036854775808 := by omega
        rw [hq']; decide
      · rfl

end OakSailBridge
