// Package lean extracts a bounded imperative Oak subset into Lean 4
// definitions (docs/spec/95-extraction.md). The output is the shallow
// embedding the verification experiment's hand-written models use, produced
// mechanically from the type-checked program: every fixed-width integer is
// the Lean UInt of that width (wrapping arithmetic, exactly Oak's), every
// array, view, and span is an Array value, every function returns an Option
// of its result together with the spans it wrote, every while loop is a
// fuel-indexed structurally recursive helper, and every conditional is an
// if over the variables the branches assign. Anything outside the subset
// is an error, never an approximation.
//
// Two modeling choices are deliberate and stated: an out-of-range read
// yields the element type's zero and an out-of-range write is dropped where
// Oak would trap, and division by zero yields zero where Oak would trap.
// Both are sound for the refinement direction the experiment proves — an Oak
// run that produced a result took no trapping path, and on such runs the
// model computes the same values — and both are what the experiment's
// hand-written models already assume.
package lean

import (
	"fmt"
	"math"
	"sort"
	"strings"

	"github.com/SCKelemen/oak/ast"
	"github.com/SCKelemen/oak/typechecker"
)

// Emit extracts the named declarations of program (all of them when names is
// nil) into one Lean module body under the given namespace.
func Emit(program *ast.Program, tc *typechecker.TypeChecker, namespace string, names map[string]bool) (string, error) {
	em := &emitter{
		tc:          tc,
		env:         tc.Env(),
		adts:        map[string]*ast.ADTType{},
		records:     map[string]*ast.ADTType{},
		usedTypes:   map[string]bool{},
		leanNames:   map[string]string{},
		functions:   map[string]*ast.FunctionStatement{},
		globals:     map[string]*ast.VariableDeclaration{},
		usedGlobals: map[string]bool{},
	}
	em.collectTypes(program)
	for _, stmt := range program.Statements {
		if decl, ok := stmt.(*ast.VariableDeclaration); ok && decl.Name != nil && decl.Value != nil {
			em.globals[decl.Name.Value] = decl
			em.globalOrder = append(em.globalOrder, decl.Name.Value)
		}
	}
	for name, adt := range em.adts {
		if len(adt.TypeParams) == 0 {
			em.leanNames[ident(name)] = name
		}
	}
	// Every ordinary function is a candidate; the ones outside the subset
	// fail closed only when the extraction reaches them.
	candidates := map[string]*ast.FunctionStatement{}
	var declared []string
	for _, stmt := range program.Statements {
		if fn, ok := stmt.(*ast.FunctionStatement); ok && fn.Name != nil {
			candidates[fn.Name.Value] = fn
			declared = append(declared, fn.Name.Value)
		}
	}
	// The roots are the named declarations (all of them when names is
	// nil); the extraction closes over their callees, so a program that
	// calls into the standard library extracts the library functions it
	// uses (docs/spec/95-extraction.md section 4).
	var functionOrder []string
	queue := []string{}
	for _, name := range declared {
		if names == nil || names[name] {
			queue = append(queue, name)
		}
	}
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if _, done := em.functions[name]; done {
			continue
		}
		fn := candidates[name]
		if fn.Receiver != nil || len(fn.TypeParams) != 0 || fn.ExternSymbol != "" || fn.Body == nil {
			return "", fmt.Errorf("lean: %s: methods, generics, and extern functions are outside the extracted subset", name)
		}
		em.functions[name] = fn
		functionOrder = append(functionOrder, name)
		for _, callee := range em.callees(fn) {
			if _, known := candidates[callee]; known {
				queue = append(queue, callee)
			}
		}
	}
	ordered, err := em.dependencyOrder(functionOrder)
	if err != nil {
		return "", err
	}
	var functions strings.Builder
	for _, name := range ordered {
		text, err := em.emitFunction(em.functions[name])
		if err != nil {
			return "", err
		}
		functions.WriteString(text)
		functions.WriteString("\n")
	}
	globalsText, err := em.emitGlobals()
	if err != nil {
		return "", err
	}
	typeRoots := map[string]bool{}
	for name := range em.adts {
		if names == nil || names[name] {
			typeRoots[name] = true
		}
	}
	var out strings.Builder
	out.WriteString("-- Generated by the Oak compiler (codegen/lean): do not edit.\n")
	out.WriteString("-- Extracted from the type-checked program; docs/spec/95-extraction.md\n")
	out.WriteString("-- states the translation and its modeling choices.\n\n")
	for _, name := range ordered {
		if em.functions[name].Theorem {
			// Theorem statements try bv_decide, which lives outside Init.
			out.WriteString("import Std.Tactic.BVDecide\n\n")
			break
		}
	}
	if em.usesFloatOps {
		out.WriteString("import Oak.FloatOps\n\n")
	}
	if em.usesUtf8 {
		out.WriteString("import Oak.Utf8Exec\n\n")
	}
	out.WriteString("set_option autoImplicit false\n")
	// Straight-line translation rebinds and returns variables the source
	// never reads again; that is the source's shape, not a defect.
	out.WriteString("set_option linter.unusedVariables false\n")
	// An unrolled function (a hash compression round) is one long do-block;
	// the elaborator's default recursion limit is sized for hand-written code.
	out.WriteString("set_option maxRecDepth 65536\n")
	// The code generator's budget is sized the same way; an unrolled
	// compression function is one definition with hundreds of binds.
	out.WriteString("set_option maxHeartbeats 4000000\n")
	fmt.Fprintf(&out, "namespace %s\n\n", namespace)
	for _, name := range ordered {
		if em.functions[name].Theorem {
			// The lemma the theorem scripts use to push a bind through a
			// construction's guard (docs/spec/125-verification.md §5).
			out.WriteString("theorem oak_bind_ite {α β : Type} (c : Prop) [Decidable c] (a : α) (f : α → Option β) :\n")
			out.WriteString("    (if c then some a else none).bind f = if c then f a else none := by\n")
			out.WriteString("  split <;> rfl\n\n")
			break
		}
	}
	for _, name := range em.orderedTypes(typeRoots) {
		adt := em.adts[name]
		var text string
		if isRecordADT(adt) {
			text, err = em.emitRecord(adt)
		} else {
			text, err = em.emitSum(adt)
		}
		if err != nil {
			return "", err
		}
		out.WriteString(text)
		out.WriteString("\n")
	}
	out.WriteString(globalsText)
	out.WriteString(functions.String())
	fmt.Fprintf(&out, "end %s\n", namespace)
	return out.String(), nil
}

// emitGlobals renders the top-level constants the extracted functions
// read, in declaration order, closing over the constants they mention. A
// global initializer is a pure term: one that needs a call fails closed.
func (em *emitter) emitGlobals() (string, error) {
	rendered := map[string]string{}
	for {
		progressed := false
		for _, name := range em.globalOrder {
			if !em.usedGlobals[name] || rendered[name] != "" {
				continue
			}
			decl := em.globals[name]
			var typ string
			var err error
			if decl.Type != nil {
				typ, err = em.leanType(decl.Type)
			} else if declared := em.env.CheckedDeclarationType(decl); declared != nil {
				typ, err = em.leanTypeOf(declared)
			} else {
				err = fmt.Errorf("global %s has no type", name)
			}
			if err != nil {
				return "", fmt.Errorf("lean: %w", err)
			}
			if _, isTargetConstant := typechecker.TargetConstantCall(decl.Value); isTargetConstant {
				// A target constant (docs/spec/92-ffi.md section 2.11) is a
				// value the target's C headers define; the extraction knows
				// only its type, so it is an uninterpreted constant and a
				// theorem about code reading it holds for every value
				// (95-extraction.md section 3).
				rendered[name] = fmt.Sprintf("opaque %s : %s\n\n", ident(name), typ)
				progressed = true
				continue
			}
			em.fnName = name
			em.scope = newScope(nil)
			var hoisted []string
			em.hoisted = &hoisted
			term, err := em.expr(decl.Value, typ)
			em.hoisted = nil
			if err != nil {
				return "", fmt.Errorf("lean: global %s: %w", name, err)
			}
			if len(hoisted) != 0 {
				return "", fmt.Errorf("lean: global %s: an initializer that calls a function is outside the extracted subset", name)
			}
			rendered[name] = fmt.Sprintf("def %s : %s := %s\n\n", ident(name), typ, term)
			progressed = true
		}
		if !progressed {
			break
		}
	}
	var out strings.Builder
	for _, name := range em.globalOrder {
		out.WriteString(rendered[name])
	}
	return out.String(), nil
}

type emitter struct {
	tc  *typechecker.TypeChecker
	env *typechecker.TypeEnvironment
	// valueBinding is the Lean name `value` reads as while a refinement's
	// predicate is rendered (predicateTerm); empty otherwise.
	valueBinding string
	// recursive marks the functions that call themselves; they extract by
	// structural recursion on the fuel (docs/spec/95-extraction.md §2).
	recursive map[string]bool
	// adts holds every ADT declaration of the program plus every recorded
	// generic instantiation, specialized; templates are never emitted.
	adts      map[string]*ast.ADTType
	typeOrder []string
	// records is the record-shaped subset of adts (one field-list variant).
	records   map[string]*ast.ADTType
	usedTypes map[string]bool
	// leanNames maps a Lean type name back to the ADT it renders.
	leanNames map[string]string
	functions map[string]*ast.FunctionStatement
	// globals holds the program's initialized top-level bindings; the ones
	// the extracted functions read are emitted as Lean definitions.
	globals     map[string]*ast.VariableDeclaration
	globalOrder []string
	usedGlobals map[string]bool
	// usesFloatOps records a call to fma, copysign, or round_even, whose
	// bit-exact carriers live in Oak.FloatOps rather than in Lean's core.
	usesFloatOps bool
	// usesUtf8 records a call to is_valid_utf8, decided over the carrier by
	// Oak.Utf8Exec.valid (docs/spec/95-extraction.md section 3).
	usesUtf8 bool

	// Per-function state.
	fnName  string
	scope   *scope
	helpers []string // loop helpers, innermost first
	loops   int
	temps   int
	// hoisted collects the do-lines a statement's expressions need before
	// the statement itself (calls bound with <-).
	hoisted *[]string
	indent  string
}

// scope is the ordered set of Lean-visible variables with their Lean types.
type scope struct {
	names   []string
	types   map[string]string
	aliases map[string]spanAlias
	outer   *scope
}

// spanAlias records that a writable span variable is a window of another
// array in scope: `s: [*]T = owner[lo:hi]` or `s: [*]T = span(&owner)`.
// In Oak the window aliases the owner's storage; the extraction models it
// as a copy, so every write to the alias is written back into the owner
// (docs/spec/95-extraction.md section 2). low is the Lean variable holding
// the window's start; whole marks a span of the entire owner.
type spanAlias struct {
	owner string
	low   string
	whole bool
}

func newScope(outer *scope) *scope {
	return &scope{types: map[string]string{}, aliases: map[string]spanAlias{}, outer: outer}
}

func (s *scope) declareAlias(name string, alias spanAlias) { s.aliases[name] = alias }

// alias finds the window a span variable was declared as, if any.
func (s *scope) alias(name string) (spanAlias, bool) {
	for cur := s; cur != nil; cur = cur.outer {
		if a, ok := cur.aliases[name]; ok {
			return a, true
		}
	}
	return spanAlias{}, false
}

func (s *scope) declare(name, typ string) {
	if _, exists := s.types[name]; !exists {
		s.names = append(s.names, name)
	}
	s.types[name] = typ
}

func (s *scope) lookup(name string) (string, bool) {
	for cur := s; cur != nil; cur = cur.outer {
		if typ, ok := cur.types[name]; ok {
			return typ, true
		}
	}
	return "", false
}

// ordered lists every visible variable, outermost scope first.
func (s *scope) ordered() []string {
	if s == nil {
		return nil
	}
	return append(s.outer.ordered(), s.names...)
}

// dependencyOrder sorts functions so callees precede callers; recursion is
// outside the subset.
func (em *emitter) dependencyOrder(names []string) ([]string, error) {
	var ordered []string
	state := map[string]int{}
	var visit func(name string, path []string) error
	visit = func(name string, path []string) error {
		switch state[name] {
		case 2:
			return nil
		case 1:
			return fmt.Errorf("lean: recursive functions are outside the extracted subset: %s", strings.Join(append(path, name), " -> "))
		}
		state[name] = 1
		for _, callee := range em.callees(em.functions[name]) {
			if callee == name {
				// Direct self-recursion extracts by structural recursion on
				// the fuel (emitFunction); mutual recursion still fails closed.
				if em.recursive == nil {
					em.recursive = map[string]bool{}
				}
				em.recursive[name] = true
				continue
			}
			if _, known := em.functions[callee]; known {
				if err := visit(callee, append(path, name)); err != nil {
					return err
				}
			}
		}
		state[name] = 2
		ordered = append(ordered, name)
		return nil
	}
	for _, name := range names {
		if err := visit(name, nil); err != nil {
			return nil, err
		}
	}
	return ordered, nil
}

func (em *emitter) callees(fn *ast.FunctionStatement) []string {
	seen := map[string]bool{}
	var names []string
	walkExpressions(fn.Body, func(e ast.Expression) {
		if call, ok := e.(*ast.InvocationExpression); ok {
			if ident, ok := call.Function.(*ast.Identifier); ok && !seen[ident.Value] {
				seen[ident.Value] = true
				names = append(names, ident.Value)
			}
		}
	})
	sort.Strings(names)
	return names
}

// ---- types ----

// cScalarLean renders the c.* integer scalars a target constant may carry
// (docs/spec/92-ffi.md section 2.11) at the widths of the section 2.4
// target model, LP64: int is 32 bits, long and size_t 64.
var cScalarLean = map[string]string{
	"c.Int": "Int32", "c.UInt": "UInt32", "c.Int32": "Int32", "c.UInt32": "UInt32",
	"c.Int64": "Int64", "c.UInt64": "UInt64", "c.Long": "Int64", "c.ULong": "UInt64", "c.Size": "UInt64",
}

var primitiveLean = map[string]string{
	"u8": "UInt8", "u16": "UInt16", "u32": "UInt32", "u64": "UInt64",
	"i8": "Int8", "i16": "Int16", "i32": "Int32", "i64": "Int64",
	"Bool": "Bool", "()": "Unit",
	// f32 and f64 are Lean's Float32 and Float: the host's binary32 and
	// binary64 (docs/spec/95-extraction.md section 3).
	"f32": "Float32", "f64": "Float",
}

// leanType renders an Oak type expression.
func (em *emitter) leanType(expr ast.Expression) (string, error) {
	switch t := expr.(type) {
	case *ast.Identifier:
		if lean, ok := primitiveLean[t.Value]; ok {
			return lean, nil
		}
		// A refinement type is its base's representation
		// (docs/spec/20-types.md section 12); the predicate is stated at
		// each construction and as a hypothesis of each theorem.
		if base, _, isRefinement := em.tc.Refinement(t.Value); isRefinement {
			if lean, ok := primitiveLean[base]; ok {
				return lean, nil
			}
		}
		if lean, ok := em.adtLeanName(t.Value); ok {
			return lean, nil
		}
		if lean, ok := cScalarLean[t.Value]; ok {
			// The c.* integer scalars, at the widths of the §2.4 target
			// model (LP64: long and size_t are 64 bits); they appear as
			// the types of target constants.
			return lean, nil
		}
		return "", fmt.Errorf("lean: type %s is outside the extracted subset", t.Value)
	case *ast.IndexExpression:
		if t.Dot {
			return "", fmt.Errorf("lean: qualified type %s is outside the extracted subset", t.String())
		}
		// A generic ADT applied to its arguments is the recorded
		// instantiation under its mangled name.
		if mangled, isApplication := em.applicationName(t); isApplication {
			if lean, ok := em.adtLeanName(mangled); ok {
				return lean, nil
			}
			return "", fmt.Errorf("lean: instantiation %s was not recorded by the checker", t.String())
		}
		// [N]T, []T, [*]T all become Array T.
		element, err := em.leanType(t.Left)
		if err != nil {
			return "", err
		}
		return "Array " + element, nil
	}
	return "", fmt.Errorf("lean: type %s is outside the extracted subset", expr.String())
}

// leanTypeOf renders a checked type.
func (em *emitter) leanTypeOf(typ typechecker.Type) (string, error) {
	switch t := typ.(type) {
	case *typechecker.PrimitiveType:
		if lean, ok := primitiveLean[t.Name]; ok {
			return lean, nil
		}
		if lean, ok := primitiveLean[normalizePrimitive(t.Name)]; ok {
			return lean, nil
		}
	case *typechecker.BoolType:
		return "Bool", nil
	case *typechecker.UnitType:
		return "Unit", nil
	case *typechecker.ArrayType:
		element, err := em.leanTypeOf(t.ElementType)
		if err != nil {
			return "", err
		}
		return "Array " + element, nil
	case *typechecker.RecordType:
		if t.Name != "" {
			if lean, ok := em.adtLeanName(t.Name); ok {
				return lean, nil
			}
			return ident(t.Name), nil
		}
	case *typechecker.ADTType, *typechecker.GenericType, *typechecker.NarrowedADTVariantType:
		if name, ok := em.adtOfChecked(t); ok {
			if lean, isADT := em.adtLeanName(name); isADT {
				return lean, nil
			}
		}
	}
	return "", fmt.Errorf("lean: checked type %v is outside the extracted subset", typ)
}

func normalizePrimitive(name string) string {
	switch name {
	case "byte":
		return "u8"
	case "rune":
		return "u32"
	}
	return name
}

// zeroOf is the default value of a Lean type.
func zeroOf(leanType string) string {
	switch {
	case leanType == "Bool":
		return "false"
	case leanType == "Unit":
		return "()"
	case strings.HasPrefix(leanType, "UInt") || strings.HasPrefix(leanType, "Int"):
		return "(0 : " + leanType + ")"
	case isFloatLean(leanType):
		return "(" + leanType + ".ofBits 0)"
	case strings.HasPrefix(leanType, "Array "):
		return "(#[] : " + leanType + ")"
	default:
		return "(default : " + leanType + ")"
	}
}

func elementOf(leanType string) (string, bool) {
	if strings.HasPrefix(leanType, "Array ") {
		return strings.TrimPrefix(leanType, "Array "), true
	}
	return "", false
}

// ---- records ----

func (em *emitter) emitRecord(adt *ast.ADTType) (string, error) {
	record := adt.Variants[0].Literal.(*ast.RecordLiteral)
	var out strings.Builder
	fmt.Fprintf(&out, "structure %s where\n", ident(adt.Name.Value))
	var zero []string
	for _, field := range record.FieldOrder {
		typ, err := em.leanType(field.Value)
		if err != nil {
			return "", fmt.Errorf("lean: %s.%s: %w", adt.Name.Value, field.Name, err)
		}
		fmt.Fprintf(&out, "  %s : %s\n", ident(field.Name), typ)
		zero = append(zero, fmt.Sprintf("%s := %s", ident(field.Name), em.initialValue(field.Value, typ)))
	}
	out.WriteString("  deriving Repr, BEq, DecidableEq\n")
	// The default value is the zero record Oak's uninitialized declaration
	// denotes: a fixed array field `[N]T` is N zeroes, not the empty array
	// `deriving Inhabited` would pick, whose element stores would all be
	// dropped as out of range (docs/spec/95-extraction.md section 3).
	fmt.Fprintf(&out, "instance : Inhabited %s := ⟨{ %s }⟩\n", ident(adt.Name.Value), strings.Join(zero, ", "))
	return out.String(), nil
}

// ---- functions ----

// threadedParams lists the indices of a function's parameters that carry
// writable storage — span parameters, and record parameters holding a span
// field (a `MutTensor2` written through `t.data[i] = v`) — the storage it
// may write and therefore returns beside its result
// (docs/spec/95-extraction.md section 2).
func (em *emitter) threadedParams(fn *ast.FunctionStatement) []int {
	var threaded []int
	for i, p := range fn.Parameters {
		if em.isThreadedType(p.Type) {
			threaded = append(threaded, i)
		}
	}
	return threaded
}

// isThreadedType reports a span type or a record type with a span field.
func (em *emitter) isThreadedType(typ ast.Expression) bool {
	if isSpanType(typ) {
		return true
	}
	name, ok := typ.(*ast.Identifier)
	if !ok {
		return false
	}
	return em.recordHasSpan(name.Value)
}

// recordHasSpan reports whether a declared record has a span field.
func (em *emitter) recordHasSpan(recordType string) bool {
	adt, ok := em.records[recordType]
	if !ok || len(adt.Variants) == 0 {
		return false
	}
	record, isRecord := adt.Variants[0].Literal.(*ast.RecordLiteral)
	if !isRecord {
		return false
	}
	for _, f := range record.FieldOrder {
		if isSpanType(f.Value) {
			return true
		}
	}
	return false
}

func isSpanType(expr ast.Expression) bool {
	index, ok := expr.(*ast.IndexExpression)
	if !ok || index.Dot {
		return false
	}
	marker, ok := index.Index.(*ast.Identifier)
	return ok && marker.Value == "*"
}

func (em *emitter) emitFunction(fn *ast.FunctionStatement) (string, error) {
	em.fnName = fn.Name.Value
	em.scope = newScope(nil)
	em.helpers = nil
	em.loops = 0
	em.temps = 0

	var params []string
	for _, p := range fn.Parameters {
		if p.Variadic {
			return "", fmt.Errorf("lean: %s: variadic parameters are outside the extracted subset", fn.Name.Value)
		}
		typ, err := em.leanType(p.Type)
		if err != nil {
			return "", fmt.Errorf("lean: %s: parameter %s: %w", fn.Name.Value, p.Name.Value, err)
		}
		em.scope.declare(p.Name.Value, typ)
		params = append(params, fmt.Sprintf("(%s : %s)", ident(p.Name.Value), typ))
	}
	returnType := "Unit"
	if fn.ReturnType != nil {
		var err error
		if returnType, err = em.leanType(fn.ReturnType); err != nil {
			return "", fmt.Errorf("lean: %s: return type: %w", fn.Name.Value, err)
		}
	}
	resultTypes := []string{returnType}
	var spanNames []string
	for _, i := range em.threadedParams(fn) {
		typ, _ := em.scope.lookup(fn.Parameters[i].Name.Value)
		resultTypes = append(resultTypes, typ)
		spanNames = append(spanNames, ident(fn.Parameters[i].Name.Value))
	}

	body := newScope(em.scope)
	em.scope = body
	var lines []string
	em.indent = "  "
	if em.recursive[fn.Name.Value] {
		em.indent = "    "
	}
	statements, result, err := em.functionBody(fn, returnType)
	if err != nil {
		return "", err
	}
	if err := em.block(statements, &lines); err != nil {
		return "", fmt.Errorf("lean: %s: %w", fn.Name.Value, err)
	}
	resultTerm := "()"
	if result != nil {
		var hoisted []string
		em.hoisted = &hoisted
		term, err := em.expr(result, returnType)
		em.hoisted = nil
		if err != nil {
			return "", fmt.Errorf("lean: %s: result: %w", fn.Name.Value, err)
		}
		lines = append(lines, hoisted...)
		resultTerm = term
	}
	lines = append(lines, em.indent+"pure "+tuple(append([]string{resultTerm}, spanNames...)))

	var out strings.Builder
	for _, helper := range em.helpers {
		out.WriteString(helper)
		out.WriteString("\n")
	}
	if em.recursive[fn.Name.Value] {
		// A self-recursive function is a definition by recursion on the
		// fuel: no fuel, no result; otherwise the body, whose recursive
		// calls pass the fuel that remains.
		fmt.Fprintf(&out, "def %s %s : Nat → Option %s\n", ident(fn.Name.Value), strings.Join(params, " "), tupleType(resultTypes))
		out.WriteString("  | 0 => none\n")
		out.WriteString("  | fuel + 1 => do\n")
	} else {
		fmt.Fprintf(&out, "def %s %s (fuel : Nat) : Option %s := do\n", ident(fn.Name.Value), strings.Join(params, " "), tupleType(resultTypes))
	}
	out.WriteString(strings.Join(lines, "\n"))
	out.WriteString("\n")
	if fn.Theorem {
		out.WriteString(em.theoremStatement(fn, params))
	}
	return out.String(), nil
}

// predicateTerm renders a refinement's predicate with `value` read as the
// given Lean binding, in the current scope.
func (em *emitter) predicateTerm(predicate ast.Expression, binding string) (string, error) {
	saved := em.valueBinding
	em.valueBinding = binding
	defer func() { em.valueBinding = saved }()
	return em.expr(predicate, "Bool")
}

// theoremStatement states a theorem's universal claim over its extracted
// definition (docs/spec/125-verification.md section 5): for every
// argument and every fuel, the definition returns `some true`. The proof
// script tries the kernel's deciders in turn — `decide` for closed and
// small statements, `omega` for linear arithmetic over the naturals the
// `toNat` views expose, `bv_decide` for fixed-width bit-vector claims —
// and a statement none of them settles is left for a hand-written proof
// in a module of its own; the build reports it open.
func (em *emitter) theoremStatement(fn *ast.FunctionStatement, params []string) string {
	var out strings.Builder
	name := ident(fn.Name.Value)
	// A parameter of a refinement type carries its predicate as a
	// hypothesis: the theorem is about the values the construction admits
	// (docs/spec/20-types.md section 12).
	var hypotheses []string
	for _, p := range fn.Parameters {
		typeName, isIdent := p.Type.(*ast.Identifier)
		if !isIdent {
			continue
		}
		if _, predicate, isRefinement := em.tc.Refinement(typeName.Value); isRefinement {
			if cond, err := em.predicateTerm(predicate, ident(p.Name.Value)); err == nil {
				hypotheses = append(hypotheses, fmt.Sprintf("(h_%s : %s = true)", ident(p.Name.Value), cond))
			}
		}
	}
	out.WriteString("set_option linter.unusedSimpArgs false in\n")
	fmt.Fprintf(&out, "theorem %s_holds %s %s(fuel : Nat) : %s", name, strings.Join(params, " "),
		strings.Join(append(hypotheses, ""), " "), name)
	for _, p := range fn.Parameters {
		out.WriteString(" " + ident(p.Name.Value))
	}
	out.WriteString(" fuel = some true := by\n")
	// The theorem and every extracted function it reaches are unfolded, so
	// the deciders see one term.
	unfolds := []string{name}
	seen := map[string]bool{fn.Name.Value: true}
	queue := []*ast.FunctionStatement{fn}
	for len(queue) > 0 {
		current := queue[0]
		queue = queue[1:]
		for _, callee := range em.callees(current) {
			target, known := em.functions[callee]
			if !known || seen[callee] {
				continue
			}
			seen[callee] = true
			unfolds = append(unfolds, ident(callee))
			queue = append(queue, target)
		}
	}
	fmt.Fprintf(&out, "  unfold %s\n", strings.Join(unfolds, " "))
	out.WriteString("  simp only [pure, bind, Option.bind_some, Option.bind_none, oak_bind_ite, Option.ite_none_right_eq_some, Option.some.injEq, decide_eq_true_eq] at *\n")
	out.WriteString("  first | rfl | decide | omega | bv_decide\n")
	return out.String()
}

// functionBody splits a body into its statements and result expression.
func (em *emitter) functionBody(fn *ast.FunctionStatement, returnType string) ([]ast.Statement, ast.Expression, error) {
	block, isBlock := fn.Body.(*ast.BlockExpression)
	if !isBlock {
		return nil, fn.Body, nil
	}
	if block.Block == nil {
		return nil, nil, nil
	}
	statements := block.Block.Statements
	if returnType == "Unit" || len(statements) == 0 {
		return statements, nil, nil
	}
	last, isExpr := statements[len(statements)-1].(*ast.ExpressionStatement)
	if !isExpr {
		return nil, nil, fmt.Errorf("lean: %s: body does not end in its result expression", fn.Name.Value)
	}
	return statements[:len(statements)-1], last.Expression, nil
}

func tuple(items []string) string {
	if len(items) == 1 {
		return items[0]
	}
	return "(" + strings.Join(items, ", ") + ")"
}

func tupleType(items []string) string {
	if len(items) == 1 {
		return "(" + items[0] + ")"
	}
	return "(" + strings.Join(items, " × ") + ")"
}

// ---- statements ----

// block emits statements as do-lines at the current indent.
func (em *emitter) block(statements []ast.Statement, lines *[]string) error {
	for _, stmt := range statements {
		if err := em.statement(stmt, lines); err != nil {
			return err
		}
	}
	return nil
}

// statement emits one statement, then writes every span window the
// statement rebound back into its owner, transitively, so the owner's
// value agrees with the compiled program where the window aliased it.
func (em *emitter) statement(stmt ast.Statement, lines *[]string) error {
	if err := em.statementInner(stmt, lines); err != nil {
		return err
	}
	written := em.assignedOuter(&ast.BlockExpression{Block: &ast.BlockStatement{Statements: []ast.Statement{stmt}}})
	pending := append([]string(nil), written...)
	seen := map[string]bool{}
	for len(pending) > 0 {
		name := pending[0]
		pending = pending[1:]
		if seen[name] {
			continue
		}
		seen[name] = true
		alias, ok := em.scope.alias(name)
		if !ok {
			continue
		}
		if alias.whole {
			*lines = append(*lines, fmt.Sprintf("%slet %s := %s", em.indent, ident(alias.owner), ident(name)))
		} else {
			*lines = append(*lines, fmt.Sprintf("%slet %s := ((%s.extract 0 %s) ++ %s ++ (%s.extract (%s + %s.size) %s.size))",
				em.indent, ident(alias.owner), ident(alias.owner), alias.low, ident(name), ident(alias.owner), alias.low, ident(name), ident(alias.owner)))
		}
		pending = append(pending, alias.owner)
	}
	return nil
}

func (em *emitter) statementInner(stmt ast.Statement, lines *[]string) error {
	var hoisted []string
	em.hoisted = &hoisted
	defer func() { em.hoisted = nil }()
	emit := func(format string, args ...any) {
		*lines = append(*lines, hoisted...)
		hoisted = nil
		*lines = append(*lines, em.indent+fmt.Sprintf(format, args...))
	}
	switch s := stmt.(type) {
	case *ast.VariableDeclaration:
		var typ string
		var err error
		if s.Type != nil {
			typ, err = em.leanType(s.Type)
		} else if declared := em.env.CheckedDeclarationType(s); declared != nil {
			typ, err = em.leanTypeOf(declared)
		} else {
			err = fmt.Errorf("declaration %s has no type", s.Name.Value)
		}
		if err != nil {
			return err
		}
		if s.Value == nil {
			emit("let %s : %s := %s", ident(s.Name.Value), typ, em.initialValue(s.Type, typ))
		} else {
			term, err := em.expr(s.Value, typ)
			if err != nil {
				return err
			}
			emit("let %s : %s := %s", ident(s.Name.Value), typ, term)
		}
		em.scope.declare(s.Name.Value, typ)
		if s.Type != nil && isSpanType(s.Type) {
			if owner, low, whole := spanWindow(s.Value); owner != "" {
				if _, known := em.scope.lookup(owner); known {
					alias := spanAlias{owner: owner, whole: whole}
					if !whole {
						alias.low = ident(s.Name.Value) + "_lo"
						lowTerm, err := em.indexTerm(low)
						if err != nil {
							return err
						}
						emit("let %s : Nat := %s", alias.low, lowTerm)
						em.scope.declare(s.Name.Value+"_lo", "Nat")
					}
					em.scope.declareAlias(s.Name.Value, alias)
				}
			}
		}
		return nil
	case *ast.AssignmentStatement:
		typ, ok := em.scope.lookup(s.Name.Value)
		if !ok {
			return fmt.Errorf("assignment to unknown variable %s", s.Name.Value)
		}
		term, err := em.expr(s.Value, typ)
		if err != nil {
			return err
		}
		emit("let %s := %s", ident(s.Name.Value), term)
		return nil
	case *ast.IndexAssignmentStatement:
		if s.Target.Dot {
			if elementAccess, isElement := s.Target.Left.(*ast.IndexExpression); isElement && !elementAccess.Dot {
				// arr[i].field = v: the element record is read, its field
				// replaced, and the record stored back at the same index
				// (docs/spec/95-extraction.md section 2); out-of-range
				// stores are dropped like every other element store.
				array, isIdent := elementAccess.Left.(*ast.Identifier)
				field, isName := s.Target.Index.(*ast.Identifier)
				if !isIdent || !isName {
					return fmt.Errorf("field assignment %s is outside the extracted subset (one level of fields)", s.Target.String())
				}
				arrayType, known := em.scope.lookup(array.Value)
				element, isArray := elementOf(arrayType)
				if !known || !isArray {
					return fmt.Errorf("field assignment into non-array %s", array.Value)
				}
				fieldType, err := em.recordFieldType(element, field.Value)
				if err != nil {
					return err
				}
				index, err := em.indexTerm(elementAccess.Index)
				if err != nil {
					return err
				}
				term, err := em.expr(s.Value, fieldType)
				if err != nil {
					return err
				}
				emit("let %s := %s.setIfInBounds %s { (%s.getD %s %s) with %s := %s }", ident(array.Value), ident(array.Value), index, ident(array.Value), index, zeroOf(element), ident(field.Value), term)
				return nil
			}
			base, ok := s.Target.Left.(*ast.Identifier)
			field, isField := s.Target.Index.(*ast.Identifier)
			if !ok || !isField {
				return fmt.Errorf("field assignment %s is outside the extracted subset (one level of fields)", s.Target.String())
			}
			fieldType, err := em.fieldType(base.Value, field.Value)
			if err != nil {
				return err
			}
			term, err := em.expr(s.Value, fieldType)
			if err != nil {
				return err
			}
			emit("let %s := { %s with %s := %s }", ident(base.Value), ident(base.Value), ident(field.Value), term)
			return nil
		}
		if fieldAccess, isField := s.Target.Left.(*ast.IndexExpression); isField && fieldAccess.Dot {
			// r.field[i] = v: the field's array is updated and written back
			// into the record (one level of fields, as for field assignment).
			record, isIdent := fieldAccess.Left.(*ast.Identifier)
			field, isName := fieldAccess.Index.(*ast.Identifier)
			if !isIdent || !isName {
				return fmt.Errorf("element assignment into %s is outside the extracted subset (one level of fields)", s.Target.Left.String())
			}
			fieldType, err := em.fieldType(record.Value, field.Value)
			if err != nil {
				return err
			}
			element, isArray := elementOf(fieldType)
			if !isArray {
				return fmt.Errorf("element assignment into non-array field %s", s.Target.Left.String())
			}
			index, err := em.indexTerm(s.Target.Index)
			if err != nil {
				return err
			}
			term, err := em.expr(s.Value, element)
			if err != nil {
				return err
			}
			emit("let %s := { %s with %s := %s.%s.setIfInBounds %s %s }", ident(record.Value), ident(record.Value), ident(field.Value), ident(record.Value), ident(field.Value), index, term)
			return nil
		}
		base, ok := s.Target.Left.(*ast.Identifier)
		if !ok {
			return fmt.Errorf("element assignment into %s is outside the extracted subset", s.Target.Left.String())
		}
		arrayType, known := em.scope.lookup(base.Value)
		element, isArray := elementOf(arrayType)
		if !known || !isArray {
			return fmt.Errorf("element assignment into non-array %s", base.Value)
		}
		index, err := em.indexTerm(s.Target.Index)
		if err != nil {
			return err
		}
		term, err := em.expr(s.Value, element)
		if err != nil {
			return err
		}
		emit("let %s := %s.setIfInBounds %s %s", ident(base.Value), ident(base.Value), index, term)
		return nil
	case *ast.WhileStatement:
		return em.whileStatement(s, lines, &hoisted)
	case *ast.ExpressionStatement:
		if match, ok := s.Expression.(*ast.MatchExpression); ok && (isBoolConditional(match) || isIntegerMatch(match)) {
			return em.conditionalStatement(match, lines, &hoisted)
		}
		if match, ok := s.Expression.(*ast.MatchExpression); ok && isVariantMatch(match) {
			return em.matchStatement(match, lines, &hoisted)
		}
		if call, ok := s.Expression.(*ast.InvocationExpression); ok {
			if callee, isIdent := call.Function.(*ast.Identifier); isIdent && callee.Value == "assert" && len(call.Arguments) == 1 {
				cond, err := em.expr(call.Arguments[0], "Bool")
				if err != nil {
					return err
				}
				emit("let () ← (if %s then pure () else none)", cond)
				return nil
			}
			// assert_eq / assert_ne trap exactly when the comparison fails; the
			// values they would print are not part of the model.
			if callee, isIdent := call.Function.(*ast.Identifier); isIdent && (callee.Value == "assert_eq" || callee.Value == "assert_ne") && len(call.Arguments) == 2 {
				got, err := em.expr(call.Arguments[0], "")
				if err != nil {
					return err
				}
				want, err := em.expr(call.Arguments[1], "")
				if err != nil {
					return err
				}
				if callee.Value == "assert_eq" {
					emit("let () ← (if %s == %s then pure () else none)", got, want)
				} else {
					emit("let () ← (if %s == %s then none else pure ())", got, want)
				}
				return nil
			}
			// A call in statement position is evaluated for its span effects.
			if _, err := em.expr(call, ""); err != nil {
				return err
			}
			*lines = append(*lines, hoisted...)
			return nil
		}
		return fmt.Errorf("expression statement %s is outside the extracted subset", s.Expression.String())
	case *ast.BlockStatement:
		return em.block(s.Statements, lines)
	}
	return fmt.Errorf("statement %T is outside the extracted subset", stmt)
}

// initialValue is the zero value of a declared-without-initializer binding.
func (em *emitter) initialValue(typeExpr ast.Expression, leanType string) string {
	if index, ok := typeExpr.(*ast.IndexExpression); ok && !index.Dot {
		if length, isLiteral := index.Index.(*ast.IntegerLiteral); isLiteral {
			element, _ := elementOf(leanType)
			return fmt.Sprintf("Array.replicate %d %s", length.Value, zeroOf(element))
		}
	}
	return zeroOf(leanType)
}

func (em *emitter) fieldType(variable, field string) (string, error) {
	recordType, ok := em.scope.lookup(variable)
	if !ok {
		return "", fmt.Errorf("unknown variable %s", variable)
	}
	return em.recordFieldType(recordType, field)
}

func (em *emitter) recordFieldType(recordType, field string) (string, error) {
	adt, ok := em.records[recordType]
	if !ok {
		return "", fmt.Errorf("%s is not an extracted record", recordType)
	}
	record := adt.Variants[0].Literal.(*ast.RecordLiteral)
	for _, f := range record.FieldOrder {
		if f.Name == field {
			return em.leanType(f.Value)
		}
	}
	return "", fmt.Errorf("record %s has no field %s", recordType, field)
}

func isBoolConditional(match *ast.MatchExpression) bool {
	if len(match.Arms) != 2 {
		return false
	}
	for _, arm := range match.Arms {
		literal, ok := arm.Pattern.(*ast.LiteralPattern)
		if !ok {
			return false
		}
		if _, isBool := literal.Value.(*ast.Boolean); !isBool {
			return false
		}
	}
	return true
}

// isIntegerMatch recognizes a match on integer constants: every arm but
// the last a literal pattern over an integer, the last a literal or the
// wildcard. It extracts as a chain of equality tests against the scrutinee
// (docs/spec/95-extraction.md section 2).
func isIntegerMatch(match *ast.MatchExpression) bool {
	if len(match.Arms) < 2 {
		return false
	}
	for i, arm := range match.Arms {
		switch pattern := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			if _, isInt := pattern.Value.(*ast.IntegerLiteral); !isInt {
				return false
			}
		case *ast.WildcardPattern:
			if i != len(match.Arms)-1 {
				return false
			}
		case *ast.BindingPattern:
			// The parser spells `_` as a binding named "_"; a real binding
			// names the scrutinee and stays outside the subset.
			if i != len(match.Arms)-1 || pattern.Name == nil || pattern.Name.Value != "_" {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// branch is one guarded arm of a conditional chain; the final arm has no
// condition.
type branch struct {
	cond string
	body ast.Expression
}

// branches renders a Bool conditional or an integer-constant match as a
// chain of guarded arms ending in the unguarded one.
func (em *emitter) branches(match *ast.MatchExpression) ([]branch, error) {
	if isBoolConditional(match) {
		trueBody, falseBody := match.Arms[0].Body, match.Arms[1].Body
		if literal := match.Arms[0].Pattern.(*ast.LiteralPattern).Value.(*ast.Boolean); !literal.Value {
			trueBody, falseBody = falseBody, trueBody
		}
		cond, err := em.expr(match.Scrutinee, "Bool")
		if err != nil {
			return nil, err
		}
		return []branch{{cond, trueBody}, {"", falseBody}}, nil
	}
	typ := em.checkedLeanType(match.Scrutinee)
	scrutinee, err := em.expr(match.Scrutinee, typ)
	if err != nil {
		return nil, err
	}
	var chain []branch
	for i, arm := range match.Arms {
		if i == len(match.Arms)-1 {
			// The last arm is the else, whether a wildcard or the closing
			// literal of an exhaustive match.
			chain = append(chain, branch{"", arm.Body})
			break
		}
		literal := arm.Pattern.(*ast.LiteralPattern).Value.(*ast.IntegerLiteral)
		chain = append(chain, branch{fmt.Sprintf("(%s == %s)", scrutinee, literalTerm(literal.Value, typ)), arm.Body})
	}
	return chain, nil
}

// conditionalStatement emits a Bool conditional or integer-constant match
// whose arms are blocks: the variables any arm assigns are rebound from the
// chosen arm, through a chain of `if ... then (do ...) else if ...`.
func (em *emitter) conditionalStatement(match *ast.MatchExpression, lines *[]string, hoisted *[]string) error {
	chain, err := em.branches(match)
	if err != nil {
		return err
	}
	*lines = append(*lines, *hoisted...)
	*hoisted = nil
	var bodies []ast.Expression
	for _, b := range chain {
		bodies = append(bodies, b.body)
	}
	written := em.assignedOuter(bodies...)
	outs := tuple(identAll(written))
	if len(written) == 0 {
		outs = "()"
	}
	for i, b := range chain {
		switch {
		case i == 0:
			*lines = append(*lines, fmt.Sprintf("%slet %s ← (if %s then (do", em.indent, outs, b.cond))
		case b.cond != "":
			*lines = append(*lines, fmt.Sprintf("%s  else if %s then (do", em.indent, b.cond))
		default:
			*lines = append(*lines, em.indent+"  else (do")
		}
		saved := em.indent
		em.indent = saved + "    "
		var armLines []string
		if err := em.branchBody(b.body, &armLines); err != nil {
			return err
		}
		armLines = append(armLines, em.indent+"pure "+outs+")")
		em.indent = saved
		*lines = append(*lines, armLines...)
	}
	last := len(*lines) - 1
	(*lines)[last] += ")"
	return nil
}

// branchBody emits a conditional arm: a block's statements, or a single
// expression (evaluated for effects only in statement position).
func (em *emitter) branchBody(body ast.Expression, lines *[]string) error {
	switch b := body.(type) {
	case *ast.BlockExpression:
		if b.Block == nil {
			return nil
		}
		inner := newScope(em.scope)
		em.scope = inner
		err := em.block(b.Block.Statements, lines)
		em.scope = inner.outer
		return err
	case *ast.MatchExpression:
		if isBoolConditional(b) || isIntegerMatch(b) {
			var hoisted []string
			return em.conditionalStatement(b, lines, &hoisted)
		}
		if isVariantMatch(b) {
			var hoisted []string
			return em.matchStatement(b, lines, &hoisted)
		}
	}
	return fmt.Errorf("conditional arm %s is outside the extracted subset in statement position", body.String())
}

// whileStatement emits a loop as a fuel-indexed helper taking every outer
// variable the loop reads and returning every outer variable it writes.
func (em *emitter) whileStatement(loop *ast.WhileStatement, lines *[]string, hoisted *[]string) error {
	em.loops++
	name := fmt.Sprintf("%s.loop%d", ident(em.fnName), em.loops)
	reads := em.referencedOuter(loop.Condition, &ast.BlockExpression{Block: loop.Body})
	writes := em.assignedOuter(&ast.BlockExpression{Block: loop.Body})
	// Parameters: every referenced outer variable, in scope order.
	var params []string
	for _, v := range reads {
		typ, _ := em.scope.lookup(v)
		params = append(params, fmt.Sprintf("(%s : %s)", ident(v), typ))
	}
	var resultTypes []string
	for _, v := range writes {
		typ, _ := em.scope.lookup(v)
		resultTypes = append(resultTypes, typ)
	}
	outs := tuple(identAll(writes))
	if len(writes) == 0 {
		outs = "()"
		resultTypes = []string{"Unit"}
	}

	// The helper body is emitted in a scope holding only its parameters.
	savedScope, savedIndent, savedHoisted := em.scope, em.indent, em.hoisted
	helperScope := newScope(nil)
	for _, v := range reads {
		typ, _ := savedScope.lookup(v)
		helperScope.declare(v, typ)
	}
	em.scope = newScope(helperScope)
	em.indent = "    "
	var condHoisted []string
	em.hoisted = &condHoisted
	cond, err := em.expr(loop.Condition, "Bool")
	em.hoisted = nil
	if err != nil {
		em.scope, em.indent, em.hoisted = savedScope, savedIndent, savedHoisted
		return err
	}
	var bodyLines []string
	em.indent = "      "
	if err := em.block(loop.Body.Statements, &bodyLines); err != nil {
		em.scope, em.indent, em.hoisted = savedScope, savedIndent, savedHoisted
		return err
	}
	em.scope, em.indent, em.hoisted = savedScope, savedIndent, savedHoisted

	var helper strings.Builder
	fmt.Fprintf(&helper, "def %s %s : Nat → Option %s\n", name, strings.Join(params, " "), tupleType(resultTypes))
	helper.WriteString("  | 0 => none\n")
	helper.WriteString("  | fuel + 1 => do\n")
	for _, line := range condHoisted {
		helper.WriteString(line + "\n")
	}
	fmt.Fprintf(&helper, "    if %s then do\n", cond)
	for _, line := range bodyLines {
		helper.WriteString(line + "\n")
	}
	fmt.Fprintf(&helper, "      %s %s fuel\n", name, strings.Join(identAll(reads), " "))
	fmt.Fprintf(&helper, "    else pure %s\n", outs)
	em.helpers = append(em.helpers, helper.String())

	*lines = append(*lines, *hoisted...)
	*hoisted = nil
	*lines = append(*lines, fmt.Sprintf("%slet %s ← %s %s fuel", em.indent, outs, name, strings.Join(identAll(reads), " ")))
	return nil
}

// assignedOuter lists the variables in the current scope chain that the
// given expressions assign (directly, by element or field, or as a span
// argument), in scope order.
func (em *emitter) assignedOuter(bodies ...ast.Expression) []string {
	written := map[string]bool{}
	declaredInside := map[string]bool{}
	for _, body := range bodies {
		walkStatements(body, func(stmt ast.Statement) {
			switch s := stmt.(type) {
			case *ast.VariableDeclaration:
				declaredInside[s.Name.Value] = true
			case *ast.AssignmentStatement:
				written[s.Name.Value] = true
			case *ast.IndexAssignmentStatement:
				if root := rootIdentifier(s.Target); root != "" {
					written[root] = true
				}
			}
		})
		walkExpressions(body, func(e ast.Expression) {
			if call, ok := e.(*ast.InvocationExpression); ok {
				for _, owner := range em.callWrites(call) {
					written[owner] = true
				}
			}
		})
	}
	// A write to a span window is a write to its owner (and the owner's
	// owner): windows declared in scope and windows declared inside the
	// bodies both count.
	aliases := map[string]string{}
	for _, body := range bodies {
		walkStatements(body, func(stmt ast.Statement) {
			if decl, ok := stmt.(*ast.VariableDeclaration); ok && decl.Type != nil && isSpanType(decl.Type) {
				if owner, _, _ := spanWindow(decl.Value); owner != "" {
					aliases[decl.Name.Value] = owner
				}
			}
		})
	}
	for changed := true; changed; {
		changed = false
		for name := range written {
			owner, ok := aliases[name]
			if !ok {
				if alias, inScope := em.scope.alias(name); inScope {
					owner, ok = alias.owner, true
				}
			}
			if ok && !written[owner] {
				written[owner] = true
				changed = true
			}
		}
	}
	var result []string
	for _, name := range em.scope.ordered() {
		if written[name] && !declaredInside[name] {
			result = append(result, name)
		}
	}
	return result
}

// spanWindow recognizes the two window forms a span variable is declared
// as: owner[lo:hi] (low is the lo expression, nil for 0) and span(&owner).
func spanWindow(value ast.Expression) (owner string, low ast.Expression, whole bool) {
	switch v := value.(type) {
	case *ast.SliceExpression:
		if id, ok := v.Seq.(*ast.Identifier); ok {
			if v.Low == nil {
				return id.Value, &ast.IntegerLiteral{Value: 0}, false
			}
			return id.Value, v.Low, false
		}
	case *ast.InvocationExpression:
		if callee, ok := v.Function.(*ast.Identifier); ok && callee.Value == "span" && len(v.Arguments) == 1 {
			if o := addressOf(v.Arguments[0]); o != "" {
				return o, nil, true
			}
		}
	}
	return "", nil, false
}

// referencedOuter lists the outer variables the expressions mention.
func (em *emitter) referencedOuter(bodies ...ast.Expression) []string {
	mentioned := map[string]bool{}
	for _, body := range bodies {
		walkExpressions(body, func(e ast.Expression) {
			if id, ok := e.(*ast.Identifier); ok {
				mentioned[id.Value] = true
			}
		})
		walkStatements(body, func(stmt ast.Statement) {
			switch s := stmt.(type) {
			case *ast.AssignmentStatement:
				mentioned[s.Name.Value] = true
			case *ast.IndexAssignmentStatement:
				if root := rootIdentifier(s.Target); root != "" {
					mentioned[root] = true
				}
			}
		})
	}
	// Writing back a window mentions its owner and its start.
	for _, name := range em.assignedOuter(bodies...) {
		if alias, ok := em.scope.alias(name); ok {
			mentioned[alias.owner] = true
			if !alias.whole {
				mentioned[name+"_lo"] = true
			}
		}
	}
	var result []string
	for _, name := range em.scope.ordered() {
		if mentioned[name] {
			result = append(result, name)
		}
	}
	return result
}

func rootIdentifier(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.Identifier:
		return e.Value
	case *ast.IndexExpression:
		return rootIdentifier(e.Left)
	}
	return ""
}

// callWrites names every owner a call rebinds: the operands of inline
// span(&owner) arguments, and for a call to an extracted function the owner
// behind every argument at a span parameter — a bare span variable or a
// view/span of one — exactly the set the hoisted call rebinds
// (`let (r, items) ← f items ...`). Omitting the span-variable case dropped
// such writes from loop and arm write sets (oak #186).
func (em *emitter) callWrites(call *ast.InvocationExpression) []string {
	owners := spanArguments(call)
	callee, ok := call.Function.(*ast.Identifier)
	if !ok {
		return owners
	}
	fn, known := em.functions[callee.Value]
	if !known || len(fn.Parameters) != len(call.Arguments) {
		return owners
	}
	for i, arg := range call.Arguments {
		if !em.isThreadedType(fn.Parameters[i].Type) {
			continue
		}
		owner := addressOf(argOperand(arg))
		if owner == "" {
			if id, isIdent := arg.(*ast.Identifier); isIdent {
				owner = id.Value
			}
		}
		if owner != "" {
			owners = append(owners, owner)
		}
	}
	return owners
}

// spanArguments names the owners a call writes through span(&owner)
// arguments or span variables.
func spanArguments(call *ast.InvocationExpression) []string {
	var owners []string
	for _, arg := range call.Arguments {
		if inner, ok := arg.(*ast.InvocationExpression); ok {
			if callee, isIdent := inner.Function.(*ast.Identifier); isIdent && callee.Value == "span" && len(inner.Arguments) == 1 {
				if owner := addressOf(inner.Arguments[0]); owner != "" {
					owners = append(owners, owner)
				}
			}
		}
	}
	return owners
}

func addressOf(expr ast.Expression) string {
	prefix, ok := expr.(*ast.PrefixExpression)
	if !ok || prefix.Operator != "&" {
		return ""
	}
	if id, isIdent := prefix.Right.(*ast.Identifier); isIdent {
		return id.Value
	}
	return ""
}

// ---- expressions ----

// expr renders an expression as a pure Lean term; calls are hoisted into
// the current statement's preceding lines. want is the Lean type the
// context expects, used to type integer literals.
// arrayLiteralTerm renders an array literal. Lean elaborates `#[...]`
// through a nested list literal, so a long table (a 2048-entry CRC table)
// exceeds the default recursion depth as one literal; it is emitted as a
// concatenation of chunks instead, which denotes the same array.
func arrayLiteralTerm(terms []string, element string) string {
	const chunk = 128
	if len(terms) <= chunk {
		return fmt.Sprintf("(#[%s] : Array %s)", strings.Join(terms, ", "), element)
	}
	var chunks []string
	for start := 0; start < len(terms); start += chunk {
		end := start + chunk
		if end > len(terms) {
			end = len(terms)
		}
		chunks = append(chunks, fmt.Sprintf("#[%s]", strings.Join(terms[start:end], ", ")))
	}
	return fmt.Sprintf("((%s) : Array %s)", strings.Join(chunks, " ++ "), element)
}

// literalTerm renders an integer literal at a Lean type. The parser stores
// every literal in an int64, so an unsigned constant above 2^63 - 1 arrives
// wrapped negative and is printed back as the unsigned value it spells.
func literalTerm(value int64, typ string) string {
	if value < 0 && strings.HasPrefix(typ, "UInt") {
		return fmt.Sprintf("(%d : %s)", uint64(value), typ)
	}
	return fmt.Sprintf("(%d : %s)", value, typ)
}

// leanIntWidth is the bit width of a Lean fixed-width integer type name,
// and whether it is signed.
func leanIntWidth(name string) (int, bool, bool) {
	switch name {
	case "UInt8":
		return 8, false, true
	case "UInt16":
		return 16, false, true
	case "UInt32":
		return 32, false, true
	case "UInt64":
		return 64, false, true
	case "Int8":
		return 8, true, true
	case "Int16":
		return 16, true, true
	case "Int32":
		return 32, true, true
	case "Int64":
		return 64, true, true
	}
	return 0, false, false
}

// expr renders an expression where a value of Lean type `want` is expected
// (or "" when the context fixes nothing). Oak widens a narrower integer of
// the same signedness implicitly (docs/spec/20-types.md section 11.1); the
// extraction makes that widening explicit with the `toUIntN`/`toIntN` of
// the wanted type, since Lean has no such coercion.
func (em *emitter) expr(expr ast.Expression, want string) (string, error) {
	term, err := em.exprValue(expr, want)
	if err != nil {
		return "", err
	}
	wantBits, wantSigned, wantInt := leanIntWidth(want)
	if !wantInt {
		return term, nil
	}
	have := em.checkedLeanType(expr)
	haveBits, haveSigned, haveInt := leanIntWidth(have)
	if !haveInt || have == want || haveSigned != wantSigned || haveBits >= wantBits {
		return term, nil
	}
	return fmt.Sprintf("(%s.to%s)", term, want), nil
}

func (em *emitter) exprValue(expr ast.Expression, want string) (string, error) {
	switch e := expr.(type) {
	case *ast.IntegerLiteral:
		typ := want
		if checked := em.checkedLeanType(e); checked != "" {
			typ = checked
		}
		if typ == "" {
			return "", fmt.Errorf("integer literal %d has no type in context", e.Value)
		}
		return literalTerm(e.Value, typ), nil
	case *ast.FloatLiteral:
		typ := want
		if checked := em.checkedLeanType(e); checked != "" {
			typ = checked
		}
		return floatLiteralTerm(e.Text, typ)
	case *ast.Boolean:
		if e.Value {
			return "true", nil
		}
		return "false", nil
	case *ast.Identifier:
		if e.Value == "value" && em.valueBinding != "" {
			// A refinement's predicate, read at the value it guards.
			return em.valueBinding, nil
		}
		if _, ok := em.scope.lookup(e.Value); !ok {
			if _, isGlobal := em.globals[e.Value]; isGlobal {
				em.usedGlobals[e.Value] = true
				return ident(e.Value), nil
			}
			return "", fmt.Errorf("identifier %s is not a variable in scope", e.Value)
		}
		return ident(e.Value), nil
	case *ast.PrefixExpression:
		switch e.Operator {
		case "!":
			inner, err := em.expr(e.Right, "Bool")
			if err != nil {
				return "", err
			}
			return "(!" + inner + ")", nil
		case "-":
			typ := em.checkedLeanType(e)
			if typ == "" {
				typ = want
			}
			inner, err := em.expr(e.Right, typ)
			if err != nil {
				return "", err
			}
			if isFloatLean(typ) {
				// Negation flips the sign bit (section 11.3.5); `0 - x` would
				// give +0 for x = +0.
				return "(-" + inner + ")", nil
			}
			return "(0 - " + inner + ")", nil
		case "^":
			// Bitwise complement over the operand's width.
			typ := em.checkedLeanType(e)
			if typ == "" {
				typ = want
			}
			inner, err := em.expr(e.Right, typ)
			if err != nil {
				return "", err
			}
			return "(~~~" + inner + ")", nil
		}
		return "", fmt.Errorf("prefix %s is outside the extracted subset", e.Operator)
	case *ast.InfixExpression:
		return em.infix(e, want)
	case *ast.IndexExpression:
		if e.Dot {
			field, ok := e.Index.(*ast.Identifier)
			if !ok {
				return "", fmt.Errorf("field access %s is outside the extracted subset", e.String())
			}
			base, err := em.expr(e.Left, "")
			if err != nil {
				return "", err
			}
			return base + "." + ident(field.Value), nil
		}
		base, err := em.expr(e.Left, "")
		if err != nil {
			return "", err
		}
		element := em.elementTypeOf(e.Left)
		if element == "" {
			return "", fmt.Errorf("indexing %s: element type unknown", e.Left.String())
		}
		index, err := em.indexTerm(e.Index)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s.getD %s %s)", base, index, zeroOf(element)), nil
	case *ast.SliceExpression:
		base, err := em.expr(e.Seq, "")
		if err != nil {
			return "", err
		}
		low := "0"
		if e.Low != nil {
			if low, err = em.indexTerm(e.Low); err != nil {
				return "", err
			}
		}
		high := base + ".size"
		if e.High != nil {
			if high, err = em.indexTerm(e.High); err != nil {
				return "", err
			}
		}
		return fmt.Sprintf("(%s.extract %s %s)", base, low, high), nil
	case *ast.ArrayLiteral:
		// [N]T{ e1, ..., eN } is the Lean array literal; the element type
		// comes from the literal's own type, else from the context.
		arrayType := want
		if e.Type != nil {
			typ, err := em.leanType(e.Type)
			if err != nil {
				return "", err
			}
			arrayType = typ
		}
		element, isArray := elementOf(arrayType)
		if !isArray {
			if checked := em.checkedLeanType(e); checked != "" {
				element, isArray = elementOf(checked)
			}
		}
		if !isArray {
			return "", fmt.Errorf("array literal has no element type in context")
		}
		terms := make([]string, 0, len(e.Elements))
		for _, item := range e.Elements {
			term, err := em.expr(item, element)
			if err != nil {
				return "", err
			}
			terms = append(terms, term)
		}
		return arrayLiteralTerm(terms, element), nil
	case *ast.RecordLiteral:
		if e.TypeName == nil {
			return "", fmt.Errorf("record literal without a type name is outside the extracted subset")
		}
		var fields []string
		for _, field := range e.FieldOrder {
			fieldType, err := em.recordFieldType(e.TypeName.Value, field.Name)
			if err != nil {
				return "", err
			}
			term, err := em.expr(field.Value, fieldType)
			if err != nil {
				return "", err
			}
			fields = append(fields, fmt.Sprintf("%s := %s", ident(field.Name), term))
		}
		return fmt.Sprintf("({ %s } : %s)", strings.Join(fields, ", "), ident(e.TypeName.Value)), nil
	case *ast.VariantExpression:
		return em.variant(e, want)
	case *ast.MatchExpression:
		variantMatch := isVariantMatch(e)
		if !isBoolConditional(e) && !isIntegerMatch(e) && !variantMatch {
			return "", fmt.Errorf("match %s is outside the extracted subset (Bool conditionals, integer-constant matches, and variant matches only)", e.String())
		}
		for _, arm := range e.Arms {
			if em.needsDo(arm.Body) {
				return em.doValue(e, want)
			}
		}
		if variantMatch {
			return em.matchValue(e, want)
		}
		chain, err := em.branches(e)
		if err != nil {
			return "", err
		}
		var out strings.Builder
		out.WriteString("(")
		for i, b := range chain {
			value, err := em.armValue(b.body, want)
			if err != nil {
				return "", err
			}
			if b.cond == "" {
				out.WriteString("else " + value)
				break
			}
			if i > 0 {
				out.WriteString("else ")
			}
			out.WriteString(fmt.Sprintf("if %s then %s ", b.cond, value))
		}
		out.WriteString(")")
		return out.String(), nil
	case *ast.BlockExpression:
		return em.armValue(e, want)
	case *ast.InvocationExpression:
		return em.call(e, want)
	}
	return "", fmt.Errorf("expression %T is outside the extracted subset", expr)
}

// armValue renders a value-position conditional arm: an expression, or a
// block whose only statement is its result.
func (em *emitter) armValue(body ast.Expression, want string) (string, error) {
	block, isBlock := body.(*ast.BlockExpression)
	if !isBlock {
		return em.expr(body, want)
	}
	if block.Block == nil || len(block.Block.Statements) != 1 {
		return "", fmt.Errorf("value-position block with statements must be bound through a do-block")
	}
	stmt, ok := block.Block.Statements[0].(*ast.ExpressionStatement)
	if !ok {
		return "", fmt.Errorf("value-position block with statements must be bound through a do-block")
	}
	return em.expr(stmt.Expression, want)
}

func (em *emitter) infix(e *ast.InfixExpression, want string) (string, error) {
	switch e.Operator {
	case "&&", "||":
		left, err := em.expr(e.Left, "Bool")
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, "Bool")
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	case "==", "!=", "<", "<=", ">", ">=":
		operand := em.checkedLeanType(e.Left)
		if operand == "" {
			operand = em.checkedLeanType(e.Right)
		}
		left, err := em.expr(e.Left, operand)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, operand)
		if err != nil {
			return "", err
		}
		switch e.Operator {
		case "==":
			return fmt.Sprintf("(%s == %s)", left, right), nil
		case "!=":
			return fmt.Sprintf("(%s != %s)", left, right), nil
		}
		return fmt.Sprintf("(decide (%s %s %s))", left, e.Operator, right), nil
	case "&", "|", "^", "<<", ">>":
		// Bitwise operators over one fixed width. Oak traps on a shift count
		// reaching the operand width (10-syntax.md section 3b); Lean masks
		// the count, which is the same on every run that produced a result
		// (docs/spec/95-extraction.md section 3).
		typ := em.checkedLeanType(e)
		if typ == "" {
			typ = em.checkedLeanType(e.Left)
		}
		if typ == "" {
			typ = want
		}
		left, err := em.expr(e.Left, typ)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, typ)
		if err != nil {
			return "", err
		}
		leanOp := map[string]string{"&": "&&&", "|": "|||", "^": "^^^", "<<": "<<<", ">>": ">>>"}[e.Operator]
		return fmt.Sprintf("(%s %s %s)", left, leanOp, right), nil
	case "+", "-", "*", "/", "%":
		typ := em.checkedLeanType(e)
		if typ == "" {
			typ = em.checkedLeanType(e.Left)
		}
		if typ == "" {
			typ = em.checkedLeanType(e.Right)
		}
		if typ == "" {
			typ = want
		}
		left, err := em.expr(e.Left, typ)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, typ)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	}
	return "", fmt.Errorf("operator %s is outside the extracted subset", e.Operator)
}

// indexTerm renders an index as a Nat.
func (em *emitter) indexTerm(index ast.Expression) (string, error) {
	if literal, ok := index.(*ast.IntegerLiteral); ok {
		return fmt.Sprintf("%d", literal.Value), nil
	}
	typ := em.checkedLeanType(index)
	if typ == "" {
		typ = "UInt32"
	}
	term, err := em.expr(index, typ)
	if err != nil {
		return "", err
	}
	return term + ".toNat", nil
}

// call renders a builtin or a user function call; user calls are hoisted.
func (em *emitter) call(call *ast.InvocationExpression, want string) (string, error) {
	callee, ok := call.Function.(*ast.Identifier)
	if !ok {
		return "", fmt.Errorf("call through %s is outside the extracted subset", call.Function.String())
	}
	switch callee.Value {
	case "len":
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("len takes one argument")
		}
		base, err := em.expr(call.Arguments[0], "")
		if err != nil {
			return "", err
		}
		return "(" + base + ".size.toUInt32)", nil
	case "is_valid_utf8":
		// The compiler's UTF-8 validity intrinsic (docs/spec/70-strings.md)
		// decides Table 3-7 over a view; the extraction runs the same
		// decision procedure over the carrier (Oak.Utf8Exec.valid).
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("is_valid_utf8 takes one argument")
		}
		base, err := em.expr(call.Arguments[0], "")
		if err != nil {
			return "", err
		}
		em.usesUtf8 = true
		return "(Oak.Utf8Exec.valid " + base + ")", nil
	case "subslice":
		// subslice(v, start, n) is the window of n elements from start
		// (docs/spec/50-borrowing.md); Oak traps past the end, the extraction
		// clamps the window to the array (docs/spec/95-extraction.md section
		// 3), which agrees on every run that produced a result.
		if len(call.Arguments) != 3 {
			return "", fmt.Errorf("subslice takes three arguments")
		}
		base, err := em.expr(call.Arguments[0], "")
		if err != nil {
			return "", err
		}
		start, err := em.indexTerm(call.Arguments[1])
		if err != nil {
			return "", err
		}
		count, err := em.indexTerm(call.Arguments[2])
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s.extract %s (%s + %s))", base, start, start, count), nil
	case "view", "span":
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("%s takes one argument", callee.Value)
		}
		owner := addressOf(call.Arguments[0])
		if owner == "" {
			return "", fmt.Errorf("%s of %s is outside the extracted subset", callee.Value, call.Arguments[0].String())
		}
		if _, known := em.scope.lookup(owner); !known {
			// A view of a top-level constant is the constant's array value;
			// a writable span of one would mutate the global and fails closed.
			if _, isGlobal := em.globals[owner]; isGlobal && callee.Value == "view" {
				em.usedGlobals[owner] = true
				return ident(owner), nil
			}
			if _, isGlobal := em.globals[owner]; isGlobal {
				return "", fmt.Errorf("span of the global %s is outside the extracted subset (globals are read-only constants here)", owner)
			}
			return "", fmt.Errorf("%s of unknown owner %s", callee.Value, owner)
		}
		return ident(owner), nil
	case "f32", "f64":
		// The implicit widening constructor (section 11.3.4): f64 of an f32 is
		// exact; the storage formats have no carrier here.
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("%s takes one argument", callee.Value)
		}
		target := primitiveLean[callee.Value]
		source := em.checkedLeanType(call.Arguments[0])
		inner, err := em.expr(call.Arguments[0], target)
		if err != nil {
			return "", err
		}
		switch {
		case source == target || source == "":
			return inner, nil
		case target == "Float" && source == "Float32":
			return "(" + inner + ".toFloat)", nil
		}
		return "", fmt.Errorf("%s of a %s is outside the extracted subset", callee.Value, source)
	case "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64":
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("%s takes one argument", callee.Value)
		}
		target := primitiveLean[callee.Value]
		if literal, isLiteral := call.Arguments[0].(*ast.IntegerLiteral); isLiteral {
			return literalTerm(literal.Value, target), nil
		}
		source := em.checkedLeanType(call.Arguments[0])
		inner, err := em.expr(call.Arguments[0], source)
		if err != nil {
			return "", err
		}
		if source == target || source == "" {
			return inner, nil
		}
		return fmt.Sprintf("(%s.to%s)", inner, target), nil
	}
	if term, handled, err := em.conversion(callee.Value, call); handled {
		return term, err
	}
	if _, shadowed := em.functions[callee.Value]; !shadowed && typechecker.FloatIntrinsicName(callee.Value) {
		return em.floatIntrinsic(callee.Value, call, want)
	}
	// A refinement's construction Name(v): the value when the predicate
	// holds, no result (the trap) otherwise, bound like a call
	// (docs/spec/20-types.md section 12).
	if base, predicate, isRefinement := em.tc.Refinement(callee.Value); isRefinement && len(call.Arguments) == 1 {
		baseLean, ok := primitiveLean[base]
		if !ok {
			return "", fmt.Errorf("refinement %s over %s is outside the extracted subset", callee.Value, base)
		}
		value, err := em.expr(call.Arguments[0], baseLean)
		if err != nil {
			return "", err
		}
		if em.hoisted == nil {
			return "", fmt.Errorf("construction of %s in a position that cannot bind its result", callee.Value)
		}
		em.temps++
		result := fmt.Sprintf("r%d", em.temps)
		*em.hoisted = append(*em.hoisted, fmt.Sprintf("%slet %s : %s := %s", em.indent, result, baseLean, value))
		em.scope.declare(result, baseLean)
		cond, err := em.predicateTerm(predicate, result)
		if err != nil {
			return "", err
		}
		*em.hoisted = append(*em.hoisted, fmt.Sprintf("%slet () ← (if %s then pure () else none)", em.indent, cond))
		return result, nil
	}
	fn, known := em.functions[callee.Value]
	if !known {
		return "", fmt.Errorf("call to %s is outside the extracted subset", callee.Value)
	}
	if len(call.Arguments) != len(fn.Parameters) {
		return "", fmt.Errorf("call to %s passes %d arguments for %d parameters", callee.Value, len(call.Arguments), len(fn.Parameters))
	}
	var args []string
	var rebinds []string
	for i, arg := range call.Arguments {
		paramType, err := em.leanType(fn.Parameters[i].Type)
		if err != nil {
			return "", err
		}
		term, err := em.expr(arg, paramType)
		if err != nil {
			return "", err
		}
		args = append(args, term)
		if em.isThreadedType(fn.Parameters[i].Type) {
			owner := addressOf(argOperand(arg))
			if owner == "" {
				if id, isIdent := arg.(*ast.Identifier); isIdent {
					owner = id.Value
				}
			}
			if owner == "" {
				return "", fmt.Errorf("writable argument %s to %s must name its owner (a span, its owner, or a record holding a span)", arg.String(), callee.Value)
			}
			rebinds = append(rebinds, ident(owner))
		}
	}
	em.temps++
	result := fmt.Sprintf("r%d", em.temps)
	if em.hoisted == nil {
		return "", fmt.Errorf("call to %s in a position that cannot bind its result", callee.Value)
	}
	*em.hoisted = append(*em.hoisted, fmt.Sprintf("%slet %s ← %s %s fuel", em.indent, tuple(append([]string{result}, rebinds...)), ident(callee.Value), strings.Join(args, " ")))
	return result, nil
}

// argOperand unwraps span(&x) / view(&x) to the &x operand.
func argOperand(arg ast.Expression) ast.Expression {
	if call, ok := arg.(*ast.InvocationExpression); ok && len(call.Arguments) == 1 {
		if callee, isIdent := call.Function.(*ast.Identifier); isIdent && (callee.Value == "span" || callee.Value == "view") {
			return call.Arguments[0]
		}
	}
	return arg
}

// checkedLeanType is the Lean type of an expression's checked type, or "".
// conversion extracts the integer rows of the `{target}_{op}_{source}`
// scheme (docs/spec/20-types.md section 11.1): `trunc` is Lean's wrapping
// `toUIntN`/`toIntN`, `bits` the same-width reinterpretation, `saturating`
// a clamp before the truncation. `checked` builds an ADT value and the
// floating-point rows have no Lean carrier here, so both stay outside the
// subset and fail closed.
func (em *emitter) conversion(name string, call *ast.InvocationExpression) (string, bool, error) {
	target, op, source, ok := typechecker.ConversionParts(name)
	if !ok {
		return "", false, nil
	}
	targetLean, targetKnown := primitiveLean[target]
	sourceLean, sourceKnown := primitiveLean[source]
	if !targetKnown || !sourceKnown || target == "Bool" || source == "Bool" {
		return "", true, fmt.Errorf("call to %s is outside the extracted subset (integer and f32/f64 conversions only)", name)
	}
	if len(call.Arguments) != 1 {
		return "", true, fmt.Errorf("%s takes one argument", name)
	}
	inner, err := em.expr(call.Arguments[0], sourceLean)
	if err != nil {
		return "", true, err
	}
	if isFloatLean(targetLean) || isFloatLean(sourceLean) {
		term, err := floatConversion(name, op, targetLean, sourceLean, inner)
		return term, true, err
	}
	switch op {
	case "trunc", "bits":
		return fmt.Sprintf("(%s.to%s)", inner, targetLean), true, nil
	case "saturating":
		bits := typechecker.PrimitiveBits(target)
		if target[0] == 'u' {
			max := uint64(1)<<uint(bits) - 1
			return fmt.Sprintf("(if %s > (%d : %s) then (%d : %s) else %s.to%s)", inner, max, sourceLean, max, targetLean, inner, targetLean), true, nil
		}
		max := int64(1)<<uint(bits-1) - 1
		min := -int64(1) << uint(bits-1)
		return fmt.Sprintf("(if %s > (%d : %s) then (%d : %s) else if %s < (%d : %s) then (%d : %s) else %s.to%s)",
			inner, max, sourceLean, max, targetLean, inner, min, sourceLean, min, targetLean, inner, targetLean), true, nil
	case "checked":
		// A checked conversion builds Result[target, Overflow]: Ok with the
		// wrapped value when the source lies within the target's range,
		// Err(Overflow) otherwise (docs/spec/20-types.md section 11.1).
		resultName := typechecker.Instantiation{ADT: "Result", Args: []string{target, "Overflow"}}.MangledName()
		result, known := em.adtLeanName(resultName)
		overflow, knownOverflow := em.adtLeanName("Overflow")
		if !known || !knownOverflow {
			return "", true, fmt.Errorf("call to %s: instantiation %s was not recorded by the checker", name, resultName)
		}
		bits := typechecker.PrimitiveBits(target)
		sourceBits := typechecker.PrimitiveBits(source)
		var outOfRange string
		switch {
		case target[0] == 'u' && source[0] == 'u':
			if bits >= sourceBits {
				outOfRange = "false"
			} else {
				outOfRange = fmt.Sprintf("%s > (%d : %s)", inner, uint64(1)<<uint(bits)-1, sourceLean)
			}
		case target[0] == 'u':
			max := uint64(1)<<uint(bits) - 1
			if bits >= sourceBits {
				outOfRange = fmt.Sprintf("%s < (0 : %s)", inner, sourceLean)
			} else {
				outOfRange = fmt.Sprintf("(%s < (0 : %s) || %s > (%d : %s))", inner, sourceLean, inner, max, sourceLean)
			}
		case source[0] == 'u':
			max := uint64(1)<<uint(bits-1) - 1
			if bits > sourceBits {
				outOfRange = "false"
			} else {
				outOfRange = fmt.Sprintf("%s > (%d : %s)", inner, max, sourceLean)
			}
		default:
			if bits >= sourceBits {
				outOfRange = "false"
			} else {
				max := int64(1)<<uint(bits-1) - 1
				min := -int64(1) << uint(bits-1)
				outOfRange = fmt.Sprintf("(%s < (%d : %s) || %s > (%d : %s))", inner, min, sourceLean, inner, max, sourceLean)
			}
		}
		return fmt.Sprintf("(if %s then %s.Err %s.Overflow else %s.Ok %s.to%s)", outOfRange, result, overflow, result, inner, targetLean), true, nil
	}
	return "", true, fmt.Errorf("call to %s is outside the extracted subset (%s conversions are not modeled)", name, op)
}

func (em *emitter) checkedLeanType(expr ast.Expression) string {
	typ := em.env.CheckedExpressionType(expr)
	if typ == nil {
		return ""
	}
	lean, err := em.leanTypeOf(typ)
	if err != nil {
		return ""
	}
	return lean
}

// elementTypeOf is the Lean element type of an array-valued expression.
func (em *emitter) elementTypeOf(expr ast.Expression) string {
	if id, ok := expr.(*ast.Identifier); ok {
		if typ, known := em.scope.lookup(id.Value); known {
			if element, isArray := elementOf(typ); isArray {
				return element
			}
		}
	}
	if typ := em.checkedLeanType(expr); typ != "" {
		if element, isArray := elementOf(typ); isArray {
			return element
		}
	}
	return ""
}

// ---- identifiers ----

var leanReserved = map[string]bool{
	"at": true, "end": true, "do": true, "then": true, "else": true, "if": true, "fun": true, "let": true,
	"have": true, "from": true, "in": true, "match": true, "with": true, "by": true, "def": true,
	"structure": true, "where": true, "deriving": true, "open": true, "namespace": true, "section": true,
	"variable": true, "theorem": true, "example": true, "calc": true, "show": true, "suffices": true,
	"obtain": true, "exact": true, "intro": true, "type": true, "instance": true, "class": true,
	"mutual": true, "partial": true, "private": true, "protected": true, "noncomputable": true,
	"abbrev": true, "axiom": true, "inductive": true, "extends": true, "import": true, "sorry": true,
	"macro": true, "syntax": true, "notation": true, "infix": true, "prefix": true, "postfix": true,
	"universe": true, "opaque": true, "unsafe": true, "return": true, "break": true, "continue": true,
	"for": true, "unless": true, "repeat": true, "while": true, "try": true, "catch": true,
	"finally": true, "mut": true, "pure": true, "fuel": true, "default": true, "none": true, "some": true,
	"true": true, "false": true, "Nat": true, "Bool": true, "Array": true, "Option": true, "id": true,
	// Keywords of later Lean releases and the float carriers, so a parameter
	// named like one (the float package's `meta`) is escaped the same way.
	"meta": true, "public": true, "export": true, "omit": true, "include": true, "lemma": true,
	"only": true, "using": true, "attribute": true, "scoped": true, "local": true, "renaming": true,
	"hiding": true, "nomatch": true, "nofun": true, "termination_by": true, "decreasing_by": true,
	"Type": true, "Prop": true, "Sort": true, "Float": true, "Float32": true,
}

// ident renders an Oak identifier as a Lean identifier: Lean keywords and
// the names the translation itself uses get a trailing underscore.
func ident(name string) string {
	if leanReserved[name] {
		return name + "_"
	}
	return name
}

func identAll(names []string) []string {
	out := make([]string, len(names))
	for i, name := range names {
		out[i] = ident(name)
	}
	return out
}

// ---- walking ----

// walkStatements visits every statement nested in an expression.
func walkStatements(expr ast.Expression, visit func(ast.Statement)) {
	var stmts func(list []ast.Statement)
	var exprs func(e ast.Expression)
	stmts = func(list []ast.Statement) {
		for _, stmt := range list {
			visit(stmt)
			switch s := stmt.(type) {
			case *ast.VariableDeclaration:
				exprs(s.Value)
			case *ast.AssignmentStatement:
				exprs(s.Value)
			case *ast.IndexAssignmentStatement:
				exprs(s.Value)
			case *ast.WhileStatement:
				exprs(s.Condition)
				if s.Body != nil {
					stmts(s.Body.Statements)
				}
			case *ast.ExpressionStatement:
				exprs(s.Expression)
			case *ast.BlockStatement:
				stmts(s.Statements)
			}
		}
	}
	exprs = func(e ast.Expression) {
		switch x := e.(type) {
		case *ast.BlockExpression:
			if x.Block != nil {
				stmts(x.Block.Statements)
			}
		case *ast.MatchExpression:
			exprs(x.Scrutinee)
			for _, arm := range x.Arms {
				exprs(arm.Body)
			}
		case *ast.InfixExpression:
			exprs(x.Left)
			exprs(x.Right)
		case *ast.PrefixExpression:
			exprs(x.Right)
		case *ast.InvocationExpression:
			for _, arg := range x.Arguments {
				exprs(arg)
			}
		case *ast.ArrayLiteral:
			for _, element := range x.Elements {
				exprs(element)
			}
		case *ast.RecordLiteral:
			for _, field := range x.FieldOrder {
				exprs(field.Value)
			}
		case *ast.VariantExpression:
			exprs(x.Payload)
		}
	}
	exprs(expr)
}

// walkExpressions visits every expression nested in an expression,
// including those inside nested statements.
func walkExpressions(expr ast.Expression, visit func(ast.Expression)) {
	var stmts func(list []ast.Statement)
	var exprs func(e ast.Expression)
	stmts = func(list []ast.Statement) {
		for _, stmt := range list {
			switch s := stmt.(type) {
			case *ast.VariableDeclaration:
				exprs(s.Value)
			case *ast.AssignmentStatement:
				exprs(s.Value)
			case *ast.IndexAssignmentStatement:
				exprs(s.Target)
				exprs(s.Value)
			case *ast.WhileStatement:
				exprs(s.Condition)
				if s.Body != nil {
					stmts(s.Body.Statements)
				}
			case *ast.ExpressionStatement:
				exprs(s.Expression)
			case *ast.BlockStatement:
				stmts(s.Statements)
			}
		}
	}
	exprs = func(e ast.Expression) {
		if e == nil {
			return
		}
		visit(e)
		switch x := e.(type) {
		case *ast.BlockExpression:
			if x.Block != nil {
				stmts(x.Block.Statements)
			}
		case *ast.MatchExpression:
			exprs(x.Scrutinee)
			for _, arm := range x.Arms {
				exprs(arm.Body)
			}
		case *ast.InfixExpression:
			exprs(x.Left)
			exprs(x.Right)
		case *ast.PrefixExpression:
			exprs(x.Right)
		case *ast.InvocationExpression:
			exprs(x.Function)
			for _, arg := range x.Arguments {
				exprs(arg)
			}
		case *ast.IndexExpression:
			exprs(x.Left)
			if !x.Dot {
				exprs(x.Index)
			}
		case *ast.SliceExpression:
			exprs(x.Seq)
			exprs(x.Low)
			exprs(x.High)
		case *ast.RecordLiteral:
			for _, field := range x.FieldOrder {
				exprs(field.Value)
			}
		case *ast.ArrayLiteral:
			for _, element := range x.Elements {
				exprs(element)
			}
		case *ast.VariantExpression:
			exprs(x.Payload)
		}
	}
	exprs(expr)
}

// ---- floating point ----

// isFloatLean reports whether a Lean type name is one of the two float
// carriers.
func isFloatLean(typ string) bool { return typ == "Float" || typ == "Float32" }

// floatLiteralTerm renders a floating-point literal exactly: the text is
// rounded once to its type's width by the checker's own rule
// (typechecker.FloatLiteralValue, correct rounding from the exact decimal
// or hexadecimal value) and the resulting bit pattern is spelled through
// `ofBits`, so no Lean-side decimal parsing takes part.
func floatLiteralTerm(text, typ string) (string, error) {
	switch typ {
	case "Float32":
		value, ok := typechecker.FloatLiteralValue(text, "f32")
		if !ok {
			return "", fmt.Errorf("floating-point literal %s does not fit f32", text)
		}
		return fmt.Sprintf("(Float32.ofBits (0x%08X : UInt32) /- %s -/)", math.Float32bits(float32(value)), text), nil
	case "Float":
		value, ok := typechecker.FloatLiteralValue(text, "f64")
		if !ok {
			return "", fmt.Errorf("floating-point literal %s does not fit f64", text)
		}
		return fmt.Sprintf("(Float.ofBits (0x%016X : UInt64) /- %s -/)", math.Float64bits(value), text), nil
	}
	return "", fmt.Errorf("floating-point literal %s in a non-float context %q", text, typ)
}

// floatConversion renders the f32/f64 rows of section 11.3.4 onto Lean's
// Float and Float32: `round` between the two formats and from the integers
// (`toFloat32`, `toFloat`), `bits` as `ofBits`/`toBits` over the same-width
// unsigned integer, `saturating` into an integer as Lean's `toUIntN`/`toIntN`
// (toward zero, clamped to the range, NaN to zero — the row's semantics), and
// `trunc` into an integer as the same operation, since the trap it would
// take out of range is a path the model does not follow (section 3).
// `checked` into an integer and every storage-format row fail closed.
func floatConversion(name, op, targetLean, sourceLean, inner string) (string, error) {
	switch {
	case op == "round" && targetLean == "Float32" && sourceLean == "Float":
		return "(" + inner + ".toFloat32)", nil
	case op == "round" && isFloatLean(targetLean) && !isFloatLean(sourceLean):
		return fmt.Sprintf("(%s.to%s)", inner, targetLean), nil
	case op == "bits" && targetLean == "Float" && sourceLean == "UInt64",
		op == "bits" && targetLean == "Float32" && sourceLean == "UInt32":
		return fmt.Sprintf("(%s.ofBits %s)", targetLean, inner), nil
	case op == "bits" && sourceLean == "Float" && targetLean == "UInt64",
		op == "bits" && sourceLean == "Float32" && targetLean == "UInt32":
		return "(" + inner + ".toBits)", nil
	case (op == "saturating" || op == "trunc") && isFloatLean(sourceLean) && !isFloatLean(targetLean):
		return fmt.Sprintf("(%s.to%s)", inner, targetLean), nil
	}
	return "", fmt.Errorf("call to %s is outside the extracted subset (the %s row from %s to %s has no Lean carrier)", name, op, sourceLean, targetLean)
}

// floatIntrinsic renders the correctly rounded intrinsics of section 11.3.5
// that Lean's Float and Float32 carry with the same contract: square root,
// absolute value, floor, ceiling, `round` (ties away from zero, as Lean's
// `Float.round`), and the classifications; fma, copysign, and round_even
// go through the bit-exact carriers in Oak.FloatOps. trunc, min/max,
// is_normal, and total_order have no exact Lean counterpart yet and fail
// closed.
func (em *emitter) floatIntrinsic(name string, call *ast.InvocationExpression, want string) (string, error) {
	// The bit-exact carriers of Oak.FloatOps (spec/lean/Oak/FloatOps.lean):
	// fma as one rounding of the exact product-sum over the bit patterns,
	// copysign as a bit operation, round_even from Lean's ties-away round
	// with the ties moved to even.
	arity := map[string]int{"fma": 3, "copysign": 2, "round_even": 1}[name]
	if arity != 0 {
		if len(call.Arguments) != arity {
			return "", fmt.Errorf("floating-point intrinsic %s: expected %d operands", name, arity)
		}
		width := ""
		for _, argument := range call.Arguments {
			if width = em.checkedLeanType(argument); width != "" {
				break
			}
		}
		if width == "" && isFloatLean(want) {
			width = want
		}
		if !isFloatLean(width) {
			return "", fmt.Errorf("floating-point intrinsic %s: operand width is not f32 or f64", name)
		}
		suffix := "64"
		if width == "Float32" {
			suffix = "32"
		}
		carrier := map[string]string{"fma": "fma", "copysign": "copysign", "round_even": "roundEven"}[name]
		terms := make([]string, len(call.Arguments))
		for i, argument := range call.Arguments {
			term, err := em.expr(argument, width)
			if err != nil {
				return "", err
			}
			terms[i] = term
		}
		em.usesFloatOps = true
		return fmt.Sprintf("(Oak.FloatOps.%s%s %s)", carrier, suffix, strings.Join(terms, " ")), nil
	}
	leanName := map[string]string{
		"sqrt": "sqrt", "abs": "abs", "floor": "floor", "ceil": "ceil", "round": "round",
		"is_nan": "isNaN", "is_finite": "isFinite", "is_infinite": "isInf",
	}[name]
	if leanName == "" || len(call.Arguments) != 1 {
		return "", fmt.Errorf("floating-point intrinsic %s is outside the extracted subset (no Lean carrier)", name)
	}
	width := em.checkedLeanType(call.Arguments[0])
	if width == "" && isFloatLean(want) {
		width = want
	}
	if !isFloatLean(width) {
		return "", fmt.Errorf("floating-point intrinsic %s: operand width is not f32 or f64", name)
	}
	inner, err := em.expr(call.Arguments[0], width)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("(%s.%s %s)", width, leanName, inner), nil
}
