// Package lean extracts a bounded imperative Oak subset into Lean 4
// definitions (docs/spec/95-extraction.md). The output is the shallow
// embedding the verification experiment's hand-written models use, produced
// mechanically from the type-checked program: every fixed-width integer is
// the Lean UInt of that width (wrapping arithmetic, exactly Oak's), every
// array, view, and span is an Array value, every function returns an Option
// of its result together with the spans it wrote, every while loop is a
// fuel-indexed structurally recursive helper, and every conditional is an
// if over the variables the branches assign. Anything outside the subset
// is an error, never an approximation.
//
// Two modeling choices are deliberate and stated: an out-of-range read
// yields the element type's zero and an out-of-range write is dropped where
// Oak would trap, and division by zero yields zero where Oak would trap.
// Both are sound for the refinement direction the experiment proves — an Oak
// run that produced a result took no trapping path, and on such runs the
// model computes the same values — and both are what the experiment's
// hand-written models already assume.
package lean

import (
	"fmt"
	"sort"
	"strings"

	"github.com/SCKelemen/oak/ast"
	"github.com/SCKelemen/oak/typechecker"
)

// Emit extracts the named declarations of program (all of them when names is
// nil) into one Lean module body under the given namespace.
func Emit(program *ast.Program, tc *typechecker.TypeChecker, namespace string, names map[string]bool) (string, error) {
	em := &emitter{
		tc:          tc,
		env:         tc.Env(),
		adts:        map[string]*ast.ADTType{},
		records:     map[string]*ast.ADTType{},
		usedTypes:   map[string]bool{},
		leanNames:   map[string]string{},
		functions:   map[string]*ast.FunctionStatement{},
		globals:     map[string]*ast.VariableDeclaration{},
		usedGlobals: map[string]bool{},
	}
	em.collectTypes(program)
	for _, stmt := range program.Statements {
		if decl, ok := stmt.(*ast.VariableDeclaration); ok && decl.Name != nil && decl.Value != nil {
			em.globals[decl.Name.Value] = decl
			em.globalOrder = append(em.globalOrder, decl.Name.Value)
		}
	}
	for name, adt := range em.adts {
		if len(adt.TypeParams) == 0 {
			em.leanNames[ident(name)] = name
		}
	}
	// Every ordinary function is a candidate; the ones outside the subset
	// fail closed only when the extraction reaches them.
	candidates := map[string]*ast.FunctionStatement{}
	var declared []string
	for _, stmt := range program.Statements {
		if fn, ok := stmt.(*ast.FunctionStatement); ok && fn.Name != nil {
			candidates[fn.Name.Value] = fn
			declared = append(declared, fn.Name.Value)
		}
	}
	// The roots are the named declarations (all of them when names is
	// nil); the extraction closes over their callees, so a program that
	// calls into the standard library extracts the library functions it
	// uses (docs/spec/95-extraction.md section 4).
	var functionOrder []string
	queue := []string{}
	for _, name := range declared {
		if names == nil || names[name] {
			queue = append(queue, name)
		}
	}
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if _, done := em.functions[name]; done {
			continue
		}
		fn := candidates[name]
		if fn.Receiver != nil || len(fn.TypeParams) != 0 || fn.ExternSymbol != "" || fn.Body == nil {
			return "", fmt.Errorf("lean: %s: methods, generics, and extern functions are outside the extracted subset", name)
		}
		em.functions[name] = fn
		functionOrder = append(functionOrder, name)
		for _, callee := range em.callees(fn) {
			if _, known := candidates[callee]; known {
				queue = append(queue, callee)
			}
		}
	}
	ordered, err := em.dependencyOrder(functionOrder)
	if err != nil {
		return "", err
	}
	var functions strings.Builder
	for _, name := range ordered {
		text, err := em.emitFunction(em.functions[name])
		if err != nil {
			return "", err
		}
		functions.WriteString(text)
		functions.WriteString("\n")
	}
	globalsText, err := em.emitGlobals()
	if err != nil {
		return "", err
	}
	typeRoots := map[string]bool{}
	for name := range em.adts {
		if names == nil || names[name] {
			typeRoots[name] = true
		}
	}
	var out strings.Builder
	out.WriteString("-- Generated by the Oak compiler (codegen/lean): do not edit.\n")
	out.WriteString("-- Extracted from the type-checked program; docs/spec/95-extraction.md\n")
	out.WriteString("-- states the translation and its modeling choices.\n\n")
	out.WriteString("set_option autoImplicit false\n")
	// Straight-line translation rebinds and returns variables the source
	// never reads again; that is the source's shape, not a defect.
	out.WriteString("set_option linter.unusedVariables false\n")
	// An unrolled function (a hash compression round) is one long do-block;
	// the elaborator's default recursion limit is sized for hand-written code.
	out.WriteString("set_option maxRecDepth 65536\n")
	// The code generator's budget is sized the same way; an unrolled
	// compression function is one definition with hundreds of binds.
	out.WriteString("set_option maxHeartbeats 4000000\n")
	fmt.Fprintf(&out, "namespace %s\n\n", namespace)
	for _, name := range em.orderedTypes(typeRoots) {
		adt := em.adts[name]
		var text string
		if isRecordADT(adt) {
			text, err = em.emitRecord(adt)
		} else {
			text, err = em.emitSum(adt)
		}
		if err != nil {
			return "", err
		}
		out.WriteString(text)
		out.WriteString("\n")
	}
	out.WriteString(globalsText)
	out.WriteString(functions.String())
	fmt.Fprintf(&out, "end %s\n", namespace)
	return out.String(), nil
}

// emitGlobals renders the top-level constants the extracted functions
// read, in declaration order, closing over the constants they mention. A
// global initializer is a pure term: one that needs a call fails closed.
func (em *emitter) emitGlobals() (string, error) {
	rendered := map[string]string{}
	for {
		progressed := false
		for _, name := range em.globalOrder {
			if !em.usedGlobals[name] || rendered[name] != "" {
				continue
			}
			decl := em.globals[name]
			var typ string
			var err error
			if decl.Type != nil {
				typ, err = em.leanType(decl.Type)
			} else if declared := em.env.CheckedDeclarationType(decl); declared != nil {
				typ, err = em.leanTypeOf(declared)
			} else {
				err = fmt.Errorf("global %s has no type", name)
			}
			if err != nil {
				return "", fmt.Errorf("lean: %w", err)
			}
			em.fnName = name
			em.scope = newScope(nil)
			var hoisted []string
			em.hoisted = &hoisted
			term, err := em.expr(decl.Value, typ)
			em.hoisted = nil
			if err != nil {
				return "", fmt.Errorf("lean: global %s: %w", name, err)
			}
			if len(hoisted) != 0 {
				return "", fmt.Errorf("lean: global %s: an initializer that calls a function is outside the extracted subset", name)
			}
			rendered[name] = fmt.Sprintf("def %s : %s := %s\n\n", ident(name), typ, term)
			progressed = true
		}
		if !progressed {
			break
		}
	}
	var out strings.Builder
	for _, name := range em.globalOrder {
		out.WriteString(rendered[name])
	}
	return out.String(), nil
}

type emitter struct {
	tc  *typechecker.TypeChecker
	env *typechecker.TypeEnvironment
	// adts holds every ADT declaration of the program plus every recorded
	// generic instantiation, specialized; templates are never emitted.
	adts      map[string]*ast.ADTType
	typeOrder []string
	// records is the record-shaped subset of adts (one field-list variant).
	records   map[string]*ast.ADTType
	usedTypes map[string]bool
	// leanNames maps a Lean type name back to the ADT it renders.
	leanNames map[string]string
	functions map[string]*ast.FunctionStatement
	// globals holds the program's initialized top-level bindings; the ones
	// the extracted functions read are emitted as Lean definitions.
	globals     map[string]*ast.VariableDeclaration
	globalOrder []string
	usedGlobals map[string]bool

	// Per-function state.
	fnName  string
	scope   *scope
	helpers []string // loop helpers, innermost first
	loops   int
	temps   int
	// hoisted collects the do-lines a statement's expressions need before
	// the statement itself (calls bound with <-).
	hoisted *[]string
	indent  string
}

// scope is the ordered set of Lean-visible variables with their Lean types.
type scope struct {
	names []string
	types map[string]string
	outer *scope
}

func newScope(outer *scope) *scope { return &scope{types: map[string]string{}, outer: outer} }

func (s *scope) declare(name, typ string) {
	if _, exists := s.types[name]; !exists {
		s.names = append(s.names, name)
	}
	s.types[name] = typ
}

func (s *scope) lookup(name string) (string, bool) {
	for cur := s; cur != nil; cur = cur.outer {
		if typ, ok := cur.types[name]; ok {
			return typ, true
		}
	}
	return "", false
}

// ordered lists every visible variable, outermost scope first.
func (s *scope) ordered() []string {
	if s == nil {
		return nil
	}
	return append(s.outer.ordered(), s.names...)
}

// dependencyOrder sorts functions so callees precede callers; recursion is
// outside the subset.
func (em *emitter) dependencyOrder(names []string) ([]string, error) {
	var ordered []string
	state := map[string]int{}
	var visit func(name string, path []string) error
	visit = func(name string, path []string) error {
		switch state[name] {
		case 2:
			return nil
		case 1:
			return fmt.Errorf("lean: recursive functions are outside the extracted subset: %s", strings.Join(append(path, name), " -> "))
		}
		state[name] = 1
		for _, callee := range em.callees(em.functions[name]) {
			if _, known := em.functions[callee]; known {
				if err := visit(callee, append(path, name)); err != nil {
					return err
				}
			}
		}
		state[name] = 2
		ordered = append(ordered, name)
		return nil
	}
	for _, name := range names {
		if err := visit(name, nil); err != nil {
			return nil, err
		}
	}
	return ordered, nil
}

func (em *emitter) callees(fn *ast.FunctionStatement) []string {
	seen := map[string]bool{}
	var names []string
	walkExpressions(fn.Body, func(e ast.Expression) {
		if call, ok := e.(*ast.InvocationExpression); ok {
			if ident, ok := call.Function.(*ast.Identifier); ok && !seen[ident.Value] {
				seen[ident.Value] = true
				names = append(names, ident.Value)
			}
		}
	})
	sort.Strings(names)
	return names
}

// ---- types ----

var primitiveLean = map[string]string{
	"u8": "UInt8", "u16": "UInt16", "u32": "UInt32", "u64": "UInt64",
	"i8": "Int8", "i16": "Int16", "i32": "Int32", "i64": "Int64",
	"Bool": "Bool", "()": "Unit",
}

// leanType renders an Oak type expression.
func (em *emitter) leanType(expr ast.Expression) (string, error) {
	switch t := expr.(type) {
	case *ast.Identifier:
		if lean, ok := primitiveLean[t.Value]; ok {
			return lean, nil
		}
		if lean, ok := em.adtLeanName(t.Value); ok {
			return lean, nil
		}
		return "", fmt.Errorf("lean: type %s is outside the extracted subset", t.Value)
	case *ast.IndexExpression:
		if t.Dot {
			return "", fmt.Errorf("lean: qualified type %s is outside the extracted subset", t.String())
		}
		// A generic ADT applied to its arguments is the recorded
		// instantiation under its mangled name.
		if mangled, isApplication := em.applicationName(t); isApplication {
			if lean, ok := em.adtLeanName(mangled); ok {
				return lean, nil
			}
			return "", fmt.Errorf("lean: instantiation %s was not recorded by the checker", t.String())
		}
		// [N]T, []T, [*]T all become Array T.
		element, err := em.leanType(t.Left)
		if err != nil {
			return "", err
		}
		return "Array " + element, nil
	}
	return "", fmt.Errorf("lean: type %s is outside the extracted subset", expr.String())
}

// leanTypeOf renders a checked type.
func (em *emitter) leanTypeOf(typ typechecker.Type) (string, error) {
	switch t := typ.(type) {
	case *typechecker.PrimitiveType:
		if lean, ok := primitiveLean[t.Name]; ok {
			return lean, nil
		}
		if lean, ok := primitiveLean[normalizePrimitive(t.Name)]; ok {
			return lean, nil
		}
	case *typechecker.BoolType:
		return "Bool", nil
	case *typechecker.UnitType:
		return "Unit", nil
	case *typechecker.ArrayType:
		element, err := em.leanTypeOf(t.ElementType)
		if err != nil {
			return "", err
		}
		return "Array " + element, nil
	case *typechecker.RecordType:
		if t.Name != "" {
			if lean, ok := em.adtLeanName(t.Name); ok {
				return lean, nil
			}
			return ident(t.Name), nil
		}
	case *typechecker.ADTType, *typechecker.GenericType, *typechecker.NarrowedADTVariantType:
		if name, ok := em.adtOfChecked(t); ok {
			if lean, isADT := em.adtLeanName(name); isADT {
				return lean, nil
			}
		}
	}
	return "", fmt.Errorf("lean: checked type %v is outside the extracted subset", typ)
}

func normalizePrimitive(name string) string {
	switch name {
	case "byte":
		return "u8"
	case "rune":
		return "u32"
	}
	return name
}

// zeroOf is the default value of a Lean type.
func zeroOf(leanType string) string {
	switch {
	case leanType == "Bool":
		return "false"
	case leanType == "Unit":
		return "()"
	case strings.HasPrefix(leanType, "UInt") || strings.HasPrefix(leanType, "Int"):
		return "(0 : " + leanType + ")"
	case strings.HasPrefix(leanType, "Array "):
		return "(#[] : " + leanType + ")"
	default:
		return "(default : " + leanType + ")"
	}
}

func elementOf(leanType string) (string, bool) {
	if strings.HasPrefix(leanType, "Array ") {
		return strings.TrimPrefix(leanType, "Array "), true
	}
	return "", false
}

// ---- records ----

func (em *emitter) emitRecord(adt *ast.ADTType) (string, error) {
	record := adt.Variants[0].Literal.(*ast.RecordLiteral)
	var out strings.Builder
	fmt.Fprintf(&out, "structure %s where\n", ident(adt.Name.Value))
	for _, field := range record.FieldOrder {
		typ, err := em.leanType(field.Value)
		if err != nil {
			return "", fmt.Errorf("lean: %s.%s: %w", adt.Name.Value, field.Name, err)
		}
		fmt.Fprintf(&out, "  %s : %s\n", ident(field.Name), typ)
	}
	out.WriteString("  deriving Repr, Inhabited, BEq, DecidableEq\n")
	return out.String(), nil
}

// ---- functions ----

// spanParams lists the indices of a function's span parameters — the
// storage it writes and therefore returns.
func spanParams(fn *ast.FunctionStatement) []int {
	var spans []int
	for i, p := range fn.Parameters {
		if isSpanType(p.Type) {
			spans = append(spans, i)
		}
	}
	return spans
}

func isSpanType(expr ast.Expression) bool {
	index, ok := expr.(*ast.IndexExpression)
	if !ok || index.Dot {
		return false
	}
	marker, ok := index.Index.(*ast.Identifier)
	return ok && marker.Value == "*"
}

func (em *emitter) emitFunction(fn *ast.FunctionStatement) (string, error) {
	em.fnName = fn.Name.Value
	em.scope = newScope(nil)
	em.helpers = nil
	em.loops = 0
	em.temps = 0

	var params []string
	for _, p := range fn.Parameters {
		if p.Variadic {
			return "", fmt.Errorf("lean: %s: variadic parameters are outside the extracted subset", fn.Name.Value)
		}
		typ, err := em.leanType(p.Type)
		if err != nil {
			return "", fmt.Errorf("lean: %s: parameter %s: %w", fn.Name.Value, p.Name.Value, err)
		}
		em.scope.declare(p.Name.Value, typ)
		params = append(params, fmt.Sprintf("(%s : %s)", ident(p.Name.Value), typ))
	}
	returnType := "Unit"
	if fn.ReturnType != nil {
		var err error
		if returnType, err = em.leanType(fn.ReturnType); err != nil {
			return "", fmt.Errorf("lean: %s: return type: %w", fn.Name.Value, err)
		}
	}
	resultTypes := []string{returnType}
	var spanNames []string
	for _, i := range spanParams(fn) {
		typ, _ := em.scope.lookup(fn.Parameters[i].Name.Value)
		resultTypes = append(resultTypes, typ)
		spanNames = append(spanNames, ident(fn.Parameters[i].Name.Value))
	}

	body := newScope(em.scope)
	em.scope = body
	var lines []string
	em.indent = "  "
	statements, result, err := em.functionBody(fn, returnType)
	if err != nil {
		return "", err
	}
	if err := em.block(statements, &lines); err != nil {
		return "", fmt.Errorf("lean: %s: %w", fn.Name.Value, err)
	}
	resultTerm := "()"
	if result != nil {
		var hoisted []string
		em.hoisted = &hoisted
		term, err := em.expr(result, returnType)
		em.hoisted = nil
		if err != nil {
			return "", fmt.Errorf("lean: %s: result: %w", fn.Name.Value, err)
		}
		lines = append(lines, hoisted...)
		resultTerm = term
	}
	lines = append(lines, em.indent+"pure "+tuple(append([]string{resultTerm}, spanNames...)))

	var out strings.Builder
	for _, helper := range em.helpers {
		out.WriteString(helper)
		out.WriteString("\n")
	}
	fmt.Fprintf(&out, "def %s %s (fuel : Nat) : Option %s := do\n", ident(fn.Name.Value), strings.Join(params, " "), tupleType(resultTypes))
	out.WriteString(strings.Join(lines, "\n"))
	out.WriteString("\n")
	return out.String(), nil
}

// functionBody splits a body into its statements and result expression.
func (em *emitter) functionBody(fn *ast.FunctionStatement, returnType string) ([]ast.Statement, ast.Expression, error) {
	block, isBlock := fn.Body.(*ast.BlockExpression)
	if !isBlock {
		return nil, fn.Body, nil
	}
	if block.Block == nil {
		return nil, nil, nil
	}
	statements := block.Block.Statements
	if returnType == "Unit" || len(statements) == 0 {
		return statements, nil, nil
	}
	last, isExpr := statements[len(statements)-1].(*ast.ExpressionStatement)
	if !isExpr {
		return nil, nil, fmt.Errorf("lean: %s: body does not end in its result expression", fn.Name.Value)
	}
	return statements[:len(statements)-1], last.Expression, nil
}

func tuple(items []string) string {
	if len(items) == 1 {
		return items[0]
	}
	return "(" + strings.Join(items, ", ") + ")"
}

func tupleType(items []string) string {
	if len(items) == 1 {
		return "(" + items[0] + ")"
	}
	return "(" + strings.Join(items, " × ") + ")"
}

// ---- statements ----

// block emits statements as do-lines at the current indent.
func (em *emitter) block(statements []ast.Statement, lines *[]string) error {
	for _, stmt := range statements {
		if err := em.statement(stmt, lines); err != nil {
			return err
		}
	}
	return nil
}

func (em *emitter) statement(stmt ast.Statement, lines *[]string) error {
	var hoisted []string
	em.hoisted = &hoisted
	defer func() { em.hoisted = nil }()
	emit := func(format string, args ...any) {
		*lines = append(*lines, hoisted...)
		hoisted = nil
		*lines = append(*lines, em.indent+fmt.Sprintf(format, args...))
	}
	switch s := stmt.(type) {
	case *ast.VariableDeclaration:
		var typ string
		var err error
		if s.Type != nil {
			typ, err = em.leanType(s.Type)
		} else if declared := em.env.CheckedDeclarationType(s); declared != nil {
			typ, err = em.leanTypeOf(declared)
		} else {
			err = fmt.Errorf("declaration %s has no type", s.Name.Value)
		}
		if err != nil {
			return err
		}
		if s.Value == nil {
			emit("let %s : %s := %s", ident(s.Name.Value), typ, em.initialValue(s.Type, typ))
		} else {
			term, err := em.expr(s.Value, typ)
			if err != nil {
				return err
			}
			emit("let %s : %s := %s", ident(s.Name.Value), typ, term)
		}
		em.scope.declare(s.Name.Value, typ)
		return nil
	case *ast.AssignmentStatement:
		typ, ok := em.scope.lookup(s.Name.Value)
		if !ok {
			return fmt.Errorf("assignment to unknown variable %s", s.Name.Value)
		}
		term, err := em.expr(s.Value, typ)
		if err != nil {
			return err
		}
		emit("let %s := %s", ident(s.Name.Value), term)
		return nil
	case *ast.IndexAssignmentStatement:
		if s.Target.Dot {
			base, ok := s.Target.Left.(*ast.Identifier)
			field, isField := s.Target.Index.(*ast.Identifier)
			if !ok || !isField {
				return fmt.Errorf("field assignment %s is outside the extracted subset (one level of fields)", s.Target.String())
			}
			fieldType, err := em.fieldType(base.Value, field.Value)
			if err != nil {
				return err
			}
			term, err := em.expr(s.Value, fieldType)
			if err != nil {
				return err
			}
			emit("let %s := { %s with %s := %s }", ident(base.Value), ident(base.Value), ident(field.Value), term)
			return nil
		}
		if fieldAccess, isField := s.Target.Left.(*ast.IndexExpression); isField && fieldAccess.Dot {
			// r.field[i] = v: the field's array is updated and written back
			// into the record (one level of fields, as for field assignment).
			record, isIdent := fieldAccess.Left.(*ast.Identifier)
			field, isName := fieldAccess.Index.(*ast.Identifier)
			if !isIdent || !isName {
				return fmt.Errorf("element assignment into %s is outside the extracted subset (one level of fields)", s.Target.Left.String())
			}
			fieldType, err := em.fieldType(record.Value, field.Value)
			if err != nil {
				return err
			}
			element, isArray := elementOf(fieldType)
			if !isArray {
				return fmt.Errorf("element assignment into non-array field %s", s.Target.Left.String())
			}
			index, err := em.indexTerm(s.Target.Index)
			if err != nil {
				return err
			}
			term, err := em.expr(s.Value, element)
			if err != nil {
				return err
			}
			emit("let %s := { %s with %s := %s.%s.setIfInBounds %s %s }", ident(record.Value), ident(record.Value), ident(field.Value), ident(record.Value), ident(field.Value), index, term)
			return nil
		}
		base, ok := s.Target.Left.(*ast.Identifier)
		if !ok {
			return fmt.Errorf("element assignment into %s is outside the extracted subset", s.Target.Left.String())
		}
		arrayType, known := em.scope.lookup(base.Value)
		element, isArray := elementOf(arrayType)
		if !known || !isArray {
			return fmt.Errorf("element assignment into non-array %s", base.Value)
		}
		index, err := em.indexTerm(s.Target.Index)
		if err != nil {
			return err
		}
		term, err := em.expr(s.Value, element)
		if err != nil {
			return err
		}
		emit("let %s := %s.setIfInBounds %s %s", ident(base.Value), ident(base.Value), index, term)
		return nil
	case *ast.WhileStatement:
		return em.whileStatement(s, lines, &hoisted)
	case *ast.ExpressionStatement:
		if match, ok := s.Expression.(*ast.MatchExpression); ok && (isBoolConditional(match) || isIntegerMatch(match)) {
			return em.conditionalStatement(match, lines, &hoisted)
		}
		if match, ok := s.Expression.(*ast.MatchExpression); ok && isVariantMatch(match) {
			return em.matchStatement(match, lines, &hoisted)
		}
		if call, ok := s.Expression.(*ast.InvocationExpression); ok {
			if callee, isIdent := call.Function.(*ast.Identifier); isIdent && callee.Value == "assert" && len(call.Arguments) == 1 {
				cond, err := em.expr(call.Arguments[0], "Bool")
				if err != nil {
					return err
				}
				emit("let () ← (if %s then pure () else none)", cond)
				return nil
			}
			// A call in statement position is evaluated for its span effects.
			if _, err := em.expr(call, ""); err != nil {
				return err
			}
			*lines = append(*lines, hoisted...)
			return nil
		}
		return fmt.Errorf("expression statement %s is outside the extracted subset", s.Expression.String())
	case *ast.BlockStatement:
		return em.block(s.Statements, lines)
	}
	return fmt.Errorf("statement %T is outside the extracted subset", stmt)
}

// initialValue is the zero value of a declared-without-initializer binding.
func (em *emitter) initialValue(typeExpr ast.Expression, leanType string) string {
	if index, ok := typeExpr.(*ast.IndexExpression); ok && !index.Dot {
		if length, isLiteral := index.Index.(*ast.IntegerLiteral); isLiteral {
			element, _ := elementOf(leanType)
			return fmt.Sprintf("Array.replicate %d %s", length.Value, zeroOf(element))
		}
	}
	return zeroOf(leanType)
}

func (em *emitter) fieldType(variable, field string) (string, error) {
	recordType, ok := em.scope.lookup(variable)
	if !ok {
		return "", fmt.Errorf("unknown variable %s", variable)
	}
	return em.recordFieldType(recordType, field)
}

func (em *emitter) recordFieldType(recordType, field string) (string, error) {
	adt, ok := em.records[recordType]
	if !ok {
		return "", fmt.Errorf("%s is not an extracted record", recordType)
	}
	record := adt.Variants[0].Literal.(*ast.RecordLiteral)
	for _, f := range record.FieldOrder {
		if f.Name == field {
			return em.leanType(f.Value)
		}
	}
	return "", fmt.Errorf("record %s has no field %s", recordType, field)
}

func isBoolConditional(match *ast.MatchExpression) bool {
	if len(match.Arms) != 2 {
		return false
	}
	for _, arm := range match.Arms {
		literal, ok := arm.Pattern.(*ast.LiteralPattern)
		if !ok {
			return false
		}
		if _, isBool := literal.Value.(*ast.Boolean); !isBool {
			return false
		}
	}
	return true
}

// isIntegerMatch recognizes a match on integer constants: every arm but
// the last a literal pattern over an integer, the last a literal or the
// wildcard. It extracts as a chain of equality tests against the scrutinee
// (docs/spec/95-extraction.md section 2).
func isIntegerMatch(match *ast.MatchExpression) bool {
	if len(match.Arms) < 2 {
		return false
	}
	for i, arm := range match.Arms {
		switch pattern := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			if _, isInt := pattern.Value.(*ast.IntegerLiteral); !isInt {
				return false
			}
		case *ast.WildcardPattern:
			if i != len(match.Arms)-1 {
				return false
			}
		case *ast.BindingPattern:
			// The parser spells `_` as a binding named "_"; a real binding
			// names the scrutinee and stays outside the subset.
			if i != len(match.Arms)-1 || pattern.Name == nil || pattern.Name.Value != "_" {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// branch is one guarded arm of a conditional chain; the final arm has no
// condition.
type branch struct {
	cond string
	body ast.Expression
}

// branches renders a Bool conditional or an integer-constant match as a
// chain of guarded arms ending in the unguarded one.
func (em *emitter) branches(match *ast.MatchExpression) ([]branch, error) {
	if isBoolConditional(match) {
		trueBody, falseBody := match.Arms[0].Body, match.Arms[1].Body
		if literal := match.Arms[0].Pattern.(*ast.LiteralPattern).Value.(*ast.Boolean); !literal.Value {
			trueBody, falseBody = falseBody, trueBody
		}
		cond, err := em.expr(match.Scrutinee, "Bool")
		if err != nil {
			return nil, err
		}
		return []branch{{cond, trueBody}, {"", falseBody}}, nil
	}
	typ := em.checkedLeanType(match.Scrutinee)
	scrutinee, err := em.expr(match.Scrutinee, typ)
	if err != nil {
		return nil, err
	}
	var chain []branch
	for i, arm := range match.Arms {
		if i == len(match.Arms)-1 {
			// The last arm is the else, whether a wildcard or the closing
			// literal of an exhaustive match.
			chain = append(chain, branch{"", arm.Body})
			break
		}
		literal := arm.Pattern.(*ast.LiteralPattern).Value.(*ast.IntegerLiteral)
		chain = append(chain, branch{fmt.Sprintf("(%s == %s)", scrutinee, literalTerm(literal.Value, typ)), arm.Body})
	}
	return chain, nil
}

// conditionalStatement emits a Bool conditional or integer-constant match
// whose arms are blocks: the variables any arm assigns are rebound from the
// chosen arm, through a chain of `if ... then (do ...) else if ...`.
func (em *emitter) conditionalStatement(match *ast.MatchExpression, lines *[]string, hoisted *[]string) error {
	chain, err := em.branches(match)
	if err != nil {
		return err
	}
	*lines = append(*lines, *hoisted...)
	*hoisted = nil
	var bodies []ast.Expression
	for _, b := range chain {
		bodies = append(bodies, b.body)
	}
	written := em.assignedOuter(bodies...)
	outs := tuple(identAll(written))
	if len(written) == 0 {
		outs = "()"
	}
	for i, b := range chain {
		switch {
		case i == 0:
			*lines = append(*lines, fmt.Sprintf("%slet %s ← (if %s then (do", em.indent, outs, b.cond))
		case b.cond != "":
			*lines = append(*lines, fmt.Sprintf("%s  else if %s then (do", em.indent, b.cond))
		default:
			*lines = append(*lines, em.indent+"  else (do")
		}
		saved := em.indent
		em.indent = saved + "    "
		var armLines []string
		if err := em.branchBody(b.body, &armLines); err != nil {
			return err
		}
		armLines = append(armLines, em.indent+"pure "+outs+")")
		em.indent = saved
		*lines = append(*lines, armLines...)
	}
	last := len(*lines) - 1
	(*lines)[last] += ")"
	return nil
}

// branchBody emits a conditional arm: a block's statements, or a single
// expression (evaluated for effects only in statement position).
func (em *emitter) branchBody(body ast.Expression, lines *[]string) error {
	switch b := body.(type) {
	case *ast.BlockExpression:
		if b.Block == nil {
			return nil
		}
		inner := newScope(em.scope)
		em.scope = inner
		err := em.block(b.Block.Statements, lines)
		em.scope = inner.outer
		return err
	case *ast.MatchExpression:
		if isBoolConditional(b) || isIntegerMatch(b) {
			var hoisted []string
			return em.conditionalStatement(b, lines, &hoisted)
		}
		if isVariantMatch(b) {
			var hoisted []string
			return em.matchStatement(b, lines, &hoisted)
		}
	}
	return fmt.Errorf("conditional arm %s is outside the extracted subset in statement position", body.String())
}

// whileStatement emits a loop as a fuel-indexed helper taking every outer
// variable the loop reads and returning every outer variable it writes.
func (em *emitter) whileStatement(loop *ast.WhileStatement, lines *[]string, hoisted *[]string) error {
	em.loops++
	name := fmt.Sprintf("%s.loop%d", ident(em.fnName), em.loops)
	reads := em.referencedOuter(loop.Condition, &ast.BlockExpression{Block: loop.Body})
	writes := em.assignedOuter(&ast.BlockExpression{Block: loop.Body})
	// Parameters: every referenced outer variable, in scope order.
	var params []string
	for _, v := range reads {
		typ, _ := em.scope.lookup(v)
		params = append(params, fmt.Sprintf("(%s : %s)", ident(v), typ))
	}
	var resultTypes []string
	for _, v := range writes {
		typ, _ := em.scope.lookup(v)
		resultTypes = append(resultTypes, typ)
	}
	outs := tuple(identAll(writes))
	if len(writes) == 0 {
		outs = "()"
		resultTypes = []string{"Unit"}
	}

	// The helper body is emitted in a scope holding only its parameters.
	savedScope, savedIndent, savedHoisted := em.scope, em.indent, em.hoisted
	helperScope := newScope(nil)
	for _, v := range reads {
		typ, _ := savedScope.lookup(v)
		helperScope.declare(v, typ)
	}
	em.scope = newScope(helperScope)
	em.indent = "    "
	var condHoisted []string
	em.hoisted = &condHoisted
	cond, err := em.expr(loop.Condition, "Bool")
	em.hoisted = nil
	if err != nil {
		em.scope, em.indent, em.hoisted = savedScope, savedIndent, savedHoisted
		return err
	}
	var bodyLines []string
	em.indent = "      "
	if err := em.block(loop.Body.Statements, &bodyLines); err != nil {
		em.scope, em.indent, em.hoisted = savedScope, savedIndent, savedHoisted
		return err
	}
	em.scope, em.indent, em.hoisted = savedScope, savedIndent, savedHoisted

	var helper strings.Builder
	fmt.Fprintf(&helper, "def %s %s : Nat → Option %s\n", name, strings.Join(params, " "), tupleType(resultTypes))
	helper.WriteString("  | 0 => none\n")
	helper.WriteString("  | fuel + 1 => do\n")
	for _, line := range condHoisted {
		helper.WriteString(line + "\n")
	}
	fmt.Fprintf(&helper, "    if %s then do\n", cond)
	for _, line := range bodyLines {
		helper.WriteString(line + "\n")
	}
	fmt.Fprintf(&helper, "      %s %s fuel\n", name, strings.Join(identAll(reads), " "))
	fmt.Fprintf(&helper, "    else pure %s\n", outs)
	em.helpers = append(em.helpers, helper.String())

	*lines = append(*lines, *hoisted...)
	*hoisted = nil
	*lines = append(*lines, fmt.Sprintf("%slet %s ← %s %s fuel", em.indent, outs, name, strings.Join(identAll(reads), " ")))
	return nil
}

// assignedOuter lists the variables in the current scope chain that the
// given expressions assign (directly, by element or field, or as a span
// argument), in scope order.
func (em *emitter) assignedOuter(bodies ...ast.Expression) []string {
	written := map[string]bool{}
	declaredInside := map[string]bool{}
	for _, body := range bodies {
		walkStatements(body, func(stmt ast.Statement) {
			switch s := stmt.(type) {
			case *ast.VariableDeclaration:
				declaredInside[s.Name.Value] = true
			case *ast.AssignmentStatement:
				written[s.Name.Value] = true
			case *ast.IndexAssignmentStatement:
				if root := rootIdentifier(s.Target); root != "" {
					written[root] = true
				}
			}
		})
		walkExpressions(body, func(e ast.Expression) {
			if call, ok := e.(*ast.InvocationExpression); ok {
				for _, owner := range spanArguments(call) {
					written[owner] = true
				}
			}
		})
	}
	var result []string
	for _, name := range em.scope.ordered() {
		if written[name] && !declaredInside[name] {
			result = append(result, name)
		}
	}
	return result
}

// referencedOuter lists the outer variables the expressions mention.
func (em *emitter) referencedOuter(bodies ...ast.Expression) []string {
	mentioned := map[string]bool{}
	for _, body := range bodies {
		walkExpressions(body, func(e ast.Expression) {
			if id, ok := e.(*ast.Identifier); ok {
				mentioned[id.Value] = true
			}
		})
		walkStatements(body, func(stmt ast.Statement) {
			switch s := stmt.(type) {
			case *ast.AssignmentStatement:
				mentioned[s.Name.Value] = true
			case *ast.IndexAssignmentStatement:
				if root := rootIdentifier(s.Target); root != "" {
					mentioned[root] = true
				}
			}
		})
	}
	var result []string
	for _, name := range em.scope.ordered() {
		if mentioned[name] {
			result = append(result, name)
		}
	}
	return result
}

func rootIdentifier(expr ast.Expression) string {
	switch e := expr.(type) {
	case *ast.Identifier:
		return e.Value
	case *ast.IndexExpression:
		return rootIdentifier(e.Left)
	}
	return ""
}

// spanArguments names the owners a call writes through span(&owner)
// arguments or span variables.
func spanArguments(call *ast.InvocationExpression) []string {
	var owners []string
	for _, arg := range call.Arguments {
		if inner, ok := arg.(*ast.InvocationExpression); ok {
			if callee, isIdent := inner.Function.(*ast.Identifier); isIdent && callee.Value == "span" && len(inner.Arguments) == 1 {
				if owner := addressOf(inner.Arguments[0]); owner != "" {
					owners = append(owners, owner)
				}
			}
		}
	}
	return owners
}

func addressOf(expr ast.Expression) string {
	prefix, ok := expr.(*ast.PrefixExpression)
	if !ok || prefix.Operator != "&" {
		return ""
	}
	if id, isIdent := prefix.Right.(*ast.Identifier); isIdent {
		return id.Value
	}
	return ""
}

// ---- expressions ----

// expr renders an expression as a pure Lean term; calls are hoisted into
// the current statement's preceding lines. want is the Lean type the
// context expects, used to type integer literals.
// arrayLiteralTerm renders an array literal. Lean elaborates `#[...]`
// through a nested list literal, so a long table (a 2048-entry CRC table)
// exceeds the default recursion depth as one literal; it is emitted as a
// concatenation of chunks instead, which denotes the same array.
func arrayLiteralTerm(terms []string, element string) string {
	const chunk = 128
	if len(terms) <= chunk {
		return fmt.Sprintf("(#[%s] : Array %s)", strings.Join(terms, ", "), element)
	}
	var chunks []string
	for start := 0; start < len(terms); start += chunk {
		end := start + chunk
		if end > len(terms) {
			end = len(terms)
		}
		chunks = append(chunks, fmt.Sprintf("#[%s]", strings.Join(terms[start:end], ", ")))
	}
	return fmt.Sprintf("((%s) : Array %s)", strings.Join(chunks, " ++ "), element)
}

// literalTerm renders an integer literal at a Lean type. The parser stores
// every literal in an int64, so an unsigned constant above 2^63 - 1 arrives
// wrapped negative and is printed back as the unsigned value it spells.
func literalTerm(value int64, typ string) string {
	if value < 0 && strings.HasPrefix(typ, "UInt") {
		return fmt.Sprintf("(%d : %s)", uint64(value), typ)
	}
	return fmt.Sprintf("(%d : %s)", value, typ)
}

// leanIntWidth is the bit width of a Lean fixed-width integer type name,
// and whether it is signed.
func leanIntWidth(name string) (int, bool, bool) {
	switch name {
	case "UInt8":
		return 8, false, true
	case "UInt16":
		return 16, false, true
	case "UInt32":
		return 32, false, true
	case "UInt64":
		return 64, false, true
	case "Int8":
		return 8, true, true
	case "Int16":
		return 16, true, true
	case "Int32":
		return 32, true, true
	case "Int64":
		return 64, true, true
	}
	return 0, false, false
}

// expr renders an expression where a value of Lean type `want` is expected
// (or "" when the context fixes nothing). Oak widens a narrower integer of
// the same signedness implicitly (docs/spec/20-types.md section 11.1); the
// extraction makes that widening explicit with the `toUIntN`/`toIntN` of
// the wanted type, since Lean has no such coercion.
func (em *emitter) expr(expr ast.Expression, want string) (string, error) {
	term, err := em.exprValue(expr, want)
	if err != nil {
		return "", err
	}
	wantBits, wantSigned, wantInt := leanIntWidth(want)
	if !wantInt {
		return term, nil
	}
	have := em.checkedLeanType(expr)
	haveBits, haveSigned, haveInt := leanIntWidth(have)
	if !haveInt || have == want || haveSigned != wantSigned || haveBits >= wantBits {
		return term, nil
	}
	return fmt.Sprintf("(%s.to%s)", term, want), nil
}

func (em *emitter) exprValue(expr ast.Expression, want string) (string, error) {
	switch e := expr.(type) {
	case *ast.IntegerLiteral:
		typ := want
		if checked := em.checkedLeanType(e); checked != "" {
			typ = checked
		}
		if typ == "" {
			return "", fmt.Errorf("integer literal %d has no type in context", e.Value)
		}
		return literalTerm(e.Value, typ), nil
	case *ast.Boolean:
		if e.Value {
			return "true", nil
		}
		return "false", nil
	case *ast.Identifier:
		if _, ok := em.scope.lookup(e.Value); !ok {
			if _, isGlobal := em.globals[e.Value]; isGlobal {
				em.usedGlobals[e.Value] = true
				return ident(e.Value), nil
			}
			return "", fmt.Errorf("identifier %s is not a variable in scope", e.Value)
		}
		return ident(e.Value), nil
	case *ast.PrefixExpression:
		switch e.Operator {
		case "!":
			inner, err := em.expr(e.Right, "Bool")
			if err != nil {
				return "", err
			}
			return "(!" + inner + ")", nil
		case "-":
			typ := em.checkedLeanType(e)
			if typ == "" {
				typ = want
			}
			inner, err := em.expr(e.Right, typ)
			if err != nil {
				return "", err
			}
			return "(0 - " + inner + ")", nil
		case "^":
			// Bitwise complement over the operand's width.
			typ := em.checkedLeanType(e)
			if typ == "" {
				typ = want
			}
			inner, err := em.expr(e.Right, typ)
			if err != nil {
				return "", err
			}
			return "(~~~" + inner + ")", nil
		}
		return "", fmt.Errorf("prefix %s is outside the extracted subset", e.Operator)
	case *ast.InfixExpression:
		return em.infix(e, want)
	case *ast.IndexExpression:
		if e.Dot {
			field, ok := e.Index.(*ast.Identifier)
			if !ok {
				return "", fmt.Errorf("field access %s is outside the extracted subset", e.String())
			}
			base, err := em.expr(e.Left, "")
			if err != nil {
				return "", err
			}
			return base + "." + ident(field.Value), nil
		}
		base, err := em.expr(e.Left, "")
		if err != nil {
			return "", err
		}
		element := em.elementTypeOf(e.Left)
		if element == "" {
			return "", fmt.Errorf("indexing %s: element type unknown", e.Left.String())
		}
		index, err := em.indexTerm(e.Index)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s.getD %s %s)", base, index, zeroOf(element)), nil
	case *ast.SliceExpression:
		base, err := em.expr(e.Seq, "")
		if err != nil {
			return "", err
		}
		low := "0"
		if e.Low != nil {
			if low, err = em.indexTerm(e.Low); err != nil {
				return "", err
			}
		}
		high := base + ".size"
		if e.High != nil {
			if high, err = em.indexTerm(e.High); err != nil {
				return "", err
			}
		}
		return fmt.Sprintf("(%s.extract %s %s)", base, low, high), nil
	case *ast.ArrayLiteral:
		// [N]T{ e1, ..., eN } is the Lean array literal; the element type
		// comes from the literal's own type, else from the context.
		arrayType := want
		if e.Type != nil {
			typ, err := em.leanType(e.Type)
			if err != nil {
				return "", err
			}
			arrayType = typ
		}
		element, isArray := elementOf(arrayType)
		if !isArray {
			if checked := em.checkedLeanType(e); checked != "" {
				element, isArray = elementOf(checked)
			}
		}
		if !isArray {
			return "", fmt.Errorf("array literal has no element type in context")
		}
		terms := make([]string, 0, len(e.Elements))
		for _, item := range e.Elements {
			term, err := em.expr(item, element)
			if err != nil {
				return "", err
			}
			terms = append(terms, term)
		}
		return arrayLiteralTerm(terms, element), nil
	case *ast.RecordLiteral:
		if e.TypeName == nil {
			return "", fmt.Errorf("record literal without a type name is outside the extracted subset")
		}
		var fields []string
		for _, field := range e.FieldOrder {
			fieldType, err := em.recordFieldType(e.TypeName.Value, field.Name)
			if err != nil {
				return "", err
			}
			term, err := em.expr(field.Value, fieldType)
			if err != nil {
				return "", err
			}
			fields = append(fields, fmt.Sprintf("%s := %s", ident(field.Name), term))
		}
		return fmt.Sprintf("({ %s } : %s)", strings.Join(fields, ", "), ident(e.TypeName.Value)), nil
	case *ast.VariantExpression:
		return em.variant(e, want)
	case *ast.MatchExpression:
		variantMatch := isVariantMatch(e)
		if !isBoolConditional(e) && !isIntegerMatch(e) && !variantMatch {
			return "", fmt.Errorf("match %s is outside the extracted subset (Bool conditionals, integer-constant matches, and variant matches only)", e.String())
		}
		for _, arm := range e.Arms {
			if em.needsDo(arm.Body) {
				return em.doValue(e, want)
			}
		}
		if variantMatch {
			return em.matchValue(e, want)
		}
		chain, err := em.branches(e)
		if err != nil {
			return "", err
		}
		var out strings.Builder
		out.WriteString("(")
		for i, b := range chain {
			value, err := em.armValue(b.body, want)
			if err != nil {
				return "", err
			}
			if b.cond == "" {
				out.WriteString("else " + value)
				break
			}
			if i > 0 {
				out.WriteString("else ")
			}
			out.WriteString(fmt.Sprintf("if %s then %s ", b.cond, value))
		}
		out.WriteString(")")
		return out.String(), nil
	case *ast.BlockExpression:
		return em.armValue(e, want)
	case *ast.InvocationExpression:
		return em.call(e, want)
	}
	return "", fmt.Errorf("expression %T is outside the extracted subset", expr)
}

// armValue renders a value-position conditional arm: an expression, or a
// block whose only statement is its result.
func (em *emitter) armValue(body ast.Expression, want string) (string, error) {
	block, isBlock := body.(*ast.BlockExpression)
	if !isBlock {
		return em.expr(body, want)
	}
	if block.Block == nil || len(block.Block.Statements) != 1 {
		return "", fmt.Errorf("value-position block with statements must be bound through a do-block")
	}
	stmt, ok := block.Block.Statements[0].(*ast.ExpressionStatement)
	if !ok {
		return "", fmt.Errorf("value-position block with statements must be bound through a do-block")
	}
	return em.expr(stmt.Expression, want)
}

func (em *emitter) infix(e *ast.InfixExpression, want string) (string, error) {
	switch e.Operator {
	case "&&", "||":
		left, err := em.expr(e.Left, "Bool")
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, "Bool")
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	case "==", "!=", "<", "<=", ">", ">=":
		operand := em.checkedLeanType(e.Left)
		if operand == "" {
			operand = em.checkedLeanType(e.Right)
		}
		left, err := em.expr(e.Left, operand)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, operand)
		if err != nil {
			return "", err
		}
		switch e.Operator {
		case "==":
			return fmt.Sprintf("(%s == %s)", left, right), nil
		case "!=":
			return fmt.Sprintf("(%s != %s)", left, right), nil
		}
		return fmt.Sprintf("(decide (%s %s %s))", left, e.Operator, right), nil
	case "&", "|", "^", "<<", ">>":
		// Bitwise operators over one fixed width. Oak traps on a shift count
		// reaching the operand width (10-syntax.md section 3b); Lean masks
		// the count, which is the same on every run that produced a result
		// (docs/spec/95-extraction.md section 3).
		typ := em.checkedLeanType(e)
		if typ == "" {
			typ = em.checkedLeanType(e.Left)
		}
		if typ == "" {
			typ = want
		}
		left, err := em.expr(e.Left, typ)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, typ)
		if err != nil {
			return "", err
		}
		leanOp := map[string]string{"&": "&&&", "|": "|||", "^": "^^^", "<<": "<<<", ">>": ">>>"}[e.Operator]
		return fmt.Sprintf("(%s %s %s)", left, leanOp, right), nil
	case "+", "-", "*", "/", "%":
		typ := em.checkedLeanType(e)
		if typ == "" {
			typ = em.checkedLeanType(e.Left)
		}
		if typ == "" {
			typ = em.checkedLeanType(e.Right)
		}
		if typ == "" {
			typ = want
		}
		left, err := em.expr(e.Left, typ)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, typ)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	}
	return "", fmt.Errorf("operator %s is outside the extracted subset", e.Operator)
}

// indexTerm renders an index as a Nat.
func (em *emitter) indexTerm(index ast.Expression) (string, error) {
	if literal, ok := index.(*ast.IntegerLiteral); ok {
		return fmt.Sprintf("%d", literal.Value), nil
	}
	typ := em.checkedLeanType(index)
	if typ == "" {
		typ = "UInt32"
	}
	term, err := em.expr(index, typ)
	if err != nil {
		return "", err
	}
	return term + ".toNat", nil
}

// call renders a builtin or a user function call; user calls are hoisted.
func (em *emitter) call(call *ast.InvocationExpression, want string) (string, error) {
	callee, ok := call.Function.(*ast.Identifier)
	if !ok {
		return "", fmt.Errorf("call through %s is outside the extracted subset", call.Function.String())
	}
	switch callee.Value {
	case "len":
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("len takes one argument")
		}
		base, err := em.expr(call.Arguments[0], "")
		if err != nil {
			return "", err
		}
		return "(" + base + ".size.toUInt32)", nil
	case "view", "span":
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("%s takes one argument", callee.Value)
		}
		owner := addressOf(call.Arguments[0])
		if owner == "" {
			return "", fmt.Errorf("%s of %s is outside the extracted subset", callee.Value, call.Arguments[0].String())
		}
		if _, known := em.scope.lookup(owner); !known {
			// A view of a top-level constant is the constant's array value;
			// a writable span of one would mutate the global and fails closed.
			if _, isGlobal := em.globals[owner]; isGlobal && callee.Value == "view" {
				em.usedGlobals[owner] = true
				return ident(owner), nil
			}
			if _, isGlobal := em.globals[owner]; isGlobal {
				return "", fmt.Errorf("span of the global %s is outside the extracted subset (globals are read-only constants here)", owner)
			}
			return "", fmt.Errorf("%s of unknown owner %s", callee.Value, owner)
		}
		return ident(owner), nil
	case "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64":
		if len(call.Arguments) != 1 {
			return "", fmt.Errorf("%s takes one argument", callee.Value)
		}
		target := primitiveLean[callee.Value]
		if literal, isLiteral := call.Arguments[0].(*ast.IntegerLiteral); isLiteral {
			return literalTerm(literal.Value, target), nil
		}
		source := em.checkedLeanType(call.Arguments[0])
		inner, err := em.expr(call.Arguments[0], source)
		if err != nil {
			return "", err
		}
		if source == target || source == "" {
			return inner, nil
		}
		return fmt.Sprintf("(%s.to%s)", inner, target), nil
	}
	if term, handled, err := em.conversion(callee.Value, call); handled {
		return term, err
	}
	fn, known := em.functions[callee.Value]
	if !known {
		return "", fmt.Errorf("call to %s is outside the extracted subset", callee.Value)
	}
	if len(call.Arguments) != len(fn.Parameters) {
		return "", fmt.Errorf("call to %s passes %d arguments for %d parameters", callee.Value, len(call.Arguments), len(fn.Parameters))
	}
	var args []string
	var rebinds []string
	for i, arg := range call.Arguments {
		paramType, err := em.leanType(fn.Parameters[i].Type)
		if err != nil {
			return "", err
		}
		term, err := em.expr(arg, paramType)
		if err != nil {
			return "", err
		}
		args = append(args, term)
		if isSpanType(fn.Parameters[i].Type) {
			owner := addressOf(argOperand(arg))
			if owner == "" {
				if id, isIdent := arg.(*ast.Identifier); isIdent {
					owner = id.Value
				}
			}
			if owner == "" {
				return "", fmt.Errorf("span argument %s to %s must name its owner", arg.String(), callee.Value)
			}
			rebinds = append(rebinds, ident(owner))
		}
	}
	em.temps++
	result := fmt.Sprintf("r%d", em.temps)
	if em.hoisted == nil {
		return "", fmt.Errorf("call to %s in a position that cannot bind its result", callee.Value)
	}
	*em.hoisted = append(*em.hoisted, fmt.Sprintf("%slet %s ← %s %s fuel", em.indent, tuple(append([]string{result}, rebinds...)), ident(callee.Value), strings.Join(args, " ")))
	return result, nil
}

// argOperand unwraps span(&x) / view(&x) to the &x operand.
func argOperand(arg ast.Expression) ast.Expression {
	if call, ok := arg.(*ast.InvocationExpression); ok && len(call.Arguments) == 1 {
		if callee, isIdent := call.Function.(*ast.Identifier); isIdent && (callee.Value == "span" || callee.Value == "view") {
			return call.Arguments[0]
		}
	}
	return arg
}

// checkedLeanType is the Lean type of an expression's checked type, or "".
// conversion extracts the integer rows of the `{target}_{op}_{source}`
// scheme (docs/spec/20-types.md section 11.1): `trunc` is Lean's wrapping
// `toUIntN`/`toIntN`, `bits` the same-width reinterpretation, `saturating`
// a clamp before the truncation. `checked` builds an ADT value and the
// floating-point rows have no Lean carrier here, so both stay outside the
// subset and fail closed.
func (em *emitter) conversion(name string, call *ast.InvocationExpression) (string, bool, error) {
	target, op, source, ok := typechecker.ConversionParts(name)
	if !ok {
		return "", false, nil
	}
	targetLean, targetKnown := primitiveLean[target]
	sourceLean, sourceKnown := primitiveLean[source]
	if !targetKnown || !sourceKnown || target == "Bool" || source == "Bool" {
		return "", true, fmt.Errorf("call to %s is outside the extracted subset (integer conversions only)", name)
	}
	if len(call.Arguments) != 1 {
		return "", true, fmt.Errorf("%s takes one argument", name)
	}
	inner, err := em.expr(call.Arguments[0], sourceLean)
	if err != nil {
		return "", true, err
	}
	switch op {
	case "trunc", "bits":
		return fmt.Sprintf("(%s.to%s)", inner, targetLean), true, nil
	case "saturating":
		bits := typechecker.PrimitiveBits(target)
		if target[0] == 'u' {
			max := uint64(1)<<uint(bits) - 1
			return fmt.Sprintf("(if %s > (%d : %s) then (%d : %s) else %s.to%s)", inner, max, sourceLean, max, targetLean, inner, targetLean), true, nil
		}
		max := int64(1)<<uint(bits-1) - 1
		min := -int64(1) << uint(bits-1)
		return fmt.Sprintf("(if %s > (%d : %s) then (%d : %s) else if %s < (%d : %s) then (%d : %s) else %s.to%s)",
			inner, max, sourceLean, max, targetLean, inner, min, sourceLean, min, targetLean, inner, targetLean), true, nil
	case "checked":
		// A checked conversion builds Result[target, Overflow]: Ok with the
		// wrapped value when the source lies within the target's range,
		// Err(Overflow) otherwise (docs/spec/20-types.md section 11.1).
		resultName := typechecker.Instantiation{ADT: "Result", Args: []string{target, "Overflow"}}.MangledName()
		result, known := em.adtLeanName(resultName)
		overflow, knownOverflow := em.adtLeanName("Overflow")
		if !known || !knownOverflow {
			return "", true, fmt.Errorf("call to %s: instantiation %s was not recorded by the checker", name, resultName)
		}
		bits := typechecker.PrimitiveBits(target)
		sourceBits := typechecker.PrimitiveBits(source)
		var outOfRange string
		switch {
		case target[0] == 'u' && source[0] == 'u':
			if bits >= sourceBits {
				outOfRange = "false"
			} else {
				outOfRange = fmt.Sprintf("%s > (%d : %s)", inner, uint64(1)<<uint(bits)-1, sourceLean)
			}
		case target[0] == 'u':
			max := uint64(1)<<uint(bits) - 1
			if bits >= sourceBits {
				outOfRange = fmt.Sprintf("%s < (0 : %s)", inner, sourceLean)
			} else {
				outOfRange = fmt.Sprintf("(%s < (0 : %s) || %s > (%d : %s))", inner, sourceLean, inner, max, sourceLean)
			}
		case source[0] == 'u':
			max := uint64(1)<<uint(bits-1) - 1
			if bits > sourceBits {
				outOfRange = "false"
			} else {
				outOfRange = fmt.Sprintf("%s > (%d : %s)", inner, max, sourceLean)
			}
		default:
			if bits >= sourceBits {
				outOfRange = "false"
			} else {
				max := int64(1)<<uint(bits-1) - 1
				min := -int64(1) << uint(bits-1)
				outOfRange = fmt.Sprintf("(%s < (%d : %s) || %s > (%d : %s))", inner, min, sourceLean, inner, max, sourceLean)
			}
		}
		return fmt.Sprintf("(if %s then %s.Err %s.Overflow else %s.Ok %s.to%s)", outOfRange, result, overflow, result, inner, targetLean), true, nil
	}
	return "", true, fmt.Errorf("call to %s is outside the extracted subset (%s conversions are not modeled)", name, op)
}

func (em *emitter) checkedLeanType(expr ast.Expression) string {
	typ := em.env.CheckedExpressionType(expr)
	if typ == nil {
		return ""
	}
	lean, err := em.leanTypeOf(typ)
	if err != nil {
		return ""
	}
	return lean
}

// elementTypeOf is the Lean element type of an array-valued expression.
func (em *emitter) elementTypeOf(expr ast.Expression) string {
	if id, ok := expr.(*ast.Identifier); ok {
		if typ, known := em.scope.lookup(id.Value); known {
			if element, isArray := elementOf(typ); isArray {
				return element
			}
		}
	}
	if typ := em.checkedLeanType(expr); typ != "" {
		if element, isArray := elementOf(typ); isArray {
			return element
		}
	}
	return ""
}

// ---- identifiers ----

var leanReserved = map[string]bool{
	"at": true, "end": true, "do": true, "then": true, "else": true, "if": true, "fun": true, "let": true,
	"have": true, "from": true, "in": true, "match": true, "with": true, "by": true, "def": true,
	"structure": true, "where": true, "deriving": true, "open": true, "namespace": true, "section": true,
	"variable": true, "theorem": true, "example": true, "calc": true, "show": true, "suffices": true,
	"obtain": true, "exact": true, "intro": true, "type": true, "instance": true, "class": true,
	"mutual": true, "partial": true, "private": true, "protected": true, "noncomputable": true,
	"abbrev": true, "axiom": true, "inductive": true, "extends": true, "import": true, "sorry": true,
	"macro": true, "syntax": true, "notation": true, "infix": true, "prefix": true, "postfix": true,
	"universe": true, "opaque": true, "unsafe": true, "return": true, "break": true, "continue": true,
	"for": true, "unless": true, "repeat": true, "while": true, "try": true, "catch": true,
	"finally": true, "mut": true, "pure": true, "fuel": true, "default": true, "none": true, "some": true,
	"true": true, "false": true, "Nat": true, "Bool": true, "Array": true, "Option": true, "id": true,
}

// ident renders an Oak identifier as a Lean identifier: Lean keywords and
// the names the translation itself uses get a trailing underscore.
func ident(name string) string {
	if leanReserved[name] {
		return name + "_"
	}
	return name
}

func identAll(names []string) []string {
	out := make([]string, len(names))
	for i, name := range names {
		out[i] = ident(name)
	}
	return out
}

// ---- walking ----

// walkStatements visits every statement nested in an expression.
func walkStatements(expr ast.Expression, visit func(ast.Statement)) {
	var stmts func(list []ast.Statement)
	var exprs func(e ast.Expression)
	stmts = func(list []ast.Statement) {
		for _, stmt := range list {
			visit(stmt)
			switch s := stmt.(type) {
			case *ast.VariableDeclaration:
				exprs(s.Value)
			case *ast.AssignmentStatement:
				exprs(s.Value)
			case *ast.IndexAssignmentStatement:
				exprs(s.Value)
			case *ast.WhileStatement:
				exprs(s.Condition)
				if s.Body != nil {
					stmts(s.Body.Statements)
				}
			case *ast.ExpressionStatement:
				exprs(s.Expression)
			case *ast.BlockStatement:
				stmts(s.Statements)
			}
		}
	}
	exprs = func(e ast.Expression) {
		switch x := e.(type) {
		case *ast.BlockExpression:
			if x.Block != nil {
				stmts(x.Block.Statements)
			}
		case *ast.MatchExpression:
			exprs(x.Scrutinee)
			for _, arm := range x.Arms {
				exprs(arm.Body)
			}
		case *ast.InfixExpression:
			exprs(x.Left)
			exprs(x.Right)
		case *ast.PrefixExpression:
			exprs(x.Right)
		case *ast.InvocationExpression:
			for _, arg := range x.Arguments {
				exprs(arg)
			}
		case *ast.ArrayLiteral:
			for _, element := range x.Elements {
				exprs(element)
			}
		case *ast.RecordLiteral:
			for _, field := range x.FieldOrder {
				exprs(field.Value)
			}
		case *ast.VariantExpression:
			exprs(x.Payload)
		}
	}
	exprs(expr)
}

// walkExpressions visits every expression nested in an expression,
// including those inside nested statements.
func walkExpressions(expr ast.Expression, visit func(ast.Expression)) {
	var stmts func(list []ast.Statement)
	var exprs func(e ast.Expression)
	stmts = func(list []ast.Statement) {
		for _, stmt := range list {
			switch s := stmt.(type) {
			case *ast.VariableDeclaration:
				exprs(s.Value)
			case *ast.AssignmentStatement:
				exprs(s.Value)
			case *ast.IndexAssignmentStatement:
				exprs(s.Target)
				exprs(s.Value)
			case *ast.WhileStatement:
				exprs(s.Condition)
				if s.Body != nil {
					stmts(s.Body.Statements)
				}
			case *ast.ExpressionStatement:
				exprs(s.Expression)
			case *ast.BlockStatement:
				stmts(s.Statements)
			}
		}
	}
	exprs = func(e ast.Expression) {
		if e == nil {
			return
		}
		visit(e)
		switch x := e.(type) {
		case *ast.BlockExpression:
			if x.Block != nil {
				stmts(x.Block.Statements)
			}
		case *ast.MatchExpression:
			exprs(x.Scrutinee)
			for _, arm := range x.Arms {
				exprs(arm.Body)
			}
		case *ast.InfixExpression:
			exprs(x.Left)
			exprs(x.Right)
		case *ast.PrefixExpression:
			exprs(x.Right)
		case *ast.InvocationExpression:
			exprs(x.Function)
			for _, arg := range x.Arguments {
				exprs(arg)
			}
		case *ast.IndexExpression:
			exprs(x.Left)
			if !x.Dot {
				exprs(x.Index)
			}
		case *ast.SliceExpression:
			exprs(x.Seq)
			exprs(x.Low)
			exprs(x.High)
		case *ast.RecordLiteral:
			for _, field := range x.FieldOrder {
				exprs(field.Value)
			}
		case *ast.ArrayLiteral:
			for _, element := range x.Elements {
				exprs(element)
			}
		case *ast.VariantExpression:
			exprs(x.Payload)
		}
	}
	exprs(expr)
}
