"""Regenerate the tables in normalize.oak from unicode17_normalize.json.

The extract comes from extract_normalize.py (Unicode 17.0.0, see
UNICODE-LICENSE.txt). Everything between the BEGIN/END GENERATED markers in
normalize.oak is replaced; the normalization algorithm around it is
hand-written. Run python stdlib/generate_normalize.py from any working
directory.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent
data = json.loads((root / 'unicode17_normalize.json').read_text())
assert data['version'] == '17.0.0'


def table(name, values, comment):
    return (f'// {comment}\n'
            f'// Internal table: callers must not mutate this static binding.\n'
            f'pub {name}: [{len(values)}]u32 = [{len(values)}]u32{{' + ', '.join(map(str, values)) + '}\n')


flat = lambda rows: [v for row in rows for v in row]
version = data['version']
body = (f'// Generated by generate_normalize.py from unicode17_normalize.json (Unicode '
        f'{version}; see UNICODE-LICENSE.txt).\n'
        + table('normalize_props_table', flat(data['props']),
                f'{len(data["props"])} ranges of (first, last, ccc | flags << 8), sorted, non-overlapping; flags: '
                f'1 NFD_QC=N, 2 NFKD_QC=N, 4 NFC_QC=N, 8 NFC_QC=M, 16 NFKC_QC=N, 32 NFKC_QC=M.')
        + table('normalize_nfd_table', flat(data['nfd']),
                f'{len(data["nfd"])} entries of (scalar, pool offset, length): the full canonical decomposition, sorted by scalar.')
        + table('normalize_nfkd_table', flat(data['nfkd']),
                f'{len(data["nfkd"])} entries of (scalar, pool offset, length): the full compatibility decomposition where it differs from the canonical one, sorted by scalar.')
        + table('normalize_pairs_table', flat(data['pairs']),
                f'{len(data["pairs"])} entries of (first, second, composite): the primary composites, sorted by (first, second).')
        + (f'// {len(data["blocks"])} flags, one per 256-scalar block (scalar >> 8): 1 when the block holds a scalar with a nonzero\n'
           f'// property, a decomposition, or a Hangul syllable; blocks past the end are 0.\n'
           f'// Internal table: callers must not mutate this static binding.\n'
           f'pub normalize_block_table: [{len(data["blocks"])}]u8 = [{len(data["blocks"])}]u8{{' + ', '.join(map(str, data['blocks'])) + '}\n')
        + table('normalize_pool', data['pool'],
                f'{len(data["pool"])} scalars: the decomposition sequences the nfd and nfkd tables index into.'))
source = (root / 'normalize.oak').read_text()
pattern = re.compile(r'(// BEGIN GENERATED\n).*?(// END GENERATED\n)', re.S)
assert pattern.search(source), 'normalize.oak lacks the GENERATED markers'
(root / 'normalize.oak').write_text(pattern.sub(lambda m: m.group(1) + body + m.group(2), source))
print(f'{len(data["props"])} prop ranges, {len(data["nfd"])} nfd, {len(data["nfkd"])} nfkd, '
      f'{len(data["pairs"])} pairs, {len(data["pool"])} pool scalars')
