"""Regenerate the tables in normalize.oak and the Lean tables from
unicode17_normalize.json.

The extract comes from extract_normalize.py (Unicode 17.0.0, see
UNICODE-LICENSE.txt). Everything between the BEGIN/END GENERATED markers in
normalize.oak is replaced; the normalization algorithm around it is
hand-written. The same data is written as key trees to
spec/lean/Oak/Stdlib/NormalizeTables.lean, the instance of the Lean model
(Oak/Normalization.lean) for which Oak/Stdlib/Normalize17.lean discharges
the closure and inverse hypotheses. Run python stdlib/generate_normalize.py
from any working directory.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent
data = json.loads((root / 'unicode17_normalize.json').read_text())
assert data['version'] == '17.0.0'


def table(name, values, comment):
    return (f'// {comment}\n'
            f'// Internal table: callers must not mutate this static binding.\n'
            f'pub {name}: [{len(values)}]u32 = [{len(values)}]u32{{' + ', '.join(map(str, values)) + '}\n')


flat = lambda rows: [v for row in rows for v in row]
version = data['version']
body = (f'// Generated by generate_normalize.py from unicode17_normalize.json (Unicode '
        f'{version}; see UNICODE-LICENSE.txt).\n'
        + table('normalize_props_table', flat(data['props']),
                f'{len(data["props"])} ranges of (first, last, ccc | flags << 8), sorted, non-overlapping; flags: '
                f'1 NFD_QC=N, 2 NFKD_QC=N, 4 NFC_QC=N, 8 NFC_QC=M, 16 NFKC_QC=N, 32 NFKC_QC=M.')
        + table('normalize_nfd_table', flat(data['nfd']),
                f'{len(data["nfd"])} entries of (scalar, pool offset, length): the full canonical decomposition, sorted by scalar.')
        + table('normalize_nfkd_table', flat(data['nfkd']),
                f'{len(data["nfkd"])} entries of (scalar, pool offset, length): the full compatibility decomposition where it differs from the canonical one, sorted by scalar.')
        + table('normalize_pairs_table', flat(data['pairs']),
                f'{len(data["pairs"])} entries of (first, second, composite): the primary composites, sorted by (first, second).')
        + (f'// {len(data["blocks"])} flags, one per 256-scalar block (scalar >> 8): 1 when the block holds a scalar with a nonzero\n'
           f'// property, a decomposition, or a Hangul syllable; blocks past the end are 0.\n'
           f'// Internal table: callers must not mutate this static binding.\n'
           f'pub normalize_block_table: [{len(data["blocks"])}]u8 = [{len(data["blocks"])}]u8{{' + ', '.join(map(str, data['blocks'])) + '}\n')
        + table('normalize_pool', data['pool'],
                f'{len(data["pool"])} scalars: the decomposition sequences the nfd and nfkd tables index into.'))
source = (root / 'normalize.oak').read_text()
pattern = re.compile(r'(// BEGIN GENERATED\n).*?(// END GENERATED\n)', re.S)
assert pattern.search(source), 'normalize.oak lacks the GENERATED markers'
(root / 'normalize.oak').write_text(pattern.sub(lambda m: m.group(1) + body + m.group(2), source))
print(f'{len(data["props"])} prop ranges, {len(data["nfd"])} nfd, {len(data["nfkd"])} nfkd, '
      f'{len(data["pairs"])} pairs, {len(data["pool"])} pool scalars')


def ktree(items, leaf):
    """A balanced key tree over sorted (key, value) items as a Lean term.

    Keys below a node's split go left, the rest right, matching
    Oak.Stdlib.KeyTree.lookup. Each node is one line; depth is the indent."""
    def build(lo, hi, depth):
        pad = '  ' * (depth + 1)
        if hi == lo:
            return pad + '.nil'
        if hi - lo == 1:
            key, value = items[lo]
            return pad + f'(.leaf {key} {leaf(value)})'
        mid = (lo + hi) // 2
        return (pad + f'(.node {items[mid][0]}\n' + build(lo, mid, depth + 1) + '\n'
                + build(mid, hi, depth + 1) + ')')
    return build(0, len(items), 0)


pool = data['pool']
decomp_items = sorted((scalar, pool[offset:offset + length]) for scalar, offset, length in data['nfd'])
pair_items = sorted((first * 2097152 + second, composite) for first, second, composite in data['pairs'])
assert all(first < 2097152 and second < 2097152 for first, second, _ in data['pairs'])
ccc_items = sorted((scalar, entry & 255) for first, last, entry in data['props']
                   if entry & 255 for scalar in range(first, last + 1))
lean = (f'import Oak.Stdlib.KeyTree\n\n'
        f'/-! Generated by stdlib/generate_normalize.py from unicode17_normalize.json (Unicode\n'
        f'{version}; see stdlib/UNICODE-LICENSE.txt). Do not edit: the standard-library\n'
        f'workflow regenerates this file and fails on a difference. -/\n\n'
        f'namespace Oak.Stdlib.Normalize17\n\n'
        f'open Oak.Stdlib.KeyTree\n\n'
        f'set_option maxRecDepth 65536\n\n'
        f'/-- The full canonical decomposition of every scalar that has one\n'
        f'    ({len(decomp_items)} entries; Hangul syllables are algorithmic and absent). -/\n'
        f'def decompTree : KTree (List Nat) :=\n'
        + ktree(decomp_items, lambda d: '[' + ', '.join(map(str, d)) + ']') + '\n\n'
        f'/-- The primary composite of a pair, keyed by `first * 2097152 + second`\n'
        f'    ({len(pair_items)} entries; exclusions already applied; Hangul absent). -/\n'
        f'def pairTree : KTree Nat :=\n'
        + ktree(pair_items, str) + '\n\n'
        f'/-- Canonical_Combining_Class of every scalar with a nonzero class\n'
        f'    ({len(ccc_items)} entries). -/\n'
        f'def cccTree : KTree Nat :=\n'
        + ktree(ccc_items, str) + '\n\n'
        f'end Oak.Stdlib.Normalize17\n')
(root.parent / 'spec' / 'lean' / 'Oak' / 'Stdlib' / 'NormalizeTables.lean').write_text(lean)
print(f'lean tables: {len(decomp_items)} decompositions, {len(pair_items)} pairs, {len(ccc_items)} combining classes')
