"""Regenerate the range table in grapheme.oak from unicode17_grapheme.json.

The extract comes from extract_grapheme.py (Unicode 17.0.0, see
UNICODE-LICENSE.txt). Everything between the BEGIN/END GENERATED markers in
grapheme.oak is replaced; the segmentation rules around it are hand-written.
Run python stdlib/generate_grapheme.py from any working directory.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent
data = json.loads((root / 'unicode17_grapheme.json').read_text())
assert data['version'] == '17.0.0'
values = [v for triple in data['ranges'] for v in triple]
table = (f'// Generated by generate_grapheme.py from unicode17_grapheme.json (Unicode '
         f'{data["version"]}; see UNICODE-LICENSE.txt): {len(data["ranges"])} ranges of\n'
         f'// (first, last, gcb | incb << 8 | pictographic << 10), sorted, non-overlapping.\n'
         f'// Internal table: callers must not mutate this static binding.\n'
         f'pub grapheme_table: [{len(values)}]u32 = [{len(values)}]u32{{' + ', '.join(map(str, values)) + '}\n')
source = (root / 'grapheme.oak').read_text()
pattern = re.compile(r'(// BEGIN GENERATED\n).*?(// END GENERATED\n)', re.S)
assert pattern.search(source), 'grapheme.oak lacks the GENERATED markers'
(root / 'grapheme.oak').write_text(pattern.sub(lambda m: m.group(1) + table + m.group(2), source))
print(f'{len(data["ranges"])} ranges, {len(values)} words')
