"""Generate allocation-free Unicode 17 casing tables from the checked-in extract.

unicode17.json is extracted from UCD UnicodeData, SpecialCasing (unconditional),
CaseFolding (C/F), and DerivedCoreProperties (Cased/Case_Ignorable), version 17.0.0.
Locale-specific casing is deliberately excluded. Default Final_Sigma is handled
in strings.oak. Run python stdlib/generate_unicode.py from any working directory.
"""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent
data = json.loads((root / 'unicode17.json').read_text())
assert data['version'] == '17.0.0'
out = ['// Generated by generate_unicode.py. Unicode 17.0.0; see UNICODE-LICENSE.txt.',
       'package unicode',
       '// Internal tables: callers must not mutate these static bindings.',
       'pub UnicodeMapping: type = struct { count: u32, first: u32, second: u32, third: u32 }']

def table(name, values):
    out.append(f'pub {name}: [{len(values)}]u32 = [{len(values)}]u32{{' + ', '.join(map(str, values)) + '}')

for name, mappings in data['maps'].items():
    values = []
    for cp, mapped in sorted(mappings.items(), key=lambda item: int(item[0])):
        assert 1 <= len(mapped) <= 3
        values.extend([int(cp), len(mapped), *mapped, *([0] * (3-len(mapped)))])
    table('unicode_' + name + '_table', values)
    out.append(f'''pub unicode_{name}: (value: u32): UnicodeMapping {{
  table: []u32 = view(&unicode_{name}_table)
  unicode_lookup(table, value)
}}''')
for name, ranges in data['properties'].items():
    symbol = name.lower()
    table('unicode_' + symbol + '_table', [v for pair in ranges for v in pair])
    out.append(f'''pub unicode_is_{symbol}: (value: u32): Bool {{
  table: []u32 = view(&unicode_{symbol}_table)
  unicode_in_ranges(table, value)
}}''')
out.append('''pub unicode_lookup: (table: []u32, value: u32): UnicodeMapping {
  low: u32 = 0
  high: u32 = len(table) / u32(5)
  while low < high {
    mid: u32 = low + (high - low) / u32(2)
    table[mid * u32(5)] < value ? { low = mid + u32(1) } | { high = mid }
  }
  at: u32 = low * u32(5)
  at < len(table) && table[at] == value ? {
    count: u32 = table[at + u32(1)]
    first: u32 = table[at + u32(2)]
    second: u32 = table[at + u32(3)]
    third: u32 = table[at + u32(4)]
    UnicodeMapping { count: count, first: first, second: second, third: third }
  } | { UnicodeMapping { count: u32(1), first: value, second: u32(0), third: u32(0) } }
}
pub unicode_in_ranges: (table: []u32, value: u32): Bool {
  low: u32 = 0
  high: u32 = len(table) / u32(2)
  while low < high {
    mid: u32 = low + (high - low) / u32(2)
    table[mid * u32(2) + u32(1)] < value ? { low = mid + u32(1) } | { high = mid }
  }
  low < len(table) / u32(2) && table[low * u32(2)] <= value
}
pub unicode_mapping_at: (mapping: UnicodeMapping, index: u32): u32 {
  assert(index < mapping.count)
  index == u32(0) ? mapping.first | index == u32(1) ? mapping.second | mapping.third
}
''')
# Every generated top-level declaration is an explicit export
# (docs/spec/83-modules.md section 9): the standard library carries pub marks.
_DECL = re.compile(r'^(?:fn |[A-Za-z_][A-Za-z0-9_]*(?:\[[^\]]*\])?\s*(?::|\(|:=))')


def mark_pub(text):
    lines = []
    for line in text.split('\n'):
        if line and not line.startswith(('pub ', ' ', '\t', '//')) and _DECL.match(line):
            lines.append('pub ' + line)
        else:
            lines.append(line)
    return '\n'.join(lines)


(root / 'unicode.oak').write_text(mark_pub('\n\n'.join(out)))
