-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.ArrayList

inductive Error where
  | Full
  | Empty
  | OutOfBounds
  deriving Repr, Inhabited, BEq, DecidableEq

structure Cursor where
  length : UInt32
  deriving Repr, BEq, DecidableEq
instance : Inhabited Cursor := ⟨{ length := (0 : UInt32) }⟩

inductive Result_u32_Error where
  | Ok (payload : UInt32)
  | Err (payload : Error)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u8_Error where
  | Ok (payload : UInt8)
  | Err (payload : Error)
  deriving Repr, Inhabited, BEq, DecidableEq

def check (cursor : Array Cursor) (capacity : UInt32) (fuel : Nat) : Option (Unit × Array Cursor) := do
  let () ← (if ((cursor.size.toUInt32) == (1 : UInt32)) then pure () else none)
  let () ← (if (decide ((cursor.getD 0 (default : Cursor)).length <= capacity)) then pure () else none)
  pure ((), cursor)

def clear (cursor : Array Cursor) (capacity : UInt32) (fuel : Nat) : Option (Unit × Array Cursor) := do
  let (r1, cursor) ← check cursor capacity fuel
  let cursor := cursor.setIfInBounds 0 { (cursor.getD 0 (default : Cursor)) with length := (0 : UInt32) }
  pure ((), cursor)

def push_u8 (cursor : Array Cursor) (storage : Array UInt8) (value : UInt8) (fuel : Nat) : Option (Result_u32_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  let index : UInt32 := (cursor.getD 0 (default : Cursor)).length
  let (r2, cursor, storage) ← (
    if (index == (storage.size.toUInt32)) then (do
      pure ((Result_u32_Error.Err Error.Full), cursor, storage))
    else (do
      let storage := storage.setIfInBounds index.toNat value
      let cursor := cursor.setIfInBounds 0 { (cursor.getD 0 (default : Cursor)) with length := (index + (1 : UInt32)) }
      pure ((Result_u32_Error.Ok index), cursor, storage)))
  pure (r2, cursor, storage)

def drive_push_u8 (cursor : Array Cursor) (storage : Array UInt8) (value : UInt8) (fuel : Nat) : Option (Result_u32_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor, storage) ← push_u8 cursor storage value fuel
  pure (r1, cursor, storage)

def get_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (fuel : Nat) : Option (Result_u8_Error × Array Cursor) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  pure ((if (decide (index >= (cursor.getD 0 (default : Cursor)).length)) then (Result_u8_Error.Err Error.OutOfBounds) else (Result_u8_Error.Ok (storage.getD index.toNat (0 : UInt8)))), cursor)

def drive_get_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (fuel : Nat) : Option (Result_u8_Error × Array Cursor) := do
  let (r1, cursor) ← get_u8 cursor storage index fuel
  pure (r1, cursor)

def set_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (value : UInt8) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  let (r2, storage) ← (
    if (decide (index >= (cursor.getD 0 (default : Cursor)).length)) then (do
      pure ((Result_u8_Error.Err Error.OutOfBounds), storage))
    else (do
      let previous : UInt8 := (storage.getD index.toNat (0 : UInt8))
      let storage := storage.setIfInBounds index.toNat value
      pure ((Result_u8_Error.Ok previous), storage)))
  pure (r2, cursor, storage)

def drive_set_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (value : UInt8) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor, storage) ← set_u8 cursor storage index value fuel
  pure (r1, cursor, storage)

def pop_u8 (cursor : Array Cursor) (storage : Array UInt8) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  let (r2, cursor) ← (
    if ((cursor.getD 0 (default : Cursor)).length == (0 : UInt32)) then (do
      pure ((Result_u8_Error.Err Error.Empty), cursor))
    else (do
      let cursor := cursor.setIfInBounds 0 { (cursor.getD 0 (default : Cursor)) with length := ((cursor.getD 0 (default : Cursor)).length - (1 : UInt32)) }
      pure ((Result_u8_Error.Ok (storage.getD (cursor.getD 0 (default : Cursor)).length.toNat (0 : UInt8))), cursor)))
  pure (r2, cursor, storage)

def drive_pop_u8 (cursor : Array Cursor) (storage : Array UInt8) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor, storage) ← pop_u8 cursor storage fuel
  pure (r1, cursor, storage)

def insert_u8.loop1 (storage : Array UInt8) (index : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i > index)) then do
      let storage := storage.setIfInBounds i.toNat (storage.getD (i - (1 : UInt32)).toNat (0 : UInt8))
      let i := (i - (1 : UInt32))
      insert_u8.loop1 storage index i fuel
    else pure (storage, i)

def insert_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (value : UInt8) (fuel : Nat) : Option (Result_u32_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  let (r2, cursor, storage) ← (
    if (decide (index > (cursor.getD 0 (default : Cursor)).length)) then (do
      pure ((Result_u32_Error.Err Error.OutOfBounds), cursor, storage))
    else (do
      let (r3, cursor, storage) ← (
        if ((cursor.getD 0 (default : Cursor)).length == (storage.size.toUInt32)) then (do
          pure ((Result_u32_Error.Err Error.Full), cursor, storage))
        else (do
          let i : UInt32 := (cursor.getD 0 (default : Cursor)).length
          let (storage, i) ← insert_u8.loop1 storage index i fuel
          let storage := storage.setIfInBounds index.toNat value
          let cursor := cursor.setIfInBounds 0 { (cursor.getD 0 (default : Cursor)) with length := ((cursor.getD 0 (default : Cursor)).length + (1 : UInt32)) }
          pure ((Result_u32_Error.Ok index), cursor, storage)))
      pure (r3, cursor, storage)))
  pure (r2, cursor, storage)

def drive_insert_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (value : UInt8) (fuel : Nat) : Option (Result_u32_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor, storage) ← insert_u8 cursor storage index value fuel
  pure (r1, cursor, storage)

def remove_u8.loop1 (storage : Array UInt8) (i : UInt32) (last : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < last)) then do
      let storage := storage.setIfInBounds i.toNat (storage.getD (i + (1 : UInt32)).toNat (0 : UInt8))
      let i := (i + (1 : UInt32))
      remove_u8.loop1 storage i last fuel
    else pure (storage, i)

def remove_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  let (r2, cursor, storage) ← (
    if (decide (index >= (cursor.getD 0 (default : Cursor)).length)) then (do
      pure ((Result_u8_Error.Err Error.OutOfBounds), cursor, storage))
    else (do
      let value : UInt8 := (storage.getD index.toNat (0 : UInt8))
      let i : UInt32 := index
      let last : UInt32 := ((cursor.getD 0 (default : Cursor)).length - (1 : UInt32))
      let (storage, i) ← remove_u8.loop1 storage i last fuel
      let cursor := cursor.setIfInBounds 0 { (cursor.getD 0 (default : Cursor)) with length := last }
      pure ((Result_u8_Error.Ok value), cursor, storage)))
  pure (r2, cursor, storage)

def drive_remove_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor, storage) ← remove_u8 cursor storage index fuel
  pure (r1, cursor, storage)

def swap_remove_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor) ← check cursor (storage.size.toUInt32) fuel
  let (r2, cursor, storage) ← (
    if (decide (index >= (cursor.getD 0 (default : Cursor)).length)) then (do
      pure ((Result_u8_Error.Err Error.OutOfBounds), cursor, storage))
    else (do
      let value : UInt8 := (storage.getD index.toNat (0 : UInt8))
      let last : UInt32 := ((cursor.getD 0 (default : Cursor)).length - (1 : UInt32))
      let storage := storage.setIfInBounds index.toNat (storage.getD last.toNat (0 : UInt8))
      let cursor := cursor.setIfInBounds 0 { (cursor.getD 0 (default : Cursor)) with length := last }
      pure ((Result_u8_Error.Ok value), cursor, storage)))
  pure (r2, cursor, storage)

def drive_swap_remove_u8 (cursor : Array Cursor) (storage : Array UInt8) (index : UInt32) (fuel : Nat) : Option (Result_u8_Error × Array Cursor × Array UInt8) := do
  let (r1, cursor, storage) ← swap_remove_u8 cursor storage index fuel
  pure (r1, cursor, storage)

end Oak.Stdlib.ArrayList
