-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Bytes

inductive CopyError where
  | DestinationTooSmall
  deriving Repr, Inhabited, BEq, DecidableEq

inductive RangeError where
  | OutOfBounds
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Option_u32 where
  | Some (payload : UInt32)
  | None
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u32_CopyError where
  | Ok (payload : UInt32)
  | Err (payload : CopyError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u32_RangeError where
  | Ok (payload : UInt32)
  | Err (payload : RangeError)
  deriving Repr, Inhabited, BEq, DecidableEq

def range_fits (length : UInt32) (offset : UInt32) (width : UInt32) (fuel : Nat) : Option (Bool) := do
  pure (if (decide (offset > length)) then false else (decide (width <= (length - offset))))

def copy_into.loop1 (dst : Array UInt8) (src : Array UInt8) (n : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < n)) then do
      let dst := dst.setIfInBounds i.toNat (src.getD i.toNat (0 : UInt8))
      let i := (i + (1 : UInt32))
      copy_into.loop1 dst src n i fuel
    else pure (dst, i)

def copy_into (dst : Array UInt8) (src : Array UInt8) (fuel : Nat) : Option (Result_u32_CopyError × Array UInt8) := do
  let n : UInt32 := (src.size.toUInt32)
  let (r1, dst) ← (
    if (decide ((dst.size.toUInt32) < n)) then (do
      pure ((Result_u32_CopyError.Err CopyError.DestinationTooSmall), dst))
    else (do
      let i : UInt32 := (0 : UInt32)
      let (dst, i) ← copy_into.loop1 dst src n i fuel
      pure ((Result_u32_CopyError.Ok n), dst)))
  pure (r1, dst)

def equal.loop1 (left : Array UInt8) (right : Array UInt8) (n : UInt32) (same : Bool) (i : UInt32) : Nat → Option (Bool × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < n)) then do
      let same := (same && ((left.getD i.toNat (0 : UInt8)) == (right.getD i.toNat (0 : UInt8))))
      let i := (i + (1 : UInt32))
      equal.loop1 left right n same i fuel
    else pure (same, i)

def equal (left : Array UInt8) (right : Array UInt8) (fuel : Nat) : Option (Bool) := do
  let n : UInt32 := (left.size.toUInt32)
  let r1 ← (
    if (n == (right.size.toUInt32)) then (do
      let same : Bool := true
      let i : UInt32 := (0 : UInt32)
      let (same, i) ← equal.loop1 left right n same i fuel
      pure same)
    else (do
      pure false))
  pure r1

def find.loop1 (src : Array UInt8) (needle : UInt8) (n : UInt32) (index : UInt32) (i : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < n)) then do
      let index ← (if ((index == n) && ((src.getD i.toNat (0 : UInt8)) == needle)) then (do
          let index := i
          pure index)
        else (do
          pure index))
      let i := (i + (1 : UInt32))
      find.loop1 src needle n index i fuel
    else pure (index, i)

def find (src : Array UInt8) (needle : UInt8) (fuel : Nat) : Option (Option_u32) := do
  let n : UInt32 := (src.size.toUInt32)
  let index : UInt32 := n
  let i : UInt32 := (0 : UInt32)
  let (index, i) ← find.loop1 src needle n index i fuel
  pure (if (index == n) then Option_u32.None else (Option_u32.Some index))

def fill.loop1 (dst : Array UInt8) (value : UInt8) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (dst.size.toUInt32))) then do
      let dst := dst.setIfInBounds i.toNat value
      let i := (i + (1 : UInt32))
      fill.loop1 dst value i fuel
    else pure (dst, i)

def fill (dst : Array UInt8) (value : UInt8) (fuel : Nat) : Option (Unit × Array UInt8) := do
  let i : UInt32 := (0 : UInt32)
  let (dst, i) ← fill.loop1 dst value i fuel
  pure ((), dst)

def copy_at.loop1 (dst : Array UInt8) (offset : UInt32) (src : Array UInt8) (n : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < n)) then do
      let dst := dst.setIfInBounds (offset + i).toNat (src.getD i.toNat (0 : UInt8))
      let i := (i + (1 : UInt32))
      copy_at.loop1 dst offset src n i fuel
    else pure (dst, i)

def copy_at (dst : Array UInt8) (offset : UInt32) (src : Array UInt8) (fuel : Nat) : Option (Result_u32_RangeError × Array UInt8) := do
  let n : UInt32 := (src.size.toUInt32)
  let r1 ← range_fits (dst.size.toUInt32) offset n fuel
  let (r2, dst) ← (
    if r1 then (do
      let i : UInt32 := (0 : UInt32)
      let (dst, i) ← copy_at.loop1 dst offset src n i fuel
      pure ((Result_u32_RangeError.Ok n), dst))
    else (do
      pure ((Result_u32_RangeError.Err RangeError.OutOfBounds), dst)))
  pure (r2, dst)

def move_within.loop1 (storage : Array UInt8) (dst : UInt32) (src : UInt32) (remaining : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (remaining > (0 : UInt32))) then do
      let remaining := (remaining - (1 : UInt32))
      let storage := storage.setIfInBounds (dst + remaining).toNat (storage.getD (src + remaining).toNat (0 : UInt8))
      move_within.loop1 storage dst src remaining fuel
    else pure (storage, remaining)

def move_within.loop2 (storage : Array UInt8) (dst : UInt32) (src : UInt32) (count : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < count)) then do
      let storage := storage.setIfInBounds (dst + i).toNat (storage.getD (src + i).toNat (0 : UInt8))
      let i := (i + (1 : UInt32))
      move_within.loop2 storage dst src count i fuel
    else pure (storage, i)

def move_within (storage : Array UInt8) (dst : UInt32) (src : UInt32) (count : UInt32) (fuel : Nat) : Option (Result_u32_RangeError × Array UInt8) := do
  let r1 ← range_fits (storage.size.toUInt32) dst count fuel
  let r2 ← range_fits (storage.size.toUInt32) src count fuel
  let valid : Bool := (r1 && r2)
  let (r3, storage) ← (
    if valid then (do
      let storage ← (if (decide (dst > src)) then (do
          let remaining : UInt32 := count
          let (storage, remaining) ← move_within.loop1 storage dst src remaining fuel
          pure storage)
        else (do
          let i : UInt32 := (0 : UInt32)
          let (storage, i) ← move_within.loop2 storage dst src count i fuel
          pure storage))
      pure ((Result_u32_RangeError.Ok count), storage))
    else (do
      pure ((Result_u32_RangeError.Err RangeError.OutOfBounds), storage)))
  pure (r3, storage)

def compare.loop1 (left : Array UInt8) (right : Array UInt8) (limit : UInt32) (order : Int32) (i : UInt32) : Nat → Option (Int32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < limit)) && (order == (0 : Int32))) then do
      let order ← (if (decide ((left.getD i.toNat (0 : UInt8)) < (right.getD i.toNat (0 : UInt8)))) then (do
          let order := (0 - (1 : Int32))
          pure order)
        else (do
          pure order))
      let order ← (if (decide ((left.getD i.toNat (0 : UInt8)) > (right.getD i.toNat (0 : UInt8)))) then (do
          let order := (1 : Int32)
          pure order)
        else (do
          pure order))
      let i := (i + (1 : UInt32))
      compare.loop1 left right limit order i fuel
    else pure (order, i)

def compare (left : Array UInt8) (right : Array UInt8) (fuel : Nat) : Option (Int32) := do
  let limit : UInt32 := (if (decide ((left.size.toUInt32) < (right.size.toUInt32))) then (left.size.toUInt32) else (right.size.toUInt32))
  let order : Int32 := (0 : Int32)
  let i : UInt32 := (0 : UInt32)
  let (order, i) ← compare.loop1 left right limit order i fuel
  let order ← (if (order == (0 : Int32)) then (do
      let order ← (if (decide ((left.size.toUInt32) < (right.size.toUInt32))) then (do
          let order := (0 - (1 : Int32))
          pure order)
        else (do
          pure order))
      let order ← (if (decide ((left.size.toUInt32) > (right.size.toUInt32))) then (do
          let order := (1 : Int32)
          pure order)
        else (do
          pure order))
      pure order)
    else (do
      pure order))
  pure order

end Oak.Stdlib.Bytes
