-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Endian

inductive Error where
  | BufferTooSmall
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u16_Error where
  | Ok (payload : UInt16)
  | Err (payload : Error)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u32_Error where
  | Ok (payload : UInt32)
  | Err (payload : Error)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u64_Error where
  | Ok (payload : UInt64)
  | Err (payload : Error)
  deriving Repr, Inhabited, BEq, DecidableEq

def range_fits (length : UInt32) (offset : UInt32) (width : UInt32) (fuel : Nat) : Option (Bool) := do
  pure (if (decide (offset > length)) then false else (decide (width <= (length - offset))))

def read_u16_le (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_u16_Error) := do
  let r1 ← range_fits (src.size.toUInt32) offset (2 : UInt32) fuel
  let r2 ← (
    if r1 then (do
      let value : UInt16 := (0 : UInt16)
      let value := (value ||| (((src.getD (offset + (0 : UInt32)).toNat (0 : UInt8)).toUInt16) <<< (0 : UInt16)))
      let value := (value ||| (((src.getD (offset + (1 : UInt32)).toNat (0 : UInt8)).toUInt16) <<< (8 : UInt16)))
      pure (Result_u16_Error.Ok value))
    else (do
      pure (Result_u16_Error.Err Error.BufferTooSmall)))
  pure r2

def write_u16_le (dst : Array UInt8) (offset : UInt32) (value : UInt16) (fuel : Nat) : Option (Result_u32_Error × Array UInt8) := do
  let r1 ← range_fits (dst.size.toUInt32) offset (2 : UInt32) fuel
  let (r2, dst) ← (
    if r1 then (do
      let dst := dst.setIfInBounds (offset + (0 : UInt32)).toNat ((value >>> (0 : UInt16)).toUInt8)
      let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat ((value >>> (8 : UInt16)).toUInt8)
      pure ((Result_u32_Error.Ok (2 : UInt32)), dst))
    else (do
      pure ((Result_u32_Error.Err Error.BufferTooSmall), dst)))
  pure (r2, dst)

def read_u16_be (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_u16_Error) := do
  let r1 ← range_fits (src.size.toUInt32) offset (2 : UInt32) fuel
  let r2 ← (
    if r1 then (do
      let value : UInt16 := (0 : UInt16)
      let value := (value ||| (((src.getD (offset + (0 : UInt32)).toNat (0 : UInt8)).toUInt16) <<< (8 : UInt16)))
      let value := (value ||| (((src.getD (offset + (1 : UInt32)).toNat (0 : UInt8)).toUInt16) <<< (0 : UInt16)))
      pure (Result_u16_Error.Ok value))
    else (do
      pure (Result_u16_Error.Err Error.BufferTooSmall)))
  pure r2

def write_u16_be (dst : Array UInt8) (offset : UInt32) (value : UInt16) (fuel : Nat) : Option (Result_u32_Error × Array UInt8) := do
  let r1 ← range_fits (dst.size.toUInt32) offset (2 : UInt32) fuel
  let (r2, dst) ← (
    if r1 then (do
      let dst := dst.setIfInBounds (offset + (0 : UInt32)).toNat ((value >>> (8 : UInt16)).toUInt8)
      let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat ((value >>> (0 : UInt16)).toUInt8)
      pure ((Result_u32_Error.Ok (2 : UInt32)), dst))
    else (do
      pure ((Result_u32_Error.Err Error.BufferTooSmall), dst)))
  pure (r2, dst)

def read_u32_le (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_u32_Error) := do
  let r1 ← range_fits (src.size.toUInt32) offset (4 : UInt32) fuel
  let r2 ← (
    if r1 then (do
      let value : UInt32 := (0 : UInt32)
      let value := (value ||| (((src.getD (offset + (0 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (0 : UInt32)))
      let value := (value ||| (((src.getD (offset + (1 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (8 : UInt32)))
      let value := (value ||| (((src.getD (offset + (2 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (16 : UInt32)))
      let value := (value ||| (((src.getD (offset + (3 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (24 : UInt32)))
      pure (Result_u32_Error.Ok value))
    else (do
      pure (Result_u32_Error.Err Error.BufferTooSmall)))
  pure r2

def write_u32_le (dst : Array UInt8) (offset : UInt32) (value : UInt32) (fuel : Nat) : Option (Result_u32_Error × Array UInt8) := do
  let r1 ← range_fits (dst.size.toUInt32) offset (4 : UInt32) fuel
  let (r2, dst) ← (
    if r1 then (do
      let dst := dst.setIfInBounds (offset + (0 : UInt32)).toNat ((value >>> (0 : UInt32)).toUInt8)
      let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat ((value >>> (8 : UInt32)).toUInt8)
      let dst := dst.setIfInBounds (offset + (2 : UInt32)).toNat ((value >>> (16 : UInt32)).toUInt8)
      let dst := dst.setIfInBounds (offset + (3 : UInt32)).toNat ((value >>> (24 : UInt32)).toUInt8)
      pure ((Result_u32_Error.Ok (4 : UInt32)), dst))
    else (do
      pure ((Result_u32_Error.Err Error.BufferTooSmall), dst)))
  pure (r2, dst)

def read_u32_be (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_u32_Error) := do
  let r1 ← range_fits (src.size.toUInt32) offset (4 : UInt32) fuel
  let r2 ← (
    if r1 then (do
      let value : UInt32 := (0 : UInt32)
      let value := (value ||| (((src.getD (offset + (0 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (24 : UInt32)))
      let value := (value ||| (((src.getD (offset + (1 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (16 : UInt32)))
      let value := (value ||| (((src.getD (offset + (2 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (8 : UInt32)))
      let value := (value ||| (((src.getD (offset + (3 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (0 : UInt32)))
      pure (Result_u32_Error.Ok value))
    else (do
      pure (Result_u32_Error.Err Error.BufferTooSmall)))
  pure r2

def write_u32_be (dst : Array UInt8) (offset : UInt32) (value : UInt32) (fuel : Nat) : Option (Result_u32_Error × Array UInt8) := do
  let r1 ← range_fits (dst.size.toUInt32) offset (4 : UInt32) fuel
  let (r2, dst) ← (
    if r1 then (do
      let dst := dst.setIfInBounds (offset + (0 : UInt32)).toNat ((value >>> (24 : UInt32)).toUInt8)
      let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat ((value >>> (16 : UInt32)).toUInt8)
      let dst := dst.setIfInBounds (offset + (2 : UInt32)).toNat ((value >>> (8 : UInt32)).toUInt8)
      let dst := dst.setIfInBounds (offset + (3 : UInt32)).toNat ((value >>> (0 : UInt32)).toUInt8)
      pure ((Result_u32_Error.Ok (4 : UInt32)), dst))
    else (do
      pure ((Result_u32_Error.Err Error.BufferTooSmall), dst)))
  pure (r2, dst)

def read_u64_le (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_u64_Error) := do
  let r1 ← range_fits (src.size.toUInt32) offset (8 : UInt32) fuel
  let r2 ← (
    if r1 then (do
      let value : UInt64 := (0 : UInt64)
      let value := (value ||| (((src.getD (offset + (0 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (0 : UInt64)))
      let value := (value ||| (((src.getD (offset + (1 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (8 : UInt64)))
      let value := (value ||| (((src.getD (offset + (2 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (16 : UInt64)))
      let value := (value ||| (((src.getD (offset + (3 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (24 : UInt64)))
      let value := (value ||| (((src.getD (offset + (4 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (32 : UInt64)))
      let value := (value ||| (((src.getD (offset + (5 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (40 : UInt64)))
      let value := (value ||| (((src.getD (offset + (6 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (48 : UInt64)))
      let value := (value ||| (((src.getD (offset + (7 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (56 : UInt64)))
      pure (Result_u64_Error.Ok value))
    else (do
      pure (Result_u64_Error.Err Error.BufferTooSmall)))
  pure r2

def write_u64_le (dst : Array UInt8) (offset : UInt32) (value : UInt64) (fuel : Nat) : Option (Result_u32_Error × Array UInt8) := do
  let r1 ← range_fits (dst.size.toUInt32) offset (8 : UInt32) fuel
  let (r2, dst) ← (
    if r1 then (do
      let dst := dst.setIfInBounds (offset + (0 : UInt32)).toNat ((value >>> (0 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat ((value >>> (8 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (2 : UInt32)).toNat ((value >>> (16 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (3 : UInt32)).toNat ((value >>> (24 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (4 : UInt32)).toNat ((value >>> (32 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (5 : UInt32)).toNat ((value >>> (40 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (6 : UInt32)).toNat ((value >>> (48 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (7 : UInt32)).toNat ((value >>> (56 : UInt64)).toUInt8)
      pure ((Result_u32_Error.Ok (8 : UInt32)), dst))
    else (do
      pure ((Result_u32_Error.Err Error.BufferTooSmall), dst)))
  pure (r2, dst)

def read_u64_be (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_u64_Error) := do
  let r1 ← range_fits (src.size.toUInt32) offset (8 : UInt32) fuel
  let r2 ← (
    if r1 then (do
      let value : UInt64 := (0 : UInt64)
      let value := (value ||| (((src.getD (offset + (0 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (56 : UInt64)))
      let value := (value ||| (((src.getD (offset + (1 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (48 : UInt64)))
      let value := (value ||| (((src.getD (offset + (2 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (40 : UInt64)))
      let value := (value ||| (((src.getD (offset + (3 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (32 : UInt64)))
      let value := (value ||| (((src.getD (offset + (4 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (24 : UInt64)))
      let value := (value ||| (((src.getD (offset + (5 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (16 : UInt64)))
      let value := (value ||| (((src.getD (offset + (6 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (8 : UInt64)))
      let value := (value ||| (((src.getD (offset + (7 : UInt32)).toNat (0 : UInt8)).toUInt64) <<< (0 : UInt64)))
      pure (Result_u64_Error.Ok value))
    else (do
      pure (Result_u64_Error.Err Error.BufferTooSmall)))
  pure r2

def write_u64_be (dst : Array UInt8) (offset : UInt32) (value : UInt64) (fuel : Nat) : Option (Result_u32_Error × Array UInt8) := do
  let r1 ← range_fits (dst.size.toUInt32) offset (8 : UInt32) fuel
  let (r2, dst) ← (
    if r1 then (do
      let dst := dst.setIfInBounds (offset + (0 : UInt32)).toNat ((value >>> (56 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat ((value >>> (48 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (2 : UInt32)).toNat ((value >>> (40 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (3 : UInt32)).toNat ((value >>> (32 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (4 : UInt32)).toNat ((value >>> (24 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (5 : UInt32)).toNat ((value >>> (16 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (6 : UInt32)).toNat ((value >>> (8 : UInt64)).toUInt8)
      let dst := dst.setIfInBounds (offset + (7 : UInt32)).toNat ((value >>> (0 : UInt64)).toUInt8)
      pure ((Result_u32_Error.Ok (8 : UInt32)), dst))
    else (do
      pure ((Result_u32_Error.Err Error.BufferTooSmall), dst)))
  pure (r2, dst)

end Oak.Stdlib.Endian
