-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Float

inductive FloatError where
  | InvalidSyntax
  | OutOfRange
  | DestinationTooSmall
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_f32_FloatError where
  | Ok (payload : Float32)
  | Err (payload : FloatError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_f64_FloatError where
  | Ok (payload : Float)
  | Err (payload : FloatError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u32_FloatError where
  | Ok (payload : UInt32)
  | Err (payload : FloatError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u64_FloatError where
  | Ok (payload : UInt64)
  | Err (payload : FloatError)
  deriving Repr, Inhabited, BEq, DecidableEq

def DEC_DIGITS : UInt32 := (800 : UInt32)

def DP_BIAS : Int32 := (65536 : Int32)

def MAX_SHIFT : UInt32 := (27 : UInt32)

def float_error_code (reason : FloatError) (fuel : Nat) : Option (UInt32) := do
  pure (match reason with | .InvalidSyntax => (1 : UInt32) | .OutOfRange => (2 : UInt32) | .DestinationTooSmall => (3 : UInt32))

def float_ok (result : Result_u32_FloatError) (fuel : Nat) : Option (Bool) := do
  pure (match result with | (.Ok n) => true | (.Err e) => false)

def float_written (result : Result_u32_FloatError) (fuel : Nat) : Option (UInt32) := do
  pure (match result with | (.Ok n) => n | (.Err e) => (0 : UInt32))

def float_failure (result : Result_u32_FloatError) (fuel : Nat) : Option (UInt32) := do
  let r1 ← (match result with
    | (.Ok n) => (do
      pure (0 : UInt32))
    | (.Err e) => (do
      let r2 ← float_error_code e fuel
      pure r2))
  pure r1

def float_parse_ok (result : Result_f64_FloatError) (fuel : Nat) : Option (Bool) := do
  pure (match result with | (.Ok v) => true | (.Err e) => false)

def float_parse_value (result : Result_f64_FloatError) (fallback : Float) (fuel : Nat) : Option (Float) := do
  pure (match result with | (.Ok v) => v | (.Err e) => fallback)

def float_parse_failure (result : Result_f64_FloatError) (fuel : Nat) : Option (UInt32) := do
  let r1 ← (match result with
    | (.Ok v) => (do
      pure (0 : UInt32))
    | (.Err e) => (do
      let r2 ← float_error_code e fuel
      pure r2))
  pure r1

def float_parse_ok_f32 (result : Result_f32_FloatError) (fuel : Nat) : Option (Bool) := do
  pure (match result with | (.Ok v) => true | (.Err e) => false)

def float_parse_value_f32 (result : Result_f32_FloatError) (fallback : Float32) (fuel : Nat) : Option (Float32) := do
  pure (match result with | (.Ok v) => v | (.Err e) => fallback)

def float_parse_failure_f32 (result : Result_f32_FloatError) (fuel : Nat) : Option (UInt32) := do
  let r1 ← (match result with
    | (.Ok v) => (do
      pure (0 : UInt32))
    | (.Err e) => (do
      let r2 ← float_error_code e fuel
      pure r2))
  pure r1

def dec_init (meta_ : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let meta_ := meta_.setIfInBounds 0 (0 : UInt32)
  let meta_ := meta_.setIfInBounds 1 (DP_BIAS.toUInt32)
  let meta_ := meta_.setIfInBounds 2 (0 : UInt32)
  let meta_ := meta_.setIfInBounds 3 (0 : UInt32)
  let meta_ := meta_.setIfInBounds 4 (0 : UInt32)
  pure ((), meta_)

def dec_dp (meta_ : Array UInt32) (fuel : Nat) : Option (Int32 × Array UInt32) := do
  pure ((((meta_.getD 1 (0 : UInt32)).toInt32) - DP_BIAS), meta_)

def dec_set_dp (meta_ : Array UInt32) (dp : Int32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let meta_ := meta_.setIfInBounds 1 ((dp + DP_BIAS).toUInt32)
  pure ((), meta_)

def dec_trim.loop1 (digits : Array UInt8) (nd : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (nd > (0 : UInt32))) && ((digits.getD (nd - (1 : UInt32)).toNat (0 : UInt8)) == (48 : UInt8))) then do
      let nd := (nd - (1 : UInt32))
      dec_trim.loop1 digits nd fuel
    else pure nd

def dec_trim (digits : Array UInt8) (meta_ : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let nd : UInt32 := (meta_.getD 0 (0 : UInt32))
  let nd ← dec_trim.loop1 digits nd fuel
  let meta_ := meta_.setIfInBounds 0 nd
  let () ← (if (nd == (0 : UInt32)) then (do
      let (r1, meta_) ← dec_set_dp meta_ (0 : Int32) fuel
      pure ())
    else (do
      pure ()))
  pure ((), digits, meta_)

def dec_assign.loop1 (buf : Array UInt8) (n : UInt32) (value : UInt64) : Nat → Option (Array UInt8 × UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (value > (0 : UInt64))) then do
      let v1 : UInt64 := (value / (10 : UInt64))
      let buf := buf.setIfInBounds n.toNat (((value - ((10 : UInt64) * v1)).toUInt8) + (48 : UInt8))
      let n := (n + (1 : UInt32))
      let value := v1
      dec_assign.loop1 buf n value fuel
    else pure (buf, n, value)

def dec_assign.loop2 (digits : Array UInt8) (buf : Array UInt8) (n : UInt32) (nd : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (n > (0 : UInt32))) then do
      let n := (n - (1 : UInt32))
      let digits := digits.setIfInBounds nd.toNat (buf.getD n.toNat (0 : UInt8))
      let nd := (nd + (1 : UInt32))
      dec_assign.loop2 digits buf n nd fuel
    else pure (digits, n, nd)

def dec_assign (digits : Array UInt8) (meta_ : Array UInt32) (v : UInt64) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let buf : Array UInt8 := Array.replicate 24 (0 : UInt8)
  let n : UInt32 := (0 : UInt32)
  let value : UInt64 := v
  let (buf, n, value) ← dec_assign.loop1 buf n value fuel
  let nd : UInt32 := (0 : UInt32)
  let (digits, n, nd) ← dec_assign.loop2 digits buf n nd fuel
  let meta_ := meta_.setIfInBounds 0 nd
  let (r1, meta_) ← dec_set_dp meta_ (nd.toInt32) fuel
  let (r2, digits, meta_) ← dec_trim digits meta_ fuel
  pure ((), digits, meta_)

def dec_right_shift.loop2 (k : UInt32) (r : UInt32) (n : UInt64) : Nat → Option (UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if ((n >>> (k.toUInt64)) == (0 : UInt64)) then do
      let n := (n * (10 : UInt64))
      let r := (r + (1 : UInt32))
      dec_right_shift.loop2 k r n fuel
    else pure (r, n)

def dec_right_shift.loop1 (digits : Array UInt8) (k : UInt32) (nd : UInt32) (r : UInt32) (n : UInt64) (done : Bool) (empty : Bool) : Nat → Option (UInt32 × UInt64 × Bool × Bool)
  | 0 => none
  | fuel + 1 => do
    if (!done) then do
      let (r, n, done, empty) ← (if ((n >>> (k.toUInt64)) != (0 : UInt64)) then (do
          let done := true
          pure (r, n, done, empty))
        else (do
          let (r, n, done, empty) ← (if (decide (r >= nd)) then (do
              let (r, n, done, empty) ← (if (n == (0 : UInt64)) then (do
                  let empty := true
                  let done := true
                  pure (r, n, done, empty))
                else (do
                  let (r, n) ← dec_right_shift.loop2 k r n fuel
                  let done := true
                  pure (r, n, done, empty)))
              pure (r, n, done, empty))
            else (do
              let n := (((n * (10 : UInt64)) + ((digits.getD r.toNat (0 : UInt8)).toUInt64)) - (48 : UInt64))
              let r := (r + (1 : UInt32))
              pure (r, n, done, empty)))
          pure (r, n, done, empty)))
      dec_right_shift.loop1 digits k nd r n done empty fuel
    else pure (r, n, done, empty)

def dec_right_shift.loop3 (digits : Array UInt8) (k : UInt32) (nd : UInt32) (r : UInt32) (w : UInt32) (n : UInt64) (mask : UInt64) : Nat → Option (Array UInt8 × UInt32 × UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (r < nd)) then do
      let dig : UInt64 := (n >>> (k.toUInt64))
      let n := (n &&& mask)
      let digits := digits.setIfInBounds w.toNat ((dig.toUInt8) + (48 : UInt8))
      let w := (w + (1 : UInt32))
      let n := (((n * (10 : UInt64)) + ((digits.getD r.toNat (0 : UInt8)).toUInt64)) - (48 : UInt64))
      let r := (r + (1 : UInt32))
      dec_right_shift.loop3 digits k nd r w n mask fuel
    else pure (digits, r, w, n)

def dec_right_shift.loop4 (digits : Array UInt8) (meta_ : Array UInt32) (k : UInt32) (w : UInt32) (n : UInt64) (mask : UInt64) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (n > (0 : UInt64))) then do
      let dig2 : UInt64 := (n >>> (k.toUInt64))
      let n := (n &&& mask)
      let (digits, meta_, w) ← (if (decide (w < DEC_DIGITS)) then (do
          let digits := digits.setIfInBounds w.toNat ((dig2.toUInt8) + (48 : UInt8))
          let w := (w + (1 : UInt32))
          pure (digits, meta_, w))
        else (do
          let meta_ ← (if (decide (dig2 > (0 : UInt64))) then (do
              let meta_ := meta_.setIfInBounds 3 (1 : UInt32)
              pure meta_)
            else (do
              pure meta_))
          pure (digits, meta_, w)))
      let n := (n * (10 : UInt64))
      dec_right_shift.loop4 digits meta_ k w n mask fuel
    else pure (digits, meta_, w, n)

def dec_right_shift (digits : Array UInt8) (meta_ : Array UInt32) (k : UInt32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let nd : UInt32 := (meta_.getD 0 (0 : UInt32))
  let r : UInt32 := (0 : UInt32)
  let w : UInt32 := (0 : UInt32)
  let n : UInt64 := (0 : UInt64)
  let done : Bool := false
  let empty : Bool := false
  let (r, n, done, empty) ← dec_right_shift.loop1 digits k nd r n done empty fuel
  let (digits, meta_, r, w, n) ← (if empty then (do
      let meta_ := meta_.setIfInBounds 0 (0 : UInt32)
      pure (digits, meta_, r, w, n))
    else (do
      let (r1, meta_) ← dec_dp meta_ fuel
      let (r2, meta_) ← dec_set_dp meta_ (r1 - ((r.toInt32) - (1 : Int32))) fuel
      let mask : UInt64 := (((1 : UInt64) <<< (k.toUInt64)) - (1 : UInt64))
      let (digits, r, w, n) ← dec_right_shift.loop3 digits k nd r w n mask fuel
      let (digits, meta_, w, n) ← dec_right_shift.loop4 digits meta_ k w n mask fuel
      let meta_ := meta_.setIfInBounds 0 w
      let (r3, digits, meta_) ← dec_trim digits meta_ fuel
      pure (digits, meta_, r, w, n)))
  pure ((), digits, meta_)

def dec_count_digits.loop1 (count : UInt32) (rest : UInt64) : Nat → Option (UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (rest > (0 : UInt64))) then do
      let rest := (rest / (10 : UInt64))
      let count := (count + (1 : UInt32))
      dec_count_digits.loop1 count rest fuel
    else pure (count, rest)

def dec_count_digits (v : UInt64) (fuel : Nat) : Option (UInt32) := do
  let count : UInt32 := (0 : UInt32)
  let rest : UInt64 := v
  let (count, rest) ← dec_count_digits.loop1 count rest fuel
  pure count

def dec_pow5_digits.loop1 (k : UInt32) (value : UInt64) (i : UInt32) : Nat → Option (UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < k)) then do
      let value := (value * (5 : UInt64))
      let i := (i + (1 : UInt32))
      dec_pow5_digits.loop1 k value i fuel
    else pure (value, i)

def dec_pow5_digits.loop2 (cut : Array UInt8) (value : UInt64) (at_ : UInt32) : Nat → Option (Array UInt8 × UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (at_ > (0 : UInt32))) then do
      let at_ := (at_ - (1 : UInt32))
      let cut := cut.setIfInBounds at_.toNat (((value % (10 : UInt64)).toUInt8) + (48 : UInt8))
      let value := (value / (10 : UInt64))
      dec_pow5_digits.loop2 cut value at_ fuel
    else pure (cut, value, at_)

def dec_pow5_digits (cut : Array UInt8) (k : UInt32) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let value : UInt64 := (1 : UInt64)
  let i : UInt32 := (0 : UInt32)
  let (value, i) ← dec_pow5_digits.loop1 k value i fuel
  let r1 ← dec_count_digits value fuel
  let count : UInt32 := r1
  let at_ : UInt32 := count
  let (cut, value, at_) ← dec_pow5_digits.loop2 cut value at_ fuel
  pure (count, cut)

def dec_prefix_less.loop1 (digits : Array UInt8) (nd : UInt32) (cut : Array UInt8) (cutn : UInt32) (result : Bool) (decided : Bool) (i : UInt32) : Nat → Option (Bool × Bool × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < cutn)) && (!decided)) then do
      let (result, decided, i) ← (if (decide (i >= nd)) then (do
          let result := true
          let decided := true
          pure (result, decided, i))
        else (do
          let (result, decided, i) ← (if ((digits.getD i.toNat (0 : UInt8)) != (cut.getD i.toNat (0 : UInt8))) then (do
              let result := (decide ((digits.getD i.toNat (0 : UInt8)) < (cut.getD i.toNat (0 : UInt8))))
              let decided := true
              pure (result, decided, i))
            else (do
              let i := (i + (1 : UInt32))
              pure (result, decided, i)))
          pure (result, decided, i)))
      dec_prefix_less.loop1 digits nd cut cutn result decided i fuel
    else pure (result, decided, i)

def dec_prefix_less (digits : Array UInt8) (nd : UInt32) (cut : Array UInt8) (cutn : UInt32) (fuel : Nat) : Option (Bool × Array UInt8 × Array UInt8) := do
  let result : Bool := false
  let decided : Bool := false
  let i : UInt32 := (0 : UInt32)
  let (result, decided, i) ← dec_prefix_less.loop1 digits nd cut cutn result decided i fuel
  pure (result, digits, cut)

def dec_left_shift.loop1 (digits : Array UInt8) (meta_ : Array UInt32) (k : UInt32) (r : UInt32) (w : UInt32) (n : UInt64) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (r > (0 : UInt32))) then do
      let r := (r - (1 : UInt32))
      let n := (n + ((((digits.getD r.toNat (0 : UInt8)).toUInt64) - (48 : UInt64)) <<< (k.toUInt64)))
      let quo : UInt64 := (n / (10 : UInt64))
      let rem : UInt64 := (n - ((10 : UInt64) * quo))
      let w := (w - (1 : UInt32))
      let (digits, meta_) ← (if (decide (w < DEC_DIGITS)) then (do
          let digits := digits.setIfInBounds w.toNat ((rem.toUInt8) + (48 : UInt8))
          pure (digits, meta_))
        else (do
          let meta_ ← (if (rem != (0 : UInt64)) then (do
              let meta_ := meta_.setIfInBounds 3 (1 : UInt32)
              pure meta_)
            else (do
              pure meta_))
          pure (digits, meta_)))
      let n := quo
      dec_left_shift.loop1 digits meta_ k r w n fuel
    else pure (digits, meta_, r, w, n)

def dec_left_shift.loop2 (digits : Array UInt8) (meta_ : Array UInt32) (w : UInt32) (n : UInt64) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (n > (0 : UInt64))) then do
      let quo2 : UInt64 := (n / (10 : UInt64))
      let rem2 : UInt64 := (n - ((10 : UInt64) * quo2))
      let w := (w - (1 : UInt32))
      let (digits, meta_) ← (if (decide (w < DEC_DIGITS)) then (do
          let digits := digits.setIfInBounds w.toNat ((rem2.toUInt8) + (48 : UInt8))
          pure (digits, meta_))
        else (do
          let meta_ ← (if (rem2 != (0 : UInt64)) then (do
              let meta_ := meta_.setIfInBounds 3 (1 : UInt32)
              pure meta_)
            else (do
              pure meta_))
          pure (digits, meta_)))
      let n := quo2
      dec_left_shift.loop2 digits meta_ w n fuel
    else pure (digits, meta_, w, n)

def dec_left_shift (digits : Array UInt8) (meta_ : Array UInt32) (k : UInt32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let cut : Array UInt8 := Array.replicate 24 (0 : UInt8)
  let cutn : UInt32 := (0 : UInt32)
  let r1 ← dec_count_digits ((1 : UInt64) <<< (k.toUInt64)) fuel
  let delta : UInt32 := r1
  let (cutn, delta) ← (if true then (do
      let c : Array UInt8 := cut
      let (r2, c) ← dec_pow5_digits c k fuel
      let cutn := r2
      let (r3, digits, c) ← dec_prefix_less digits (meta_.getD 0 (0 : UInt32)) c cutn fuel
      let delta ← (if r3 then (do
          let delta := (delta - (1 : UInt32))
          pure delta)
        else (do
          pure delta))
      pure (cutn, delta))
    else (do
      pure (cutn, delta)))
  let r : UInt32 := (meta_.getD 0 (0 : UInt32))
  let w : UInt32 := ((meta_.getD 0 (0 : UInt32)) + delta)
  let n : UInt64 := (0 : UInt64)
  let (digits, meta_, r, w, n) ← dec_left_shift.loop1 digits meta_ k r w n fuel
  let (digits, meta_, w, n) ← dec_left_shift.loop2 digits meta_ w n fuel
  let nd : UInt32 := ((meta_.getD 0 (0 : UInt32)) + delta)
  let nd ← (if (decide (nd > DEC_DIGITS)) then (do
      let nd := DEC_DIGITS
      pure nd)
    else (do
      pure nd))
  let meta_ := meta_.setIfInBounds 0 nd
  let (r4, meta_) ← dec_dp meta_ fuel
  let (r5, meta_) ← dec_set_dp meta_ (r4 + (delta.toInt32)) fuel
  let (r6, digits, meta_) ← dec_trim digits meta_ fuel
  pure ((), digits, meta_)

def dec_shift.loop1 (digits : Array UInt8) (meta_ : Array UInt32) (limit : Int32) (rest : Int32) : Nat → Option (Int32)
  | 0 => none
  | fuel + 1 => do
    if (decide (rest > limit)) then do
      let (r1, digits, meta_) ← dec_left_shift digits meta_ MAX_SHIFT fuel
      let rest := (rest - limit)
      dec_shift.loop1 digits meta_ limit rest fuel
    else pure rest

def dec_shift.loop2 (digits : Array UInt8) (meta_ : Array UInt32) (limit : Int32) (rest2 : Int32) : Nat → Option (Int32)
  | 0 => none
  | fuel + 1 => do
    if (decide (rest2 > limit)) then do
      let (r3, digits, meta_) ← dec_right_shift digits meta_ MAX_SHIFT fuel
      let rest2 := (rest2 - limit)
      dec_shift.loop2 digits meta_ limit rest2 fuel
    else pure rest2

def dec_shift (digits : Array UInt8) (meta_ : Array UInt32) (k : Int32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let limit : Int32 := (MAX_SHIFT.toInt32)
  let () ← (if (((meta_.getD 0 (0 : UInt32)) != (0 : UInt32)) && (decide (k > (0 : Int32)))) then (do
      let rest : Int32 := k
      let rest ← dec_shift.loop1 digits meta_ limit rest fuel
      let (r2, digits, meta_) ← dec_left_shift digits meta_ (rest.toUInt32) fuel
      pure ())
    else (do
      pure ()))
  let () ← (if (((meta_.getD 0 (0 : UInt32)) != (0 : UInt32)) && (decide (k < (0 : Int32)))) then (do
      let rest2 : Int32 := ((0 : Int32) - k)
      let rest2 ← dec_shift.loop2 digits meta_ limit rest2 fuel
      let (r4, digits, meta_) ← dec_right_shift digits meta_ (rest2.toUInt32) fuel
      pure ())
    else (do
      pure ()))
  pure ((), digits, meta_)

def dec_should_round_up (digits : Array UInt8) (meta_ : Array UInt32) (nd : UInt32) (fuel : Nat) : Option (Bool × Array UInt8 × Array UInt32) := do
  pure ((if (((digits.getD nd.toNat (0 : UInt8)) == (53 : UInt8)) && ((nd + (1 : UInt32)) == (meta_.getD 0 (0 : UInt32)))) then (if ((meta_.getD 3 (0 : UInt32)) != (0 : UInt32)) then true else ((decide (nd > (0 : UInt32))) && (((((digits.getD (nd - (1 : UInt32)).toNat (0 : UInt8)).toUInt32) - (48 : UInt32)) % (2 : UInt32)) != (0 : UInt32)))) else (decide ((digits.getD nd.toNat (0 : UInt8)) >= (53 : UInt8)))), digits, meta_)

def dec_round_down (digits : Array UInt8) (meta_ : Array UInt32) (nd : Int32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let meta_ ← (if ((decide (nd >= (0 : Int32))) && (decide ((nd.toUInt32) < (meta_.getD 0 (0 : UInt32))))) then (do
      let meta_ := meta_.setIfInBounds 0 (nd.toUInt32)
      let (r1, digits, meta_) ← dec_trim digits meta_ fuel
      pure meta_)
    else (do
      pure meta_))
  pure ((), digits, meta_)

def dec_round_up.loop1 (digits : Array UInt8) (meta_ : Array UInt32) (i : UInt32) (done : Bool) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i > (0 : UInt32))) && (!done)) then do
      let i := (i - (1 : UInt32))
      let (digits, meta_, done) ← (if (decide ((digits.getD i.toNat (0 : UInt8)) < (57 : UInt8))) then (do
          let digits := digits.setIfInBounds i.toNat ((digits.getD i.toNat (0 : UInt8)) + (1 : UInt8))
          let meta_ := meta_.setIfInBounds 0 (i + (1 : UInt32))
          let done := true
          pure (digits, meta_, done))
        else (do
          pure (digits, meta_, done)))
      dec_round_up.loop1 digits meta_ i done fuel
    else pure (digits, meta_, i, done)

def dec_round_up (digits : Array UInt8) (meta_ : Array UInt32) (nd : Int32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let (digits, meta_) ← (if ((decide (nd >= (0 : Int32))) && (decide ((nd.toUInt32) < (meta_.getD 0 (0 : UInt32))))) then (do
      let i : UInt32 := (nd.toUInt32)
      let done : Bool := false
      let (digits, meta_, i, done) ← dec_round_up.loop1 digits meta_ i done fuel
      let (digits, meta_) ← (if (!done) then (do
          let digits := digits.setIfInBounds 0 (49 : UInt8)
          let meta_ := meta_.setIfInBounds 0 (1 : UInt32)
          let (r1, meta_) ← dec_dp meta_ fuel
          let (r2, meta_) ← dec_set_dp meta_ (r1 + (1 : Int32)) fuel
          pure (digits, meta_))
        else (do
          pure (digits, meta_)))
      pure (digits, meta_))
    else (do
      pure (digits, meta_)))
  pure ((), digits, meta_)

def dec_round (digits : Array UInt8) (meta_ : Array UInt32) (nd : Int32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let () ← (if ((decide (nd >= (0 : Int32))) && (decide ((nd.toUInt32) < (meta_.getD 0 (0 : UInt32))))) then (do
      let (r1, digits, meta_) ← dec_should_round_up digits meta_ (nd.toUInt32) fuel
      let () ← (if r1 then (do
          let (r2, digits, meta_) ← dec_round_up digits meta_ nd fuel
          pure ())
        else (do
          let (r3, digits, meta_) ← dec_round_down digits meta_ nd fuel
          pure ()))
      pure ())
    else (do
      pure ()))
  pure ((), digits, meta_)

def dec_rounded_integer.loop1 (digits : Array UInt8) (meta_ : Array UInt32) (dpu : UInt32) (n : UInt64) (i : UInt32) : Nat → Option (UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < dpu)) && (decide (i < (meta_.getD 0 (0 : UInt32))))) then do
      let n := (((n * (10 : UInt64)) + ((digits.getD i.toNat (0 : UInt8)).toUInt64)) - (48 : UInt64))
      let i := (i + (1 : UInt32))
      dec_rounded_integer.loop1 digits meta_ dpu n i fuel
    else pure (n, i)

def dec_rounded_integer.loop2 (dpu : UInt32) (n : UInt64) (i : UInt32) : Nat → Option (UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < dpu)) then do
      let n := (n * (10 : UInt64))
      let i := (i + (1 : UInt32))
      dec_rounded_integer.loop2 dpu n i fuel
    else pure (n, i)

def dec_rounded_integer (digits : Array UInt8) (meta_ : Array UInt32) (fuel : Nat) : Option (UInt64 × Array UInt8 × Array UInt32) := do
  let (r1, meta_) ← dec_dp meta_ fuel
  let dp : Int32 := r1
  let r2 ← (
    if (decide (dp > (20 : Int32))) then (do
      pure (18446744073709551615 : UInt64))
    else (do
      let dpu : UInt32 := (if (decide (dp < (0 : Int32))) then (0 : UInt32) else (dp.toUInt32))
      let n : UInt64 := (0 : UInt64)
      let i : UInt32 := (0 : UInt32)
      let (n, i) ← dec_rounded_integer.loop1 digits meta_ dpu n i fuel
      let (n, i) ← dec_rounded_integer.loop2 dpu n i fuel
      let (r3, digits, meta_) ← dec_should_round_up digits meta_ dpu fuel
      pure (if (((decide (dp >= (0 : Int32))) && (decide (dpu < (meta_.getD 0 (0 : UInt32))))) && r3) then (n + (1 : UInt64)) else n)))
  pure (r2, digits, meta_)

def float_fmt_e_size (neg : Bool) (nd : UInt32) (dp : Int32) (prec : Int32) (fuel : Nat) : Option (UInt32) := do
  let bexp : Int32 := (if (nd == (0 : UInt32)) then (0 : Int32) else (dp - (1 : Int32)))
  let mag : Int32 := (if (decide (bexp < (0 : Int32))) then ((0 : Int32) - bexp) else bexp)
  let sign : UInt32 := (if neg then (1 : UInt32) else (0 : UInt32))
  let frac : UInt32 := (if (decide (prec > (0 : Int32))) then ((1 : UInt32) + (prec.toUInt32)) else (0 : UInt32))
  let expw : UInt32 := (if (decide (mag < (100 : Int32))) then (2 : UInt32) else (3 : UInt32))
  pure ((((sign + (1 : UInt32)) + frac) + (2 : UInt32)) + expw)

def float_fmt_e.loop1 (dst : Array UInt8) (digits : Array UInt8) (out : UInt32) (i : UInt32) (m : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < m)) then do
      let dst := dst.setIfInBounds out.toNat (digits.getD i.toNat (0 : UInt8))
      let out := (out + (1 : UInt32))
      let i := (i + (1 : UInt32))
      float_fmt_e.loop1 dst digits out i m fuel
    else pure (dst, out, i)

def float_fmt_e.loop2 (dst : Array UInt8) (out : UInt32) (p : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i <= p)) then do
      let dst := dst.setIfInBounds out.toNat (48 : UInt8)
      let out := (out + (1 : UInt32))
      let i := (i + (1 : UInt32))
      float_fmt_e.loop2 dst out p i fuel
    else pure (dst, out, i)

def float_fmt_e (dst : Array UInt8) (digits : Array UInt8) (nd : UInt32) (dp : Int32) (prec : Int32) (neg : Bool) (fuel : Nat) : Option (UInt32 × Array UInt8 × Array UInt8) := do
  let out : UInt32 := (0 : UInt32)
  let (dst, out) ← (if neg then (do
      let dst := dst.setIfInBounds out.toNat (45 : UInt8)
      let out := (out + (1 : UInt32))
      pure (dst, out))
    else (do
      pure (dst, out)))
  let dst := dst.setIfInBounds out.toNat (if (nd != (0 : UInt32)) then (digits.getD 0 (0 : UInt8)) else (48 : UInt8))
  let out := (out + (1 : UInt32))
  let (dst, out) ← (if (decide (prec > (0 : Int32))) then (do
      let dst := dst.setIfInBounds out.toNat (46 : UInt8)
      let out := (out + (1 : UInt32))
      let p : UInt32 := (prec.toUInt32)
      let i : UInt32 := (1 : UInt32)
      let m : UInt32 := (if (decide (nd < (p + (1 : UInt32)))) then nd else (p + (1 : UInt32)))
      let (dst, out, i) ← float_fmt_e.loop1 dst digits out i m fuel
      let (dst, out, i) ← float_fmt_e.loop2 dst out p i fuel
      pure (dst, out))
    else (do
      pure (dst, out)))
  let dst := dst.setIfInBounds out.toNat (101 : UInt8)
  let out := (out + (1 : UInt32))
  let bexp : Int32 := (if (nd == (0 : UInt32)) then (0 : Int32) else (dp - (1 : Int32)))
  let (dst, bexp) ← (if (decide (bexp < (0 : Int32))) then (do
      let dst := dst.setIfInBounds out.toNat (45 : UInt8)
      let bexp := ((0 : Int32) - bexp)
      pure (dst, bexp))
    else (do
      let dst := dst.setIfInBounds out.toNat (43 : UInt8)
      pure (dst, bexp)))
  let out := (out + (1 : UInt32))
  let e : UInt32 := (bexp.toUInt32)
  let (dst, out) ← (if (decide (e < (10 : UInt32))) then (do
      let dst := dst.setIfInBounds out.toNat (48 : UInt8)
      let dst := dst.setIfInBounds (out + (1 : UInt32)).toNat ((48 : UInt8) + (e.toUInt8))
      let out := (out + (2 : UInt32))
      pure (dst, out))
    else (do
      let (dst, out) ← (if (decide (e < (100 : UInt32))) then (do
          let dst := dst.setIfInBounds out.toNat ((48 : UInt8) + ((e / (10 : UInt32)).toUInt8))
          let dst := dst.setIfInBounds (out + (1 : UInt32)).toNat ((48 : UInt8) + ((e % (10 : UInt32)).toUInt8))
          let out := (out + (2 : UInt32))
          pure (dst, out))
        else (do
          let dst := dst.setIfInBounds out.toNat ((48 : UInt8) + ((e / (100 : UInt32)).toUInt8))
          let dst := dst.setIfInBounds (out + (1 : UInt32)).toNat ((48 : UInt8) + (((e / (10 : UInt32)) % (10 : UInt32)).toUInt8))
          let dst := dst.setIfInBounds (out + (2 : UInt32)).toNat ((48 : UInt8) + ((e % (10 : UInt32)).toUInt8))
          let out := (out + (3 : UInt32))
          pure (dst, out)))
      pure (dst, out)))
  pure (out, dst, digits)

def float_fmt_f_size (neg : Bool) (dp : Int32) (prec : UInt32) (fuel : Nat) : Option (UInt32) := do
  let sign : UInt32 := (if neg then (1 : UInt32) else (0 : UInt32))
  let whole : UInt32 := (if (decide (dp > (0 : Int32))) then (dp.toUInt32) else (1 : UInt32))
  let frac : UInt32 := (if (decide (prec > (0 : UInt32))) then ((1 : UInt32) + prec) else (0 : UInt32))
  pure ((sign + whole) + frac)

def float_fmt_f.loop1 (dst : Array UInt8) (digits : Array UInt8) (out : UInt32) (m : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < m)) then do
      let dst := dst.setIfInBounds out.toNat (digits.getD i.toNat (0 : UInt8))
      let out := (out + (1 : UInt32))
      let i := (i + (1 : UInt32))
      float_fmt_f.loop1 dst digits out m i fuel
    else pure (dst, out, i)

def float_fmt_f.loop2 (dst : Array UInt8) (out : UInt32) (dpu : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < dpu)) then do
      let dst := dst.setIfInBounds out.toNat (48 : UInt8)
      let out := (out + (1 : UInt32))
      let i := (i + (1 : UInt32))
      float_fmt_f.loop2 dst out dpu i fuel
    else pure (dst, out, i)

def float_fmt_f.loop3 (dst : Array UInt8) (digits : Array UInt8) (nd : UInt32) (dp : Int32) (prec : UInt32) (out : UInt32) (f : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (f < prec)) then do
      let j : Int32 := (dp + (f.toInt32))
      let ch : UInt8 := (48 : UInt8)
      let ch ← (if ((decide (j >= (0 : Int32))) && (decide ((j.toUInt32) < nd))) then (do
          let ch := (digits.getD (j.toUInt32).toNat (0 : UInt8))
          pure ch)
        else (do
          pure ch))
      let dst := dst.setIfInBounds out.toNat ch
      let out := (out + (1 : UInt32))
      let f := (f + (1 : UInt32))
      float_fmt_f.loop3 dst digits nd dp prec out f fuel
    else pure (dst, out, f)

def float_fmt_f (dst : Array UInt8) (digits : Array UInt8) (nd : UInt32) (dp : Int32) (prec : UInt32) (neg : Bool) (fuel : Nat) : Option (UInt32 × Array UInt8 × Array UInt8) := do
  let out : UInt32 := (0 : UInt32)
  let (dst, out) ← (if neg then (do
      let dst := dst.setIfInBounds out.toNat (45 : UInt8)
      let out := (out + (1 : UInt32))
      pure (dst, out))
    else (do
      pure (dst, out)))
  let (dst, out) ← (if (decide (dp > (0 : Int32))) then (do
      let dpu : UInt32 := (dp.toUInt32)
      let m : UInt32 := (if (decide (nd < dpu)) then nd else dpu)
      let i : UInt32 := (0 : UInt32)
      let (dst, out, i) ← float_fmt_f.loop1 dst digits out m i fuel
      let (dst, out, i) ← float_fmt_f.loop2 dst out dpu i fuel
      pure (dst, out))
    else (do
      let dst := dst.setIfInBounds out.toNat (48 : UInt8)
      let out := (out + (1 : UInt32))
      pure (dst, out)))
  let (dst, out) ← (if (decide (prec > (0 : UInt32))) then (do
      let dst := dst.setIfInBounds out.toNat (46 : UInt8)
      let out := (out + (1 : UInt32))
      let f : UInt32 := (0 : UInt32)
      let (dst, out, f) ← float_fmt_f.loop3 dst digits nd dp prec out f fuel
      pure (dst, out))
    else (do
      pure (dst, out)))
  pure (out, dst, digits)

def float_format_digits (dst : Array UInt8) (digits : Array UInt8) (nd : UInt32) (dp : Int32) (prec : Int32) (fmt : UInt8) (shortest : Bool) (neg : Bool) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8 × Array UInt8) := do
  let ndi : Int32 := (nd.toInt32)
  let use_e : Bool := (fmt == (101 : UInt8))
  let eprec : Int32 := prec
  let fprec : Int32 := prec
  let (use_e, eprec, fprec) ← (if (fmt == (103 : UInt8)) then (do
      let limit : Int32 := prec
      let limit ← (if ((decide (limit > ndi)) && (decide (ndi >= dp))) then (do
          let limit := ndi
          pure limit)
        else (do
          pure limit))
      let limit ← (if shortest then (do
          let limit := (6 : Int32)
          pure limit)
        else (do
          pure limit))
      let bexp : Int32 := (dp - (1 : Int32))
      let (use_e, eprec, fprec) ← (if ((decide (bexp < (0 - (4 : Int32)))) || (decide (bexp >= limit))) then (do
          let use_e := true
          let eprec := ((if (decide (prec > ndi)) then ndi else prec) - (1 : Int32))
          pure (use_e, eprec, fprec))
        else (do
          let p : Int32 := (if (decide (prec > dp)) then ndi else prec)
          let fprec := (if (decide ((p - dp) > (0 : Int32))) then (p - dp) else (0 : Int32))
          pure (use_e, eprec, fprec)))
      pure (use_e, eprec, fprec))
    else (do
      pure (use_e, eprec, fprec)))
  let fprec ← (if (decide (fprec < (0 : Int32))) then (do
      let fprec := (0 : Int32)
      pure fprec)
    else (do
      pure fprec))
  let r1 ← (
    if use_e then (do
      let r2 ← float_fmt_e_size neg nd dp eprec fuel
      pure r2)
    else (do
      let r3 ← float_fmt_f_size neg dp (fprec.toUInt32) fuel
      pure r3))
  let needed : UInt32 := r1
  let r4 ← (
    if (decide (needed > (dst.size.toUInt32))) then (do
      pure (Result_u32_FloatError.Err FloatError.DestinationTooSmall))
    else (do
      let r5 ← (
        if use_e then (do
          let (r6, dst, digits) ← float_fmt_e dst digits nd dp eprec neg fuel
          pure (Result_u32_FloatError.Ok r6))
        else (do
          let (r7, dst, digits) ← float_fmt_f dst digits nd dp (fprec.toUInt32) neg fuel
          pure (Result_u32_FloatError.Ok r7)))
      pure r5))
  pure (r4, dst, digits)

def float_round_shortest.loop1 (d : Array UInt8) (dmeta : Array UInt32) (up : Array UInt8) (lo : Array UInt8) (dp : Int32) (nd : Int32) (inclusive : Bool) (upperdelta : UInt32) (udp : Int32) (und : Int32) (ldp : Int32) (lnd : Int32) (ui : Int32) (done : Bool) : Nat → Option (UInt32 × Int32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if (!done) then do
      let mi : Int32 := ((ui - udp) + dp)
      let (upperdelta, ui, done) ← (if (decide (mi >= nd)) then (do
          let done := true
          pure (upperdelta, ui, done))
        else (do
          let li : Int32 := ((ui - udp) + ldp)
          let l : UInt8 := (48 : UInt8)
          let l ← (if ((decide (li >= (0 : Int32))) && (decide (li < lnd))) then (do
              let l := (lo.getD (li.toUInt32).toNat (0 : UInt8))
              pure l)
            else (do
              pure l))
          let m : UInt8 := (48 : UInt8)
          let m ← (if (decide (mi >= (0 : Int32))) then (do
              let m := (d.getD (mi.toUInt32).toNat (0 : UInt8))
              pure m)
            else (do
              pure m))
          let u : UInt8 := (48 : UInt8)
          let u ← (if (decide (ui < und)) then (do
              let u := (up.getD (ui.toUInt32).toNat (0 : UInt8))
              pure u)
            else (do
              pure u))
          let okdown : Bool := ((l != m) || (inclusive && ((li + (1 : Int32)) == lnd)))
          let prev : UInt32 := upperdelta
          let upperdelta ← (if ((prev == (0 : UInt32)) && (decide ((m + (1 : UInt8)) < u))) then (do
              let upperdelta := (2 : UInt32)
              pure upperdelta)
            else (do
              pure upperdelta))
          let upperdelta ← (if (((prev == (0 : UInt32)) && (decide ((m + (1 : UInt8)) >= u))) && (m != u)) then (do
              let upperdelta := (1 : UInt32)
              pure upperdelta)
            else (do
              pure upperdelta))
          let upperdelta ← (if ((prev == (1 : UInt32)) && ((m != (57 : UInt8)) || (u != (48 : UInt8)))) then (do
              let upperdelta := (2 : UInt32)
              pure upperdelta)
            else (do
              pure upperdelta))
          let okup : Bool := ((decide (upperdelta > (0 : UInt32))) && ((inclusive || (decide (upperdelta > (1 : UInt32)))) || (decide ((ui + (1 : Int32)) < und))))
          let (ui, done) ← (if (okdown && okup) then (do
              let (r10, d, dmeta) ← dec_round d dmeta (mi + (1 : Int32)) fuel
              let done := true
              pure (ui, done))
            else (do
              let (ui, done) ← (if okdown then (do
                  let (r11, d, dmeta) ← dec_round_down d dmeta (mi + (1 : Int32)) fuel
                  let done := true
                  pure (ui, done))
                else (do
                  let (ui, done) ← (if okup then (do
                      let (r12, d, dmeta) ← dec_round_up d dmeta (mi + (1 : Int32)) fuel
                      let done := true
                      pure (ui, done))
                    else (do
                      let ui := (ui + (1 : Int32))
                      pure (ui, done)))
                  pure (ui, done)))
              pure (ui, done)))
          pure (upperdelta, ui, done)))
      float_round_shortest.loop1 d dmeta up lo dp nd inclusive upperdelta udp und ldp lnd ui done fuel
    else pure (upperdelta, ui, done)

def float_round_shortest (d : Array UInt8) (dmeta : Array UInt32) (up : Array UInt8) (umeta : Array UInt32) (lo : Array UInt8) (lmeta : Array UInt32) (mant : UInt64) (bexp : Int32) (mantbits : UInt32) (bias : Int32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32) := do
  let dmeta ← (if (mant == (0 : UInt64)) then (do
      let dmeta := dmeta.setIfInBounds 0 (0 : UInt32)
      pure dmeta)
    else (do
      let minexp : Int32 := (bias + (1 : Int32))
      let mb : Int32 := (mantbits.toInt32)
      let (r1, dmeta) ← dec_dp dmeta fuel
      let dp : Int32 := r1
      let nd : Int32 := ((dmeta.getD 0 (0 : UInt32)).toInt32)
      let already : Bool := ((decide (bexp > minexp)) && (decide (((332 : Int32) * (dp - nd)) >= ((100 : Int32) * (bexp - mb)))))
      let () ← (if (!already) then (do
          let (r2, umeta) ← dec_init umeta fuel
          let (r3, up, umeta) ← dec_assign up umeta ((mant * (2 : UInt64)) + (1 : UInt64)) fuel
          let (r4, up, umeta) ← dec_shift up umeta ((bexp - mb) - (1 : Int32)) fuel
          let mantlo : UInt64 := (0 : UInt64)
          let explo : Int32 := (0 : Int32)
          let (mantlo, explo) ← (if ((decide (mant > ((1 : UInt64) <<< (mantbits.toUInt64)))) || (bexp == minexp)) then (do
              let mantlo := (mant - (1 : UInt64))
              let explo := bexp
              pure (mantlo, explo))
            else (do
              let mantlo := ((mant * (2 : UInt64)) - (1 : UInt64))
              let explo := (bexp - (1 : Int32))
              pure (mantlo, explo)))
          let (r5, lmeta) ← dec_init lmeta fuel
          let (r6, lo, lmeta) ← dec_assign lo lmeta ((mantlo * (2 : UInt64)) + (1 : UInt64)) fuel
          let (r7, lo, lmeta) ← dec_shift lo lmeta ((explo - mb) - (1 : Int32)) fuel
          let inclusive : Bool := ((mant % (2 : UInt64)) == (0 : UInt64))
          let upperdelta : UInt32 := (0 : UInt32)
          let (r8, umeta) ← dec_dp umeta fuel
          let udp : Int32 := r8
          let und : Int32 := ((umeta.getD 0 (0 : UInt32)).toInt32)
          let (r9, lmeta) ← dec_dp lmeta fuel
          let ldp : Int32 := r9
          let lnd : Int32 := ((lmeta.getD 0 (0 : UInt32)).toInt32)
          let ui : Int32 := (0 : Int32)
          let done : Bool := false
          let (upperdelta, ui, done) ← float_round_shortest.loop1 d dmeta up lo dp nd inclusive upperdelta udp und ldp lnd ui done fuel
          pure ())
        else (do
          pure ()))
      pure dmeta))
  pure ((), d, dmeta, up, umeta, lo, lmeta)

def float_big_ftoa (dst : Array UInt8) (d : Array UInt8) (dmeta : Array UInt32) (up : Array UInt8) (umeta : Array UInt32) (lo : Array UInt8) (lmeta : Array UInt32) (prec : Int32) (fmt : UInt8) (neg : Bool) (mant : UInt64) (bexp : Int32) (mantbits : UInt32) (bias : Int32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8 × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32) := do
  let (r1, dmeta) ← dec_init dmeta fuel
  let (r2, d, dmeta) ← dec_assign d dmeta mant fuel
  let (r3, d, dmeta) ← dec_shift d dmeta (bexp - (mantbits.toInt32)) fuel
  let shortest : Bool := (decide (prec < (0 : Int32)))
  let p : Int32 := prec
  let p ← (if shortest then (do
      let (r4, d, dmeta, up, umeta, lo, lmeta) ← float_round_shortest d dmeta up umeta lo lmeta mant bexp mantbits bias fuel
      let nd : Int32 := ((dmeta.getD 0 (0 : UInt32)).toInt32)
      let (r5, dmeta) ← dec_dp dmeta fuel
      let dp : Int32 := r5
      let p ← (if (fmt == (101 : UInt8)) then (do
          let p := (nd - (1 : Int32))
          pure p)
        else (do
          let p ← (if (fmt == (102 : UInt8)) then (do
              let p := (if (decide ((nd - dp) > (0 : Int32))) then (nd - dp) else (0 : Int32))
              pure p)
            else (do
              let p := nd
              pure p))
          pure p))
      pure p)
    else (do
      let p ← (if (fmt == (101 : UInt8)) then (do
          let (r6, d, dmeta) ← dec_round d dmeta (p + (1 : Int32)) fuel
          pure p)
        else (do
          let p ← (if (fmt == (102 : UInt8)) then (do
              let (r7, dmeta) ← dec_dp dmeta fuel
              let (r8, d, dmeta) ← dec_round d dmeta (r7 + p) fuel
              pure p)
            else (do
              let p ← (if (p == (0 : Int32)) then (do
                  let p := (1 : Int32)
                  pure p)
                else (do
                  pure p))
              let (r9, d, dmeta) ← dec_round d dmeta p fuel
              pure p))
          pure p))
      pure p))
  let (r10, dmeta) ← dec_dp dmeta fuel
  let (r11, dst, d) ← float_format_digits dst d (dmeta.getD 0 (0 : UInt32)) r10 p fmt shortest neg fuel
  pure (r11, dst, d, dmeta, up, umeta, lo, lmeta)

def float_write_special (dst : Array UInt8) (is_nan : Bool) (neg : Bool) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let needed : UInt32 := (if is_nan then (3 : UInt32) else (4 : UInt32))
  let (r1, dst) ← (
    if (decide (needed > (dst.size.toUInt32))) then (do
      pure ((Result_u32_FloatError.Err FloatError.DestinationTooSmall), dst))
    else (do
      let (r2, dst) ← (
        if is_nan then (do
          let dst := dst.setIfInBounds 0 (78 : UInt8)
          let dst := dst.setIfInBounds 1 (97 : UInt8)
          let dst := dst.setIfInBounds 2 (78 : UInt8)
          pure ((Result_u32_FloatError.Ok (3 : UInt32)), dst))
        else (do
          let dst := dst.setIfInBounds 0 (if neg then (45 : UInt8) else (43 : UInt8))
          let dst := dst.setIfInBounds 1 (73 : UInt8)
          let dst := dst.setIfInBounds 2 (110 : UInt8)
          let dst := dst.setIfInBounds 3 (102 : UInt8)
          pure ((Result_u32_FloatError.Ok (4 : UInt32)), dst)))
      pure (r2, dst)))
  pure (r1, dst)

def float_generic (dst : Array UInt8) (bits : UInt64) (mantbits : UInt32) (expbits : UInt32) (bias : Int32) (fmt : UInt8) (prec : Int32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let neg : Bool := ((bits >>> ((mantbits + expbits).toUInt64)) != (0 : UInt64))
  let expmask : UInt32 := (((1 : UInt32) <<< expbits) - (1 : UInt32))
  let expfield : UInt32 := (((bits >>> (mantbits.toUInt64)).toUInt32) &&& expmask)
  let mant : UInt64 := (bits &&& (((1 : UInt64) <<< (mantbits.toUInt64)) - (1 : UInt64)))
  let (r1, mant) ← (
    if (expfield == expmask) then (do
      let (r2, dst) ← float_write_special dst (mant != (0 : UInt64)) neg fuel
      pure (r2, mant))
    else (do
      let bexp : Int32 := ((if (expfield == (0 : UInt32)) then (1 : Int32) else (expfield.toInt32)) + bias)
      let mant ← (if (expfield != (0 : UInt32)) then (do
          let mant := (mant ||| ((1 : UInt64) <<< (mantbits.toUInt64)))
          pure mant)
        else (do
          pure mant))
      let d : Array UInt8 := Array.replicate 800 (0 : UInt8)
      let dmeta : Array UInt32 := Array.replicate 5 (0 : UInt32)
      let up : Array UInt8 := Array.replicate 800 (0 : UInt8)
      let umeta : Array UInt32 := Array.replicate 5 (0 : UInt32)
      let lo : Array UInt8 := Array.replicate 800 (0 : UInt8)
      let lmeta : Array UInt32 := Array.replicate 5 (0 : UInt32)
      let (r3, dst, d, dmeta, up, umeta, lo, lmeta) ← float_big_ftoa dst d dmeta up umeta lo lmeta prec fmt neg mant bexp mantbits bias fuel
      pure (r3, mant)))
  pure (r1, dst)

def float_format (dst : Array UInt8) (value : Float) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let (r1, dst) ← float_generic dst (value.toBits) (52 : UInt32) (11 : UInt32) (0 - (1023 : Int32)) (103 : UInt8) (0 - (1 : Int32)) fuel
  pure (r1, dst)

def float_format_fixed (dst : Array UInt8) (value : Float) (digits : UInt32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let (r1, dst) ← float_generic dst (value.toBits) (52 : UInt32) (11 : UInt32) (0 - (1023 : Int32)) (102 : UInt8) (digits.toInt32) fuel
  pure (r1, dst)

def float_format_exp (dst : Array UInt8) (value : Float) (digits : UInt32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let (r1, dst) ← float_generic dst (value.toBits) (52 : UInt32) (11 : UInt32) (0 - (1023 : Int32)) (101 : UInt8) (digits.toInt32) fuel
  pure (r1, dst)

def float_format_f32 (dst : Array UInt8) (value : Float32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let (r1, dst) ← float_generic dst ((value.toBits).toUInt64) (23 : UInt32) (8 : UInt32) (0 - (127 : Int32)) (103 : UInt8) (0 - (1 : Int32)) fuel
  pure (r1, dst)

def float_format_fixed_f32 (dst : Array UInt8) (value : Float32) (digits : UInt32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let (r1, dst) ← float_generic dst ((value.toBits).toUInt64) (23 : UInt32) (8 : UInt32) (0 - (127 : Int32)) (102 : UInt8) (digits.toInt32) fuel
  pure (r1, dst)

def float_format_exp_f32 (dst : Array UInt8) (value : Float32) (digits : UInt32) (fuel : Nat) : Option (Result_u32_FloatError × Array UInt8) := do
  let (r1, dst) ← float_generic dst ((value.toBits).toUInt64) (23 : UInt32) (8 : UInt32) (0 - (127 : Int32)) (101 : UInt8) (digits.toInt32) fuel
  pure (r1, dst)

def float_lower (unit : UInt8) (fuel : Nat) : Option (UInt8) := do
  pure (if ((decide (unit >= (65 : UInt8))) && (decide (unit <= (90 : UInt8)))) then (unit + (32 : UInt8)) else unit)

def float_special (src : Array UInt8) (fuel : Nat) : Option (UInt32) := do
  let n : UInt32 := (src.size.toUInt32)
  let i : UInt32 := (0 : UInt32)
  let has_sign : Bool := ((decide (n > (0 : UInt32))) && (((src.getD 0 (0 : UInt8)) == (43 : UInt8)) || ((src.getD 0 (0 : UInt8)) == (45 : UInt8))))
  let neg : Bool := ((decide (n > (0 : UInt32))) && ((src.getD 0 (0 : UInt8)) == (45 : UInt8)))
  let i ← (if has_sign then (do
      let i := (1 : UInt32)
      pure i)
    else (do
      pure i))
  let rest : UInt32 := (n - i)
  let r1 ← float_lower (src.getD i.toNat (0 : UInt8)) fuel
  let r2 ← float_lower (src.getD (i + (1 : UInt32)).toNat (0 : UInt8)) fuel
  let r3 ← float_lower (src.getD (i + (2 : UInt32)).toNat (0 : UInt8)) fuel
  let inf3 : Bool := ((((rest == (3 : UInt32)) && (r1 == (105 : UInt8))) && (r2 == (110 : UInt8))) && (r3 == (102 : UInt8)))
  let r4 ← float_lower (src.getD i.toNat (0 : UInt8)) fuel
  let r5 ← float_lower (src.getD (i + (1 : UInt32)).toNat (0 : UInt8)) fuel
  let r6 ← float_lower (src.getD (i + (2 : UInt32)).toNat (0 : UInt8)) fuel
  let r7 ← float_lower (src.getD (i + (3 : UInt32)).toNat (0 : UInt8)) fuel
  let r8 ← float_lower (src.getD (i + (4 : UInt32)).toNat (0 : UInt8)) fuel
  let r9 ← float_lower (src.getD (i + (5 : UInt32)).toNat (0 : UInt8)) fuel
  let r10 ← float_lower (src.getD (i + (6 : UInt32)).toNat (0 : UInt8)) fuel
  let r11 ← float_lower (src.getD (i + (7 : UInt32)).toNat (0 : UInt8)) fuel
  let inf8 : Bool := (((((((((rest == (8 : UInt32)) && (r4 == (105 : UInt8))) && (r5 == (110 : UInt8))) && (r6 == (102 : UInt8))) && (r7 == (105 : UInt8))) && (r8 == (110 : UInt8))) && (r9 == (105 : UInt8))) && (r10 == (116 : UInt8))) && (r11 == (121 : UInt8)))
  let r12 ← float_lower (src.getD 0 (0 : UInt8)) fuel
  let r13 ← float_lower (src.getD 1 (0 : UInt8)) fuel
  let r14 ← float_lower (src.getD 2 (0 : UInt8)) fuel
  let is_nan : Bool := (((((!has_sign) && (rest == (3 : UInt32))) && (r12 == (110 : UInt8))) && (r13 == (97 : UInt8))) && (r14 == (110 : UInt8)))
  pure (if (inf3 || inf8) then (if neg then (2 : UInt32) else (1 : UInt32)) else (if is_nan then (3 : UInt32) else (0 : UInt32)))

def dec_set.loop1 (digits : Array UInt8) (meta_ : Array UInt32) (src : Array UInt8) (n : UInt32) (i : UInt32) (sawdot : Bool) (sawdigits : Bool) (bad : Bool) (nd : UInt32) (dp : Int32) (scanning : Bool) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × Bool × Bool × Bool × UInt32 × Int32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if (scanning && (decide (i < n))) then do
      let c : UInt8 := (src.getD i.toNat (0 : UInt8))
      let (digits, meta_, i, sawdot, sawdigits, bad, nd, dp, scanning) ← (if (c == (46 : UInt8)) then (do
          let (i, sawdot, bad, dp, scanning) ← (if sawdot then (do
              let bad := true
              let scanning := false
              pure (i, sawdot, bad, dp, scanning))
            else (do
              let sawdot := true
              let dp := (nd.toInt32)
              let i := (i + (1 : UInt32))
              pure (i, sawdot, bad, dp, scanning)))
          pure (digits, meta_, i, sawdot, sawdigits, bad, nd, dp, scanning))
        else (do
          let (digits, meta_, i, sawdigits, nd, dp, scanning) ← (if ((decide (c >= (48 : UInt8))) && (decide (c <= (57 : UInt8)))) then (do
              let sawdigits := true
              let (digits, meta_, nd, dp) ← (if ((c == (48 : UInt8)) && (nd == (0 : UInt32))) then (do
                  let dp := (dp - (1 : Int32))
                  pure (digits, meta_, nd, dp))
                else (do
                  let (digits, meta_, nd) ← (if (decide (nd < DEC_DIGITS)) then (do
                      let digits := digits.setIfInBounds nd.toNat c
                      let nd := (nd + (1 : UInt32))
                      pure (digits, meta_, nd))
                    else (do
                      let meta_ ← (if (c != (48 : UInt8)) then (do
                          let meta_ := meta_.setIfInBounds 3 (1 : UInt32)
                          pure meta_)
                        else (do
                          pure meta_))
                      pure (digits, meta_, nd)))
                  pure (digits, meta_, nd, dp)))
              let i := (i + (1 : UInt32))
              pure (digits, meta_, i, sawdigits, nd, dp, scanning))
            else (do
              let scanning := false
              pure (digits, meta_, i, sawdigits, nd, dp, scanning)))
          pure (digits, meta_, i, sawdot, sawdigits, bad, nd, dp, scanning)))
      dec_set.loop1 digits meta_ src n i sawdot sawdigits bad nd dp scanning fuel
    else pure (digits, meta_, i, sawdot, sawdigits, bad, nd, dp, scanning)

def dec_set.loop2 (src : Array UInt8) (n : UInt32) (i : UInt32) (e : Int32) : Nat → Option (UInt32 × Int32)
  | 0 => none
  | fuel + 1 => do
    if (((decide (i < n)) && (decide ((src.getD i.toNat (0 : UInt8)) >= (48 : UInt8)))) && (decide ((src.getD i.toNat (0 : UInt8)) <= (57 : UInt8)))) then do
      let e ← (if (decide (e < (10000 : Int32))) then (do
          let e := ((e * (10 : Int32)) + ((((src.getD i.toNat (0 : UInt8)).toUInt32) - (48 : UInt32)).toInt32))
          pure e)
        else (do
          pure e))
      let i := (i + (1 : UInt32))
      dec_set.loop2 src n i e fuel
    else pure (i, e)

def dec_set (digits : Array UInt8) (meta_ : Array UInt32) (src : Array UInt8) (fuel : Nat) : Option (Bool × Array UInt8 × Array UInt32) := do
  let n : UInt32 := (src.size.toUInt32)
  let i : UInt32 := (0 : UInt32)
  let i ← (if ((decide (n > (0 : UInt32))) && ((src.getD 0 (0 : UInt8)) == (43 : UInt8))) then (do
      let i := (1 : UInt32)
      pure i)
    else (do
      pure i))
  let (meta_, i) ← (if ((decide (n > (0 : UInt32))) && ((src.getD 0 (0 : UInt8)) == (45 : UInt8))) then (do
      let i := (1 : UInt32)
      let meta_ := meta_.setIfInBounds 2 (1 : UInt32)
      pure (meta_, i))
    else (do
      pure (meta_, i)))
  let sawdot : Bool := false
  let sawdigits : Bool := false
  let bad : Bool := false
  let nd : UInt32 := (0 : UInt32)
  let dp : Int32 := (0 : Int32)
  let scanning : Bool := true
  let (digits, meta_, i, sawdot, sawdigits, bad, nd, dp, scanning) ← dec_set.loop1 digits meta_ src n i sawdot sawdigits bad nd dp scanning fuel
  let dp ← (if (!sawdot) then (do
      let dp := (nd.toInt32)
      pure dp)
    else (do
      pure dp))
  let (i, bad, dp) ← (if ((((!bad) && sawdigits) && (decide (i < n))) && (((src.getD i.toNat (0 : UInt8)) == (101 : UInt8)) || ((src.getD i.toNat (0 : UInt8)) == (69 : UInt8)))) then (do
      let i := (i + (1 : UInt32))
      let esign : Int32 := (1 : Int32)
      let i ← (if ((decide (i < n)) && ((src.getD i.toNat (0 : UInt8)) == (43 : UInt8))) then (do
          let i := (i + (1 : UInt32))
          pure i)
        else (do
          pure i))
      let (i, esign) ← (if ((decide (i < n)) && ((src.getD i.toNat (0 : UInt8)) == (45 : UInt8))) then (do
          let i := (i + (1 : UInt32))
          let esign := (0 - (1 : Int32))
          pure (i, esign))
        else (do
          pure (i, esign)))
      let (i, bad, dp) ← (if (((decide (i >= n)) || (decide ((src.getD i.toNat (0 : UInt8)) < (48 : UInt8)))) || (decide ((src.getD i.toNat (0 : UInt8)) > (57 : UInt8)))) then (do
          let bad := true
          pure (i, bad, dp))
        else (do
          let e : Int32 := (0 : Int32)
          let (i, e) ← dec_set.loop2 src n i e fuel
          let dp := (dp + (e * esign))
          pure (i, bad, dp)))
      pure (i, bad, dp))
    else (do
      pure (i, bad, dp)))
  let meta_ := meta_.setIfInBounds 0 nd
  let (r1, meta_) ← dec_set_dp meta_ dp fuel
  pure ((((!bad) && sawdigits) && (i == n)), digits, meta_)

def dec_float_bits.loop1 (digits : Array UInt8) (meta_ : Array UInt32) (powtab : Array Int32) (bexp : Int32) : Nat → Option (Int32)
  | 0 => none
  | fuel + 1 => do
    let (r2, meta_) ← dec_dp meta_ fuel
    if (decide (r2 > (0 : Int32))) then do
      let (r3, meta_) ← dec_dp meta_ fuel
      let cur : Int32 := r3
      let n : Int32 := (if (decide (cur >= (9 : Int32))) then (27 : Int32) else (powtab.getD (cur.toUInt32).toNat (0 : Int32)))
      let (r4, digits, meta_) ← dec_shift digits meta_ ((0 : Int32) - n) fuel
      let bexp := (bexp + n)
      dec_float_bits.loop1 digits meta_ powtab bexp fuel
    else pure bexp

def dec_float_bits.loop2 (digits : Array UInt8) (meta_ : Array UInt32) (powtab : Array Int32) (bexp : Int32) : Nat → Option (Int32)
  | 0 => none
  | fuel + 1 => do
    let (r5, meta_) ← dec_dp meta_ fuel
    let (r6, meta_) ← dec_dp meta_ fuel
    if ((decide (r5 < (0 : Int32))) || ((r6 == (0 : Int32)) && (decide ((digits.getD 0 (0 : UInt8)) < (53 : UInt8))))) then do
      let (r7, meta_) ← dec_dp meta_ fuel
      let cur2 : Int32 := ((0 : Int32) - r7)
      let n2 : Int32 := (if (decide (cur2 >= (9 : Int32))) then (27 : Int32) else (powtab.getD (cur2.toUInt32).toNat (0 : Int32)))
      let (r8, digits, meta_) ← dec_shift digits meta_ n2 fuel
      let bexp := (bexp - n2)
      dec_float_bits.loop2 digits meta_ powtab bexp fuel
    else pure bexp

def dec_float_bits (digits : Array UInt8) (meta_ : Array UInt32) (mantbits : UInt32) (expbits : UInt32) (bias : Int32) (fuel : Nat) : Option (UInt64 × Array UInt8 × Array UInt32) := do
  let powtab : Array Int32 := (#[(1 : Int32), (3 : Int32), (6 : Int32), (9 : Int32), (13 : Int32), (16 : Int32), (19 : Int32), (23 : Int32), (26 : Int32)] : Array Int32)
  let expmax : Int32 := ((((1 : UInt32) <<< expbits) - (1 : UInt32)).toInt32)
  let bexp : Int32 := bias
  let mant : UInt64 := (0 : UInt64)
  let overflow : Bool := false
  let (r1, meta_) ← dec_dp meta_ fuel
  let dp : Int32 := r1
  let (bexp, mant, overflow) ← (if ((meta_.getD 0 (0 : UInt32)) == (0 : UInt32)) then (do
      let mant := (0 : UInt64)
      pure (bexp, mant, overflow))
    else (do
      let (bexp, mant, overflow) ← (if (decide (dp > (310 : Int32))) then (do
          let overflow := true
          pure (bexp, mant, overflow))
        else (do
          let (bexp, mant, overflow) ← (if (decide (dp < (0 - (330 : Int32)))) then (do
              let mant := (0 : UInt64)
              pure (bexp, mant, overflow))
            else (do
              let bexp := (0 : Int32)
              let bexp ← dec_float_bits.loop1 digits meta_ powtab bexp fuel
              let bexp ← dec_float_bits.loop2 digits meta_ powtab bexp fuel
              let bexp := (bexp - (1 : Int32))
              let bexp ← (if (decide (bexp < (bias + (1 : Int32)))) then (do
                  let lift : Int32 := ((bias + (1 : Int32)) - bexp)
                  let (r9, digits, meta_) ← dec_shift digits meta_ ((0 : Int32) - lift) fuel
                  let bexp := (bexp + lift)
                  pure bexp)
                else (do
                  pure bexp))
              let (bexp, mant, overflow) ← (if (decide ((bexp - bias) >= expmax)) then (do
                  let overflow := true
                  pure (bexp, mant, overflow))
                else (do
                  let (r10, digits, meta_) ← dec_shift digits meta_ ((1 : Int32) + (mantbits.toInt32)) fuel
                  let (r11, digits, meta_) ← dec_rounded_integer digits meta_ fuel
                  let mant := r11
                  let (bexp, mant, overflow) ← (if (mant == ((2 : UInt64) <<< (mantbits.toUInt64))) then (do
                      let mant := (mant >>> (1 : UInt64))
                      let bexp := (bexp + (1 : Int32))
                      let overflow ← (if (decide ((bexp - bias) >= expmax)) then (do
                          let overflow := true
                          pure overflow)
                        else (do
                          pure overflow))
                      pure (bexp, mant, overflow))
                    else (do
                      pure (bexp, mant, overflow)))
                  let bexp ← (if ((!overflow) && ((mant &&& ((1 : UInt64) <<< (mantbits.toUInt64))) == (0 : UInt64))) then (do
                      let bexp := bias
                      pure bexp)
                    else (do
                      pure bexp))
                  pure (bexp, mant, overflow)))
              pure (bexp, mant, overflow)))
          pure (bexp, mant, overflow)))
      pure (bexp, mant, overflow)))
  let (meta_, bexp, mant) ← (if overflow then (do
      let mant := (0 : UInt64)
      let bexp := (expmax + bias)
      let meta_ := meta_.setIfInBounds 4 (1 : UInt32)
      pure (meta_, bexp, mant))
    else (do
      pure (meta_, bexp, mant)))
  let bits : UInt64 := (mant &&& (((1 : UInt64) <<< (mantbits.toUInt64)) - (1 : UInt64)))
  let bits := (bits ||| (((((bexp - bias).toUInt32) &&& (expmax.toUInt32)).toUInt64) <<< (mantbits.toUInt64)))
  let bits ← (if ((meta_.getD 2 (0 : UInt32)) != (0 : UInt32)) then (do
      let bits := (bits ||| ((1 : UInt64) <<< ((mantbits + expbits).toUInt64)))
      pure bits)
    else (do
      pure bits))
  pure (bits, digits, meta_)

def float_parse_bits (src : Array UInt8) (mantbits : UInt32) (expbits : UInt32) (bias : Int32) (saturate : Bool) (fuel : Nat) : Option (Result_u64_FloatError) := do
  let r1 ← float_special src fuel
  let special : UInt32 := r1
  let infbits : UInt64 := (((((1 : UInt32) <<< expbits) - (1 : UInt32)).toUInt64) <<< (mantbits.toUInt64))
  let r2 ← (
    if (special == (1 : UInt32)) then (do
      pure (Result_u64_FloatError.Ok infbits))
    else (do
      let r3 ← (
        if (special == (2 : UInt32)) then (do
          pure (Result_u64_FloatError.Ok (infbits ||| ((1 : UInt64) <<< ((mantbits + expbits).toUInt64)))))
        else (do
          let r4 ← (
            if (special == (3 : UInt32)) then (do
              pure (Result_u64_FloatError.Ok (infbits ||| ((1 : UInt64) <<< ((mantbits - (1 : UInt32)).toUInt64)))))
            else (do
              let digits : Array UInt8 := Array.replicate 800 (0 : UInt8)
              let meta_ : Array UInt32 := Array.replicate 5 (0 : UInt32)
              let d : Array UInt8 := digits
              let m : Array UInt32 := meta_
              let (r5, m) ← dec_init m fuel
              let (r6, d, m) ← dec_set d m src fuel
              let r7 ← (
                if r6 then (do
                  let (r8, d, m) ← dec_float_bits d m mantbits expbits bias fuel
                  let bits : UInt64 := r8
                  pure (if (((m.getD 4 (0 : UInt32)) != (0 : UInt32)) && (!saturate)) then (Result_u64_FloatError.Err FloatError.OutOfRange) else (Result_u64_FloatError.Ok bits)))
                else (do
                  pure (Result_u64_FloatError.Err FloatError.InvalidSyntax)))
              pure r7))
          pure r4))
      pure r3))
  pure r2

def float_parse (src : Array UInt8) (fuel : Nat) : Option (Result_f64_FloatError) := do
  let r1 ← float_parse_bits src (52 : UInt32) (11 : UInt32) (0 - (1023 : Int32)) false fuel
  pure (match r1 with | (.Ok bits) => (Result_f64_FloatError.Ok (Float.ofBits bits)) | (.Err reason) => (Result_f64_FloatError.Err reason))

def float_parse_saturating (src : Array UInt8) (fuel : Nat) : Option (Result_f64_FloatError) := do
  let r1 ← float_parse_bits src (52 : UInt32) (11 : UInt32) (0 - (1023 : Int32)) true fuel
  pure (match r1 with | (.Ok bits) => (Result_f64_FloatError.Ok (Float.ofBits bits)) | (.Err reason) => (Result_f64_FloatError.Err reason))

def float_parse_f32 (src : Array UInt8) (fuel : Nat) : Option (Result_f32_FloatError) := do
  let r1 ← float_parse_bits src (23 : UInt32) (8 : UInt32) (0 - (127 : Int32)) false fuel
  pure (match r1 with | (.Ok bits) => (Result_f32_FloatError.Ok (Float32.ofBits (bits.toUInt32))) | (.Err reason) => (Result_f32_FloatError.Err reason))

def float_parse_saturating_f32 (src : Array UInt8) (fuel : Nat) : Option (Result_f32_FloatError) := do
  let r1 ← float_parse_bits src (23 : UInt32) (8 : UInt32) (0 - (127 : Int32)) true fuel
  pure (match r1 with | (.Ok bits) => (Result_f32_FloatError.Ok (Float32.ofBits (bits.toUInt32))) | (.Err reason) => (Result_f32_FloatError.Err reason))

end Oak.Stdlib.Float
