-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Hash

structure Sha256State where
  h : Array UInt32
  block : Array UInt8
  filled : UInt32
  total : UInt64
  deriving Repr, Inhabited, BEq, DecidableEq

structure Blake3State where
  cv : Array UInt32
  block : Array UInt8
  block_len : UInt32
  blocks_compressed : UInt32
  chunk_counter : UInt64
  stack : Array UInt32
  stack_len : UInt32
  deriving Repr, Inhabited, BEq, DecidableEq

def SHA256_K : Array UInt32 := (#[(1116352408 : UInt32), (1899447441 : UInt32), (3049323471 : UInt32), (3921009573 : UInt32), (961987163 : UInt32), (1508970993 : UInt32), (2453635748 : UInt32), (2870763221 : UInt32), (3624381080 : UInt32), (310598401 : UInt32), (607225278 : UInt32), (1426881987 : UInt32), (1925078388 : UInt32), (2162078206 : UInt32), (2614888103 : UInt32), (3248222580 : UInt32), (3835390401 : UInt32), (4022224774 : UInt32), (264347078 : UInt32), (604807628 : UInt32), (770255983 : UInt32), (1249150122 : UInt32), (1555081692 : UInt32), (1996064986 : UInt32), (2554220882 : UInt32), (2821834349 : UInt32), (2952996808 : UInt32), (3210313671 : UInt32), (3336571891 : UInt32), (3584528711 : UInt32), (113926993 : UInt32), (338241895 : UInt32), (666307205 : UInt32), (773529912 : UInt32), (1294757372 : UInt32), (1396182291 : UInt32), (1695183700 : UInt32), (1986661051 : UInt32), (2177026350 : UInt32), (2456956037 : UInt32), (2730485921 : UInt32), (2820302411 : UInt32), (3259730800 : UInt32), (3345764771 : UInt32), (3516065817 : UInt32), (3600352804 : UInt32), (4094571909 : UInt32), (275423344 : UInt32), (430227734 : UInt32), (506948616 : UInt32), (659060556 : UInt32), (883997877 : UInt32), (958139571 : UInt32), (1322822218 : UInt32), (1537002063 : UInt32), (1747873779 : UInt32), (1955562222 : UInt32), (2024104815 : UInt32), (2227730452 : UInt32), (2361852424 : UInt32), (2428436474 : UInt32), (2756734187 : UInt32), (3204031479 : UInt32), (3329325298 : UInt32)] : Array UInt32)

def BLAKE3_IV : Array UInt32 := (#[(1779033703 : UInt32), (3144134277 : UInt32), (1013904242 : UInt32), (2773480762 : UInt32), (1359893119 : UInt32), (2600822924 : UInt32), (528734635 : UInt32), (1541459225 : UInt32)] : Array UInt32)

def BLAKE3_CHUNK_START : UInt32 := (1 : UInt32)

def BLAKE3_CHUNK_END : UInt32 := (2 : UInt32)

def BLAKE3_PARENT : UInt32 := (4 : UInt32)

def BLAKE3_ROOT : UInt32 := (8 : UInt32)

def rotr32 (x : UInt32) (n : UInt32) (fuel : Nat) : Option (UInt32) := do
  pure ((x >>> n) ||| (x <<< ((32 : UInt32) - n)))

def sha256_compress.loop1 (block : Array UInt8) (w : Array UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (16 : UInt32))) then do
      let at_ : UInt32 := (i * (4 : UInt32))
      let w := w.setIfInBounds i.toNat ((((((block.getD at_.toNat (0 : UInt8)).toUInt32) <<< (24 : UInt32)) ||| (((block.getD (at_ + (1 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (16 : UInt32))) ||| (((block.getD (at_ + (2 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (8 : UInt32))) ||| ((block.getD (at_ + (3 : UInt32)).toNat (0 : UInt8)).toUInt32))
      let i := (i + (1 : UInt32))
      sha256_compress.loop1 block w i fuel
    else pure (w, i)

def sha256_compress.loop2 (w : Array UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (64 : UInt32))) then do
      let w15 : UInt32 := (w.getD (i - (15 : UInt32)).toNat (0 : UInt32))
      let w2 : UInt32 := (w.getD (i - (2 : UInt32)).toNat (0 : UInt32))
      let r1 ← rotr32 w15 (7 : UInt32) fuel
      let r2 ← rotr32 w15 (18 : UInt32) fuel
      let s0 : UInt32 := ((r1 ^^^ r2) ^^^ (w15 >>> (3 : UInt32)))
      let r3 ← rotr32 w2 (17 : UInt32) fuel
      let r4 ← rotr32 w2 (19 : UInt32) fuel
      let s1 : UInt32 := ((r3 ^^^ r4) ^^^ (w2 >>> (10 : UInt32)))
      let w := w.setIfInBounds i.toNat ((((w.getD (i - (16 : UInt32)).toNat (0 : UInt32)) + s0) + (w.getD (i - (7 : UInt32)).toNat (0 : UInt32))) + s1)
      let i := (i + (1 : UInt32))
      sha256_compress.loop2 w i fuel
    else pure (w, i)

def sha256_compress.loop3 (w : Array UInt32) (i : UInt32) (a : UInt32) (b : UInt32) (c : UInt32) (d : UInt32) (e : UInt32) (f : UInt32) (g : UInt32) (hh : UInt32) : Nat → Option (UInt32 × UInt32 × UInt32 × UInt32 × UInt32 × UInt32 × UInt32 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (64 : UInt32))) then do
      let r5 ← rotr32 e (6 : UInt32) fuel
      let r6 ← rotr32 e (11 : UInt32) fuel
      let r7 ← rotr32 e (25 : UInt32) fuel
      let big1 : UInt32 := ((r5 ^^^ r6) ^^^ r7)
      let choose : UInt32 := ((e &&& f) ^^^ ((~~~e) &&& g))
      let temp1 : UInt32 := ((((hh + big1) + choose) + (SHA256_K.getD i.toNat (0 : UInt32))) + (w.getD i.toNat (0 : UInt32)))
      let r8 ← rotr32 a (2 : UInt32) fuel
      let r9 ← rotr32 a (13 : UInt32) fuel
      let r10 ← rotr32 a (22 : UInt32) fuel
      let big0 : UInt32 := ((r8 ^^^ r9) ^^^ r10)
      let majority : UInt32 := (((a &&& b) ^^^ (a &&& c)) ^^^ (b &&& c))
      let temp2 : UInt32 := (big0 + majority)
      let hh := g
      let g := f
      let f := e
      let e := (d + temp1)
      let d := c
      let c := b
      let b := a
      let a := (temp1 + temp2)
      let i := (i + (1 : UInt32))
      sha256_compress.loop3 w i a b c d e f g hh fuel
    else pure (i, a, b, c, d, e, f, g, hh)

def sha256_compress (h : Array UInt32) (block : Array UInt8) (fuel : Nat) : Option (Array UInt32) := do
  let w : Array UInt32 := Array.replicate 64 (0 : UInt32)
  let i : UInt32 := (0 : UInt32)
  let (w, i) ← sha256_compress.loop1 block w i fuel
  let (w, i) ← sha256_compress.loop2 w i fuel
  let a : UInt32 := (h.getD 0 (0 : UInt32))
  let b : UInt32 := (h.getD 1 (0 : UInt32))
  let c : UInt32 := (h.getD 2 (0 : UInt32))
  let d : UInt32 := (h.getD 3 (0 : UInt32))
  let e : UInt32 := (h.getD 4 (0 : UInt32))
  let f : UInt32 := (h.getD 5 (0 : UInt32))
  let g : UInt32 := (h.getD 6 (0 : UInt32))
  let hh : UInt32 := (h.getD 7 (0 : UInt32))
  let i := (0 : UInt32)
  let (i, a, b, c, d, e, f, g, hh) ← sha256_compress.loop3 w i a b c d e f g hh fuel
  pure (#[((h.getD 0 (0 : UInt32)) + a), ((h.getD 1 (0 : UInt32)) + b), ((h.getD 2 (0 : UInt32)) + c), ((h.getD 3 (0 : UInt32)) + d), ((h.getD 4 (0 : UInt32)) + e), ((h.getD 5 (0 : UInt32)) + f), ((h.getD 6 (0 : UInt32)) + g), ((h.getD 7 (0 : UInt32)) + hh)] : Array UInt32)

def sha256_init  (fuel : Nat) : Option (Sha256State) := do
  let state : Sha256State := (default : Sha256State)
  let state := { state with h := (#[(1779033703 : UInt32), (3144134277 : UInt32), (1013904242 : UInt32), (2773480762 : UInt32), (1359893119 : UInt32), (2600822924 : UInt32), (528734635 : UInt32), (1541459225 : UInt32)] : Array UInt32) }
  let state := { state with filled := (0 : UInt32) }
  let state := { state with total := (0 : UInt64) }
  pure state

def sha256_update.loop1 (src : Array UInt8) (next : Sha256State) (i : UInt32) : Nat → Option (Sha256State × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (src.size.toUInt32))) then do
      let next := { next with block := next.block.setIfInBounds next.filled.toNat (src.getD i.toNat (0 : UInt8)) }
      let next := { next with filled := (next.filled + (1 : UInt32)) }
      let next ← (if (next.filled == (64 : UInt32)) then (do
          let r1 ← sha256_compress next.h next.block fuel
          let next := { next with h := r1 }
          let next := { next with filled := (0 : UInt32) }
          pure next)
        else (do
          pure next))
      let i := (i + (1 : UInt32))
      sha256_update.loop1 src next i fuel
    else pure (next, i)

def sha256_update (state : Sha256State) (src : Array UInt8) (fuel : Nat) : Option (Sha256State) := do
  let next : Sha256State := state
  let i : UInt32 := (0 : UInt32)
  let (next, i) ← sha256_update.loop1 src next i fuel
  let next := { next with total := (next.total + ((src.size.toUInt32).toUInt64)) }
  pure next

def sha256_final.loop1 (tail : Sha256State) : Nat → Option (Sha256State)
  | 0 => none
  | fuel + 1 => do
    if (decide (tail.filled < (64 : UInt32))) then do
      let tail := { tail with block := tail.block.setIfInBounds tail.filled.toNat (0 : UInt8) }
      let tail := { tail with filled := (tail.filled + (1 : UInt32)) }
      sha256_final.loop1 tail fuel
    else pure tail

def sha256_final.loop2 (tail : Sha256State) : Nat → Option (Sha256State)
  | 0 => none
  | fuel + 1 => do
    if (decide (tail.filled < (56 : UInt32))) then do
      let tail := { tail with block := tail.block.setIfInBounds tail.filled.toNat (0 : UInt8) }
      let tail := { tail with filled := (tail.filled + (1 : UInt32)) }
      sha256_final.loop2 tail fuel
    else pure tail

def sha256_final.loop3 (tail : Sha256State) (bits : UInt64) (k : UInt32) : Nat → Option (Sha256State × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (k < (8 : UInt32))) then do
      let tail := { tail with block := tail.block.setIfInBounds ((56 : UInt32) + k).toNat ((bits >>> ((56 : UInt64) - ((8 : UInt64) * (k.toUInt64)))).toUInt8) }
      let k := (k + (1 : UInt32))
      sha256_final.loop3 tail bits k fuel
    else pure (tail, k)

def sha256_final.loop4 (out : Array UInt8) (tail : Sha256State) (j : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (j < (8 : UInt32))) then do
      let word : UInt32 := (tail.h.getD j.toNat (0 : UInt32))
      let at_ : UInt32 := (j * (4 : UInt32))
      let out := out.setIfInBounds at_.toNat ((word >>> (24 : UInt32)).toUInt8)
      let out := out.setIfInBounds (at_ + (1 : UInt32)).toNat ((word >>> (16 : UInt32)).toUInt8)
      let out := out.setIfInBounds (at_ + (2 : UInt32)).toNat ((word >>> (8 : UInt32)).toUInt8)
      let out := out.setIfInBounds (at_ + (3 : UInt32)).toNat (word.toUInt8)
      let j := (j + (1 : UInt32))
      sha256_final.loop4 out tail j fuel
    else pure (out, j)

def sha256_final (state : Sha256State) (out : Array UInt8) (fuel : Nat) : Option (Bool × Array UInt8) := do
  let (r1, out) ← (
    if (decide ((out.size.toUInt32) < (32 : UInt32))) then (do
      pure (false, out))
    else (do
      let tail : Sha256State := state
      let bits : UInt64 := (tail.total * (8 : UInt64))
      let tail := { tail with block := tail.block.setIfInBounds tail.filled.toNat (128 : UInt8) }
      let tail := { tail with filled := (tail.filled + (1 : UInt32)) }
      let tail ← (if (decide (tail.filled > (56 : UInt32))) then (do
          let tail ← sha256_final.loop1 tail fuel
          let r2 ← sha256_compress tail.h tail.block fuel
          let tail := { tail with h := r2 }
          let tail := { tail with filled := (0 : UInt32) }
          pure tail)
        else (do
          pure tail))
      let tail ← sha256_final.loop2 tail fuel
      let k : UInt32 := (0 : UInt32)
      let (tail, k) ← sha256_final.loop3 tail bits k fuel
      let r3 ← sha256_compress tail.h tail.block fuel
      let tail := { tail with h := r3 }
      let j : UInt32 := (0 : UInt32)
      let (out, j) ← sha256_final.loop4 out tail j fuel
      pure (true, out)))
  pure (r1, out)

def sha256 (src : Array UInt8) (out : Array UInt8) (fuel : Nat) : Option (Bool × Array UInt8) := do
  let r1 ← sha256_init  fuel
  let r2 ← sha256_update r1 src fuel
  let (r3, out) ← sha256_final r2 out fuel
  pure (r3, out)

def crc32c_update.loop2 (state : UInt32) (bit : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (bit < (8 : UInt32))) then do
      let mask : UInt32 := ((0 : UInt32) - (state &&& (1 : UInt32)))
      let state := ((state >>> (1 : UInt32)) ^^^ ((2197175160 : UInt32) &&& mask))
      let bit := (bit + (1 : UInt32))
      crc32c_update.loop2 state bit fuel
    else pure (state, bit)

def crc32c_update.loop1 (src : Array UInt8) (state : UInt32) (i : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (src.size.toUInt32))) then do
      let state := (state ^^^ ((src.getD i.toNat (0 : UInt8)).toUInt32))
      let bit : UInt32 := (0 : UInt32)
      let (state, bit) ← crc32c_update.loop2 state bit fuel
      let i := (i + (1 : UInt32))
      crc32c_update.loop1 src state i fuel
    else pure (state, i)

def crc32c_update (crc : UInt32) (src : Array UInt8) (fuel : Nat) : Option (UInt32) := do
  let state : UInt32 := (crc ^^^ (4294967295 : UInt32))
  let i : UInt32 := (0 : UInt32)
  let (state, i) ← crc32c_update.loop1 src state i fuel
  pure (state ^^^ (4294967295 : UInt32))

def crc32c (src : Array UInt8) (fuel : Nat) : Option (UInt32) := do
  let r1 ← crc32c_update (0 : UInt32) src fuel
  pure r1

def blake3_g (v : Array UInt32) (a : UInt32) (b : UInt32) (c : UInt32) (d : UInt32) (mx : UInt32) (my : UInt32) (fuel : Nat) : Option (Array UInt32) := do
  let state : Array UInt32 := v
  let state := state.setIfInBounds a.toNat (((state.getD a.toNat (0 : UInt32)) + (state.getD b.toNat (0 : UInt32))) + mx)
  let r1 ← rotr32 ((state.getD d.toNat (0 : UInt32)) ^^^ (state.getD a.toNat (0 : UInt32))) (16 : UInt32) fuel
  let state := state.setIfInBounds d.toNat r1
  let state := state.setIfInBounds c.toNat ((state.getD c.toNat (0 : UInt32)) + (state.getD d.toNat (0 : UInt32)))
  let r2 ← rotr32 ((state.getD b.toNat (0 : UInt32)) ^^^ (state.getD c.toNat (0 : UInt32))) (12 : UInt32) fuel
  let state := state.setIfInBounds b.toNat r2
  let state := state.setIfInBounds a.toNat (((state.getD a.toNat (0 : UInt32)) + (state.getD b.toNat (0 : UInt32))) + my)
  let r3 ← rotr32 ((state.getD d.toNat (0 : UInt32)) ^^^ (state.getD a.toNat (0 : UInt32))) (8 : UInt32) fuel
  let state := state.setIfInBounds d.toNat r3
  let state := state.setIfInBounds c.toNat ((state.getD c.toNat (0 : UInt32)) + (state.getD d.toNat (0 : UInt32)))
  let r4 ← rotr32 ((state.getD b.toNat (0 : UInt32)) ^^^ (state.getD c.toNat (0 : UInt32))) (7 : UInt32) fuel
  let state := state.setIfInBounds b.toNat r4
  pure state

def blake3_permute (m : Array UInt32) (fuel : Nat) : Option (Array UInt32) := do
  pure (#[(m.getD 2 (0 : UInt32)), (m.getD 6 (0 : UInt32)), (m.getD 3 (0 : UInt32)), (m.getD 10 (0 : UInt32)), (m.getD 7 (0 : UInt32)), (m.getD 0 (0 : UInt32)), (m.getD 4 (0 : UInt32)), (m.getD 13 (0 : UInt32)), (m.getD 1 (0 : UInt32)), (m.getD 11 (0 : UInt32)), (m.getD 12 (0 : UInt32)), (m.getD 5 (0 : UInt32)), (m.getD 9 (0 : UInt32)), (m.getD 14 (0 : UInt32)), (m.getD 15 (0 : UInt32)), (m.getD 8 (0 : UInt32))] : Array UInt32)

def blake3_compress.loop1 (v : Array UInt32) (m : Array UInt32) (round : UInt32) : Nat → Option (Array UInt32 × Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (round < (7 : UInt32))) then do
      let r1 ← blake3_g v (0 : UInt32) (4 : UInt32) (8 : UInt32) (12 : UInt32) (m.getD 0 (0 : UInt32)) (m.getD 1 (0 : UInt32)) fuel
      let v := r1
      let r2 ← blake3_g v (1 : UInt32) (5 : UInt32) (9 : UInt32) (13 : UInt32) (m.getD 2 (0 : UInt32)) (m.getD 3 (0 : UInt32)) fuel
      let v := r2
      let r3 ← blake3_g v (2 : UInt32) (6 : UInt32) (10 : UInt32) (14 : UInt32) (m.getD 4 (0 : UInt32)) (m.getD 5 (0 : UInt32)) fuel
      let v := r3
      let r4 ← blake3_g v (3 : UInt32) (7 : UInt32) (11 : UInt32) (15 : UInt32) (m.getD 6 (0 : UInt32)) (m.getD 7 (0 : UInt32)) fuel
      let v := r4
      let r5 ← blake3_g v (0 : UInt32) (5 : UInt32) (10 : UInt32) (15 : UInt32) (m.getD 8 (0 : UInt32)) (m.getD 9 (0 : UInt32)) fuel
      let v := r5
      let r6 ← blake3_g v (1 : UInt32) (6 : UInt32) (11 : UInt32) (12 : UInt32) (m.getD 10 (0 : UInt32)) (m.getD 11 (0 : UInt32)) fuel
      let v := r6
      let r7 ← blake3_g v (2 : UInt32) (7 : UInt32) (8 : UInt32) (13 : UInt32) (m.getD 12 (0 : UInt32)) (m.getD 13 (0 : UInt32)) fuel
      let v := r7
      let r8 ← blake3_g v (3 : UInt32) (4 : UInt32) (9 : UInt32) (14 : UInt32) (m.getD 14 (0 : UInt32)) (m.getD 15 (0 : UInt32)) fuel
      let v := r8
      let m ← (if (decide (round < (6 : UInt32))) then (do
          let r9 ← blake3_permute m fuel
          let m := r9
          pure m)
        else (do
          pure m))
      let round := (round + (1 : UInt32))
      blake3_compress.loop1 v m round fuel
    else pure (v, m, round)

def blake3_compress.loop2 (cv : Array UInt32) (v : Array UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (8 : UInt32))) then do
      let v := v.setIfInBounds i.toNat ((v.getD i.toNat (0 : UInt32)) ^^^ (v.getD (i + (8 : UInt32)).toNat (0 : UInt32)))
      let v := v.setIfInBounds (i + (8 : UInt32)).toNat ((v.getD (i + (8 : UInt32)).toNat (0 : UInt32)) ^^^ (cv.getD i.toNat (0 : UInt32)))
      let i := (i + (1 : UInt32))
      blake3_compress.loop2 cv v i fuel
    else pure (v, i)

def blake3_compress (cv : Array UInt32) (block : Array UInt32) (counter : UInt64) (block_len : UInt32) (flags : UInt32) (fuel : Nat) : Option (Array UInt32) := do
  let v : Array UInt32 := (#[(cv.getD 0 (0 : UInt32)), (cv.getD 1 (0 : UInt32)), (cv.getD 2 (0 : UInt32)), (cv.getD 3 (0 : UInt32)), (cv.getD 4 (0 : UInt32)), (cv.getD 5 (0 : UInt32)), (cv.getD 6 (0 : UInt32)), (cv.getD 7 (0 : UInt32)), (BLAKE3_IV.getD 0 (0 : UInt32)), (BLAKE3_IV.getD 1 (0 : UInt32)), (BLAKE3_IV.getD 2 (0 : UInt32)), (BLAKE3_IV.getD 3 (0 : UInt32)), (counter.toUInt32), ((counter >>> (32 : UInt64)).toUInt32), block_len, flags] : Array UInt32)
  let m : Array UInt32 := block
  let round : UInt32 := (0 : UInt32)
  let (v, m, round) ← blake3_compress.loop1 v m round fuel
  let i : UInt32 := (0 : UInt32)
  let (v, i) ← blake3_compress.loop2 cv v i fuel
  pure v

def blake3_words.loop1 (block : Array UInt8) (m : Array UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (16 : UInt32))) then do
      let at_ : UInt32 := (i * (4 : UInt32))
      let m := m.setIfInBounds i.toNat (((((block.getD at_.toNat (0 : UInt8)).toUInt32) ||| (((block.getD (at_ + (1 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (8 : UInt32))) ||| (((block.getD (at_ + (2 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (16 : UInt32))) ||| (((block.getD (at_ + (3 : UInt32)).toNat (0 : UInt8)).toUInt32) <<< (24 : UInt32)))
      let i := (i + (1 : UInt32))
      blake3_words.loop1 block m i fuel
    else pure (m, i)

def blake3_words (block : Array UInt8) (fuel : Nat) : Option (Array UInt32) := do
  let m : Array UInt32 := Array.replicate 16 (0 : UInt32)
  let i : UInt32 := (0 : UInt32)
  let (m, i) ← blake3_words.loop1 block m i fuel
  pure m

def blake3_first8 (v : Array UInt32) (fuel : Nat) : Option (Array UInt32) := do
  pure (#[(v.getD 0 (0 : UInt32)), (v.getD 1 (0 : UInt32)), (v.getD 2 (0 : UInt32)), (v.getD 3 (0 : UInt32)), (v.getD 4 (0 : UInt32)), (v.getD 5 (0 : UInt32)), (v.getD 6 (0 : UInt32)), (v.getD 7 (0 : UInt32))] : Array UInt32)

def blake3_init  (fuel : Nat) : Option (Blake3State) := do
  let state : Blake3State := (default : Blake3State)
  let state := { state with cv := BLAKE3_IV }
  let state := { state with block_len := (0 : UInt32) }
  let state := { state with blocks_compressed := (0 : UInt32) }
  let state := { state with chunk_counter := (0 : UInt64) }
  let state := { state with stack_len := (0 : UInt32) }
  pure state

def blake3_start_flag (state : Blake3State) (fuel : Nat) : Option (UInt32) := do
  pure (if (state.blocks_compressed == (0 : UInt32)) then BLAKE3_CHUNK_START else (0 : UInt32))

def blake3_absorb_block (state : Blake3State) (fuel : Nat) : Option (Blake3State) := do
  let next : Blake3State := state
  let r1 ← blake3_words next.block fuel
  let r2 ← blake3_start_flag next fuel
  let r3 ← blake3_compress next.cv r1 next.chunk_counter (64 : UInt32) r2 fuel
  let out : Array UInt32 := r3
  let r4 ← blake3_first8 out fuel
  let next := { next with cv := r4 }
  let next := { next with blocks_compressed := (next.blocks_compressed + (1 : UInt32)) }
  let next := { next with block_len := (0 : UInt32) }
  pure next

def blake3_chunk_cv.loop1 (block : Array UInt8) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (64 : UInt32))) then do
      let block := block.setIfInBounds i.toNat (0 : UInt8)
      let i := (i + (1 : UInt32))
      blake3_chunk_cv.loop1 block i fuel
    else pure (block, i)

def blake3_chunk_cv (state : Blake3State) (fuel : Nat) : Option (Array UInt32) := do
  let block : Array UInt8 := state.block
  let i : UInt32 := state.block_len
  let (block, i) ← blake3_chunk_cv.loop1 block i fuel
  let r1 ← blake3_words block fuel
  let r2 ← blake3_start_flag state fuel
  let r3 ← blake3_compress state.cv r1 state.chunk_counter state.block_len (r2 ||| BLAKE3_CHUNK_END) fuel
  let out : Array UInt32 := r3
  let r4 ← blake3_first8 out fuel
  pure r4

def blake3_parent_words (left : Array UInt32) (right : Array UInt32) (fuel : Nat) : Option (Array UInt32) := do
  pure (#[(left.getD 0 (0 : UInt32)), (left.getD 1 (0 : UInt32)), (left.getD 2 (0 : UInt32)), (left.getD 3 (0 : UInt32)), (left.getD 4 (0 : UInt32)), (left.getD 5 (0 : UInt32)), (left.getD 6 (0 : UInt32)), (left.getD 7 (0 : UInt32)), (right.getD 0 (0 : UInt32)), (right.getD 1 (0 : UInt32)), (right.getD 2 (0 : UInt32)), (right.getD 3 (0 : UInt32)), (right.getD 4 (0 : UInt32)), (right.getD 5 (0 : UInt32)), (right.getD 6 (0 : UInt32)), (right.getD 7 (0 : UInt32))] : Array UInt32)

def blake3_push_chunk.loop1 (next : Blake3State) (merged : Array UInt32) (total : UInt64) : Nat → Option (Blake3State × Array UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (((total % (2 : UInt64)) == (0 : UInt64)) && (decide (next.stack_len > (0 : UInt32)))) then do
      let top : UInt32 := ((next.stack_len - (1 : UInt32)) * (8 : UInt32))
      let left : Array UInt32 := (#[(next.stack.getD top.toNat (0 : UInt32)), (next.stack.getD (top + (1 : UInt32)).toNat (0 : UInt32)), (next.stack.getD (top + (2 : UInt32)).toNat (0 : UInt32)), (next.stack.getD (top + (3 : UInt32)).toNat (0 : UInt32)), (next.stack.getD (top + (4 : UInt32)).toNat (0 : UInt32)), (next.stack.getD (top + (5 : UInt32)).toNat (0 : UInt32)), (next.stack.getD (top + (6 : UInt32)).toNat (0 : UInt32)), (next.stack.getD (top + (7 : UInt32)).toNat (0 : UInt32))] : Array UInt32)
      let r1 ← blake3_parent_words left merged fuel
      let r2 ← blake3_compress BLAKE3_IV r1 (0 : UInt64) (64 : UInt32) BLAKE3_PARENT fuel
      let parent : Array UInt32 := r2
      let r3 ← blake3_first8 parent fuel
      let merged := r3
      let next := { next with stack_len := (next.stack_len - (1 : UInt32)) }
      let total := (total / (2 : UInt64))
      blake3_push_chunk.loop1 next merged total fuel
    else pure (next, merged, total)

def blake3_push_chunk.loop2 (next : Blake3State) (merged : Array UInt32) (at_ : UInt32) (k : UInt32) : Nat → Option (Blake3State × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (k < (8 : UInt32))) then do
      let next := { next with stack := next.stack.setIfInBounds (at_ + k).toNat (merged.getD k.toNat (0 : UInt32)) }
      let k := (k + (1 : UInt32))
      blake3_push_chunk.loop2 next merged at_ k fuel
    else pure (next, k)

def blake3_push_chunk (state : Blake3State) (cv : Array UInt32) (fuel : Nat) : Option (Blake3State) := do
  let next : Blake3State := state
  let merged : Array UInt32 := cv
  let total : UInt64 := (next.chunk_counter + (1 : UInt64))
  let (next, merged, total) ← blake3_push_chunk.loop1 next merged total fuel
  let at_ : UInt32 := (next.stack_len * (8 : UInt32))
  let k : UInt32 := (0 : UInt32)
  let (next, k) ← blake3_push_chunk.loop2 next merged at_ k fuel
  let next := { next with stack_len := (next.stack_len + (1 : UInt32)) }
  let next := { next with chunk_counter := (next.chunk_counter + (1 : UInt64)) }
  let next := { next with cv := BLAKE3_IV }
  let next := { next with blocks_compressed := (0 : UInt32) }
  let next := { next with block_len := (0 : UInt32) }
  pure next

def blake3_update.loop1 (src : Array UInt8) (next : Blake3State) (i : UInt32) : Nat → Option (Blake3State × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (src.size.toUInt32))) then do
      let next ← (if ((next.block_len == (64 : UInt32)) && (next.blocks_compressed == (15 : UInt32))) then (do
          let r1 ← blake3_chunk_cv next fuel
          let r2 ← blake3_push_chunk next r1 fuel
          let next := r2
          pure next)
        else (do
          let next ← (if (next.block_len == (64 : UInt32)) then (do
              let r3 ← blake3_absorb_block next fuel
              let next := r3
              pure next)
            else (do
              pure next))
          pure next))
      let next := { next with block := next.block.setIfInBounds next.block_len.toNat (src.getD i.toNat (0 : UInt8)) }
      let next := { next with block_len := (next.block_len + (1 : UInt32)) }
      let i := (i + (1 : UInt32))
      blake3_update.loop1 src next i fuel
    else pure (next, i)

def blake3_update (state : Blake3State) (src : Array UInt8) (fuel : Nat) : Option (Blake3State) := do
  let next : Blake3State := state
  let i : UInt32 := (0 : UInt32)
  let (next, i) ← blake3_update.loop1 src next i fuel
  pure next

def blake3_final.loop1 (block : Array UInt8) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (64 : UInt32))) then do
      let block := block.setIfInBounds i.toNat (0 : UInt8)
      let i := (i + (1 : UInt32))
      blake3_final.loop1 block i fuel
    else pure (block, i)

def blake3_final.loop2 (state : Blake3State) (merged : Array UInt32) (level : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (level > (1 : UInt32))) then do
      let top : UInt32 := ((level - (1 : UInt32)) * (8 : UInt32))
      let left : Array UInt32 := (#[(state.stack.getD top.toNat (0 : UInt32)), (state.stack.getD (top + (1 : UInt32)).toNat (0 : UInt32)), (state.stack.getD (top + (2 : UInt32)).toNat (0 : UInt32)), (state.stack.getD (top + (3 : UInt32)).toNat (0 : UInt32)), (state.stack.getD (top + (4 : UInt32)).toNat (0 : UInt32)), (state.stack.getD (top + (5 : UInt32)).toNat (0 : UInt32)), (state.stack.getD (top + (6 : UInt32)).toNat (0 : UInt32)), (state.stack.getD (top + (7 : UInt32)).toNat (0 : UInt32))] : Array UInt32)
      let r8 ← blake3_parent_words left merged fuel
      let r9 ← blake3_compress BLAKE3_IV r8 (0 : UInt64) (64 : UInt32) BLAKE3_PARENT fuel
      let parent : Array UInt32 := r9
      let r10 ← blake3_first8 parent fuel
      let merged := r10
      let level := (level - (1 : UInt32))
      blake3_final.loop2 state merged level fuel
    else pure (merged, level)

def blake3_final.loop3 (out : Array UInt8) (root : Array UInt32) (j : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (j < (8 : UInt32))) then do
      let word : UInt32 := (root.getD j.toNat (0 : UInt32))
      let at_ : UInt32 := (j * (4 : UInt32))
      let out := out.setIfInBounds at_.toNat (word.toUInt8)
      let out := out.setIfInBounds (at_ + (1 : UInt32)).toNat ((word >>> (8 : UInt32)).toUInt8)
      let out := out.setIfInBounds (at_ + (2 : UInt32)).toNat ((word >>> (16 : UInt32)).toUInt8)
      let out := out.setIfInBounds (at_ + (3 : UInt32)).toNat ((word >>> (24 : UInt32)).toUInt8)
      let j := (j + (1 : UInt32))
      blake3_final.loop3 out root j fuel
    else pure (out, j)

def blake3_final (state : Blake3State) (out : Array UInt8) (fuel : Nat) : Option (Bool × Array UInt8) := do
  let (r1, out) ← (
    if (decide ((out.size.toUInt32) < (32 : UInt32))) then (do
      pure (false, out))
    else (do
      let block : Array UInt8 := state.block
      let i : UInt32 := state.block_len
      let (block, i) ← blake3_final.loop1 block i fuel
      let r2 ← blake3_words block fuel
      let words : Array UInt32 := r2
      let root : Array UInt32 := Array.replicate 16 (0 : UInt32)
      let root ← (if (state.stack_len == (0 : UInt32)) then (do
          let r3 ← blake3_start_flag state fuel
          let r4 ← blake3_compress state.cv words state.chunk_counter state.block_len ((r3 ||| BLAKE3_CHUNK_END) ||| BLAKE3_ROOT) fuel
          let root := r4
          pure root)
        else (do
          let r5 ← blake3_start_flag state fuel
          let r6 ← blake3_compress state.cv words state.chunk_counter state.block_len (r5 ||| BLAKE3_CHUNK_END) fuel
          let chunk : Array UInt32 := r6
          let r7 ← blake3_first8 chunk fuel
          let merged : Array UInt32 := r7
          let level : UInt32 := state.stack_len
          let (merged, level) ← blake3_final.loop2 state merged level fuel
          let bottom : Array UInt32 := (#[(state.stack.getD 0 (0 : UInt32)), (state.stack.getD 1 (0 : UInt32)), (state.stack.getD 2 (0 : UInt32)), (state.stack.getD 3 (0 : UInt32)), (state.stack.getD 4 (0 : UInt32)), (state.stack.getD 5 (0 : UInt32)), (state.stack.getD 6 (0 : UInt32)), (state.stack.getD 7 (0 : UInt32))] : Array UInt32)
          let r11 ← blake3_parent_words bottom merged fuel
          let r12 ← blake3_compress BLAKE3_IV r11 (0 : UInt64) (64 : UInt32) (BLAKE3_PARENT ||| BLAKE3_ROOT) fuel
          let root := r12
          pure root))
      let j : UInt32 := (0 : UInt32)
      let (out, j) ← blake3_final.loop3 out root j fuel
      pure (true, out)))
  pure (r1, out)

def blake3 (src : Array UInt8) (out : Array UInt8) (fuel : Nat) : Option (Bool × Array UInt8) := do
  let r1 ← blake3_init  fuel
  let r2 ← blake3_update r1 src fuel
  let (r3, out) ← blake3_final r2 out fuel
  pure (r3, out)

end Oak.Stdlib.Hash
