-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Random

structure Xoshiro where
  s0 : UInt64
  s1 : UInt64
  s2 : UInt64
  s3 : UInt64
  deriving Repr, BEq, DecidableEq
instance : Inhabited Xoshiro := ⟨{ s0 := (0 : UInt64), s1 := (0 : UInt64), s2 := (0 : UInt64), s3 := (0 : UInt64) }⟩

def splitmix64_next (state : UInt64) (fuel : Nat) : Option (UInt64) := do
  let z : UInt64 := (state + (11400714819323198485 : UInt64))
  let z := ((z ^^^ (z >>> (30 : UInt64))) * (13787848793156543929 : UInt64))
  let z := ((z ^^^ (z >>> (27 : UInt64))) * (10723151780598845931 : UInt64))
  pure (z ^^^ (z >>> (31 : UInt64)))

def random_seed (seed : UInt64) (fuel : Nat) : Option (Xoshiro) := do
  let a : UInt64 := (seed + (11400714819323198485 : UInt64))
  let r1 ← splitmix64_next seed fuel
  let s0 : UInt64 := r1
  let r2 ← splitmix64_next a fuel
  let s1 : UInt64 := r2
  let r3 ← splitmix64_next (a + (11400714819323198485 : UInt64)) fuel
  let s2 : UInt64 := r3
  let r4 ← splitmix64_next (a + ((11400714819323198485 : UInt64) * (2 : UInt64))) fuel
  let s3 : UInt64 := r4
  pure ({ s0 := s0, s1 := s1, s2 := s2, s3 := s3 } : Xoshiro)

def rotl64 (x : UInt64) (k : UInt32) (fuel : Nat) : Option (UInt64) := do
  pure ((x <<< (k.toUInt64)) ||| (x >>> (((64 : UInt32) - k).toUInt64)))

def random_next (state : Array Xoshiro) (fuel : Nat) : Option (UInt64 × Array Xoshiro) := do
  let () ← (if ((state.size.toUInt32) == (1 : UInt32)) then pure () else none)
  let r1 ← rotl64 ((state.getD 0 (default : Xoshiro)).s1 * (5 : UInt64)) (7 : UInt32) fuel
  let result : UInt64 := (r1 * (9 : UInt64))
  let t : UInt64 := ((state.getD 0 (default : Xoshiro)).s1 <<< (17 : UInt64))
  let s2 : UInt64 := ((state.getD 0 (default : Xoshiro)).s2 ^^^ (state.getD 0 (default : Xoshiro)).s0)
  let s3 : UInt64 := ((state.getD 0 (default : Xoshiro)).s3 ^^^ (state.getD 0 (default : Xoshiro)).s1)
  let s1 : UInt64 := ((state.getD 0 (default : Xoshiro)).s1 ^^^ s2)
  let s0 : UInt64 := ((state.getD 0 (default : Xoshiro)).s0 ^^^ s3)
  let s2 := (s2 ^^^ t)
  let r2 ← rotl64 s3 (45 : UInt32) fuel
  let s3 := r2
  let state := state.setIfInBounds 0 ({ s0 := s0, s1 := s1, s2 := s2, s3 := s3 } : Xoshiro)
  pure (result, state)

def random_below.loop1 (state : Array Xoshiro) (limit : UInt64) (draw : UInt64) : Nat → Option (Array Xoshiro × UInt64)
  | 0 => none
  | fuel + 1 => do
    if ((decide (draw >= limit)) && (limit != (0 : UInt64))) then do
      let (r3, state) ← random_next state fuel
      let draw := r3
      random_below.loop1 state limit draw fuel
    else pure (state, draw)

def random_below (state : Array Xoshiro) (bound : UInt64) (fuel : Nat) : Option (UInt64 × Array Xoshiro) := do
  let (r1, state) ← (
    if (decide (bound <= (1 : UInt64))) then (do
      pure ((0 : UInt64), state))
    else (do
      let limit : UInt64 := ((0 : UInt64) - (((0 : UInt64) - bound) % bound))
      let (r2, state) ← random_next state fuel
      let draw : UInt64 := r2
      let (state, draw) ← random_below.loop1 state limit draw fuel
      pure ((draw % bound), state)))
  pure (r1, state)

def random_range (state : Array Xoshiro) (low : UInt64) (high : UInt64) (fuel : Nat) : Option (UInt64 × Array Xoshiro) := do
  let () ← (if (decide (low <= high)) then pure () else none)
  let (r1, state) ← (
    if ((high - low) == (18446744073709551615 : UInt64)) then (do
      let (r2, state) ← random_next state fuel
      pure (r2, state))
    else (do
      let (r3, state) ← random_below state ((high - low) + (1 : UInt64)) fuel
      pure ((low + r3), state)))
  pure (r1, state)

def random_bool (state : Array Xoshiro) (fuel : Nat) : Option (Bool × Array Xoshiro) := do
  let (r1, state) ← random_next state fuel
  pure (((r1 >>> (63 : UInt64)) == (1 : UInt64)), state)

def random_fill.loop1 (state : Array Xoshiro) (dst : Array UInt8) (i : UInt32) (word : UInt64) : Nat → Option (Array Xoshiro × Array UInt8 × UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (dst.size.toUInt32))) then do
      let (state, word) ← (if ((i % (8 : UInt32)) == (0 : UInt32)) then (do
          let (r1, state) ← random_next state fuel
          let word := r1
          pure (state, word))
        else (do
          pure (state, word)))
      let dst := dst.setIfInBounds i.toNat ((word &&& (255 : UInt64)).toUInt8)
      let word := (word >>> (8 : UInt64))
      let i := (i + (1 : UInt32))
      random_fill.loop1 state dst i word fuel
    else pure (state, dst, i, word)

def random_fill (state : Array Xoshiro) (dst : Array UInt8) (fuel : Nat) : Option (Unit × Array Xoshiro × Array UInt8) := do
  let i : UInt32 := (0 : UInt32)
  let word : UInt64 := (0 : UInt64)
  let (state, dst, i, word) ← random_fill.loop1 state dst i word fuel
  pure ((), state, dst)

def random_shuffle_u32.loop1 (state : Array Xoshiro) (items : Array UInt32) (i : UInt32) : Nat → Option (Array Xoshiro × Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i > (1 : UInt32))) then do
      let (r1, state) ← random_below state (i.toUInt64) fuel
      let j : UInt32 := (r1.toUInt32)
      let i := (i - (1 : UInt32))
      let held : UInt32 := (items.getD i.toNat (0 : UInt32))
      let items := items.setIfInBounds i.toNat (items.getD j.toNat (0 : UInt32))
      let items := items.setIfInBounds j.toNat held
      random_shuffle_u32.loop1 state items i fuel
    else pure (state, items, i)

def random_shuffle_u32 (state : Array Xoshiro) (items : Array UInt32) (fuel : Nat) : Option (Unit × Array Xoshiro × Array UInt32) := do
  let i : UInt32 := (items.size.toUInt32)
  let (state, items, i) ← random_shuffle_u32.loop1 state items i fuel
  pure ((), state, items)

def drive_shuffle_u32 (state : Array Xoshiro) (items : Array UInt32) (fuel : Nat) : Option (Unit × Array Xoshiro × Array UInt32) := do
  let (r1, state, items) ← random_shuffle_u32 state items fuel
  pure ((), state, items)

end Oak.Stdlib.Random
