-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
namespace Oak.Stdlib.SortU32

inductive Option_u32 where
  | Some (payload : UInt32)
  | None
  deriving Repr, Inhabited, BEq, DecidableEq

def sort_is_sorted_u32.loop1 (items : Array UInt32) (ok : Bool) (i : UInt32) : Nat → Option (Bool × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (ok && (decide (i < (items.size.toUInt32)))) then do
      let ok := (!(decide ((items.getD i.toNat (0 : UInt32)) < (items.getD (i - (1 : UInt32)).toNat (0 : UInt32)))))
      let i := (i + (1 : UInt32))
      sort_is_sorted_u32.loop1 items ok i fuel
    else pure (ok, i)

def sort_is_sorted_u32 (items : Array UInt32) (fuel : Nat) : Option (Bool) := do
  let ok : Bool := true
  let i : UInt32 := (1 : UInt32)
  let (ok, i) ← sort_is_sorted_u32.loop1 items ok i fuel
  pure ok

def sort_u32_is_sorted (items : Array UInt32) (fuel : Nat) : Option (Bool) := do
  let r1 ← sort_is_sorted_u32 items fuel
  pure r1

def sort_insertion_u32.loop2 (items : Array UInt32) (j : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (j > (0 : UInt32))) && (decide ((items.getD j.toNat (0 : UInt32)) < (items.getD (j - (1 : UInt32)).toNat (0 : UInt32))))) then do
      let held : UInt32 := (items.getD j.toNat (0 : UInt32))
      let items := items.setIfInBounds j.toNat (items.getD (j - (1 : UInt32)).toNat (0 : UInt32))
      let items := items.setIfInBounds (j - (1 : UInt32)).toNat held
      let j := (j - (1 : UInt32))
      sort_insertion_u32.loop2 items j fuel
    else pure (items, j)

def sort_insertion_u32.loop1 (items : Array UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (items.size.toUInt32))) then do
      let j : UInt32 := i
      let (items, j) ← sort_insertion_u32.loop2 items j fuel
      let i := (i + (1 : UInt32))
      sort_insertion_u32.loop1 items i fuel
    else pure (items, i)

def sort_insertion_u32 (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let i : UInt32 := (1 : UInt32)
  let (items, i) ← sort_insertion_u32.loop1 items i fuel
  pure ((), items)

def sort_u32_insertion (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let (r1, items) ← sort_insertion_u32 items fuel
  pure ((), items)

def sort_sift_down_u32.loop1 (items : Array UInt32) (end_ : UInt32) (root : UInt32) (more : Bool) : Nat → Option (Array UInt32 × UInt32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if more then do
      let child : UInt32 := ((root * (2 : UInt32)) + (1 : UInt32))
      let (items, root, more) ← (if (decide (child >= end_)) then (do
          let more := false
          pure (items, root, more))
        else (do
          let right : UInt32 := (child + (1 : UInt32))
          let largest : UInt32 := (if ((decide (right < end_)) && (decide ((items.getD child.toNat (0 : UInt32)) < (items.getD right.toNat (0 : UInt32))))) then right else child)
          let (items, root, more) ← (if (decide ((items.getD root.toNat (0 : UInt32)) < (items.getD largest.toNat (0 : UInt32)))) then (do
              let held : UInt32 := (items.getD root.toNat (0 : UInt32))
              let items := items.setIfInBounds root.toNat (items.getD largest.toNat (0 : UInt32))
              let items := items.setIfInBounds largest.toNat held
              let root := largest
              pure (items, root, more))
            else (do
              let more := false
              pure (items, root, more)))
          pure (items, root, more)))
      sort_sift_down_u32.loop1 items end_ root more fuel
    else pure (items, root, more)

def sort_sift_down_u32 (items : Array UInt32) (start : UInt32) (end_ : UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let root : UInt32 := start
  let more : Bool := true
  let (items, root, more) ← sort_sift_down_u32.loop1 items end_ root more fuel
  pure ((), items)

def sort_heap_u32.loop1 (items : Array UInt32) (n : UInt32) (start : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (start > (0 : UInt32))) then do
      let start := (start - (1 : UInt32))
      let (r1, items) ← sort_sift_down_u32 items start n fuel
      sort_heap_u32.loop1 items n start fuel
    else pure start

def sort_heap_u32.loop2 (items : Array UInt32) (end_ : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (end_ > (1 : UInt32))) then do
      let end_ := (end_ - (1 : UInt32))
      let held : UInt32 := (items.getD 0 (0 : UInt32))
      let items := items.setIfInBounds 0 (items.getD end_.toNat (0 : UInt32))
      let items := items.setIfInBounds end_.toNat held
      let (r2, items) ← sort_sift_down_u32 items (0 : UInt32) end_ fuel
      sort_heap_u32.loop2 items end_ fuel
    else pure (items, end_)

def sort_heap_u32 (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let n : UInt32 := (items.size.toUInt32)
  let items ← (if (decide (n > (1 : UInt32))) then (do
      let start : UInt32 := (n / (2 : UInt32))
      let start ← sort_heap_u32.loop1 items n start fuel
      let end_ : UInt32 := n
      let (items, end_) ← sort_heap_u32.loop2 items end_ fuel
      pure items)
    else (do
      pure items))
  pure ((), items)

def sort_u32_heap (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let (r1, items) ← sort_heap_u32 items fuel
  pure ((), items)

def sort_span_u32 (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let () ← (if (decide ((items.size.toUInt32) <= (16 : UInt32))) then (do
      let (r1, items) ← sort_insertion_u32 items fuel
      pure ())
    else (do
      let (r2, items) ← sort_heap_u32 items fuel
      pure ()))
  pure ((), items)

def sort_u32_span (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let (r1, items) ← sort_span_u32 items fuel
  pure ((), items)

def sort_search_u32.loop1 (items : Array UInt32) (key : UInt32) (low : UInt32) (high : UInt32) (found : Option_u32) (searching : Bool) : Nat → Option (UInt32 × UInt32 × Option_u32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if (searching && (decide (low < high))) then do
      let mid : UInt32 := (low + ((high - low) / (2 : UInt32)))
      let (low, high, found, searching) ← (if (decide ((items.getD mid.toNat (0 : UInt32)) < key)) then (do
          let low := (mid + (1 : UInt32))
          pure (low, high, found, searching))
        else (do
          let (high, found, searching) ← (if (decide (key < (items.getD mid.toNat (0 : UInt32)))) then (do
              let high := mid
              pure (high, found, searching))
            else (do
              let found := (Option_u32.Some mid)
              let searching := false
              pure (high, found, searching)))
          pure (low, high, found, searching)))
      sort_search_u32.loop1 items key low high found searching fuel
    else pure (low, high, found, searching)

def sort_search_u32 (items : Array UInt32) (key : UInt32) (fuel : Nat) : Option (Option_u32) := do
  let low : UInt32 := (0 : UInt32)
  let high : UInt32 := (items.size.toUInt32)
  let found : Option_u32 := Option_u32.None
  let searching : Bool := true
  let (low, high, found, searching) ← sort_search_u32.loop1 items key low high found searching fuel
  pure found

def sort_u32_search (items : Array UInt32) (key : UInt32) (fuel : Nat) : Option (Option_u32) := do
  let r1 ← sort_search_u32 items key fuel
  pure r1

def sort_lower_bound_u32.loop1 (items : Array UInt32) (key : UInt32) (low : UInt32) (high : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (low < high)) then do
      let mid : UInt32 := (low + ((high - low) / (2 : UInt32)))
      let (low, high) ← (if (decide ((items.getD mid.toNat (0 : UInt32)) < key)) then (do
          let low := (mid + (1 : UInt32))
          pure (low, high))
        else (do
          let high := mid
          pure (low, high)))
      sort_lower_bound_u32.loop1 items key low high fuel
    else pure (low, high)

def sort_lower_bound_u32 (items : Array UInt32) (key : UInt32) (fuel : Nat) : Option (UInt32) := do
  let low : UInt32 := (0 : UInt32)
  let high : UInt32 := (items.size.toUInt32)
  let (low, high) ← sort_lower_bound_u32.loop1 items key low high fuel
  pure low

def sort_u32_lower_bound (items : Array UInt32) (key : UInt32) (fuel : Nat) : Option (UInt32) := do
  let r1 ← sort_lower_bound_u32 items key fuel
  pure r1

def sort_dedup_u32.loop1 (items : Array UInt32) (n : UInt32) (kept : UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < n)) then do
      let equal : Bool := ((!(decide ((items.getD (kept - (1 : UInt32)).toNat (0 : UInt32)) < (items.getD i.toNat (0 : UInt32))))) && (!(decide ((items.getD i.toNat (0 : UInt32)) < (items.getD (kept - (1 : UInt32)).toNat (0 : UInt32))))))
      let (items, kept) ← (if (!equal) then (do
          let items := items.setIfInBounds kept.toNat (items.getD i.toNat (0 : UInt32))
          let kept := (kept + (1 : UInt32))
          pure (items, kept))
        else (do
          pure (items, kept)))
      let i := (i + (1 : UInt32))
      sort_dedup_u32.loop1 items n kept i fuel
    else pure (items, kept, i)

def sort_dedup_u32 (items : Array UInt32) (fuel : Nat) : Option (UInt32 × Array UInt32) := do
  let n : UInt32 := (items.size.toUInt32)
  let (r1, items) ← (
    if (n == (0 : UInt32)) then (do
      pure ((0 : UInt32), items))
    else (do
      let kept : UInt32 := (1 : UInt32)
      let i : UInt32 := (1 : UInt32)
      let (items, kept, i) ← sort_dedup_u32.loop1 items n kept i fuel
      pure (kept, items)))
  pure (r1, items)

def sort_u32_dedup (items : Array UInt32) (fuel : Nat) : Option (UInt32 × Array UInt32) := do
  let (r1, items) ← sort_dedup_u32 items fuel
  pure (r1, items)

def sort_reverse_u32.loop1 (items : Array UInt32) (n : UInt32) (i : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (n > (1 : UInt32))) && (decide (i < (n / (2 : UInt32))))) then do
      let held : UInt32 := (items.getD i.toNat (0 : UInt32))
      let items := items.setIfInBounds i.toNat (items.getD ((n - (1 : UInt32)) - i).toNat (0 : UInt32))
      let items := items.setIfInBounds ((n - (1 : UInt32)) - i).toNat held
      let i := (i + (1 : UInt32))
      sort_reverse_u32.loop1 items n i fuel
    else pure (items, i)

def sort_reverse_u32 (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let n : UInt32 := (items.size.toUInt32)
  let i : UInt32 := (0 : UInt32)
  let (items, i) ← sort_reverse_u32.loop1 items n i fuel
  pure ((), items)

def sort_u32_reverse (items : Array UInt32) (fuel : Nat) : Option (Unit × Array UInt32) := do
  let (r1, items) ← sort_reverse_u32 items fuel
  pure ((), items)

end Oak.Stdlib.SortU32
