-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Url

inductive UrlError where
  | InvalidScheme
  | InvalidHost
  | InvalidPort
  | InvalidCharacter
  | InvalidPercentEncoding
  | DestinationTooSmall
  deriving Repr, Inhabited, BEq, DecidableEq

structure UrlRange where
  start : UInt32
  end_ : UInt32
  present : Bool
  deriving Repr, BEq, DecidableEq
instance : Inhabited UrlRange := ⟨{ start := (0 : UInt32), end_ := (0 : UInt32), present := false }⟩

structure Url where
  scheme : UrlRange
  userinfo : UrlRange
  host : UrlRange
  port : UrlRange
  path : UrlRange
  query : UrlRange
  fragment : UrlRange
  has_authority : Bool
  deriving Repr, BEq, DecidableEq
instance : Inhabited Url := ⟨{ scheme := (default : UrlRange), userinfo := (default : UrlRange), host := (default : UrlRange), port := (default : UrlRange), path := (default : UrlRange), query := (default : UrlRange), fragment := (default : UrlRange), has_authority := false }⟩

structure UrlPair where
  key : UrlRange
  value : UrlRange
  next : UInt32
  deriving Repr, BEq, DecidableEq
instance : Inhabited UrlPair := ⟨{ key := (default : UrlRange), value := (default : UrlRange), next := (0 : UInt32) }⟩

inductive Option_UrlPair where
  | Some (payload : UrlPair)
  | None
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Option_u32 where
  | Some (payload : UInt32)
  | None
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_Url_UrlError where
  | Ok (payload : Url)
  | Err (payload : UrlError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u32_UrlError where
  | Ok (payload : UInt32)
  | Err (payload : UrlError)
  deriving Repr, Inhabited, BEq, DecidableEq

def url_range (start : UInt32) (end_ : UInt32) (fuel : Nat) : Option (UrlRange) := do
  pure ({ start := start, end_ := end_, present := true } : UrlRange)

def url_absent  (fuel : Nat) : Option (UrlRange) := do
  pure ({ start := (0 : UInt32), end_ := (0 : UInt32), present := false } : UrlRange)

def url_range_len (range : UrlRange) (fuel : Nat) : Option (UInt32) := do
  pure (range.end_ - range.start)

def url_error_code (reason : UrlError) (fuel : Nat) : Option (UInt32) := do
  pure (match reason with | .InvalidScheme => (1 : UInt32) | .InvalidHost => (2 : UInt32) | .InvalidPort => (3 : UInt32) | .InvalidCharacter => (4 : UInt32) | .InvalidPercentEncoding => (5 : UInt32) | .DestinationTooSmall => (6 : UInt32))

def url_ok (result : Result_Url_UrlError) (fuel : Nat) : Option (Bool) := do
  pure (match result with | (.Ok parsed) => true | (.Err reason) => false)

def url_empty  (fuel : Nat) : Option (Url) := do
  let r1 ← url_absent  fuel
  let r2 ← url_absent  fuel
  let r3 ← url_absent  fuel
  let r4 ← url_absent  fuel
  let r5 ← url_range (0 : UInt32) (0 : UInt32) fuel
  let r6 ← url_absent  fuel
  let r7 ← url_absent  fuel
  pure ({ scheme := r1, userinfo := r2, host := r3, port := r4, path := r5, query := r6, fragment := r7, has_authority := false } : Url)

def url_value (result : Result_Url_UrlError) (fuel : Nat) : Option (Url) := do
  let r1 ← (match result with
    | (.Ok parsed) => (do
      pure parsed)
    | (.Err reason) => (do
      let r2 ← url_empty  fuel
      pure r2))
  pure r1

def url_failure (result : Result_Url_UrlError) (fuel : Nat) : Option (UInt32) := do
  let r1 ← (match result with
    | (.Ok parsed) => (do
      pure (0 : UInt32))
    | (.Err reason) => (do
      let r2 ← url_error_code reason fuel
      pure r2))
  pure r1

def url_written (result : Result_u32_UrlError) (fuel : Nat) : Option (UInt32) := do
  pure (match result with | (.Ok count) => count | (.Err reason) => (0 : UInt32))

def url_write_failure (result : Result_u32_UrlError) (fuel : Nat) : Option (UInt32) := do
  let r1 ← (match result with
    | (.Ok count) => (do
      pure (0 : UInt32))
    | (.Err reason) => (do
      let r2 ← url_error_code reason fuel
      pure r2))
  pure r1

def url_is_alpha (unit : UInt8) (fuel : Nat) : Option (Bool) := do
  pure (((decide (unit >= (65 : UInt8))) && (decide (unit <= (90 : UInt8)))) || ((decide (unit >= (97 : UInt8))) && (decide (unit <= (122 : UInt8)))))

def url_is_digit (unit : UInt8) (fuel : Nat) : Option (Bool) := do
  pure ((decide (unit >= (48 : UInt8))) && (decide (unit <= (57 : UInt8))))

def url_is_hex (unit : UInt8) (fuel : Nat) : Option (Bool) := do
  let r1 ← url_is_digit unit fuel
  pure ((r1 || ((decide (unit >= (65 : UInt8))) && (decide (unit <= (70 : UInt8))))) || ((decide (unit >= (97 : UInt8))) && (decide (unit <= (102 : UInt8)))))

def url_is_unreserved (unit : UInt8) (fuel : Nat) : Option (Bool) := do
  let r1 ← url_is_alpha unit fuel
  let r2 ← url_is_digit unit fuel
  pure (((((r1 || r2) || (unit == (45 : UInt8))) || (unit == (46 : UInt8))) || (unit == (95 : UInt8))) || (unit == (126 : UInt8)))

def url_is_sub_delim (unit : UInt8) (fuel : Nat) : Option (Bool) := do
  pure (((((((((((unit == (33 : UInt8)) || (unit == (36 : UInt8))) || (unit == (38 : UInt8))) || (unit == (39 : UInt8))) || (unit == (40 : UInt8))) || (unit == (41 : UInt8))) || (unit == (42 : UInt8))) || (unit == (43 : UInt8))) || (unit == (44 : UInt8))) || (unit == (59 : UInt8))) || (unit == (61 : UInt8)))

def url_scan_class.loop1 (src : Array UInt8) (end_ : UInt32) (class_ : UInt32) (i : UInt32) (code : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < end_)) && (code == (0 : UInt32))) then do
      let unit : UInt8 := (src.getD i.toNat (0 : UInt8))
      let (i, code) ← (if (unit == (37 : UInt8)) then (do
          let r1 ← url_is_hex (src.getD (i + (1 : UInt32)).toNat (0 : UInt8)) fuel
          let r2 ← url_is_hex (src.getD (i + (2 : UInt32)).toNat (0 : UInt8)) fuel
          let (i, code) ← (if (((decide ((i + (2 : UInt32)) < end_)) && r1) && r2) then (do
              let i := (i + (3 : UInt32))
              pure (i, code))
            else (do
              let code := (2 : UInt32)
              pure (i, code)))
          pure (i, code))
        else (do
          let r3 ← url_is_unreserved unit fuel
          let r4 ← url_is_sub_delim unit fuel
          let allowed : Bool := (((((r3 || r4) || ((unit == (58 : UInt8)) && (class_ != (4 : UInt32)))) || ((unit == (64 : UInt8)) && (decide (class_ <= (2 : UInt32))))) || ((unit == (47 : UInt8)) && (decide (class_ <= (2 : UInt32))))) || ((unit == (63 : UInt8)) && (class_ == (2 : UInt32))))
          let (i, code) ← (if allowed then (do
              let i := (i + (1 : UInt32))
              pure (i, code))
            else (do
              let code := (1 : UInt32)
              pure (i, code)))
          pure (i, code)))
      url_scan_class.loop1 src end_ class_ i code fuel
    else pure (i, code)

def url_scan_class (src : Array UInt8) (start : UInt32) (end_ : UInt32) (class_ : UInt32) (fuel : Nat) : Option (UInt32) := do
  let i : UInt32 := start
  let code : UInt32 := (0 : UInt32)
  let (i, code) ← url_scan_class.loop1 src end_ class_ i code fuel
  pure code

def url_find_delim.loop1 (src : Array UInt8) (a : UInt8) (b : UInt8) (c : UInt8) (i : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((((decide (i < (src.size.toUInt32))) && ((src.getD i.toNat (0 : UInt8)) != a)) && ((src.getD i.toNat (0 : UInt8)) != b)) && ((src.getD i.toNat (0 : UInt8)) != c)) then do
      let i := (i + (1 : UInt32))
      url_find_delim.loop1 src a b c i fuel
    else pure i

def url_find_delim (src : Array UInt8) (begin : UInt32) (a : UInt8) (b : UInt8) (c : UInt8) (fuel : Nat) : Option (UInt32) := do
  let i : UInt32 := begin
  let i ← url_find_delim.loop1 src a b c i fuel
  pure i

def url_scheme_end.loop1 (src : Array UInt8) (i : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    let r1 ← url_is_alpha (src.getD i.toNat (0 : UInt8)) fuel
    let r2 ← url_is_digit (src.getD i.toNat (0 : UInt8)) fuel
    if ((decide (i < (src.size.toUInt32))) && ((((r1 || r2) || ((src.getD i.toNat (0 : UInt8)) == (43 : UInt8))) || ((src.getD i.toNat (0 : UInt8)) == (45 : UInt8))) || ((src.getD i.toNat (0 : UInt8)) == (46 : UInt8)))) then do
      let i := (i + (1 : UInt32))
      url_scheme_end.loop1 src i fuel
    else pure i

def url_scheme_end (src : Array UInt8) (fuel : Nat) : Option (UInt32) := do
  let i : UInt32 := (0 : UInt32)
  let i ← url_scheme_end.loop1 src i fuel
  let r3 ← url_is_alpha (src.getD 0 (0 : UInt8)) fuel
  pure (if ((((decide (i > (0 : UInt32))) && (decide (i < (src.size.toUInt32)))) && ((src.getD i.toNat (0 : UInt8)) == (58 : UInt8))) && r3) then i else (0 : UInt32))

def url_first_segment_has_colon.loop1 (src : Array UInt8) (end_ : UInt32) (i : UInt32) (found : Bool) : Nat → Option (UInt32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < end_)) && ((src.getD i.toNat (0 : UInt8)) != (47 : UInt8))) then do
      let found ← (if ((src.getD i.toNat (0 : UInt8)) == (58 : UInt8)) then (do
          let found := true
          pure found)
        else (do
          pure found))
      let i := (i + (1 : UInt32))
      url_first_segment_has_colon.loop1 src end_ i found fuel
    else pure (i, found)

def url_first_segment_has_colon (src : Array UInt8) (start : UInt32) (end_ : UInt32) (fuel : Nat) : Option (Bool) := do
  let i : UInt32 := start
  let found : Bool := false
  let (i, found) ← url_first_segment_has_colon.loop1 src end_ i found fuel
  pure found

def url_ip_literal_ok.loop1 (src : Array UInt8) (end_ : UInt32) (i : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    let r3 ← url_is_hex (src.getD i.toNat (0 : UInt8)) fuel
    if ((decide (i < end_)) && r3) then do
      let i := (i + (1 : UInt32))
      url_ip_literal_ok.loop1 src end_ i fuel
    else pure i

def url_ip_literal_ok.loop2 (src : Array UInt8) (end_ : UInt32) (j : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    let r5 ← url_is_unreserved (src.getD j.toNat (0 : UInt8)) fuel
    let r6 ← url_is_sub_delim (src.getD j.toNat (0 : UInt8)) fuel
    if ((decide (j < end_)) && ((r5 || r6) || ((src.getD j.toNat (0 : UInt8)) == (58 : UInt8)))) then do
      let j := (j + (1 : UInt32))
      url_ip_literal_ok.loop2 src end_ j fuel
    else pure j

def url_ip_literal_ok.loop3 (src : Array UInt8) (end_ : UInt32) (k : UInt32) (colons : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    let r7 ← url_is_hex (src.getD k.toNat (0 : UInt8)) fuel
    if ((decide (k < end_)) && ((r7 || ((src.getD k.toNat (0 : UInt8)) == (58 : UInt8))) || ((src.getD k.toNat (0 : UInt8)) == (46 : UInt8)))) then do
      let colons ← (if ((src.getD k.toNat (0 : UInt8)) == (58 : UInt8)) then (do
          let colons := (colons + (1 : UInt32))
          pure colons)
        else (do
          pure colons))
      let k := (k + (1 : UInt32))
      url_ip_literal_ok.loop3 src end_ k colons fuel
    else pure (k, colons)

def url_ip_literal_ok (src : Array UInt8) (start : UInt32) (end_ : UInt32) (fuel : Nat) : Option (Bool) := do
  let r1 ← (
    if (decide (start >= end_)) then (do
      pure false)
    else (do
      let r2 ← (
        if (((src.getD start.toNat (0 : UInt8)) == (118 : UInt8)) || ((src.getD start.toNat (0 : UInt8)) == (86 : UInt8))) then (do
          let i : UInt32 := (start + (1 : UInt32))
          let i ← url_ip_literal_ok.loop1 src end_ i fuel
          let r4 ← (
            if (((decide (i > (start + (1 : UInt32)))) && (decide ((i + (1 : UInt32)) < end_))) && ((src.getD i.toNat (0 : UInt8)) == (46 : UInt8))) then (do
              let j : UInt32 := (i + (1 : UInt32))
              let j ← url_ip_literal_ok.loop2 src end_ j fuel
              pure (j == end_))
            else (do
              pure false))
          pure r4)
        else (do
          let k : UInt32 := start
          let colons : UInt32 := (0 : UInt32)
          let (k, colons) ← url_ip_literal_ok.loop3 src end_ k colons fuel
          pure ((k == end_) && (decide (colons >= (2 : UInt32))))))
      pure r2))
  pure r1

def url_with_authority.loop1 (src : Array UInt8) (end_ : UInt32) (digits : Bool) (i : UInt32) : Nat → Option (Bool × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < end_)) && digits) then do
      let r1 ← url_is_digit (src.getD i.toNat (0 : UInt8)) fuel
      let digits := r1
      let i := (i + (1 : UInt32))
      url_with_authority.loop1 src end_ digits i fuel
    else pure (digits, i)

def url_with_authority (src : Array UInt8) (userinfo : UrlRange) (host : UrlRange) (colon : UInt32) (end_ : UInt32) (fuel : Nat) : Option (Result_Url_UrlError) := do
  let has_port : Bool := (decide (colon < end_))
  let digits : Bool := true
  let i : UInt32 := (colon + (1 : UInt32))
  let (digits, i) ← url_with_authority.loop1 src end_ digits i fuel
  let r2 ← (
    if has_port then (do
      let r3 ← url_range (colon + (1 : UInt32)) end_ fuel
      pure r3)
    else (do
      let r4 ← url_absent  fuel
      pure r4))
  let port : UrlRange := r2
  let r5 ← (
    if (!digits) then (do
      pure (Result_Url_UrlError.Err UrlError.InvalidPort))
    else (do
      let r6 ← url_absent  fuel
      let r7 ← url_range (0 : UInt32) (0 : UInt32) fuel
      let r8 ← url_absent  fuel
      let r9 ← url_absent  fuel
      pure (Result_Url_UrlError.Ok ({ scheme := r6, userinfo := userinfo, host := host, port := port, path := r7, query := r8, fragment := r9, has_authority := true } : Url))))
  pure r5

def url_parse_authority.loop1 (src : Array UInt8) (end_ : UInt32) (at_ : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (at_ < end_)) && ((src.getD at_.toNat (0 : UInt8)) != (64 : UInt8))) then do
      let at_ := (at_ + (1 : UInt32))
      url_parse_authority.loop1 src end_ at_ fuel
    else pure at_

def url_parse_authority.loop2 (src : Array UInt8) (end_ : UInt32) (close : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (close < end_)) && ((src.getD close.toNat (0 : UInt8)) != (93 : UInt8))) then do
      let close := (close + (1 : UInt32))
      url_parse_authority.loop2 src end_ close fuel
    else pure close

def url_parse_authority.loop3 (src : Array UInt8) (end_ : UInt32) (colon : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (colon < end_)) && ((src.getD colon.toNat (0 : UInt8)) != (58 : UInt8))) then do
      let colon := (colon + (1 : UInt32))
      url_parse_authority.loop3 src end_ colon fuel
    else pure colon

def url_parse_authority (src : Array UInt8) (start : UInt32) (end_ : UInt32) (fuel : Nat) : Option (Result_Url_UrlError) := do
  let at_ : UInt32 := start
  let at_ ← url_parse_authority.loop1 src end_ at_ fuel
  let has_user : Bool := (decide (at_ < end_))
  let r1 ← (
    if has_user then (do
      let r2 ← url_range start at_ fuel
      pure r2)
    else (do
      let r3 ← url_absent  fuel
      pure r3))
  let userinfo : UrlRange := r1
  let host_start : UInt32 := (if has_user then (at_ + (1 : UInt32)) else start)
  let r4 ← (
    if has_user then (do
      let r5 ← url_scan_class src start at_ (3 : UInt32) fuel
      pure r5)
    else (do
      pure (0 : UInt32)))
  let user_code : UInt32 := r4
  let r6 ← (
    if (user_code == (2 : UInt32)) then (do
      pure (Result_Url_UrlError.Err UrlError.InvalidPercentEncoding))
    else (do
      let r7 ← (
        if (user_code != (0 : UInt32)) then (do
          pure (Result_Url_UrlError.Err UrlError.InvalidCharacter))
        else (do
          let r8 ← (
            if ((decide (host_start < end_)) && ((src.getD host_start.toNat (0 : UInt8)) == (91 : UInt8))) then (do
              let close : UInt32 := host_start
              let close ← url_parse_authority.loop2 src end_ close fuel
              let r9 ← (
                if (decide (close >= end_)) then (do
                  pure (Result_Url_UrlError.Err UrlError.InvalidHost))
                else (do
                  let after : UInt32 := (close + (1 : UInt32))
                  let r10 ← (
                    if ((decide (after < end_)) && ((src.getD after.toNat (0 : UInt8)) != (58 : UInt8))) then (do
                      pure (Result_Url_UrlError.Err UrlError.InvalidHost))
                    else (do
                      let r11 ← url_ip_literal_ok src (host_start + (1 : UInt32)) close fuel
                      let r12 ← (
                        if (!r11) then (do
                          pure (Result_Url_UrlError.Err UrlError.InvalidHost))
                        else (do
                          let r13 ← url_range host_start after fuel
                          let r14 ← url_with_authority src userinfo r13 after end_ fuel
                          pure r14))
                      pure r12))
                  pure r10))
              pure r9)
            else (do
              let colon : UInt32 := host_start
              let colon ← url_parse_authority.loop3 src end_ colon fuel
              let r15 ← url_scan_class src host_start colon (4 : UInt32) fuel
              let r16 ← (
                if (r15 != (0 : UInt32)) then (do
                  pure (Result_Url_UrlError.Err UrlError.InvalidHost))
                else (do
                  let r17 ← url_range host_start colon fuel
                  let r18 ← url_with_authority src userinfo r17 colon end_ fuel
                  pure r18))
              pure r16))
          pure r8))
      pure r7))
  pure r6

def url_parse (src : Array UInt8) (fuel : Nat) : Option (Result_Url_UrlError) := do
  let r1 ← url_scheme_end src fuel
  let scheme_end : UInt32 := r1
  let has_scheme : Bool := (decide (scheme_end > (0 : UInt32)))
  let r2 ← (
    if has_scheme then (do
      let r3 ← url_range (0 : UInt32) scheme_end fuel
      pure r3)
    else (do
      let r4 ← url_absent  fuel
      pure r4))
  let scheme : UrlRange := r2
  let rest : UInt32 := (if has_scheme then (scheme_end + (1 : UInt32)) else (0 : UInt32))
  let has_authority : Bool := (((decide ((rest + (1 : UInt32)) < (src.size.toUInt32))) && ((src.getD rest.toNat (0 : UInt8)) == (47 : UInt8))) && ((src.getD (rest + (1 : UInt32)).toNat (0 : UInt8)) == (47 : UInt8)))
  let authority_start : UInt32 := (if has_authority then (rest + (2 : UInt32)) else rest)
  let r5 ← (
    if has_authority then (do
      let r6 ← url_find_delim src authority_start (47 : UInt8) (63 : UInt8) (35 : UInt8) fuel
      pure r6)
    else (do
      pure rest))
  let authority_end : UInt32 := r5
  let r7 ← url_find_delim src authority_end (63 : UInt8) (35 : UInt8) (35 : UInt8) fuel
  let path_end : UInt32 := r7
  let has_query : Bool := ((decide (path_end < (src.size.toUInt32))) && ((src.getD path_end.toNat (0 : UInt8)) == (63 : UInt8)))
  let query_start : UInt32 := (if has_query then (path_end + (1 : UInt32)) else path_end)
  let r8 ← (
    if has_query then (do
      let r9 ← url_find_delim src query_start (35 : UInt8) (35 : UInt8) (35 : UInt8) fuel
      pure r9)
    else (do
      pure path_end))
  let query_end : UInt32 := r8
  let has_fragment : Bool := ((decide (query_end < (src.size.toUInt32))) && ((src.getD query_end.toNat (0 : UInt8)) == (35 : UInt8)))
  let r10 ← url_range authority_end path_end fuel
  let path : UrlRange := r10
  let r11 ← (
    if has_query then (do
      let r12 ← url_range query_start query_end fuel
      pure r12)
    else (do
      let r13 ← url_absent  fuel
      pure r13))
  let query : UrlRange := r11
  let r14 ← (
    if has_fragment then (do
      let r15 ← url_range (query_end + (1 : UInt32)) (src.size.toUInt32) fuel
      pure r15)
    else (do
      let r16 ← url_absent  fuel
      pure r16))
  let fragment : UrlRange := r14
  let r17 ← url_scan_class src authority_end path_end (1 : UInt32) fuel
  let path_code : UInt32 := r17
  let r18 ← (
    if has_query then (do
      let r19 ← url_scan_class src query_start query_end (2 : UInt32) fuel
      pure r19)
    else (do
      pure (0 : UInt32)))
  let query_code : UInt32 := r18
  let r20 ← (
    if has_fragment then (do
      let r21 ← url_scan_class src (query_end + (1 : UInt32)) (src.size.toUInt32) (2 : UInt32) fuel
      pure r21)
    else (do
      pure (0 : UInt32)))
  let fragment_code : UInt32 := r20
  let worst : UInt32 := (if (decide (path_code > query_code)) then path_code else query_code)
  let code : UInt32 := (if (decide (fragment_code > worst)) then fragment_code else worst)
  let r22 ← url_first_segment_has_colon src authority_end path_end fuel
  let noscheme_colon : Bool := (((!has_scheme) && (!has_authority)) && r22)
  let r23 ← (
    if has_authority then (do
      let r24 ← url_parse_authority src authority_start authority_end fuel
      pure r24)
    else (do
      let r25 ← url_empty  fuel
      pure (Result_Url_UrlError.Ok r25)))
  let authority : Result_Url_UrlError := r23
  pure (match authority with | (.Err reason) => (Result_Url_UrlError.Err reason) | (.Ok parts) => (if (code == (2 : UInt32)) then (Result_Url_UrlError.Err UrlError.InvalidPercentEncoding) else (if ((code != (0 : UInt32)) || noscheme_colon) then (Result_Url_UrlError.Err UrlError.InvalidCharacter) else (Result_Url_UrlError.Ok ({ scheme := scheme, userinfo := parts.userinfo, host := parts.host, port := parts.port, path := path, query := query, fragment := fragment, has_authority := has_authority } : Url)))))

def url_port_number.loop1 (src : Array UInt8) (parsed : Url) (value : UInt32) (i : UInt32) : Nat → Option (UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < parsed.port.end_)) && (decide (value <= (65535 : UInt32)))) then do
      let value := ((value * (10 : UInt32)) + (((src.getD i.toNat (0 : UInt8)) - (48 : UInt8)).toUInt32))
      let i := (i + (1 : UInt32))
      url_port_number.loop1 src parsed value i fuel
    else pure (value, i)

def url_port_number (src : Array UInt8) (parsed : Url) (fuel : Nat) : Option (Option_u32) := do
  let r1 ← (
    if ((!parsed.port.present) || (parsed.port.end_ == parsed.port.start)) then (do
      pure Option_u32.None)
    else (do
      let value : UInt32 := (0 : UInt32)
      let i : UInt32 := parsed.port.start
      let (value, i) ← url_port_number.loop1 src parsed value i fuel
      pure (if (decide (value <= (65535 : UInt32))) then (Option_u32.Some value) else Option_u32.None)))
  pure r1

def url_is_absolute (parsed : Url) (fuel : Nat) : Option (Bool) := do
  pure (parsed.scheme.present && (!parsed.fragment.present))

def url_is_relative (parsed : Url) (fuel : Nat) : Option (Bool) := do
  pure (!parsed.scheme.present)

def url_in (first : Array UInt8) (second : Array UInt8) (i : UInt32) (fuel : Nat) : Option (UInt8) := do
  pure (if (decide (i < (first.size.toUInt32))) then (first.getD i.toNat (0 : UInt8)) else (second.getD (i - (first.size.toUInt32)).toNat (0 : UInt8)))

def url_in_is (first : Array UInt8) (second : Array UInt8) (i : UInt32) (n : UInt32) (unit : UInt8) (fuel : Nat) : Option (Bool) := do
  let r1 ← url_in first second i fuel
  pure ((decide (i < n)) && (r1 == unit))

def url_drop_segment.loop1 (dst : Array UInt8) (out_start : UInt32) (cut : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (cut > out_start)) && ((dst.getD (cut - (1 : UInt32)).toNat (0 : UInt8)) != (47 : UInt8))) then do
      let cut := (cut - (1 : UInt32))
      url_drop_segment.loop1 dst out_start cut fuel
    else pure cut

def url_drop_segment (dst : Array UInt8) (out_start : UInt32) (out : UInt32) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let cut : UInt32 := out
  let cut ← url_drop_segment.loop1 dst out_start cut fuel
  pure ((if (decide (cut > out_start)) then (cut - (1 : UInt32)) else cut), dst)

def url_remove_dots_into.loop2 (dst : Array UInt8) (first : Array UInt8) (second : Array UInt8) (n : UInt32) (at_ : UInt32) (out : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    let r11 ← url_in_is first second at_ n (47 : UInt8) fuel
    if ((decide (at_ < n)) && (!r11)) then do
      let r12 ← url_in first second at_ fuel
      let dst := dst.setIfInBounds out.toNat r12
      let out := (out + (1 : UInt32))
      let at_ := (at_ + (1 : UInt32))
      url_remove_dots_into.loop2 dst first second n at_ out fuel
    else pure (dst, at_, out)

def url_remove_dots_into.loop1 (dst : Array UInt8) (out_start : UInt32) (first : Array UInt8) (second : Array UInt8) (n : UInt32) (at_ : UInt32) (out : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (at_ < n)) then do
      let rest : UInt32 := (n - at_)
      let r1 ← url_in_is first second at_ n (46 : UInt8) fuel
      let dot0 : Bool := r1
      let r2 ← url_in_is first second at_ n (47 : UInt8) fuel
      let slash0 : Bool := r2
      let r3 ← url_in_is first second (at_ + (1 : UInt32)) n (46 : UInt8) fuel
      let dot1 : Bool := r3
      let r4 ← url_in_is first second (at_ + (1 : UInt32)) n (47 : UInt8) fuel
      let slash1 : Bool := r4
      let r5 ← url_in_is first second (at_ + (2 : UInt32)) n (46 : UInt8) fuel
      let dot2 : Bool := r5
      let r6 ← url_in_is first second (at_ + (2 : UInt32)) n (47 : UInt8) fuel
      let slash2 : Bool := r6
      let r7 ← url_in_is first second (at_ + (3 : UInt32)) n (47 : UInt8) fuel
      let slash3 : Bool := r7
      let (dst, at_, out) ← (if ((dot0 && dot1) && slash2) then (do
          let at_ := (at_ + (3 : UInt32))
          pure (dst, at_, out))
        else (do
          let (dst, at_, out) ← (if (dot0 && slash1) then (do
              let at_ := (at_ + (2 : UInt32))
              pure (dst, at_, out))
            else (do
              let (dst, at_, out) ← (if ((slash0 && dot1) && slash2) then (do
                  let at_ := (at_ + (2 : UInt32))
                  pure (dst, at_, out))
                else (do
                  let (dst, at_, out) ← (if ((slash0 && dot1) && (rest == (2 : UInt32))) then (do
                      let dst := dst.setIfInBounds out.toNat (47 : UInt8)
                      let out := (out + (1 : UInt32))
                      let at_ := n
                      pure (dst, at_, out))
                    else (do
                      let (dst, at_, out) ← (if (((slash0 && dot1) && dot2) && slash3) then (do
                          let at_ := (at_ + (3 : UInt32))
                          let (r8, dst) ← url_drop_segment dst out_start out fuel
                          let out := r8
                          pure (dst, at_, out))
                        else (do
                          let (dst, at_, out) ← (if (((slash0 && dot1) && dot2) && (rest == (3 : UInt32))) then (do
                              let (r9, dst) ← url_drop_segment dst out_start out fuel
                              let out := r9
                              let dst := dst.setIfInBounds out.toNat (47 : UInt8)
                              let out := (out + (1 : UInt32))
                              let at_ := n
                              pure (dst, at_, out))
                            else (do
                              let (dst, at_, out) ← (if (dot0 && ((rest == (1 : UInt32)) || (dot1 && (rest == (2 : UInt32))))) then (do
                                  let at_ := n
                                  pure (dst, at_, out))
                                else (do
                                  let r10 ← url_in first second at_ fuel
                                  let dst := dst.setIfInBounds out.toNat r10
                                  let out := (out + (1 : UInt32))
                                  let at_ := (at_ + (1 : UInt32))
                                  let (dst, at_, out) ← url_remove_dots_into.loop2 dst first second n at_ out fuel
                                  pure (dst, at_, out)))
                              pure (dst, at_, out)))
                          pure (dst, at_, out)))
                      pure (dst, at_, out)))
                  pure (dst, at_, out)))
              pure (dst, at_, out)))
          pure (dst, at_, out)))
      url_remove_dots_into.loop1 dst out_start first second n at_ out fuel
    else pure (dst, at_, out)

def url_remove_dots_into (dst : Array UInt8) (out_start : UInt32) (first : Array UInt8) (second : Array UInt8) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let n : UInt32 := ((first.size.toUInt32) + (second.size.toUInt32))
  let at_ : UInt32 := (0 : UInt32)
  let out : UInt32 := out_start
  let (dst, at_, out) ← url_remove_dots_into.loop1 dst out_start first second n at_ out fuel
  pure ((out - out_start), dst)

def url_remove_dot_segments (dst : Array UInt8) (path : Array UInt8) (fuel : Nat) : Option (Result_u32_UrlError × Array UInt8) := do
  let (r1, dst) ← (
    if (decide ((dst.size.toUInt32) < (path.size.toUInt32))) then (do
      pure ((Result_u32_UrlError.Err UrlError.DestinationTooSmall), dst))
    else (do
      let empty : Array UInt8 := (path.extract (0 : UInt32).toNat (0 : UInt32).toNat)
      let (r2, dst) ← url_remove_dots_into dst (0 : UInt32) path empty fuel
      pure ((Result_u32_UrlError.Ok r2), dst)))
  pure (r1, dst)

def url_copy.loop1 (dst : Array UInt8) (src : Array UInt8) (range : UrlRange) (i : UInt32) (at_ : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < range.end_)) then do
      let dst := dst.setIfInBounds at_.toNat (src.getD i.toNat (0 : UInt8))
      let at_ := (at_ + (1 : UInt32))
      let i := (i + (1 : UInt32))
      url_copy.loop1 dst src range i at_ fuel
    else pure (dst, i, at_)

def url_copy (dst : Array UInt8) (out : UInt32) (src : Array UInt8) (range : UrlRange) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let i : UInt32 := range.start
  let at_ : UInt32 := out
  let (dst, i, at_) ← url_copy.loop1 dst src range i at_ fuel
  pure (at_, dst)

def url_copy_authority (dst : Array UInt8) (out : UInt32) (src : Array UInt8) (parsed : Url) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let start : UInt32 := (if parsed.userinfo.present then parsed.userinfo.start else parsed.host.start)
  let end_ : UInt32 := (if parsed.port.present then parsed.port.end_ else parsed.host.end_)
  let dst := dst.setIfInBounds out.toNat (47 : UInt8)
  let dst := dst.setIfInBounds (out + (1 : UInt32)).toNat (47 : UInt8)
  let r1 ← url_range start end_ fuel
  let (r2, dst) ← url_copy dst (out + (2 : UInt32)) src r1 fuel
  pure (r2, dst)

def url_resolve_parsed.loop1 (base : Array UInt8) (b : Url) (cut : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (cut > b.path.start)) && ((base.getD (cut - (1 : UInt32)).toNat (0 : UInt8)) != (47 : UInt8))) then do
      let cut := (cut - (1 : UInt32))
      url_resolve_parsed.loop1 base b cut fuel
    else pure cut

def url_resolve_parsed (dst : Array UInt8) (base : Array UInt8) (b : Url) (reference : Array UInt8) (r : Url) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let out : UInt32 := (0 : UInt32)
  let empty : Array UInt8 := (reference.extract (0 : UInt32).toNat (0 : UInt32).toNat)
  let ref_path : Array UInt8 := (reference.extract r.path.start.toNat r.path.end_.toNat)
  let own : Bool := (r.scheme.present || r.has_authority)
  let ref_path_empty : Bool := (r.path.end_ == r.path.start)
  let ref_path_rooted : Bool := ((!ref_path_empty) && ((reference.getD r.path.start.toNat (0 : UInt8)) == (47 : UInt8)))
  let (dst, out) ← (if r.scheme.present then (do
      let (r1, dst) ← url_copy dst out reference r.scheme fuel
      let out := r1
      pure (dst, out))
    else (do
      let (r2, dst) ← url_copy dst out base b.scheme fuel
      let out := r2
      pure (dst, out)))
  let dst := dst.setIfInBounds out.toNat (58 : UInt8)
  let out := (out + (1 : UInt32))
  let (dst, out) ← (if (own && r.has_authority) then (do
      let (r3, dst) ← url_copy_authority dst out reference r fuel
      let out := r3
      pure (dst, out))
    else (do
      pure (dst, out)))
  let (dst, out) ← (if ((!own) && b.has_authority) then (do
      let (r4, dst) ← url_copy_authority dst out base b fuel
      let out := r4
      pure (dst, out))
    else (do
      pure (dst, out)))
  let (dst, out) ← (if (own || ref_path_rooted) then (do
      let (r5, dst) ← url_remove_dots_into dst out ref_path empty fuel
      let out := (out + r5)
      pure (dst, out))
    else (do
      let (dst, out) ← (if ref_path_empty then (do
          let (r6, dst) ← url_copy dst out base b.path fuel
          let out := r6
          pure (dst, out))
        else (do
          let (dst, out) ← (if (b.has_authority && (b.path.end_ == b.path.start)) then (do
              let slash : Array UInt8 := (base.extract (b.scheme.end_ + (1 : UInt32)).toNat (b.scheme.end_ + (2 : UInt32)).toNat)
              let (r7, dst) ← url_remove_dots_into dst out slash ref_path fuel
              let out := (out + r7)
              pure (dst, out))
            else (do
              let cut : UInt32 := b.path.end_
              let cut ← url_resolve_parsed.loop1 base b cut fuel
              let prefix_ : Array UInt8 := (base.extract b.path.start.toNat cut.toNat)
              let (r8, dst) ← url_remove_dots_into dst out prefix_ ref_path fuel
              let out := (out + r8)
              pure (dst, out)))
          pure (dst, out)))
      pure (dst, out)))
  let use_base_query : Bool := (((!own) && ref_path_empty) && (!r.query.present))
  let (dst, out) ← (if (use_base_query && b.query.present) then (do
      let dst := dst.setIfInBounds out.toNat (63 : UInt8)
      let (r9, dst) ← url_copy dst (out + (1 : UInt32)) base b.query fuel
      let out := r9
      pure (dst, out))
    else (do
      pure (dst, out)))
  let (dst, out) ← (if ((!use_base_query) && r.query.present) then (do
      let dst := dst.setIfInBounds out.toNat (63 : UInt8)
      let (r10, dst) ← url_copy dst (out + (1 : UInt32)) reference r.query fuel
      let out := r10
      pure (dst, out))
    else (do
      pure (dst, out)))
  let (dst, out) ← (if r.fragment.present then (do
      let dst := dst.setIfInBounds out.toNat (35 : UInt8)
      let (r11, dst) ← url_copy dst (out + (1 : UInt32)) reference r.fragment fuel
      let out := r11
      pure (dst, out))
    else (do
      pure (dst, out)))
  pure (out, dst)

def url_resolve_with_base (dst : Array UInt8) (base : Array UInt8) (b : Url) (reference : Array UInt8) (fuel : Nat) : Option (Result_u32_UrlError × Array UInt8) := do
  let r1 ← url_parse reference fuel
  let (r2, dst) ← (match r1 with
    | (.Err reason) => (do
      pure ((Result_u32_UrlError.Err reason), dst))
    | (.Ok r) => (do
      let (r3, dst) ← url_resolve_parsed dst base b reference r fuel
      pure ((Result_u32_UrlError.Ok r3), dst)))
  pure (r2, dst)

def url_resolve_checked (dst : Array UInt8) (base : Array UInt8) (reference : Array UInt8) (fuel : Nat) : Option (Result_u32_UrlError × Array UInt8) := do
  let r1 ← url_parse base fuel
  let (r2, dst) ← (match r1 with
    | (.Err reason) => (do
      pure ((Result_u32_UrlError.Err reason), dst))
    | (.Ok b) => (do
      let (r3, dst) ← (
        if (!b.scheme.present) then (do
          pure ((Result_u32_UrlError.Err UrlError.InvalidScheme), dst))
        else (do
          let (r4, dst) ← url_resolve_with_base dst base b reference fuel
          pure (r4, dst)))
      pure (r3, dst)))
  pure (r2, dst)

def url_resolve (dst : Array UInt8) (base : Array UInt8) (reference : Array UInt8) (fuel : Nat) : Option (Result_u32_UrlError × Array UInt8) := do
  let (r1, dst) ← (
    if (decide ((dst.size.toUInt32) < (((base.size.toUInt32) + (reference.size.toUInt32)) + (1 : UInt32)))) then (do
      pure ((Result_u32_UrlError.Err UrlError.DestinationTooSmall), dst))
    else (do
      let (r2, dst) ← url_resolve_checked dst base reference fuel
      pure (r2, dst)))
  pure (r1, dst)

def url_query_next.loop1 (query : Array UInt8) (start : UInt32) : Nat → Option (UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (start < (query.size.toUInt32))) && ((query.getD start.toNat (0 : UInt8)) == (38 : UInt8))) then do
      let start := (start + (1 : UInt32))
      url_query_next.loop1 query start fuel
    else pure start

def url_query_next.loop2 (query : Array UInt8) (end_ : UInt32) (eq : UInt32) (found : Bool) : Nat → Option (UInt32 × UInt32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if ((decide (end_ < (query.size.toUInt32))) && ((query.getD end_.toNat (0 : UInt8)) != (38 : UInt8))) then do
      let (eq, found) ← (if ((!found) && ((query.getD end_.toNat (0 : UInt8)) == (61 : UInt8))) then (do
          let eq := end_
          let found := true
          pure (eq, found))
        else (do
          pure (eq, found)))
      let end_ := (end_ + (1 : UInt32))
      url_query_next.loop2 query end_ eq found fuel
    else pure (end_, eq, found)

def url_query_next (query : Array UInt8) (begin : UInt32) (fuel : Nat) : Option (Option_UrlPair) := do
  let start : UInt32 := begin
  let start ← url_query_next.loop1 query start fuel
  let r1 ← (
    if (decide (start >= (query.size.toUInt32))) then (do
      pure Option_UrlPair.None)
    else (do
      let end_ : UInt32 := start
      let eq : UInt32 := start
      let found : Bool := false
      let (end_, eq, found) ← url_query_next.loop2 query end_ eq found fuel
      let r2 ← (
        if found then (do
          let r3 ← url_range start eq fuel
          pure r3)
        else (do
          let r4 ← url_range start end_ fuel
          pure r4))
      let key : UrlRange := r2
      let r5 ← (
        if found then (do
          let r6 ← url_range (eq + (1 : UInt32)) end_ fuel
          pure r6)
        else (do
          let r7 ← url_absent  fuel
          pure r7))
      let value : UrlRange := r5
      pure (Option_UrlPair.Some ({ key := key, value := value, next := end_ } : UrlPair))))
  pure r1

def url_pair_or (item : Option_UrlPair) (fallback : UrlPair) (fuel : Nat) : Option (UrlPair) := do
  pure (match item with | (.Some pair) => pair | .None => fallback)

def url_pair_present (item : Option_UrlPair) (fuel : Nat) : Option (Bool) := do
  pure (match item with | (.Some pair) => true | .None => false)

end Oak.Stdlib.Url
