-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.Stdlib.Varint

inductive VarintError where
  | Truncated
  | Overlong
  | DestinationTooSmall
  deriving Repr, Inhabited, BEq, DecidableEq

structure VarintValue where
  value : UInt64
  next : UInt32
  deriving Repr, Inhabited, BEq, DecidableEq

structure VarintSigned where
  value : Int64
  next : UInt32
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_VarintSigned_VarintError where
  | Ok (payload : VarintSigned)
  | Err (payload : VarintError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_VarintValue_VarintError where
  | Ok (payload : VarintValue)
  | Err (payload : VarintError)
  deriving Repr, Inhabited, BEq, DecidableEq

inductive Result_u32_VarintError where
  | Ok (payload : UInt32)
  | Err (payload : VarintError)
  deriving Repr, Inhabited, BEq, DecidableEq

def varint_size.loop1 (n : UInt32) (rest : UInt64) : Nat → Option (UInt32 × UInt64)
  | 0 => none
  | fuel + 1 => do
    if (rest != (0 : UInt64)) then do
      let n := (n + (1 : UInt32))
      let rest := (rest >>> (7 : UInt64))
      varint_size.loop1 n rest fuel
    else pure (n, rest)

def varint_size (value : UInt64) (fuel : Nat) : Option (UInt32) := do
  let n : UInt32 := (1 : UInt32)
  let rest : UInt64 := (value >>> (7 : UInt64))
  let (n, rest) ← varint_size.loop1 n rest fuel
  pure n

def bytes_range_fits (length : UInt32) (offset : UInt32) (width : UInt32) (fuel : Nat) : Option (Bool) := do
  pure (if (decide (offset > length)) then false else (decide (width <= (length - offset))))

def varint_encode.loop1 (dst : Array UInt8) (offset : UInt32) (n : UInt32) (rest : UInt64) (i : UInt32) : Nat → Option (Array UInt8 × UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < n)) then do
      let unit : UInt8 := ((rest &&& (127 : UInt64)).toUInt8)
      let rest := (rest >>> (7 : UInt64))
      let dst := dst.setIfInBounds (offset + i).toNat (if (rest != (0 : UInt64)) then (unit ||| (128 : UInt8)) else unit)
      let i := (i + (1 : UInt32))
      varint_encode.loop1 dst offset n rest i fuel
    else pure (dst, rest, i)

def varint_encode (dst : Array UInt8) (offset : UInt32) (value : UInt64) (fuel : Nat) : Option (Result_u32_VarintError × Array UInt8) := do
  let r1 ← varint_size value fuel
  let n : UInt32 := r1
  let r2 ← bytes_range_fits (dst.size.toUInt32) offset n fuel
  let (r3, dst) ← (
    if (!r2) then (do
      pure ((Result_u32_VarintError.Err VarintError.DestinationTooSmall), dst))
    else (do
      let rest : UInt64 := value
      let i : UInt32 := (0 : UInt32)
      let (dst, rest, i) ← varint_encode.loop1 dst offset n rest i fuel
      pure ((Result_u32_VarintError.Ok n), dst)))
  pure (r3, dst)

def varint_decode.loop1 (src : Array UInt8) (value : UInt64) (shift : UInt32) (at_ : UInt32) (done : Bool) (failed : Bool) (overlong : Bool) : Nat → Option (UInt64 × UInt32 × UInt32 × Bool × Bool × Bool)
  | 0 => none
  | fuel + 1 => do
    if ((!done) && (!failed)) then do
      let (value, shift, at_, done, failed, overlong) ← (if (decide (at_ >= (src.size.toUInt32))) then (do
          let failed := true
          pure (value, shift, at_, done, failed, overlong))
        else (do
          let (value, shift, at_, done, failed, overlong) ← (if (decide (shift >= (70 : UInt32))) then (do
              let failed := true
              let overlong := true
              pure (value, shift, at_, done, failed, overlong))
            else (do
              let lead : UInt32 := ((src.getD at_.toNat (0 : UInt8)).toUInt32)
              let (value, shift, at_, done, failed, overlong) ← (if ((shift == (63 : UInt32)) && (decide ((lead &&& (127 : UInt32)) > (1 : UInt32)))) then (do
                  let failed := true
                  let overlong := true
                  pure (value, shift, at_, done, failed, overlong))
                else (do
                  let value := (value ||| (((lead &&& (127 : UInt32)).toUInt64) <<< (shift.toUInt64)))
                  let at_ := (at_ + (1 : UInt32))
                  let shift := (shift + (7 : UInt32))
                  let done ← (if ((lead &&& (128 : UInt32)) == (0 : UInt32)) then (do
                      let done := true
                      pure done)
                    else (do
                      pure done))
                  pure (value, shift, at_, done, failed, overlong)))
              pure (value, shift, at_, done, failed, overlong)))
          pure (value, shift, at_, done, failed, overlong)))
      varint_decode.loop1 src value shift at_ done failed overlong fuel
    else pure (value, shift, at_, done, failed, overlong)

def varint_decode (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_VarintValue_VarintError) := do
  let value : UInt64 := (0 : UInt64)
  let shift : UInt32 := (0 : UInt32)
  let at_ : UInt32 := offset
  let done : Bool := false
  let failed : Bool := false
  let overlong : Bool := false
  let (value, shift, at_, done, failed, overlong) ← varint_decode.loop1 src value shift at_ done failed overlong fuel
  pure (if failed then (if overlong then (Result_VarintValue_VarintError.Err VarintError.Overlong) else (Result_VarintValue_VarintError.Err VarintError.Truncated)) else (Result_VarintValue_VarintError.Ok ({ value := value, next := at_ } : VarintValue)))

def zigzag_encode (value : Int64) (fuel : Nat) : Option (UInt64) := do
  let sign : UInt64 := (if (decide (value < (0 : Int64))) then (18446744073709551615 : UInt64) else (0 : UInt64))
  pure (((value.toUInt64) <<< (1 : UInt64)) ^^^ sign)

def zigzag_decode (value : UInt64) (fuel : Nat) : Option (Int64) := do
  pure (((value >>> (1 : UInt64)) ^^^ ((0 : UInt64) - (value &&& (1 : UInt64)))).toInt64)

def varint_encode_signed (dst : Array UInt8) (offset : UInt32) (value : Int64) (fuel : Nat) : Option (Result_u32_VarintError × Array UInt8) := do
  let r1 ← zigzag_encode value fuel
  let (r2, dst) ← varint_encode dst offset r1 fuel
  pure (r2, dst)

def varint_decode_signed (src : Array UInt8) (offset : UInt32) (fuel : Nat) : Option (Result_VarintSigned_VarintError) := do
  let r1 ← varint_decode src offset fuel
  let r2 ← (match r1 with
    | (.Err reason) => (do
      pure (Result_VarintSigned_VarintError.Err reason))
    | (.Ok item) => (do
      let r3 ← zigzag_decode item.value fuel
      pure (Result_VarintSigned_VarintError.Ok ({ value := r3, next := item.next } : VarintSigned))))
  pure r2

def varint_ok (result : Result_VarintValue_VarintError) (fuel : Nat) : Option (Bool) := do
  pure (match result with | (.Ok v) => true | (.Err e) => false)

def varint_value (result : Result_VarintValue_VarintError) (fuel : Nat) : Option (VarintValue) := do
  pure (match result with | (.Ok v) => v | (.Err e) => ({ value := (0 : UInt64), next := (0 : UInt32) } : VarintValue))

def varint_written (result : Result_u32_VarintError) (fuel : Nat) : Option (UInt32) := do
  pure (match result with | (.Ok n) => n | (.Err e) => (0 : UInt32))

def varint_signed_ok (result : Result_VarintSigned_VarintError) (fuel : Nat) : Option (Bool) := do
  pure (match result with | (.Ok v) => true | (.Err e) => false)

def varint_signed_value (result : Result_VarintSigned_VarintError) (fuel : Nat) : Option (VarintSigned) := do
  pure (match result with | (.Ok v) => v | (.Err e) => ({ value := (0 : Int64), next := (0 : UInt32) } : VarintSigned))

end Oak.Stdlib.Varint
