import Out
import Oak.ArmASL
import Oak.AArch64Encoding
import Oak.AArch64Barrier
import Oak.AArch64ColdEntry
import Oak.AArch64Stage2Maintenance
import Oak.AArch64WeakMemory
import Oak.NeonSemantics

/-!
# The Sail bridge: Sail-generated Lean ≡ `Oak.ArmASL`

`docs/spec/94-assembler.md` §8, grounding stage 3. `Out.lean` is what Sail's
Lean backend generates from `spec/sail/arm_primitives.sail`, Arm's own
pseudocode for the primitives the assembler's semantics rest on. This file
proves the hand transliteration `Oak.ArmASL` equal to that generated code,
closing the chain Arm's ASL → Sail → Lean (mechanical) ≡ `Oak.ArmASL` ≡
`Oak.AssemblerSemantics` (proved) ≡ the Go executor (checked on the
silicon).
-/

namespace Oak.SailBridge

open Oak.AssemblerSemantics
open Oak.ArmASL

namespace A64Encoding

open Oak.AArch64Encoding

/-- Translate the enums generated by Sail to the names used by Oak's encoding
specification.  These functions change only the constructors' namespaces. -/
def barrierOp : _root_.MemBarrierOp -> Oak.AArch64Encoding.MemBarrierOp
  | .MemBarrierOp_DSB => .dsb
  | .MemBarrierOp_DMB => .dmb
  | .MemBarrierOp_ISB => .isb
  | .MemBarrierOp_SSBB => .ssbb
  | .MemBarrierOp_PSSBB => .pssbb
  | .MemBarrierOp_SB => .sb

def barrierDomain : _root_.MBReqDomain -> Oak.AArch64Encoding.MBReqDomain
  | .MBReqDomain_Nonshareable => .nonshareable
  | .MBReqDomain_InnerShareable => .innerShareable
  | .MBReqDomain_OuterShareable => .outerShareable
  | .MBReqDomain_FullSystem => .fullSystem

def barrierTypes : _root_.MBReqTypes -> Oak.AArch64Encoding.MBReqTypes
  | .MBReqTypes_Reads => .reads
  | .MBReqTypes_Writes => .writes
  | .MBReqTypes_All => .all

def barrierDecode
    (result : Bool × _root_.MemBarrierOp × _root_.MBReqDomain × _root_.MBReqTypes) :
    BarrierDecode :=
  ⟨result.1, barrierOp result.2.1, barrierDomain result.2.2.1,
    barrierTypes result.2.2.2⟩

/-! Each theorem below evaluates the word through Lean generated mechanically
by Sail from Arm's three exact `decode64` clauses and
`system_barriers_decode`.  They therefore prove both instruction-class
selection and the decoded option's operation, domain, and access types. -/

theorem dmb_ishld_decoder :
    barrierDecode (Out.Functions.decode64_barrier_pure dmbIshld) =
      dmbIshldDecode := by
  native_decide

theorem dmb_ish_decoder :
    barrierDecode (Out.Functions.decode64_barrier_pure dmbIsh) =
      dmbIshDecode := by
  native_decide

theorem dmb_sy_decoder :
    barrierDecode (Out.Functions.decode64_barrier_pure dmbSy) =
      dmbSyDecode := by
  native_decide

theorem dsb_ish_decoder :
    barrierDecode (Out.Functions.decode64_barrier_pure dsbIsh) =
      dsbIshDecode := by
  native_decide

theorem dsb_sy_decoder :
    barrierDecode (Out.Functions.decode64_barrier_pure dsbSy) =
      dsbSyDecode := by
  native_decide

theorem isb_decoder :
    barrierDecode (Out.Functions.decode64_barrier_pure isbSy) =
      isbDecode := by
  native_decide

/-! Arm's pinned `system_barriers` dispatch routes the decoded operation to a
named execution primitive.  This is stronger than decoder identity, but the
pinned primitive itself is a unit-returning stub, so the external context-sync
predicate remains an independent obligation. -/

def decodedBarrierTarget (word : BitVec 32) : Option _root_.BarrierExecutionTarget :=
  let result := Out.Functions.decode64_barrier_pure word
  match result.1 with
  | false => none
  | true => some (Out.Functions.system_barriers_target_pure
      result.2.2.1 result.2.1 result.2.2.2)

theorem isb_decoder_execution_target :
    decodedBarrierTarget isbSy = some
      .BarrierExecutionTarget_InstructionSynchronizationBarrier := by
  rfl

theorem dsb_ish_decoder_execution_target :
    decodedBarrierTarget dsbIsh = some
      .BarrierExecutionTarget_DataSynchronizationBarrier := by
  rfl

theorem invalid_barrier_has_no_execution_target :
    decodedBarrierTarget 0#32 = none := by
  rfl

open Oak.AArch64ColdEntry

/-- The exact occurrence is an ISB and Arm's generated dispatch selects its
    named instruction-synchronization primitive. -/
def SailISBDispatch {Occurrence : Type} (trace : Trace Occurrence)
    (event : Occurrence) : Prop :=
  trace.action event = .barrier isbSy ∧
    decodedBarrierTarget isbSy = some
      .BarrierExecutionTarget_InstructionSynchronizationBarrier

/-- Refine, rather than replace, the external architectural proposition with
    the generated Sail dispatch fact. -/
def sailRefinedContextSync {Occurrence : Type}
    (external : ArmContextSync Occurrence) : ArmContextSync Occurrence :=
  fun trace event => SailISBDispatch trace event ∧ external trace event

/-- Existing architectural evidence can be decorated with the generated Sail
    call-target proof without changing any occurrence or ordering witness. -/
def refineContextSyncWitnessWithSailDispatch
    {Occurrence : Type} {trace : Trace Occurrence}
    {external : ArmContextSync Occurrence}
    (sync : ContextSyncWitness trace external) :
    ContextSyncWitness trace (sailRefinedContextSync external) := {
  writeOccurrence := sync.writeOccurrence
  isbOccurrence := sync.isbOccurrence
  writesAreExact := sync.writesAreExact
  writesBeforeIsb := sync.writesBeforeIsb
  isbIsExact := sync.isbIsExact
  architecturalSync :=
    ⟨⟨sync.isbIsExact, isb_decoder_execution_target⟩, sync.architecturalSync⟩
}

/-- The refined proposition cannot manufacture architectural context sync. -/
theorem sail_refined_context_sync_requires_external
    {Occurrence : Type} {trace : Trace Occurrence} {event : Occurrence}
    {external : ArmContextSync Occurrence}
    (h : sailRefinedContextSync external trace event) :
    external trace event := h.2

/-! Refinement from the generated decoder tuples into Oak's deliberately
narrow barrier capability model.  `ofDecode` is fail-closed, so these facts
also certify that all four decoded fields match one of Oak's six admitted
source operations. -/

open Oak.AArch64Barrier

theorem dmb_ishld_barrier :
    ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dmbIshld)) =
      some .dmbIshld := by
  rw [dmb_ishld_decoder]
  rfl

theorem dmb_ish_barrier :
    ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dmbIsh)) =
      some .dmbIsh := by
  rw [dmb_ish_decoder]
  rfl

theorem dmb_sy_barrier :
    ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dmbSy)) =
      some .dmbSy := by
  rw [dmb_sy_decoder]
  rfl

theorem dsb_ish_barrier :
    ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dsbIsh)) =
      some .dsbIsh := by
  rw [dsb_ish_decoder]
  rfl

theorem dsb_sy_barrier :
    ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dsbSy)) =
      some .dsbSy := by
  rw [dsb_sy_decoder]
  rfl

theorem isb_barrier :
    ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure isbSy)) =
      some .isb := by
  rw [isb_decoder]
  rfl

theorem dsb_ish_decoder_oak_completion_capability :
    ∃ barrier,
      ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dsbIsh)) =
        some barrier ∧
      (capability barrier).completion = true := by
  exact ⟨.dsbIsh, dsb_ish_barrier, rfl⟩

theorem dsb_sy_decoder_oak_completion_capability :
    ∃ barrier,
      ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure dsbSy)) =
        some barrier ∧
      (capability barrier).completion = true := by
  exact ⟨.dsbSy, dsb_sy_barrier, rfl⟩

theorem isb_decoder_oak_instruction_sync_capability :
    ∃ barrier,
      ofDecode (barrierDecode (Out.Functions.decode64_barrier_pure isbSy)) =
        some barrier ∧
      (capability barrier).instructionSync = true := by
  exact ⟨.isb, isb_barrier, rfl⟩

/-! The decoded DMB tuple is now the index of the assumed barrier occurrence,
not an untyped "full fence" fact.  These theorems turn that occurrence into
the exact scalar `bob` edge admitted by the pinned Arm CAT projection. -/

open Oak.AArch64WeakMemory

theorem dmb_ishld_decoder_orders {Event : Type}
    (x : BaseExecution Event) (before after : Event)
    (hLoad : (x.op before).IsReturningLoad)
    (hBetween : x.barrierBetween
      (barrierDecode (Out.Functions.decode64_barrier_pure dmbIshld)) before after) :
    OrderedBefore x before after := by
  apply OrderedBefore.bobDmb _ _ _ ?_ hBetween
  rw [dmb_ishld_decoder]
  exact dmb_ishld_decode_orders_before _ |>.2 hLoad

theorem dmb_ish_decoder_orders {Event : Type}
    (x : BaseExecution Event) (before after : Event)
    (hBetween : x.barrierBetween
      (barrierDecode (Out.Functions.decode64_barrier_pure dmbIsh)) before after) :
    OrderedBefore x before after := by
  apply OrderedBefore.bobDmb _ _ _ ?_ hBetween
  rw [dmb_ish_decoder]
  simp

theorem dmb_sy_decoder_orders {Event : Type}
    (x : BaseExecution Event) (before after : Event)
    (hBetween : x.barrierBetween
      (barrierDecode (Out.Functions.decode64_barrier_pure dmbSy)) before after) :
    OrderedBefore x before after := by
  apply OrderedBefore.bobDmb _ _ _ ?_ hBetween
  rw [dmb_sy_decoder]
  simp

theorem dsb_ish_decoder_orders {Event : Type}
    (x : BaseExecution Event) (before after : Event)
    (hBetween : x.barrierBetween
      (barrierDecode (Out.Functions.decode64_barrier_pure dsbIsh)) before after) :
    OrderedBefore x before after := by
  apply OrderedBefore.dsbFull _ _ _ ?_ hBetween
  rw [dsb_ish_decoder]
  simp

theorem dsb_sy_decoder_orders {Event : Type}
    (x : BaseExecution Event) (before after : Event)
    (hBetween : x.barrierBetween
      (barrierDecode (Out.Functions.decode64_barrier_pure dsbSy)) before after) :
    OrderedBefore x before after := by
  apply OrderedBefore.dsbFull _ _ _ ?_ hBetween
  rw [dsb_sy_decoder]
  simp

theorem dsb_ish_decoder_not_dmb_ordering (beforeIsLoad : Prop) :
    ¬ decodeDataOrdersBefore
      (barrierDecode (Out.Functions.decode64_barrier_pure dsbIsh)) beforeIsLoad := by
  rw [dsb_ish_decoder]
  simp

theorem dsb_sy_decoder_not_dmb_ordering (beforeIsLoad : Prop) :
    ¬ decodeDataOrdersBefore
      (barrierDecode (Out.Functions.decode64_barrier_pure dsbSy)) beforeIsLoad := by
  rw [dsb_sy_decoder]
  simp

theorem isb_decoder_not_dmb_ordering (beforeIsLoad : Prop) :
    ¬ decodeDataOrdersBefore
      (barrierDecode (Out.Functions.decode64_barrier_pure isbSy)) beforeIsLoad := by
  rw [isb_decoder]
  simp

theorem isb_decoder_not_dsb_ordering :
    ¬ decodeDsbOrdersBefore
      (barrierDecode (Out.Functions.decode64_barrier_pure isbSy)) := by
  rw [isb_decoder]
  simp

/-! The pinned generic SYS-write dispatch for Oak's first stage-2 TLBI target.
This proves only exact word-to-call-target classification. Access admission,
trap behavior, invalidation effects, broadcast scope, and completion remain
outside the pure Sail projection. -/

def decodedTLBITarget (word : BitVec 32) : Option _root_.TLBIOperationTarget :=
  let result := Out.Functions.decode64_tlbi_target_pure word
  match result.1 with
  | false => none
  | true => some result.2

theorem tlbi_vmalls12e1is_decoder_execution_target :
    decodedTLBITarget tlbiVmalls12e1is =
      some .TLBIOperationTarget_VMALLS12E1IS := by
  rfl

theorem invalid_tlbi_has_no_execution_target :
    decodedTLBITarget 0#32 = none := by
  rfl

theorem plain_vmalls12e1_not_projected_to_vmalls12e1is :
    decodedTLBITarget 0xd50c87df#32 = none := by
  rfl

open Oak.AArch64Stage2Maintenance

/-- Decorate an externally supplied occurrence/action refinement with the
    generated Sail call-target fact. The conjunction cannot manufacture the
    architectural action, target, scope, or effects from the word. -/
def SailVmalls12e1isOccurrence {Occurrence Target : Type}
    (code : InstructionTrace Occurrence) (trace : Trace Occurrence Target)
    (event : Occurrence) (target : Target) : Prop :=
  Vmalls12e1isOccurrence code trace event target ∧
    decodedTLBITarget tlbiVmalls12e1is =
      some .TLBIOperationTarget_VMALLS12E1IS

/-- Add generated Sail dispatch identity without replacing the external
    instruction-to-execution occurrence witness. -/
theorem refineVmalls12e1isOccurrenceWithSailDispatch
    {Occurrence Target : Type} {code : InstructionTrace Occurrence}
    {trace : Trace Occurrence Target} {event : Occurrence} {target : Target}
    (occurrence : Vmalls12e1isOccurrence code trace event target) :
    SailVmalls12e1isOccurrence code trace event target :=
  ⟨occurrence, tlbi_vmalls12e1is_decoder_execution_target⟩

/-- Generated dispatch identity cannot bypass the external occurrence/action
    refinement premise. -/
theorem sail_vmalls12e1is_occurrence_requires_external
    {Occurrence Target : Type} {code : InstructionTrace Occurrence}
    {trace : Trace Occurrence Target} {event : Occurrence} {target : Target}
    (occurrence : SailVmalls12e1isOccurrence code trace event target) :
    Vmalls12e1isOccurrence code trace event target :=
  occurrence.1

/-- Generated decoder and named call-target facts decorating the externally
    supplied exact four-instruction occurrence sequence. No execution effects
    are projected from these constant facts. -/
def SailVmalls12e1isDsbIsbInstructionSequence
    {Occurrence Target : Type}
    (code : InstructionTrace Occurrence) (trace : Trace Occurrence Target)
    (target : Target)
    (preTlbiDsb tlbiEvent postTlbiDsb isbEvent : Occurrence) : Prop :=
  Vmalls12e1isDsbIsbInstructionSequence code trace target preTlbiDsb
      tlbiEvent postTlbiDsb isbEvent ∧
    barrierDecode (Out.Functions.decode64_barrier_pure dsbIsh) = dsbIshDecode ∧
    decodedBarrierTarget dsbIsh =
      some .BarrierExecutionTarget_DataSynchronizationBarrier ∧
    decodedTLBITarget tlbiVmalls12e1is =
      some .TLBIOperationTarget_VMALLS12E1IS ∧
    barrierDecode (Out.Functions.decode64_barrier_pure isbSy) = isbDecode ∧
    decodedBarrierTarget isbSy =
      some .BarrierExecutionTarget_InstructionSynchronizationBarrier

theorem refineVmalls12e1isDsbIsbSequenceWithSailDispatch
    {Occurrence Target : Type}
    {code : InstructionTrace Occurrence} {trace : Trace Occurrence Target}
    {target : Target}
    {preTlbiDsb tlbiEvent postTlbiDsb isbEvent : Occurrence}
    (sequence : Vmalls12e1isDsbIsbInstructionSequence code trace target
      preTlbiDsb tlbiEvent postTlbiDsb isbEvent) :
    SailVmalls12e1isDsbIsbInstructionSequence code trace target preTlbiDsb
      tlbiEvent postTlbiDsb isbEvent :=
  ⟨sequence, dsb_ish_decoder, dsb_ish_decoder_execution_target,
    tlbi_vmalls12e1is_decoder_execution_target, isb_decoder,
    isb_decoder_execution_target⟩

theorem sail_vmalls12e1is_dsb_isb_sequence_requires_external
    {Occurrence Target : Type}
    {code : InstructionTrace Occurrence} {trace : Trace Occurrence Target}
    {target : Target}
    {preTlbiDsb tlbiEvent postTlbiDsb isbEvent : Occurrence}
    (sequence : SailVmalls12e1isDsbIsbInstructionSequence code trace target
      preTlbiDsb tlbiEvent postTlbiDsb isbEvent) :
    Vmalls12e1isDsbIsbInstructionSequence code trace target preTlbiDsb
      tlbiEvent postTlbiDsb isbEvent :=
  sequence.1

end A64Encoding

/-- Our flags record as Arm's `nzcv` bit-vector: N is the top bit. -/
def Flags.toBits (f : Flags) : BitVec 4 :=
  ((BitVec.ofBool f.n ++ BitVec.ofBool f.z) ++ BitVec.ofBool f.c) ++ BitVec.ofBool f.v

/-- Arm's `nzcv` bit-vector as our flags record. -/
def Flags.ofBits (b : BitVec 4) : Flags :=
  { n := b.getLsbD 3, z := b.getLsbD 2, c := b.getLsbD 1, v := b.getLsbD 0 }

theorem Flags.toBits_ofBits (b : BitVec 4) : Flags.toBits (Flags.ofBits b) = b := by
  revert b; decide

theorem Flags.ofBits_toBits (f : Flags) : Flags.ofBits (Flags.toBits f) = f := by
  obtain ⟨n, z, c, v⟩ := f
  cases n <;> cases z <;> cases c <;> cases v <;> rfl

/-- **`ConditionHolds`**: the generated function on the flag bits is ours on
    the flags record, for every condition code and flag pattern. -/
theorem ConditionHolds_bridge (cond nzcv : BitVec 4) :
    Out.Functions.ConditionHolds cond nzcv = Oak.ArmASL.ConditionHolds cond (Flags.ofBits nzcv) := by
  revert cond nzcv; decide

/-- `get_slice_int` of a natural number at offset 0 is `BitVec.ofNat`. -/
theorem get_slice_int_natCast (w m : Nat) :
    Sail.get_slice_int w (m : Int) 0 = BitVec.ofNat w m := by
  apply BitVec.eq_of_toNat_eq
  simp only [Sail.get_slice_int, BitVec.extractLsb'_toNat, BitVec.ofInt_natCast, BitVec.toNat_ofNat, Nat.shiftRight_zero]
  rw [Nat.mod_mod_of_dvd]
  exact Nat.pow_dvd_pow 2 (by omega)

/-- `join1` of one bit is that bit. -/
theorem join1_single (v : BitVec 1) : Sail.BitVec.join1 [v] = v := by
  revert v; decide

/-- Arm's `x[N-1]` read through `access` is the sign bit. -/
theorem access_last {w : Nat} (hw : 0 < w) (x : BitVec w) :
    Sail.BitVec.access x (w - 1) = BitVec.ofBool x.msb := by
  have h : w - 1 < w := by omega
  simp only [Sail.BitVec.access, BitVec.msb_eq_getLsbD_last]
  congr 1
  first
    | rw [getElem!_pos x (w - 1) h, BitVec.getLsbD_eq_getElem h]
    | simp [getElem!_def, getElem?_pos, h, BitVec.getLsbD_eq_getElem h]
    | simp [getElem!, decidableGetElem?, h, BitVec.getLsbD_eq_getElem h]

theorem ite_beq_zero_one {α : Type} [DecidableEq α] (a b : α) :
    (if (a == b) = true then (0#1 : BitVec 1) else 1#1) = BitVec.ofBool (decide (a ≠ b)) := by
  by_cases h : a = b <;> simp [h]

theorem ite_beq_one_zero {α : Type} [DecidableEq α] (a b : α) :
    (if (a == b) = true then (1#1 : BitVec 1) else 0#1) = BitVec.ofBool (decide (a = b)) := by
  by_cases h : a = b <;> simp [h]

/-- **`AddWithCarry`**: the generated function is ours, result and flags. -/
theorem AddWithCarry_bridge {w : Nat} (hw : 0 < w) (x y : BitVec w) (b : Bool) :
    Out.Functions.AddWithCarry x y (BitVec.ofBool b) =
      ((Oak.ArmASL.AddWithCarry x y b).1, Flags.toBits (Oak.ArmASL.AddWithCarry x y b).2) := by
  have hw1 : ((w : Int) - 1).toNat = w - 1 := by omega
  have key : Sail.get_slice_int w ((x.toNat : Int) + y.toNat + b.toNat) 0 = BitVec.ofNat w (x.toNat + y.toNat + b.toNat) := by
    rw [← get_slice_int_natCast]; simp
  simp only [Out.Functions.AddWithCarry, Out.Functions.UInt, Out.Functions.SInt, Out.Functions.__GetSlice_int,
    Out.Functions.IsZero, Out.Functions.Zeros, Sail.BitVec.toNatInt, Sail.BitVec.length,
    Int.ofNat_eq_natCast]
  rw [join1_single]
  simp only [Int.toNat_zero, hw1, BitVec.toNat_ofBool]
  rw [key, access_last hw, ite_beq_one_zero, ite_beq_zero_one, ite_beq_zero_one]
  simp only [Oak.ArmASL.AddWithCarry, Flags.toBits, BitVec.ofNat_eq_ofNat, ← Int.natCast_add, ne_eq, Int.natCast_inj]
  first
    | rfl
    | simp only [BitVec.zero_eq]
    | simp [BitVec.zero_eq]

/-- **Conditional select**: the generated function is ours. -/
theorem conditionalSelect_bridge {w : Nat} (cond nzcv : BitVec 4) (inc inv : Bool) (a b : BitVec w) :
    Out.Functions.integer_conditional_select cond nzcv inc inv a b =
      conditionalSelect cond (Flags.ofBits nzcv) inc inv a b := by
  simp only [Out.Functions.integer_conditional_select, conditionalSelect, ConditionHolds_bridge]
  split
  · rfl
  · simp [Sail.BitVec.addInt]

/-- **Conditional compare**: the generated function is ours, as flag bits. -/
theorem conditionalCompare_bridge {w : Nat} (hw : 0 < w) (cond nzcv flags : BitVec 4) (l r : BitVec w) (sub : Bool) :
    Out.Functions.integer_conditional_compare_register cond nzcv flags l r sub =
      Flags.toBits (conditionalCompare cond (Flags.ofBits nzcv) l r (Flags.ofBits flags) sub) := by
  simp only [Out.Functions.integer_conditional_compare_register, conditionalCompare, ConditionHolds_bridge]
  split
  · cases sub
    · simpa using congrArg Prod.snd (AddWithCarry_bridge hw l r false)
    · simpa using congrArg Prod.snd (AddWithCarry_bridge hw l (~~~r) true)
  · simp [Flags.toBits_ofBits]

end Oak.SailBridge

namespace Oak.SailBridge

/-- `access` at any index is the bit (false beyond the width, as `getLsbD`). -/
theorem access_eq {w : Nat} (x : BitVec w) (n : Nat) :
    Sail.BitVec.access x n = BitVec.ofBool (x.getLsbD n) := by
  by_cases h : n < w
  · simp only [Sail.BitVec.access]
    congr 1
    rw [getElem!_pos x n h, BitVec.getLsbD_eq_getElem h]
  · simp only [Sail.BitVec.access]
    congr 1
    rw [getElem!_neg x n h, BitVec.getLsbD_of_ge x n (by omega)]
    rfl

/-- The range Arm's `foreach (i from 'N - 1 to 0 by 1 in dec)` becomes,
    with the start (`'N - 1`) as a parameter. -/
abbrev hsbRange (s : Int) : IntRange := { start := s, stop := 0, step := -1 }

theorem mem_hsbRange (s i : Int) : i ∈ hsbRange s ↔ 0 ≤ i ∧ i ≤ s := by
  simp only [Membership.mem]
  constructor
  · rintro ⟨h, -⟩
    simpa using h
  · intro h
    refine ⟨by simpa using h, ?_⟩
    simp [Int.emod_neg]

/-- The loop body Sail generated, verbatim. -/
abbrev hsbBody {w : Nat} (x : BitVec w) (s : Int) : (i : Int) → i ∈ hsbRange s → Unit → ExceptT Int Id (ForInStep Unit) :=
  fun a _ _ =>
    if (Sail.BitVec.join1 [Sail.BitVec.access x a.toNat] == 1#1) = true then do
      let v ← throw a
      pure (ForInStep.yield v)
    else pure (ForInStep.yield ())

/-- Running the generated loop from bit `n` finds the highest set bit at or
    below `n`, as our list search does. -/
theorem hsb_loop_spec {w : Nat} (x : BitVec w) (s : Int) (n : Nat) (hn : (n : Int) ≤ s)
    (hs : ((n : Int) - (hsbRange s).start) % (hsbRange s).step = 0) :
    (IntRange.forIn'.loop (hsbRange s) (hsbBody x s) () (n : Int) hs).run =
      match (List.range (n + 1)).reverse.find? (fun j => x.getLsbD j) with
      | some j => Except.error (j : Int)
      | none => Except.ok () := by
  induction n with
  | zero =>
    unfold IntRange.forIn'.loop
    rw [dif_pos ((mem_hsbRange _ _).2 ⟨by omega, by omega⟩)]
    simp only [hsbBody, access_eq, join1_single, Int.toNat_natCast,
      List.range_succ, List.range_zero, List.nil_append, List.reverse_cons, List.reverse_nil, List.find?_cons, List.find?_nil]
    cases hx : x.getLsbD 0
    · split
      · rename_i h; simp only [beq_iff_eq] at h
        first
          | exact absurd h (by simp)
          | exact absurd (congrArg BitVec.toNat h) (by simp)
      simp only [pure_bind]
      unfold IntRange.forIn'.loop
      rw [dif_neg (by rw [mem_hsbRange]; omega)]
      simp [ExceptT.run_pure]
      rfl
    · split
      · simp [ExceptT.run_throw]
        try rfl
      · rename_i h; simp only [beq_iff_eq] at h; exact (h rfl).elim
  | succ m ih =>
    unfold IntRange.forIn'.loop
    rw [dif_pos ((mem_hsbRange _ _).2 ⟨by omega, by omega⟩)]
    have hstep : ((m + 1 : Nat) : Int) + -1 = (m : Int) := by omega
    have hrange : (List.range (m + 1 + 1)).reverse = (m + 1) :: (List.range (m + 1)).reverse := by
      simp [List.range_succ]
    simp only [hsbBody, access_eq, join1_single, Int.toNat_natCast]
    rw [hrange, List.find?_cons]
    cases hx : x.getLsbD (m + 1)
    · split
      · rename_i h; simp only [beq_iff_eq] at h
        first
          | exact absurd h (by simp)
          | exact absurd (congrArg BitVec.toNat h) (by simp)
      simp only [pure_bind]
      simp only [hstep]
      rw [ih (by omega)]
    · split
      · simp [ExceptT.run_throw]
        try rfl
      · rename_i h; simp only [beq_iff_eq] at h; exact (h rfl).elim

/-- The loop specification with the start index as an arbitrary integer. -/
theorem hsb_loop_spec' {w : Nat} (x : BitVec w) (s i : Int) (n : Nat) (hi : i = n) (hn : (n : Int) ≤ s)
    (hs : (i - (hsbRange s).start) % (hsbRange s).step = 0) :
    (IntRange.forIn'.loop (hsbRange s) (hsbBody x s) () i hs).run =
      match (List.range (n + 1)).reverse.find? (fun j => x.getLsbD j) with
      | some j => Except.error (j : Int)
      | none => Except.ok () := by
  subst hi
  exact hsb_loop_spec x s n hn hs

/-- **`HighestSetBit`**: the generated early-return loop is our list search,
    at every width. -/
theorem HighestSetBit_bridge {w : Nat} (x : BitVec w) :
    Out.Functions.HighestSetBit x = Oak.ArmASL.HighestSetBit x := by
  simp only [Out.Functions.HighestSetBit, Sail.BitVec.length, forIn, forIn', IntRange.forIn',
    ExceptM.run, Oak.ArmASL.HighestSetBit]
  cases w with
  | zero =>
    unfold IntRange.forIn'.loop
    rw [dif_neg (by rw [mem_hsbRange]; omega)]
    simp [ExceptT.run_pure]
    try rfl
  | succ k =>
    rw [ExceptT.run_bind, hsb_loop_spec' x (((k + 1 : Nat) : Int) - 1) (((k + 1 : Nat) : Int) - 1) k (by omega) (by omega)]
    cases hfind : (List.range (k + 1)).reverse.find? (fun j => x.getLsbD j) <;> simp [ExceptT.run_pure] <;> try rfl

/-- **`CountLeadingZeroBits`** follows. -/
theorem CountLeadingZeroBits_bridge {w : Nat} (x : BitVec w) :
    Out.Functions.CountLeadingZeroBits x = Oak.ArmASL.CountLeadingZeroBits x := by
  simp [Out.Functions.CountLeadingZeroBits, Oak.ArmASL.CountLeadingZeroBits, HighestSetBit_bridge, Sail.BitVec.length]

end Oak.SailBridge

/-! ## The vector file (docs/spec/94-assembler.md §8, the vector increment)

`arm_primitives.sail` carries Arm's text for the Advanced SIMD instructions
the native backend emits, and `Oak.NeonSemantics` states the lane functions
the verifier applies. The theorems below identify the two at the lane
level, against the generated code: the element accessor reads the lane of
the verifier's decomposition, `Ones` is the all-ones lane, `UnsignedSatQ` of
a lane difference is `uqsub`, the equality test is `cmeq`, `ext` is
and the bitwise forms are the Lean operators. The per-lane loops that apply
a lane function across a register (`for e in [0:elements-1]`) are folds
over the lane indices (`forIn_laneRange_fold`), a written lane reads its
write (`aget_foldl_aset`), and so the register-level theorems follow:
`dup`, `add`, `sub`, `cmeq` (register and zero forms), `umin`, `umax`,
`uqsub`, `tbl`, and `umaxv` each compute the verifier's lane function over
the lanes of their operands; `ext` is the byte-lane `ext`, `ushr` the lane
shift, `sshr #7` on bytes the sign fill of `movemask`, and Arm's recursive
`Reduce` (stated by hand, since Sail's backend cannot discharge its
termination) sums eight bytes as the wrapping fold of `addv`, and `cnt` is
the population count of each lane (Arm's `BitCount` as
`Oak.Intrinsics.popcount`). Every vector instruction the native backend
emits is bridged (`docs/notes/proof-chain-audit-2026-09.md`). -/

namespace Oak.SailBridge

open Oak.Neon

/-- Arm's `Ones` is the all-ones vector. -/
theorem Ones_eq_allOnes (n : Nat) : Out.Functions.Ones n = BitVec.allOnes n := by
  apply BitVec.eq_of_getLsbD_eq
  intro i
  simp [Out.Functions.Ones, Sail.BitVec.replicateBits, BitVec.getLsbD_replicate, BitVec.getLsbD_allOnes, Nat.mod_one]

/-- ... and its value the all-ones lane of `Oak.Simd`. -/
theorem Ones_toNat (n : Nat) : (Out.Functions.Ones n).toNat = Oak.Simd.allOnes n := by
  rw [Ones_eq_allOnes, BitVec.toNat_allOnes, Oak.Simd.allOnes]

/-- The lanes of a register as the verifier decomposes it: lane `k` of
`size` bits is the bits from `k * size`. -/
def lanesOf {N : Nat} (v : BitVec N) (size : Nat) : List Nat :=
  (List.range (N / size)).map (fun k => (v.toNat >>> (k * size)) % 2 ^ size)

/-- **`Elem[]`**: the element accessor reads lane `e`. -/
theorem aget_Elem_toNat {N : Nat} (v : BitVec N) (e size : Nat) :
    (Out.Functions.aget_Elem v e size).toNat = (v.toNat >>> (e * size)) % 2 ^ size := by
  simp [Out.Functions.aget_Elem, Sail.BitVec.slice, BitVec.extractLsb'_toNat, ← Int.natCast_mul, Int.toNat_natCast]

/-- **`UnsignedSatQ`** of a lane difference is the verifier's `uqsub`
(`Oak.Neon.uqsub`, which is `Oak.Simd.subSat`): saturating at zero, never
above the lane (the minuend is a lane value). -/
theorem UnsignedSatQ_uqsub (N x y : Nat) (hx : x < 2 ^ N) :
    (Out.Functions.UnsignedSatQ ((x : Int) - y) N).1 = BitVec.ofNat N (uqsub x y) := by
  have hxI : (x : Int) < (2 : Int) ^ N := by
    have := Int.ofNat_lt.mpr hx
    rwa [Int.natCast_pow] at this
  -- The generated `2 ^i N` is the support library's integer power, `2 ^ N.toNat`.
  have hp : (2 : Int) ^ ((N : Nat) : Int) = (2 : Int) ^ N := by
    show (2 : Int) ^ ((N : Int).toNat) = _
    rw [Int.toNat_natCast]
  unfold Out.Functions.UnsignedSatQ Out.Functions.__GetSlice_int
  simp only [Int.toNat_zero]
  split
  · -- above the lane: impossible for a lane difference
    rename_i h
    simp only [decide_eq_true_eq, hp] at h
    omega
  · split
    · -- below zero: saturates to zero, as uqsub does
      rename_i _ h
      simp only [decide_eq_true_eq] at h
      have hlt : ¬ y < x := by omega
      simp only [uqsub, hlt, ↓reduceIte]
      simpa using get_slice_int_natCast N 0
    · -- in range: the difference itself
      rename_i _ h
      simp only [decide_eq_true_eq] at h
      by_cases hlt : y < x
      · have hcast : (x : Int) - y = ((x - y : Nat) : Int) := by omega
        simp only [uqsub, hlt, ↓reduceIte, hcast, get_slice_int_natCast]
      · have hz : (x : Int) - y = 0 := by omega
        simp only [uqsub, hlt, ↓reduceIte, hz]
        simpa using get_slice_int_natCast N 0

/-- **The equality test** of `cmeq` — `Ones` on equal lanes, `Zeros`
otherwise — is the verifier's `cmeq` lane function. -/
theorem cmeq_test_toNat (size : Nat) (a b : BitVec size) :
    (if (a == b) = true then Out.Functions.Ones size else Out.Functions.Zeros size).toNat
      = cmeq size a.toNat b.toNat := by
  by_cases h : a = b
  · simp [h, Ones_toNat, cmeq]
  · have hne : a.toNat ≠ b.toNat := fun heq => h (BitVec.eq_of_toNat_eq heq)
    simp [h, Out.Functions.Zeros, cmeq, hne]

/-- **`and`, `orr`, `eor`**: the bitwise forms are the operators. -/
theorem andorr_and {n : Nat} (a b : BitVec n) :
    Out.Functions.vector_arithmetic_binary_uniform_logical_andorr n false a b .LogicalOp_AND = a &&& b := rfl
theorem andorr_orr {n : Nat} (a b : BitVec n) :
    Out.Functions.vector_arithmetic_binary_uniform_logical_andorr n false a b .LogicalOp_ORR = a ||| b := rfl
theorem andorr_eor {n : Nat} (a b : BitVec n) :
    Out.Functions.vector_arithmetic_binary_uniform_logical_andorr n false a b .LogicalOp_EOR = a ^^^ b := rfl
theorem andorr_bic {n : Nat} (a b : BitVec n) :
    Out.Functions.vector_arithmetic_binary_uniform_logical_andorr n true a b .LogicalOp_AND = a &&& ~~~b := rfl


/-! ## The per-lane loops of the generated code -/

section Lanes
open Out.Functions


/-- The generated loops: `for e in [0:n-1:1]i` in `Id`, each step yielding. -/
def laneRange (n : Nat) : IntRange := { stop := (n : Int) - 1 }

theorem mem_laneRange (n : Nat) (i : Int) : i ∈ laneRange n ↔ 0 ≤ i ∧ i ≤ (n : Int) - 1 := by
  simp only [laneRange, Membership.mem, IntRange.instMemIntRange]
  constructor
  · rintro ⟨h, _⟩
    simpa using h
  · intro h
    refine ⟨by simpa using h, ?_⟩
    simp

theorem loop_fold {β : Type} (n : Nat) (g : Int → β → β) (k : Nat) :
    ∀ (i : Nat) (b : β) (hs : ((i : Int) - (laneRange n).start) % (laneRange n).step = 0), i + k = n →
      IntRange.forIn'.loop (m := Id) (laneRange n) (fun i _ b => pure (ForInStep.yield (g i b))) b i hs
        = (List.range' i k).foldl (fun s j => g (j : Int) s) b := by
  induction k with
  | zero =>
    intro i b hs hi
    rw [IntRange.forIn'.loop.eq_1]
    have hnot : ¬ ((i : Int) ∈ laneRange n) := by
      rw [mem_laneRange]; omega
    simp only [hnot, ↓reduceDIte, List.range'_zero, List.map_nil, List.foldl_nil]
    rfl
  | succ k ih =>
    intro i b hs hi
    rw [IntRange.forIn'.loop.eq_1]
    have hmem : (i : Int) ∈ laneRange n := by
      rw [mem_laneRange]; omega
    simp only [hmem, ↓reduceDIte]
    show IntRange.forIn'.loop (laneRange n) _ (g (↑i) b) ((i : Int) + (laneRange n).step) _ = _
    have hstep : ((i : Int) + (laneRange n).step) = ((i + 1 : Nat) : Int) := by simp [laneRange]
    simp only [List.range'_succ, List.map_cons, List.foldl_cons]
    have := ih (i + 1) (g (↑i) b) (by simp [laneRange]) (by omega)
    simp only [hstep]
    exact this

theorem forIn_laneRange_fold {β : Type} (n : Nat) (init : β) (g : Int → β → β) :
    (forIn (m := Id) (laneRange n) init (fun i s => ForInStep.yield (g i s)))
      = (List.range n).foldl (fun s j => g (j : Int) s) init := by
  show IntRange.forIn' (laneRange n) init (fun i _ s => pure (ForInStep.yield (g i s))) = _
  unfold IntRange.forIn'
  have := loop_fold n g n 0 init (by simp [laneRange]) (by omega)
  simp only [laneRange] at this ⊢
  rw [List.range_eq_range']
  exact this




/-- `aset_Elem` unfolded to the support library's masked update. -/
theorem aset_Elem_eq {N : Nat} (v : BitVec N) (e size : Nat) (x : BitVec size) :
    aset_Elem v e size x = Sail.BitVec.updateSubrange' v (e * size) size x := by
  simp [aset_Elem, __SetSlice_bits, Sail.set_slice, ← Int.natCast_mul, Int.toNat_natCast]

theorem getLsbD_updateSubrange' {N : Nat} (v : BitVec N) (start size : Nat) (x : BitVec size) (i : Nat) :
    (Sail.BitVec.updateSubrange' v start size x).getLsbD i
      = if start ≤ i ∧ i < start + size ∧ i < N then x.getLsbD (i - start) else v.getLsbD i := by
  simp only [Sail.BitVec.updateSubrange', BitVec.getLsbD_or, BitVec.getLsbD_and, BitVec.getLsbD_not,
    BitVec.getLsbD_shiftLeft, BitVec.getLsbD_setWidth, BitVec.getLsbD_allOnes]
  split
  · rename_i h
    obtain ⟨h1, h2, h3⟩ := h
    have f1 : ¬ i < start := by omega
    have f2 : i - start < N := by omega
    have f3 : i - start < size := by omega
    simp [h3, f1, f2, f3]
  · rename_i h
    by_cases h3 : i < N
    · have hv : (i < N) := h3
      by_cases h1 : start ≤ i
      · have h2 : ¬ i < start + size := fun h2 => h ⟨h1, h2, h3⟩
        have f1 : ¬ i < start := by omega
        have f3 : ¬ i - start < size := by omega
        have fx : x.getLsbD (i - start) = false := BitVec.getLsbD_of_ge x (i - start) (by omega)
        simp [hv, f1, f3, fx]
      · have f1 : i < start := by omega
        simp [hv, f1]
    · rw [BitVec.getLsbD_of_ge v i (by omega)]
      simp [h3]

/-- Reading the lane just written. -/
theorem aget_aset_same {N : Nat} (v : BitVec N) (e size : Nat) (x : BitVec size) (h : (e + 1) * size ≤ N) :
    aget_Elem (aset_Elem v e size x) e size = x := by
  rw [aset_Elem_eq]
  apply BitVec.eq_of_getLsbD_eq
  intro i
  simp only [aget_Elem, Sail.BitVec.slice, BitVec.getLsbD_extractLsb', getLsbD_updateSubrange',
    ← Int.natCast_mul, Int.toNat_natCast]
  have h' : e * size + size ≤ N := by rw [Nat.add_mul, Nat.one_mul] at h; exact h
  by_cases hi : i < size
  · have : e * size ≤ e * size + i ∧ e * size + i < e * size + size ∧ e * size + i < N := by omega
    simp [hi, this]
  · simp [hi]

/-- Reading another lane than the one written. -/
theorem aget_aset_other {N : Nat} (v : BitVec N) (e e' size : Nat) (x : BitVec size) (hne : e ≠ e') :
    aget_Elem (aset_Elem v e' size x) e size = aget_Elem v e size := by
  rw [aset_Elem_eq]
  apply BitVec.eq_of_getLsbD_eq
  intro i
  simp only [aget_Elem, Sail.BitVec.slice, BitVec.getLsbD_extractLsb', getLsbD_updateSubrange',
    ← Int.natCast_mul, Int.toNat_natCast]
  by_cases hi : i < size
  · have : ¬ (e' * size ≤ e * size + i ∧ e * size + i < e' * size + size ∧ e * size + i < N) := by
      rcases Nat.lt_or_gt_of_ne hne with hlt | hgt
      · have : (e + 1) * size ≤ e' * size := Nat.mul_le_mul_right size hlt
        rw [Nat.add_mul, Nat.one_mul] at this
        omega
      · have : (e' + 1) * size ≤ e * size := Nat.mul_le_mul_right size hgt
        rw [Nat.add_mul, Nat.one_mul] at this
        omega
    simp [hi, this]
  · simp [hi]


/-- A projection commutes with a left fold whose steps it follows. -/
theorem foldl_proj {β γ : Type} (p : β → γ) (g : Int → β → β) (g' : Int → γ → γ)
    (hp : ∀ e s, p (g e s) = g' e (p s)) (l : List Int) (init : β) :
    p (l.foldl (fun s j => g j s) init) = l.foldl (fun s j => g' j s) (p init) := by
  induction l generalizing init with
  | nil => rfl
  | cons j rest ih => simp only [List.foldl_cons, ih, hp]

/-- The lanes as the element accessor reads them. -/
theorem lanesOf_eq_map {N : Nat} (v : BitVec N) (size : Nat) :
    lanesOf v size = (List.range (N / size)).map (fun j => (aget_Elem v j size).toNat) := by
  simp [lanesOf, aget_Elem_toNat]

/-- Writing lanes `0 .. n-1` in order: lane `j` reads its write. -/
theorem aget_foldl_aset {N : Nat} (size n : Nat) (hn : n * size ≤ N) (W : Nat → BitVec size)
    (init : BitVec N) (j : Nat) (hj : j < n) :
    aget_Elem ((List.range n).foldl (fun r k => aset_Elem r k size (W k)) init) j size = W j := by
  induction n generalizing j with
  | zero => omega
  | succ n ih =>
    rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil]
    by_cases hjn : j = n
    · subst hjn
      exact aget_aset_same _ j size (W j) hn
    · rw [aget_aset_other _ j n size (W n) hjn]
      exact ih (by rw [Nat.succ_mul] at hn; omega) j (by omega)

/-- ... and a lane at or beyond `n` keeps the initial value. -/
theorem aget_foldl_aset_ge {N : Nat} (size n : Nat) (W : Nat → BitVec size)
    (init : BitVec N) (j : Nat) (hj : n ≤ j) :
    aget_Elem ((List.range n).foldl (fun r k => aset_Elem r k size (W k)) init) j size = aget_Elem init j size := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil,
      aget_aset_other _ j n size (W n) (by omega)]
    exact ih (by omega)


/-- The lane count of a register split into `esize` lanes. -/
theorem lanes_div (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize) :
    datasize / esize = elements := by
  subst h; exact Nat.mul_div_cancel elements hs

/-- **`dup`**: every lane is the element (`Oak.Simd.splat`). -/
theorem dup_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (x : BitVec esize) :
    lanesOf (vector_transfer_integer_dup datasize elements esize x) esize
      = Oak.Simd.splat elements x.toNat := by
  unfold vector_transfer_integer_dup
  simp only [Id.run, bind, pure]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold, lanesOf_eq_map, lanes_div datasize elements esize h hs]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [Oak.Simd.splat, List.eq_replicate_iff]
  refine ⟨by simp, ?_⟩
  intro b hb
  rw [List.mem_map] at hb
  obtain ⟨j, hj, rfl⟩ := hb
  rw [List.mem_range] at hj
  rw [aget_foldl_aset esize elements (by omega) (fun _ => x) (Zeros datasize) j hj]


/-- A generated per-lane loop whose state carries the elements beside the
result: the result component is the fold of the writes alone. -/
theorem result_of_lane_loop {E₁ E₂ : Type} {N : Nat} (size : Nat) (init : E₁ × E₂ × BitVec N)
    (f₁ : Nat → E₁) (f₂ : Nat → E₂) (W : Nat → BitVec size) (l : List Int) :
    (l.foldl (fun (s : E₁ × E₂ × BitVec N) j =>
        (f₁ j.toNat, f₂ j.toNat, aset_Elem s.2.2 j.toNat size (W j.toNat))) init).2.2
      = l.foldl (fun r j => aset_Elem r j.toNat size (W j.toNat)) init.2.2 :=
  foldl_proj (β := E₁ × E₂ × BitVec N) (γ := BitVec N) (fun s => s.2.2)
    (fun j s => (f₁ j.toNat, f₂ j.toNat, aset_Elem s.2.2 j.toNat size (W j.toNat)))
    (fun j r => aset_Elem r j.toNat size (W j.toNat)) (fun _ _ => rfl) l init

/-- The lanes of a register written lane by lane are the written values. -/
theorem lanes_of_fold_write {N : Nat} (size n : Nat) (hn : n * size = N) (hs : 0 < size)
    (W : Nat → BitVec size) (init : BitVec N) :
    lanesOf ((List.range n).foldl (fun r k => aset_Elem r k size (W k)) init) size
      = (List.range n).map (fun j => (W j).toNat) := by
  rw [lanesOf_eq_map, lanes_div N n size hn hs]
  apply List.map_congr_left
  intro j hj
  rw [List.mem_range] at hj
  rw [aget_foldl_aset size n (by omega) W init j hj]

/-- A lane-wise operation over two registers, index by index. -/
theorem zipWith_lanes {N : Nat} (size : Nat) (f : Nat → Nat → Nat) (a b : BitVec N) :
    List.zipWith f (lanesOf a size) (lanesOf b size)
      = (List.range (N / size)).map (fun j => f (aget_Elem a j size).toNat (aget_Elem b j size).toNat) := by
  rw [lanesOf_eq_map, lanesOf_eq_map, List.zipWith_map, List.zipWith_self]

/-- **`add`**: lane-wise wrapping addition (`Oak.Simd.addWrap`). -/
theorem add_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) :
    lanesOf (vector_arithmetic_binary_uniform_add_wrapping_single datasize elements esize a b false) esize
      = Oak.Simd.addWrap esize (lanesOf a esize) (lanesOf b esize) := by
  unfold vector_arithmetic_binary_uniform_add_wrapping_single
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : BitVec esize × BitVec esize × BitVec datasize) (j : Int) =>
      (aget_Elem a j.toNat esize, aget_Elem b j.toNat esize,
        aset_Elem s.2.2 j.toNat esize (aget_Elem a j.toNat esize + aget_Elem b j.toNat esize)))
      (Zeros esize, Zeros esize, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2) esize = _
  rw [result_of_lane_loop esize _ (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => aget_Elem a j esize + aget_Elem b j esize)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, Oak.Simd.addWrap, zipWith_lanes, lanes_div datasize elements esize h hs]
  apply List.map_congr_left
  intro j _
  simp [BitVec.toNat_add]




/-! ### Lane values: the written element as the verifier's lane function -/

/-- Integer `min` of two lane values is the lane minimum. -/
theorem natCast_min (m n : Nat) : min (m : Int) (n : Int) = ((min m n : Nat) : Int) := by
  by_cases h : m ≤ n
  · rw [Nat.min_def, if_pos h, Int.min_def, if_pos (Int.ofNat_le.mpr h)]
  · rw [Nat.min_def, if_neg h, Int.min_def, if_neg (fun h' => h (Int.ofNat_le.mp h'))]

theorem natCast_max (m n : Nat) : max (m : Int) (n : Int) = ((max m n : Nat) : Int) := by
  by_cases h : m ≤ n
  · rw [Nat.max_def, if_pos h, Int.max_def, if_pos (Int.ofNat_le.mpr h)]
  · rw [Nat.max_def, if_neg h, Int.max_def, if_neg (fun h' => h (Int.ofNat_le.mp h'))]

theorem UInt_eq {w : Nat} (x : BitVec w) : UInt x = (x.toNat : Int) := rfl

/-- `__GetSlice_int` of a lane value below the lane's range is that value. -/
theorem getSlice_toNat (size v : Nat) (hv : v < 2 ^ size) :
    (__GetSlice_int size (v : Int) 0).toNat = v := by
  show (Sail.get_slice_int size (v : Int) 0).toNat = v
  rw [get_slice_int_natCast, BitVec.toNat_ofNat, Nat.mod_eq_of_lt hv]

/-- `umin` lane: the lane minimum (`Oak.Neon.umin`). -/
theorem umin_lane (size : Nat) (x y : BitVec size) :
    (__GetSlice_int size (min (UInt x) (UInt y)) 0).toNat = umin x.toNat y.toNat := by
  rw [UInt_eq, UInt_eq, natCast_min, getSlice_toNat size _ (by have := x.isLt; omega), umin_eq_min]

theorem umax_lane (size : Nat) (x y : BitVec size) :
    (__GetSlice_int size (max (UInt x) (UInt y)) 0).toNat = umax x.toNat y.toNat := by
  rw [UInt_eq, UInt_eq, natCast_max, getSlice_toNat size _ (by have := x.isLt; have := y.isLt; omega), umax_eq_max]

/-- `uqsub` lane: `UnsignedSatQ` of the lane difference (`Oak.Neon.uqsub`). -/
theorem uqsub_lane (size : Nat) (x y : BitVec size) :
    (UnsignedSatQ (UInt x - UInt y) size).1.toNat = uqsub x.toNat y.toNat := by
  rw [UInt_eq, UInt_eq, UnsignedSatQ_uqsub size x.toNat y.toNat x.isLt, BitVec.toNat_ofNat, Nat.mod_eq_of_lt]
  have := x.isLt
  rw [uqsub_eq_sub]
  omega

/-- The `cmeq #0` test: `SInt` is zero exactly on the zero lane. -/
theorem cmeq_zero_test_toNat (size : Nat) (a : BitVec size) :
    (if (SInt a == 0) = true then Ones size else Zeros size).toNat = cmeq size a.toNat 0 := by
  have hiff : SInt a = 0 ↔ a = 0#size := by
    show a.toInt = 0 ↔ a = 0#size
    rw [← BitVec.toInt_zero (w := size), BitVec.toInt_inj]
  by_cases h : a = 0#size
  · subst h
    have hz : SInt (0#size) = 0 := BitVec.toInt_zero
    simp [hz, Ones_toNat, cmeq]
  · have h' : ¬ SInt a = 0 := fun h' => h (hiff.mp h')
    have hn : a.toNat ≠ 0 := fun hz => h (BitVec.eq_of_toNat_eq (by simpa using hz))
    simp [h', Zeros, cmeq, hn]

/-! ### Lane loops with more state -/

theorem mem_range_from (s : Nat) (t : Int) (i : Int) :
    i ∈ ({ start := s, stop := t } : IntRange) ↔ (s : Int) ≤ i ∧ i ≤ t := by
  simp only [Membership.mem, IntRange.instMemIntRange]
  constructor
  · rintro ⟨h, _⟩
    simpa using h
  · intro h
    refine ⟨by simpa using h, ?_⟩
    simp

/-- The range from `s` (the reductions start at lane 1). -/
theorem loop_fold_from {β : Type} (s n : Nat) (g : Int → β → β) (k : Nat) :
    ∀ (i : Nat) (b : β) (hs : ((i : Int) - (({ start := s, stop := (n : Int) - 1 } : IntRange)).start) % 1 = 0),
      s ≤ i → i + k = n →
      IntRange.forIn'.loop (m := Id) ({ start := s, stop := (n : Int) - 1 } : IntRange)
        (fun i _ b => pure (ForInStep.yield (g i b))) b i hs
        = (List.range' i k).foldl (fun t j => g (j : Int) t) b := by
  induction k with
  | zero =>
    intro i b hs hsi hi
    rw [IntRange.forIn'.loop.eq_1]
    have hnot : ¬ ((i : Int) ∈ ({ start := s, stop := (n : Int) - 1 } : IntRange)) := by
      rw [mem_range_from]; omega
    simp only [hnot, ↓reduceDIte, List.range'_zero, List.map_nil, List.foldl_nil]
    rfl
  | succ k ih =>
    intro i b hs hsi hi
    rw [IntRange.forIn'.loop.eq_1]
    have hmem : (i : Int) ∈ ({ start := s, stop := (n : Int) - 1 } : IntRange) := by
      rw [mem_range_from]; omega
    simp only [hmem, ↓reduceDIte]
    have hstep : ((i : Int) + (({ start := s, stop := (n : Int) - 1 } : IntRange)).step) = ((i + 1 : Nat) : Int) := by simp
    simp only [List.range'_succ, List.map_cons, List.foldl_cons]
    have := ih (i + 1) (g (↑i) b) (by simp) (by omega) (by omega)
    simp only [hstep]
    exact this

theorem forIn_from_fold {β : Type} (s n : Nat) (hsn : s ≤ n) (init : β) (g : Int → β → β) :
    (forIn (m := Id) ({ start := s, stop := (n : Int) - 1 } : IntRange) init (fun i t => ForInStep.yield (g i t)))
      = (List.range' s (n - s)).foldl (fun t j => g (j : Int) t) init := by
  show IntRange.forIn' _ init (fun i _ t => pure (ForInStep.yield (g i t))) = _
  unfold IntRange.forIn'
  exact loop_fold_from s n g (n - s) s init (by simp) (Nat.le_refl s) (by omega)

/-- Conditional writes: a lane at or beyond `n` keeps the initial value. -/
theorem aget_foldl_aset_cond_ge {N : Nat} (size n : Nat) (c : Nat → Bool) (W : Nat → BitVec size)
    (init : BitVec N) (j : Nat) (hj : n ≤ j) :
    aget_Elem ((List.range n).foldl (fun r k => if c k = true then aset_Elem r k size (W k) else r) init) j size
      = aget_Elem init j size := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil]
    by_cases hc : c n = true
    · simp only [hc, ↓reduceIte]
      rw [aget_aset_other _ j n size (W n) (by omega)]
      exact ih (by omega)
    · simp only [hc, Bool.false_eq_true, ↓reduceIte]
      exact ih (by omega)

/-- Conditional writes (`tbl`): a lane written under its condition, else the initial lane. -/
theorem aget_foldl_aset_cond {N : Nat} (size n : Nat) (hn : n * size ≤ N) (c : Nat → Bool) (W : Nat → BitVec size)
    (init : BitVec N) (j : Nat) (hj : j < n) :
    aget_Elem ((List.range n).foldl (fun r k => if c k = true then aset_Elem r k size (W k) else r) init) j size
      = if c j = true then W j else aget_Elem init j size := by
  induction n generalizing j with
  | zero => omega
  | succ n ih =>
    rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil]
    by_cases hjn : j = n
    · subst hjn
      by_cases hc : c j = true
      · simp only [hc, ↓reduceIte]
        exact aget_aset_same _ j size (W j) hn
      · simp only [hc, Bool.false_eq_true, ↓reduceIte]
        exact aget_foldl_aset_cond_ge size j c W init j (Nat.le_refl j)
    · have hlt : j < n := by omega
      by_cases hc : c n = true
      · simp only [hc, ↓reduceIte]
        rw [aget_aset_other _ j n size (W n) hjn]
        exact ih (by rw [Nat.succ_mul] at hn; omega) j hlt
      · simp only [hc, Bool.false_eq_true, ↓reduceIte]
        exact ih (by rw [Nat.succ_mul] at hn; omega) j hlt

/-- `aget_Elem` of the zero register is the zero lane. -/
theorem aget_Zeros (N e size : Nat) : aget_Elem (Zeros N) e size = 0#size := by
  apply BitVec.eq_of_toNat_eq
  rw [aget_Elem_toNat]
  simp [Zeros]


/-- The other tuple shapes of the generated loops. -/
theorem result_of_lane_loop4a {E₁ E₂ E₄ : Type} {N : Nat} (size : Nat) (init : E₁ × E₂ × BitVec N × E₄)
    (f₁ : Nat → E₁) (f₂ : Nat → E₂) (f₄ : Nat → E₄) (W : Nat → BitVec size) (l : List Int) :
    (l.foldl (fun (s : E₁ × E₂ × BitVec N × E₄) j =>
        (f₁ j.toNat, f₂ j.toNat, aset_Elem s.2.2.1 j.toNat size (W j.toNat), f₄ j.toNat)) init).2.2.1
      = l.foldl (fun r j => aset_Elem r j.toNat size (W j.toNat)) init.2.2.1 :=
  foldl_proj (β := E₁ × E₂ × BitVec N × E₄) (γ := BitVec N) (fun s => s.2.2.1)
    (fun j s => (f₁ j.toNat, f₂ j.toNat, aset_Elem s.2.2.1 j.toNat size (W j.toNat), f₄ j.toNat))
    (fun j r => aset_Elem r j.toNat size (W j.toNat)) (fun _ _ => rfl) l init

theorem result_of_lane_loop4b {E₁ E₂ E₃ : Type} {N : Nat} (size : Nat) (init : E₁ × E₂ × E₃ × BitVec N)
    (f₁ : Nat → E₁) (f₂ : Nat → E₂) (f₃ : Nat → E₃) (W : Nat → BitVec size) (l : List Int) :
    (l.foldl (fun (s : E₁ × E₂ × E₃ × BitVec N) j =>
        (f₁ j.toNat, f₂ j.toNat, f₃ j.toNat, aset_Elem s.2.2.2 j.toNat size (W j.toNat))) init).2.2.2
      = l.foldl (fun r j => aset_Elem r j.toNat size (W j.toNat)) init.2.2.2 :=
  foldl_proj (β := E₁ × E₂ × E₃ × BitVec N) (γ := BitVec N) (fun s => s.2.2.2)
    (fun j s => (f₁ j.toNat, f₂ j.toNat, f₃ j.toNat, aset_Elem s.2.2.2 j.toNat size (W j.toNat)))
    (fun j r => aset_Elem r j.toNat size (W j.toNat)) (fun _ _ => rfl) l init

theorem result_of_lane_loop3b {E₁ E₃ : Type} {N : Nat} (size : Nat) (init : E₁ × BitVec N × E₃)
    (f₁ : Nat → E₁) (f₃ : Nat → E₃) (W : Nat → BitVec size) (l : List Int) :
    (l.foldl (fun (s : E₁ × BitVec N × E₃) j =>
        (f₁ j.toNat, aset_Elem s.2.1 j.toNat size (W j.toNat), f₃ j.toNat)) init).2.1
      = l.foldl (fun r j => aset_Elem r j.toNat size (W j.toNat)) init.2.1 :=
  foldl_proj (β := E₁ × BitVec N × E₃) (γ := BitVec N) (fun s => s.2.1)
    (fun j s => (f₁ j.toNat, aset_Elem s.2.1 j.toNat size (W j.toNat), f₃ j.toNat))
    (fun j r => aset_Elem r j.toNat size (W j.toNat)) (fun _ _ => rfl) l init

theorem result_of_lane_loop2 {E₁ : Type} {N : Nat} (size : Nat) (init : E₁ × BitVec N)
    (f₁ : Nat → E₁) (W : Nat → BitVec size) (l : List Int) :
    (l.foldl (fun (s : E₁ × BitVec N) j => (f₁ j.toNat, aset_Elem s.2 j.toNat size (W j.toNat))) init).2
      = l.foldl (fun r j => aset_Elem r j.toNat size (W j.toNat)) init.2 :=
  foldl_proj (β := E₁ × BitVec N) (γ := BitVec N) (fun s => s.2)
    (fun j s => (f₁ j.toNat, aset_Elem s.2 j.toNat size (W j.toNat)))
    (fun j r => aset_Elem r j.toNat size (W j.toNat)) (fun _ _ => rfl) l init

/-! ### The lane theorems -/

/-- **`cmeq`** (register form): the lane equality mask (`Oak.Neon.cmeq`, `Oak.Simd.eqMask`). -/
theorem cmeq_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) :
    lanesOf (vector_arithmetic_binary_uniform_cmp_bitwise false datasize elements esize a b) esize
      = List.zipWith (cmeq esize) (lanesOf a esize) (lanesOf b esize) := by
  unfold vector_arithmetic_binary_uniform_cmp_bitwise
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : BitVec esize × BitVec esize × BitVec datasize × Bool) (j : Int) =>
      (aget_Elem a j.toNat esize, aget_Elem b j.toNat esize,
        aset_Elem s.2.2.1 j.toNat esize
          (if (aget_Elem a j.toNat esize == aget_Elem b j.toNat esize) = true then Ones esize else Zeros esize),
        aget_Elem a j.toNat esize == aget_Elem b j.toNat esize))
      (Zeros esize, Zeros esize, Zeros datasize, false) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2.1) esize = _
  rw [result_of_lane_loop4a esize _ (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => aget_Elem a j esize == aget_Elem b j esize)
    (fun j => if (aget_Elem a j esize == aget_Elem b j esize) = true then Ones esize else Zeros esize)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, zipWith_lanes, lanes_div datasize elements esize h hs]
  apply List.map_congr_left
  intro j _
  exact cmeq_test_toNat esize _ _

/-- **`umin`**: the lane minimum. -/
theorem umin_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) :
    lanesOf (vector_arithmetic_binary_uniform_maxmin_single datasize elements esize a b true true) esize
      = List.zipWith umin (lanesOf a esize) (lanesOf b esize) := by
  unfold vector_arithmetic_binary_uniform_maxmin_single
  simp only [Id.run, bind, pure, ↓reduceIte, asl_Int]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : Int × Int × Int × BitVec datasize) (j : Int) =>
      (UInt (aget_Elem a j.toNat esize), UInt (aget_Elem b j.toNat esize),
        min (UInt (aget_Elem a j.toNat esize)) (UInt (aget_Elem b j.toNat esize)),
        aset_Elem s.2.2.2 j.toNat esize
          (__GetSlice_int esize (min (UInt (aget_Elem a j.toNat esize)) (UInt (aget_Elem b j.toNat esize))) 0)))
      (0, 0, 0, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2.2) esize = _
  rw [result_of_lane_loop4b esize _ (fun j => UInt (aget_Elem a j esize)) (fun j => UInt (aget_Elem b j esize))
    (fun j => min (UInt (aget_Elem a j esize)) (UInt (aget_Elem b j esize)))
    (fun j => __GetSlice_int esize (min (UInt (aget_Elem a j esize)) (UInt (aget_Elem b j esize))) 0)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, zipWith_lanes, lanes_div datasize elements esize h hs]
  apply List.map_congr_left
  intro j _
  exact umin_lane esize _ _

/-- **`umax`**: the lane maximum. -/
theorem umax_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) :
    lanesOf (vector_arithmetic_binary_uniform_maxmin_single datasize elements esize a b false true) esize
      = List.zipWith umax (lanesOf a esize) (lanesOf b esize) := by
  unfold vector_arithmetic_binary_uniform_maxmin_single
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte, asl_Int]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : Int × Int × Int × BitVec datasize) (j : Int) =>
      (UInt (aget_Elem a j.toNat esize), UInt (aget_Elem b j.toNat esize),
        max (UInt (aget_Elem a j.toNat esize)) (UInt (aget_Elem b j.toNat esize)),
        aset_Elem s.2.2.2 j.toNat esize
          (__GetSlice_int esize (max (UInt (aget_Elem a j.toNat esize)) (UInt (aget_Elem b j.toNat esize))) 0)))
      (0, 0, 0, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2.2) esize = _
  rw [result_of_lane_loop4b esize _ (fun j => UInt (aget_Elem a j esize)) (fun j => UInt (aget_Elem b j esize))
    (fun j => max (UInt (aget_Elem a j esize)) (UInt (aget_Elem b j esize)))
    (fun j => __GetSlice_int esize (max (UInt (aget_Elem a j esize)) (UInt (aget_Elem b j esize))) 0)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, zipWith_lanes, lanes_div datasize elements esize h hs]
  apply List.map_congr_left
  intro j _
  exact umax_lane esize _ _

/-- **`uqsub`**: the saturating lane difference (`Oak.Neon.uqsub`, `Oak.Simd.subSat`). -/
theorem uqsub_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) :
    lanesOf (vector_arithmetic_binary_uniform_sub_saturating datasize elements esize a b true) esize
      = List.zipWith uqsub (lanesOf a esize) (lanesOf b esize) := by
  unfold vector_arithmetic_binary_uniform_sub_saturating
  simp only [Id.run, bind, pure, ↓reduceIte, asl_Int, SatQ]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : Int × Int × Int × BitVec datasize) (j : Int) =>
      (UInt (aget_Elem a j.toNat esize) - UInt (aget_Elem b j.toNat esize),
        UInt (aget_Elem a j.toNat esize), UInt (aget_Elem b j.toNat esize),
        aset_Elem s.2.2.2 j.toNat esize
          (UnsignedSatQ (UInt (aget_Elem a j.toNat esize) - UInt (aget_Elem b j.toNat esize)) esize).1))
      (0, 0, 0, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2.2) esize = _
  rw [result_of_lane_loop4b esize _ (fun j => UInt (aget_Elem a j esize) - UInt (aget_Elem b j esize))
    (fun j => UInt (aget_Elem a j esize)) (fun j => UInt (aget_Elem b j esize))
    (fun j => (UnsignedSatQ (UInt (aget_Elem a j esize) - UInt (aget_Elem b j esize)) esize).1)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, zipWith_lanes, lanes_div datasize elements esize h hs]
  apply List.map_congr_left
  intro j _
  exact uqsub_lane esize _ _

/-- **`cmeq #0`**: the lane compared with zero. -/
theorem cmeq_zero_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a : BitVec datasize) :
    lanesOf (vector_arithmetic_unary_cmp_int_bulk CompareOp.CompareOp_EQ datasize elements esize a) esize
      = (lanesOf a esize).map (fun x => cmeq esize x 0) := by
  unfold vector_arithmetic_unary_cmp_int_bulk
  simp only [Id.run, bind, pure]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : Int × BitVec datasize × Bool) (j : Int) =>
      (SInt (aget_Elem a j.toNat esize),
        aset_Elem s.2.1 j.toNat esize
          (if (SInt (aget_Elem a j.toNat esize) == 0) = true then Ones esize else Zeros esize),
        SInt (aget_Elem a j.toNat esize) == 0))
      (0, Zeros datasize, false) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.1) esize = _
  rw [result_of_lane_loop3b esize _ (fun j => SInt (aget_Elem a j esize)) (fun j => SInt (aget_Elem a j esize) == 0)
    (fun j => if (SInt (aget_Elem a j esize) == 0) = true then Ones esize else Zeros esize)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, lanesOf_eq_map, lanes_div datasize elements esize h hs, List.map_map]
  apply List.map_congr_left
  intro j _
  exact cmeq_zero_test_toNat esize _


/-- **`sub`**: lane-wise wrapping subtraction (`Oak.Neon.sub`). -/
theorem sub_lane (size : Nat) (x y : BitVec size) : (x - y).toNat = Oak.Neon.sub size x.toNat y.toNat := by
  rw [BitVec.toNat_sub, Oak.Neon.sub, Nat.mod_eq_of_lt y.isLt, Nat.add_comm]

theorem sub_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) :
    lanesOf (vector_arithmetic_binary_uniform_add_wrapping_single datasize elements esize a b true) esize
      = List.zipWith (Oak.Neon.sub esize) (lanesOf a esize) (lanesOf b esize) := by
  unfold vector_arithmetic_binary_uniform_add_wrapping_single
  simp only [Id.run, bind, pure, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : BitVec esize × BitVec esize × BitVec datasize) (j : Int) =>
      (aget_Elem a j.toNat esize, aget_Elem b j.toNat esize,
        aset_Elem s.2.2 j.toNat esize (aget_Elem a j.toNat esize - aget_Elem b j.toNat esize)))
      (Zeros esize, Zeros esize, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2) esize = _
  rw [result_of_lane_loop esize _ (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => aget_Elem a j esize - aget_Elem b j esize)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, zipWith_lanes, lanes_div datasize elements esize h hs]
  apply List.map_congr_left
  intro j _
  exact sub_lane esize _ _

/-- **`tbl`** with one table register over sixteen byte lanes: lane `j` is the
table's lane at index `j` when it is below sixteen, zero otherwise
(`Oak.Neon.tbl`, `Oak.Simd.tbl`). -/
theorem tbl_lanes (indices table : BitVec 128) :
    lanesOf (vector_transfer_vector_table 128 16 true indices table (Zeros 128)) 8
      = (lanesOf indices 8).map (Oak.Neon.tbl (lanesOf table 8)) := by
  unfold vector_transfer_vector_table
  simp only [Id.run, bind, pure, ↓reduceIte]
  rw [show ({ stop := ((16 : Nat) : Int) - 1 } : IntRange) = laneRange 16 from rfl, forIn_laneRange_fold]
  simp only [List.foldl_map, Int.toNat_natCast]
  simp only [lanesOf_eq_map, List.map_map, Nat.reduceDiv]
  apply List.map_congr_left
  intro j hj
  rw [List.mem_range] at hj
  simp only [Function.comp]
  rw [aget_foldl_aset_cond 8 16 (by omega) (fun k => (UInt (aget_Elem indices k 8) <b 16))
    (fun k => aget_Elem table (UInt (aget_Elem indices k 8)).toNat 8) (Zeros 128) j hj]
  have hlen : (List.map (fun j => (aget_Elem table j 8).toNat) (List.range 16)).length = 16 := by simp
  have hidx : (UInt (aget_Elem indices j 8)).toNat = (aget_Elem indices j 8).toNat := by
    rw [UInt_eq, Int.toNat_natCast]
  unfold Oak.Neon.tbl
  by_cases hlt : (aget_Elem indices j 8).toNat < 16
  · have hb : (UInt (aget_Elem indices j 8) <b 16) = true := by
      rw [UInt_eq]; exact decide_eq_true (Int.ofNat_lt.mpr hlt)
    rw [if_pos hb, dif_pos ⟨by omega, hlt⟩, hidx]
    simp [List.getElem_map, List.getElem_range]
  · have hb : (UInt (aget_Elem indices j 8) <b 16) = false := by
      rw [UInt_eq]; exact decide_eq_false (fun h' => hlt (Int.ofNat_lt.mp h'))
    rw [if_neg (by simp [hb]), dif_neg (by omega), aget_Zeros]
    rfl

/-- The reduction's running maximum stays a lane value. -/
theorem foldl_max_lt (size : Nat) (l : List Nat) (init : Nat) (hinit : init < 2 ^ size)
    (hl : ∀ x ∈ l, x < 2 ^ size) : l.foldl max init < 2 ^ size := by
  induction l generalizing init with
  | nil => exact hinit
  | cons x rest ih =>
    rw [List.foldl_cons]
    exact ih (max init x) (by have := hl x (List.mem_cons_self ..); omega)
      (fun y hy => hl y (List.mem_cons_of_mem x hy))

/-- The integer running maximum is the lane maximum, cast. -/
theorem foldl_max_cast (f : Nat → Nat) (l : List Nat) (init : Nat) :
    l.foldl (fun (m : Int) (j : Nat) => max m ((f j : Nat) : Int)) (init : Int)
      = ((l.foldl (fun m j => max m (f j)) init : Nat) : Int) := by
  induction l generalizing init with
  | nil => rfl
  | cons x rest ih => rw [List.foldl_cons, List.foldl_cons, natCast_max]; exact ih _

/-- **`umaxv`**: the unsigned maximum over the lanes (`Oak.Neon.umaxv`). -/
theorem umaxv_lane (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (he : 0 < elements) (a : BitVec datasize) :
    (vector_reduce_intmax datasize elements esize a false true).toNat = Oak.Neon.umaxv (lanesOf a esize) := by
  obtain ⟨k, rfl⟩ : ∃ k, elements = k + 1 := ⟨elements - 1, by omega⟩
  unfold vector_reduce_intmax
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte, asl_Int]
  show (__GetSlice_int esize (forIn (m := Id) ({ start := ((1 : Nat) : Int), stop := ((k + 1 : Nat) : Int) - 1 } : IntRange)
      (0, UInt (aget_Elem a 0 esize))
      (fun (e : Int) (t : Int × Int) => ForInStep.yield (UInt (aget_Elem a e.toNat esize), max t.2 (UInt (aget_Elem a e.toNat esize))))).2 0).toNat = _
  rw [forIn_from_fold 1 (k + 1) he]
  rw [foldl_proj (β := Int × Int) (γ := Int) (fun t => t.2)
    (fun e t => (UInt (aget_Elem a e.toNat esize), max t.2 (UInt (aget_Elem a e.toNat esize))))
    (fun e m => max m (UInt (aget_Elem a e.toNat esize))) (fun _ _ => rfl)]
  simp only [List.foldl_map, Int.toNat_natCast, UInt_eq, Nat.add_sub_cancel]
  rw [foldl_max_cast (fun k => (aget_Elem a k esize).toNat), getSlice_toNat]
  · rw [Oak.Neon.umaxv, lanesOf_eq_map, lanes_div datasize (k + 1) esize h hs, List.foldl_map,
      List.range_eq_range', List.range'_succ, List.foldl_cons, Nat.zero_add, Nat.zero_max]
  · rw [← List.foldl_map (f := fun j => (aget_Elem a j esize).toNat) (g := fun (m v : Nat) => max m v)]
    apply foldl_max_lt esize _ _ (aget_Elem a 0 esize).isLt
    intro x hx
    rw [List.mem_map] at hx
    obtain ⟨j, _, rfl⟩ := hx
    exact (aget_Elem a j esize).isLt


/-! ### `ext`, the shifts, and `Reduce` -/


/-! ### `ext`: the slice of `hi ++ lo` at a byte position -/

/-- A slice of a slice is the slice at the summed offset (within the outer slice). -/
theorem extractLsb'_extractLsb' {w : Nat} (x : BitVec w) (s₁ l₁ s₂ l₂ : Nat) (h : s₂ + l₂ ≤ l₁) :
    (x.extractLsb' s₁ l₁).extractLsb' s₂ l₂ = x.extractLsb' (s₁ + s₂) l₂ := by
  apply BitVec.eq_of_getLsbD_eq
  intro i
  simp only [BitVec.getLsbD_extractLsb']
  by_cases hi : i < l₂
  · have : s₂ + i < l₁ := by omega
    simp [hi, this, Nat.add_assoc]
  · simp [hi]

/-- Lane `j` of the decomposition is the element accessor's value. -/
theorem lanesOf_getElem {N : Nat} (v : BitVec N) (size j : Nat) (hj : j < (lanesOf v size).length) :
    (lanesOf v size)[j] = (aget_Elem v j size).toNat := by
  simp [lanesOf, aget_Elem_toNat]

theorem natMul_toNat (k m : Nat) : ((fun x y : Int => x * y) (k : Int) (m : Int)).toNat = k * m := by
  show ((k : Int) * (m : Int)).toNat = k * m
  rw [← Int.natCast_mul, Int.toNat_natCast]

theorem ext_lanes (hi lo : BitVec 128) (p : Nat) (hp : p ≤ 16) :
    lanesOf (vector_transfer_vector_extract 128 hi lo ((8 * p : Nat) : Int)) 8
      = Oak.Neon.ext p (lanesOf lo 8) (lanesOf hi 8) := by
  have hlen_lo : (lanesOf lo 8).length = 16 := by simp [lanesOf]
  have hlen_hi : (lanesOf hi 8).length = 16 := by simp [lanesOf]
  unfold vector_transfer_vector_extract Oak.Neon.ext
  simp only [Int.toNat_natCast, Sail.BitVec.slice]
  have hcat : BitVec.setWidth (2 * 128) (hi ++ lo) = hi ++ lo := BitVec.setWidth_eq (hi ++ lo)
  rw [hcat, lanesOf_eq_map (v := BitVec.extractLsb' (8 * p) 128 (hi ++ lo))]
  apply List.ext_getElem
  · simp [List.length_take, List.length_drop, hlen_lo, hlen_hi]; omega
  · intro k hk _
    have hk16 : k < 16 := by simpa using hk
    rw [List.getElem_map, List.getElem_range, List.getElem_take, List.getElem_drop]
    rw [aget_Elem, Sail.BitVec.slice, natMul_toNat, extractLsb'_extractLsb' _ _ _ _ _ (by omega)]
    by_cases hlt : p + k < 16
    · rw [List.getElem_append_left (by rw [hlen_lo]; omega), lanesOf_getElem, aget_Elem, Sail.BitVec.slice,
        natMul_toNat, BitVec.extractLsb'_append_eq_of_add_le (by omega),
        show 8 * p + k * 8 = (p + k) * 8 by omega]
    · rw [List.getElem_append_right (by rw [hlen_lo]; omega), lanesOf_getElem, hlen_lo, aget_Elem,
        Sail.BitVec.slice, natMul_toNat, BitVec.extractLsb'_append_eq_of_le (by omega),
        show 8 * p + k * 8 - 128 = (p + k - 16) * 8 by omega]

/-! ### The shifts: the support library's iterated halving is the shift -/

theorem iterate_div_two (n : Nat) (a : Nat) :
    Sail.Nat.iterate (fun x : Int => x / 2) n (a : Int) = ((a >>> n : Nat) : Int) := by
  induction n generalizing a with
  | zero => simp [Sail.Nat.iterate]
  | succ n ih =>
    rw [Sail.Nat.iterate]
    have : ((a : Int) / 2) = ((a / 2 : Nat) : Int) := by omega
    rw [this, ih, Nat.shiftRight_succ_inside]

theorem shiftr_natCast (a n : Nat) : Sail.Int.shiftr (a : Int) (n : Int) = ((a >>> n : Nat) : Int) := by
  show Sail.Nat.iterate (fun x : Int => x / 2) n (a : Int) = _
  exact iterate_div_two n a


/-- The `ushr` lane: the shifted lane value (`Oak.Neon.ushr`). -/
theorem ushr_lane {N : Nat} (size j sh : Nat) (x : BitVec size) :
    (aget_Elem (Zeros N) j size + __GetSlice_int size (_shr_int_general (UInt x + 0) (sh : Int)) 0).toNat
      = Oak.Neon.ushr sh x.toNat := by
  rw [aget_Zeros, BitVec.zero_add, _shr_int_general, UInt_eq, Int.add_zero]
  have hge : ((sh : Int) ≥b 0) = true := decide_eq_true (Int.ofNat_nonneg sh)
  rw [if_pos hge, shiftr_natCast, getSlice_toNat size _ (by have := x.isLt; have := Nat.shiftRight_le x.toNat sh; omega)]
  rfl

/-- **`ushr #sh`**: lane-wise logical shift right (`Oak.Neon.ushr`, `Oak.Simd.shr`). -/
theorem ushr_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a : BitVec datasize) (sh : Nat) :
    lanesOf (vector_shift_right false datasize elements esize a (Zeros datasize) false (sh : Int) true) esize
      = (lanesOf a esize).map (Oak.Neon.ushr sh) := by
  unfold vector_shift_right
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte, asl_Int]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : Int × BitVec datasize) (j : Int) =>
      (_shr_int_general (UInt (aget_Elem a j.toNat esize) + 0) (sh : Int),
        aset_Elem s.2 j.toNat esize
          (aget_Elem (Zeros datasize) j.toNat esize
            + __GetSlice_int esize (_shr_int_general (UInt (aget_Elem a j.toNat esize) + 0) (sh : Int)) 0)))
      (0, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2) esize = _
  rw [result_of_lane_loop2 esize _ (fun j => _shr_int_general (UInt (aget_Elem a j esize) + 0) (sh : Int))
    (fun j => aget_Elem (Zeros datasize) j esize
      + __GetSlice_int esize (_shr_int_general (UInt (aget_Elem a j esize) + 0) (sh : Int)) 0)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, lanesOf_eq_map, lanes_div datasize elements esize h hs, List.map_map]
  apply List.map_congr_left
  intro j _
  exact ushr_lane esize j sh _


/-! ### `sshr #7` on bytes: the sign fill of `movemask` -/

/-- The arithmetic shift of a byte by seven is its sign fill (`Oak.Neon.sshr7`):
all ones when the top bit is set, zero otherwise. Decided over the 256 bytes. -/
theorem sshr7_lane (x : BitVec 8) :
    (__GetSlice_int 8 (_shr_int_general (SInt x + 0) 7) 0).toNat = Oak.Neon.sshr7 x.toNat := by
  revert x
  decide

/-! ### `Reduce` for `addv`: Arm's recursive tree, transliterated by hand -/

/-- Arm's `Reduce(ReduceOp_ADD, input, esize)`: the sum of the two halves,
recursively, down to one element (`aarch64_vector.sail`). Sail's Lean
backend cannot discharge this recursion's termination, so it is stated
here by hand. -/
def reduceAdd (N : Nat) (input : BitVec N) (esize : Nat) : BitVec esize :=
  if h : N = esize then input.cast h
  else if hN : esize < N ∧ 0 < esize then
    reduceAdd (N / 2) (input.extractLsb' (N / 2) (N / 2)) esize
      + reduceAdd (N / 2) (input.extractLsb' 0 (N / 2)) esize
  else 0
termination_by N
decreasing_by all_goals omega

theorem reduceAdd_step (N : Nat) (input : BitVec N) (esize : Nat) (h1 : N ≠ esize) (h2 : esize < N ∧ 0 < esize) :
    reduceAdd N input esize
      = reduceAdd (N / 2) (input.extractLsb' (N / 2) (N / 2)) esize
        + reduceAdd (N / 2) (input.extractLsb' 0 (N / 2)) esize := by
  rw [reduceAdd, dif_neg h1, dif_pos h2]

theorem reduceAdd_base (N : Nat) (input : BitVec N) (esize : Nat) (h : N = esize) :
    reduceAdd N input esize = input.cast h := by
  rw [reduceAdd, dif_pos h]

/-- **`addv`** over eight bytes: the tree sum is the wrapping fold (`Oak.Neon.addv`). -/
theorem reduceAdd_eight_bytes (v : BitVec 64) :
    (reduceAdd 64 v 8).toNat = Oak.Neon.addv 8 (lanesOf v 8) := by
  have hr : List.range 8 = [0, 1, 2, 3, 4, 5, 6, 7] := rfl
  rw [reduceAdd_step 64 _ 8 (by decide) (by decide)]
  simp only [Nat.reduceDiv]
  simp only [reduceAdd_step 32 _ 8 (by decide) (by decide), Nat.reduceDiv]
  simp only [reduceAdd_step 16 _ 8 (by decide) (by decide), Nat.reduceDiv]
  simp only [reduceAdd_base 8 _ 8 rfl]
  simp only [extractLsb'_extractLsb', Nat.reduceAdd, Nat.reduceLeDiff]
  simp only [BitVec.toNat_add, BitVec.toNat_cast, BitVec.extractLsb'_toNat, Nat.reducePow, Nat.reduceAdd,
    Nat.shiftRight_zero, Oak.Neon.addv, lanesOf, hr, List.map_cons, List.map_nil, List.foldl_cons,
    List.foldl_nil, Nat.reduceMul, Nat.zero_add]
  omega




/-! ### `cnt`: Arm's `BitCount` is the population count -/

theorem popcount_append (l₁ l₂ : List Bool) :
    Oak.Intrinsics.popcount (l₁ ++ l₂) = Oak.Intrinsics.popcount l₁ + Oak.Intrinsics.popcount l₂ := by
  induction l₁ with
  | nil => simp [Oak.Intrinsics.popcount]
  | cons b rest ih => cases b <;> simp [Oak.Intrinsics.popcount, ih] <;> omega

/-- The bit test of Arm's loop is the bit. -/
theorem bitTest_eq {n : Nat} (x : BitVec n) (i : Nat) :
    ((Sail.BitVec.join1 [Sail.BitVec.access x i] == 1#1) : Bool) = x.getLsbD i := by
  rw [join1_single, access_eq]
  cases x.getLsbD i <;> rfl

/-- Counting the set bits as a fold over the bit indices. -/
theorem foldl_count (c : Nat → Bool) (n : Nat) :
    (List.range n).foldl (fun (r : Int) (i : Nat) => if c i = true then r + 1 else r) 0
      = ((Oak.Intrinsics.popcount ((List.range n).map c) : Nat) : Int) := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [List.range_succ, List.foldl_append, List.foldl_cons, List.foldl_nil, List.map_append, popcount_append, ih]
    cases hc : c n <;> simp [hc, Oak.Intrinsics.popcount]

/-- **`BitCount`** is the population count of the bits. -/
theorem BitCount_eq {n : Nat} (x : BitVec n) :
    BitCount x = ((Oak.Intrinsics.popcount ((List.range n).map (fun i => x.getLsbD i)) : Nat) : Int) := by
  unfold BitCount
  simp only [Id.run, bind, pure, Sail.BitVec.length]
  rw [show ({ stop := (n : Int) - 1 } : IntRange) = laneRange n from rfl, forIn_laneRange_fold]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [foldl_count (fun i => (Sail.BitVec.join1 [Sail.BitVec.access x i] == 1#1))]
  congr 2
  apply List.map_congr_left
  intro i _
  exact bitTest_eq x i

/-- The `cnt` lane: the population count of the lane (`Oak.Neon.cnt`). -/
theorem cnt_lane (size : Nat) (x : BitVec size) :
    (__GetSlice_int size (BitCount x) 0).toNat = Oak.Neon.cnt size x.toNat := by
  rw [BitCount_eq, getSlice_toNat]
  · rfl
  · have h1 := Oak.Intrinsics.popcount_le_width ((List.range size).map (fun i => x.getLsbD i))
    have h2 : size < 2 ^ size := Nat.lt_two_pow_self
    simp only [List.length_map, List.length_range] at h1
    omega

/-- **`cnt`**: lane-wise population count. -/
theorem cnt_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a : BitVec datasize) :
    lanesOf (vector_arithmetic_unary_cnt datasize elements esize a) esize
      = (lanesOf a esize).map (Oak.Neon.cnt esize) := by
  unfold vector_arithmetic_unary_cnt
  simp only [Id.run, bind, pure]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl,
    forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : Int × BitVec datasize) (j : Int) =>
      (BitCount (aget_Elem a j.toNat esize),
        aset_Elem s.2 j.toNat esize (__GetSlice_int esize (BitCount (aget_Elem a j.toNat esize)) 0)))
      (0, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2) esize = _
  rw [result_of_lane_loop2 esize _ (fun j => BitCount (aget_Elem a j esize))
    (fun j => __GetSlice_int esize (BitCount (aget_Elem a j esize)) 0)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs, lanesOf_eq_map, lanes_div datasize elements esize h hs, List.map_map]
  apply List.map_congr_left
  intro j _
  exact cnt_lane esize _


/-! ### The floating-point forms: the IEEE operation applied lane for lane

Arm's `FPAdd`, `FPMul`, … are uninterpreted here (`Sail.FPAdd`, …, the
support library's constants the fragment maps them to), exactly as the
verifier's operation terms are (asm/floats_ops.go, Oak.Uninterpreted). Each
theorem states that the instruction's generated body applies the operation
to the lanes of its operands, index by index — the lane structure the
verifier builds (asm/verify_float.go) — so the correspondence between the
two rests on one identification, `Sail.FPAdd` with the verifier's `fadd`,
which the differentials check against the hardware. The sign operations
`FPNeg`/`FPAbs` are bit operations on both sides and are proven as such. -/

/-- The float write loop's result: the fold over the lanes with the
written value `W j` (the three-local shape element1, element2, result). -/
theorem float_lanes_of_loop (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (f₁ f₂ : Nat → BitVec esize) (W : Nat → BitVec esize) :
    lanesOf ((List.foldl (fun (s : BitVec esize × BitVec esize × BitVec datasize) (j : Int) =>
        (f₁ j.toNat, f₂ j.toNat, aset_Elem s.2.2 j.toNat esize (W j.toNat)))
      (Zeros esize, Zeros esize, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2) esize
      = (List.range elements).map (fun j => (W j).toNat) := by
  rw [result_of_lane_loop esize _ f₁ f₂ W]
  simp only [List.foldl_map, Int.toNat_natCast]
  exact lanes_of_fold_write esize elements h hs W (Zeros datasize)

/-- **`fadd`** (vector, `pair` false): lane `j` is `FPAdd` of the operands' lanes `j`. -/
theorem fadd_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_add_fp datasize elements esize a b fpcr false) esize
      = (List.range elements).map (fun j => (Sail.FPAdd (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_add_fp
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPAdd (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

/-- **`fsub`** (`abs` false): lane `j` is `FPSub` of the lanes. -/
theorem fsub_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_sub_fp datasize elements esize a b fpcr false) esize
      = (List.range elements).map (fun j => (Sail.FPSub (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_sub_fp
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : BitVec esize × BitVec esize × BitVec esize × BitVec datasize) (j : Int) =>
      (Sail.FPSub (aget_Elem a j.toNat esize) (aget_Elem b j.toNat esize) fpcr, aget_Elem a j.toNat esize, aget_Elem b j.toNat esize,
        aset_Elem s.2.2.2 j.toNat esize (Sail.FPSub (aget_Elem a j.toNat esize) (aget_Elem b j.toNat esize) fpcr)))
      (Zeros esize, Zeros esize, Zeros esize, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2.2) esize = _
  rw [result_of_lane_loop4b esize _ (fun j => Sail.FPSub (aget_Elem a j esize) (aget_Elem b j esize) fpcr)
    (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPSub (aget_Elem a j esize) (aget_Elem b j esize) fpcr)]
  simp only [List.foldl_map, Int.toNat_natCast]
  exact lanes_of_fold_write esize elements h hs _ (Zeros datasize)

/-- **`fmul`**: lane `j` is `FPMul` of the lanes. -/
theorem fmul_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_mul_fp_product datasize elements esize a b fpcr) esize
      = (List.range elements).map (fun j => (Sail.FPMul (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_mul_fp_product
  simp only [Id.run, bind, pure]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMul (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

/-- **`fmla`** (`sub_op` false): lane `j` is `FPMulAdd` of the accumulator's
lane and the multiplicands' lanes — one rounding, the verifier's `fma`. -/
theorem fmla_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b c : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_mul_fp_fused datasize elements esize a b c fpcr false) esize
      = (List.range elements).map (fun j => (Sail.FPMulAdd (aget_Elem c j esize) (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_mul_fp_fused
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMulAdd (aget_Elem c j esize) (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

/-- **`fmls`** (`sub_op` true): the first multiplicand negated. -/
theorem fmls_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b c : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_mul_fp_fused datasize elements esize a b c fpcr true) esize
      = (List.range elements).map (fun j => (Sail.FPMulAdd (aget_Elem c j esize) (FPNeg (aget_Elem a j esize)) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_mul_fp_fused
  simp only [Id.run, bind, pure, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => FPNeg (aget_Elem a j esize)) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMulAdd (aget_Elem c j esize) (FPNeg (aget_Elem a j esize)) (aget_Elem b j esize) fpcr)

/-- **`fmin`** / **`fmax`** (1985 semantics, `pair` false). -/
theorem fmin_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_maxmin_fp_1985 datasize elements esize a b fpcr true false) esize
      = (List.range elements).map (fun j => (Sail.FPMin (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_maxmin_fp_1985
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMin (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

theorem fmax_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_maxmin_fp_1985 datasize elements esize a b fpcr false false) esize
      = (List.range elements).map (fun j => (Sail.FPMax (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_maxmin_fp_1985
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMax (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

/-- **`fminnm`** / **`fmaxnm`** (2008 semantics, `pair` false). -/
theorem fminnm_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_maxmin_fp_2008 datasize elements esize a b fpcr true false) esize
      = (List.range elements).map (fun j => (Sail.FPMinNum (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_maxmin_fp_2008
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMinNum (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

theorem fmaxnm_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_maxmin_fp_2008 datasize elements esize a b fpcr false false) esize
      = (List.range elements).map (fun j => (Sail.FPMaxNum (aget_Elem a j esize) (aget_Elem b j esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_maxmin_fp_2008
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize) (fun j => aget_Elem b j esize)
    (fun j => Sail.FPMaxNum (aget_Elem a j esize) (aget_Elem b j esize) fpcr)

/-- The unary write loop (the two-local shape element, result). -/
theorem float_unary_lanes_of_loop (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (f₁ : Nat → BitVec esize) (W : Nat → BitVec esize) :
    lanesOf ((List.foldl (fun (s : BitVec esize × BitVec datasize) (j : Int) =>
        (f₁ j.toNat, aset_Elem s.2 j.toNat esize (W j.toNat)))
      (Zeros esize, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2) esize
      = (List.range elements).map (fun j => (W j).toNat) := by
  rw [result_of_lane_loop2 esize _ f₁ W]
  simp only [List.foldl_map, Int.toNat_natCast]
  exact lanes_of_fold_write esize elements h hs W (Zeros datasize)

/-- **`fsqrt`**: lane `j` is `FPSqrt` of the lane. -/
theorem fsqrt_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_unary_special_sqrt datasize elements esize a fpcr) esize
      = (List.range elements).map (fun j => (Sail.FPSqrt (aget_Elem a j esize) fpcr).toNat) := by
  unfold vector_arithmetic_unary_special_sqrt
  simp only [Id.run, bind, pure]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_unary_lanes_of_loop datasize elements esize h hs (fun j => aget_Elem a j esize)
    (fun j => Sail.FPSqrt (aget_Elem a j esize) fpcr)

/-- **`fneg`** (`neg` true) and **`fabs`** (`neg` false): the sign operations lane for lane. -/
theorem fneg_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a : BitVec datasize) :
    lanesOf (vector_arithmetic_unary_diffneg_fp datasize elements esize a true) esize
      = (List.range elements).map (fun j => (FPNeg (aget_Elem a j esize)).toNat) := by
  unfold vector_arithmetic_unary_diffneg_fp
  simp only [Id.run, bind, pure, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_unary_lanes_of_loop datasize elements esize h hs (fun j => FPNeg (aget_Elem a j esize))
    (fun j => FPNeg (aget_Elem a j esize))

theorem fabs_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a : BitVec datasize) :
    lanesOf (vector_arithmetic_unary_diffneg_fp datasize elements esize a false) esize
      = (List.range elements).map (fun j => (FPAbs (aget_Elem a j esize)).toNat) := by
  unfold vector_arithmetic_unary_diffneg_fp
  simp only [Id.run, bind, pure, Bool.false_eq_true, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  exact float_unary_lanes_of_loop datasize elements esize h hs (fun j => FPAbs (aget_Elem a j esize))
    (fun j => FPAbs (aget_Elem a j esize))

/-- **`FPNeg`** flips the sign bit and **`FPAbs`** clears it — the verifier's
bit operations (asm/verify_float.go floatNeg, floatAbs), at both widths. The
generated code casts the one-plus-rest concatenation back to the width; the
`show` states the width arithmetic evaluated. -/
theorem FPNeg_32 (x : BitVec 32) : FPNeg x = x ^^^ 0x80000000#32 := by
  simp only [FPNeg, Sail.BitVec.length, join1_single, access_eq, Sail.BitVec.slice]
  show BitVec.setWidth 32 (~~~BitVec.ofBool (x.getLsbD 31) +++ BitVec.extractLsb' 0 31 x) = _
  rw [BitVec.setWidth_eq]
  bv_decide

theorem FPNeg_64 (x : BitVec 64) : FPNeg x = x ^^^ 0x8000000000000000#64 := by
  simp only [FPNeg, Sail.BitVec.length, join1_single, access_eq, Sail.BitVec.slice]
  show BitVec.setWidth 64 (~~~BitVec.ofBool (x.getLsbD 63) +++ BitVec.extractLsb' 0 63 x) = _
  rw [BitVec.setWidth_eq]
  bv_decide

theorem FPAbs_32 (x : BitVec 32) : FPAbs x = x &&& 0x7fffffff#32 := by
  simp only [FPAbs, Sail.BitVec.length, Sail.BitVec.slice]
  show BitVec.setWidth 32 (0#1 +++ BitVec.extractLsb' 0 31 x) = _
  rw [BitVec.setWidth_eq]
  bv_decide

theorem FPAbs_64 (x : BitVec 64) : FPAbs x = x &&& 0x7fffffffffffffff#64 := by
  simp only [FPAbs, Sail.BitVec.length, Sail.BitVec.slice]
  show BitVec.setWidth 64 (0#1 +++ BitVec.extractLsb' 0 63 x) = _
  rw [BitVec.setWidth_eq]
  bv_decide

/-- The write loop's result over the Int-indexed lanes the generated code
computes with (`2 * e`, `2 * e + 1` in Int arithmetic). -/
theorem result_of_lane_loop_int {E₁ E₂ : Type} {N : Nat} (size : Nat) (init : E₁ × E₂ × BitVec N)
    (f₁ : Int → E₁) (f₂ : Int → E₂) (W : Int → BitVec size) (l : List Int) :
    (l.foldl (fun (s : E₁ × E₂ × BitVec N) j =>
        (f₁ j, f₂ j, aset_Elem s.2.2 j.toNat size (W j))) init).2.2
      = l.foldl (fun r j => aset_Elem r j.toNat size (W j)) init.2.2 :=
  foldl_proj (β := E₁ × E₂ × BitVec N) (γ := BitVec N) (fun s => s.2.2)
    (fun j s => (f₁ j, f₂ j, aset_Elem s.2.2 j.toNat size (W j)))
    (fun j r => aset_Elem r j.toNat size (W j)) (fun _ _ => rfl) l init

/-- **`faddp`** (`pair` true): lane `j` is `FPAdd` of lanes `2j` and `2j+1` of
`operand2 @ operand1` (the generated code casts the concatenation to
`2 * datasize` bits) — the adjacent pairs of the first operand, then of
the second, the shape the verifier's `faddp` builds and the pairwise
`reduce_add` tree is made of. -/
theorem faddp_lanes (datasize elements esize : Nat) (h : elements * esize = datasize) (hs : 0 < esize)
    (a b : BitVec datasize) (fpcr : BitVec 32) :
    lanesOf (vector_arithmetic_binary_uniform_add_fp datasize elements esize a b fpcr true) esize
      = (List.range elements).map (fun j => (Sail.FPAdd (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j) esize) (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j + 1) esize) fpcr).toNat) := by
  unfold vector_arithmetic_binary_uniform_add_fp
  simp only [Id.run, bind, pure, ↓reduceIte]
  rw [show ({ stop := (elements : Int) - 1 } : IntRange) = laneRange elements from rfl, forIn_laneRange_fold]
  show lanesOf ((List.foldl (fun (s : BitVec esize × BitVec esize × BitVec datasize) (j : Int) =>
      (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j).toNat esize, aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j + 1).toNat esize,
        aset_Elem s.2.2 j.toNat esize (Sail.FPAdd (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j).toNat esize) (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j + 1).toNat esize) fpcr)))
      (Zeros esize, Zeros esize, Zeros datasize) (List.map (fun (x : Nat) => (x : Int)) (List.range elements))).2.2) esize = _
  rw [result_of_lane_loop_int esize _ (fun j => aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j).toNat esize) (fun j => aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j + 1).toNat esize)
    (fun j => Sail.FPAdd (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j).toNat esize) (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * j + 1).toNat esize) fpcr)]
  simp only [List.foldl_map, Int.toNat_natCast]
  rw [lanes_of_fold_write esize elements h hs (fun k => Sail.FPAdd (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * (k : Int)).toNat esize) (aget_Elem (BitVec.setWidth (2 * datasize) (b ++ a)) (2 * (k : Int) + 1).toNat esize) fpcr) (Zeros datasize)]
  apply List.map_congr_left
  intro j _
  have h2 : (2 * (j : Int)).toNat = 2 * j := by omega
  have h3 : (2 * (j : Int) + 1).toNat = 2 * j + 1 := by omega
  simp only [h2, h3]

end Lanes

end Oak.SailBridge
