#!/usr/bin/env python3
"""Repair the Sail RISC-V Lean export where the Lean backend leaves type-level
functions untranslated (rems-project/sail#1729, open as of 2026-09-13).

Pinned to sail-riscv 0.14 generated by Sail dba5f007 (sail2, 2026-09-11):
the export's virtual-memory type synonyms `vpn_level_size`, `pte_bits`,
`ppn_bits` apply `is_sv32_mode(k_v)` in Sail syntax and never define the
type-level predicates of model/core/vmem_types.sail, so `Defs.lean` does
not parse. This script defines those predicates as Lean abbreviations,
gives the synonyms their `k_v` parameter, and rewrites the applications;
in Vmem.lean it repairs three type ascriptions a same-named function
shadows and gives the two-stage translation's mutual recursion a
termination measure Lean accepts. It touches nothing about instruction
semantics (what the bridge in OakSailBridge/ imports). Idempotent; rerun
after `cmake --build build --target generated_lean_rv64d` regenerates
the files.

Usage: python3 spec/lean-sail/patch-export.py [path/to/Defs.lean]
"""
import re
import sys

path = sys.argv[1] if len(sys.argv) > 1 else "external/sail-riscv/build/model/Lean_RV64D/LeanRV64D/Defs.lean"
src = open(path, encoding="utf-8").read()
marker = "-- oak-sail-bridge patch (rems-project/sail#1729)"
already = marker in src
if already:
    print("already patched:", path)

predicates = f"""{marker}: the type-level predicates of
-- model/core/vmem_types.sail the Lean backend does not export.
abbrev is_sv_mode (k_v : Nat) : Bool := k_v == 32 || k_v == 39 || k_v == 48 || k_v == 57
abbrev is_svx4_mode (k_v : Nat) : Bool := k_v == 34 || k_v == 41 || k_v == 50 || k_v == 59
abbrev is_sv_or_svx4_mode (k_v : Nat) : Bool := is_sv_mode k_v || is_svx4_mode k_v
abbrev is_sv32_mode (k_v : Nat) : Bool := k_v == 32 || k_v == 34

"""
n = 0
def sub(pattern, repl, count=1):
    if already:
        return
    global src, n
    src, k = re.subn(pattern, repl, src, count=count, flags=re.M)
    n += k
    if k == 0:
        print("pattern not found:", pattern, file=sys.stderr)

sub(r"^abbrev root_level : Int :=", predicates + "abbrev root_level (k_v : Nat) : Int :=")
sub(r"^abbrev vpn_level_size : Int :=", "abbrev vpn_level_size (k_v : Nat) : Int :=")
sub(r"^abbrev (pte_bits|ppn_bits) k_v :=", r"abbrev \1 (k_v : Nat) :=", count=2)
# `( f(k_v)  : Bool)` — a Sail application inside a type-level `if`.
sub(r"\( ([a-z_0-9]+)\((k_[a-z0-9]+)\) +: Bool\)", r"(\1 \2 : Bool)", count=0)
if not already:
    open(path, "w", encoding="utf-8").write(src)
    print(f"patched {path}: {n} edits")

# Vmem.lean, next to Defs.lean: the backend's four remaining slips there.
# `satp_mode` / `hgatp_mode` name both a type synonym (BitVec 4, Defs) and a
# function (Vmem); inside Vmem the function shadows the synonym in three
# `( … : SailM satp_mode )` ascriptions. And pt_walk recurses on `level -i 1`
# under a Bool `if`, so the default termination tactic has no hypothesis;
# a dependent `if` and a `decreasing_by` supply it.
vmem = path.replace("Defs.lean", "Vmem.lean")
try:
    vsrc = open(vmem, encoding="utf-8").read()
except FileNotFoundError:
    sys.exit(0)
vmarker = "-- oak-sail-bridge patch (rems-project/sail#1729): Vmem"
if vmarker in vsrc:
    print("already patched:", vmem)
    sys.exit(0)
m = 0
vsrc, k = re.subn(r": SailM (satp_mode|hgatp_mode) \)", r": SailM (BitVec 4) )", vsrc); m += k
vsrc, k = re.subn(r"^(\s*)if \(\(level >b 0\) : Bool\)\n(\s*)then\n(\s*)\(pt_walk ",
                  r"\1if h_level : ((level >b 0) : Bool)\n\2then\n\3(pt_walk ", vsrc, count=1, flags=re.M); m += k
# The two-stage translation is one mutual block (pt_walk, translate,
# translate_PTE_addr, translate_TLB_hit, translate_TLB_miss,
# translate_g_stage, translate_stage, update_and_write_pte) whose Sail
# measure is the constant 1000 except pt_walk's level: Lean sees no
# decrease across the VS-stage walk's call into the G-stage translation.
# A lexicographic measure (stage rank: VS_Stage 1, else 0; a rank per
# function along the call chain; the walk level) decreases on every call.
rank = "(if stage == VS_Stage then 1 else 0 : Nat)"
measures = {
    "translate_g_stage": "((0 : Nat), (7 : Nat), (0 : Nat))",
    "translate_stage": f"({rank}, (6 : Nat), (0 : Nat))",
    "translate": f"({rank}, (5 : Nat), (0 : Nat))",
    "translate_TLB_hit": f"({rank}, (4 : Nat), (0 : Nat))",
    "translate_TLB_miss": f"({rank}, (4 : Nat), (0 : Nat))",
    "update_and_write_pte": f"({rank}, (3 : Nat), (0 : Nat))",
    "pt_walk": f"({rank}, (2 : Nat), level)",
    "translate_PTE_addr": f"({rank}, (1 : Nat), (0 : Nat))",
}
tactic = ("decreasing_by\n  " + vmarker + "\n"
          "  all_goals simp_wf\n"
          "  all_goals simp only [Prod.lex_def, Int.pred_toNat, Int.toNat_natCast] at *\n"
          "  all_goals (try simp_all)\n"
          "  all_goals (try split) <;> (try simp_all) <;> first | rfl | decide | omega")
block = re.compile(r"^termination_by \(let \([^)]*\) :=[\s\S]*?\n(?:1000|level)\)\.toNat$", re.M)
for name, measure in measures.items():
    head = re.search(r"^def " + name + r" ", vsrc, re.M)
    if head is None:
        print("no def", name, file=sys.stderr)
        continue
    tb = block.search(vsrc, head.end())
    if tb is None:
        print("no termination_by after", name, file=sys.stderr)
        continue
    vsrc = vsrc[:tb.start()] + "termination_by " + measure + "\n" + tactic + vsrc[tb.end():]
    m += 1
open(vmem, "w", encoding="utf-8").write(vsrc)
print(f"patched {vmem}: {m} edits")
