package typechecker

import (
	"github.com/SCKelemen/oak/ast"
)

// TypeLattice implements Oak's semantic lattice over opaque atomic types.
//
// never is bottom, any is top, UnionType is semantic join, and
// IntersectionType is semantic meet. Atomic types have no subtype relation
// beyond latticeAtomIdentical. Type.Equals also carries a few compatibility
// relations, so it is intentionally not the atom equality used here;
// nominal/structural feature-specific relations belong in their own checking
// rules rather than being smuggled into this lattice.

// A lattice clause is a conjunction of atomic types. A DNF is a disjunction
// of such clauses. This gives a small, complete decision procedure for the
// free distributive lattice generated by Oak's otherwise-incomparable atoms.
//
// The procedure (clauseImplies, latticeDNFOf, mergeClauses, IsSubtype's
// clause loop) is maintained as a line-for-line transliteration of
// spec/lean/Oak/TypeLatticeRefinement.lean, which proves it sound (accepted
// pairs are semantically contained under every valuation of the atoms),
// complete (rejected pairs have a countermodel), and normalization-faithful
// (DNF conversion preserves denotation) against the Oak.TypeLattice laws.
// The Lean model uses binary union/intersection; the n-ary folds here agree
// by associativity of join/meet.
type latticeClause []Type
type latticeDNF []latticeClause

func clauseContains(clause latticeClause, typ Type) bool {
	for _, existing := range clause {
		if latticeAtomIdentical(existing, typ) {
			return true
		}
	}
	return false
}

func mergeClauses(left, right latticeClause) latticeClause {
	merged := make(latticeClause, 0, len(left)+len(right))
	merged = append(merged, left...)
	for _, typ := range right {
		if !clauseContains(merged, typ) {
			merged = append(merged, typ)
		}
	}
	return merged
}

// latticeDNFOf normalizes only the semantic lattice constructors. All other
// Type implementations are opaque nominal atoms here.
func latticeDNFOf(typ Type) latticeDNF {
	switch t := typ.(type) {
	case *NeverType:
		// False: no satisfying clauses.
		return nil
	case *AnyType:
		// True: one empty conjunction.
		return latticeDNF{latticeClause{}}
	case *UnionType:
		var result latticeDNF
		for _, member := range t.Types {
			result = append(result, latticeDNFOf(member)...)
		}
		return result
	case *IntersectionType:
		// Empty meet is top. Intersections distribute over unions by taking
		// the cartesian product of their DNF clauses.
		result := latticeDNF{latticeClause{}}
		for _, member := range t.Types {
			memberDNF := latticeDNFOf(member)
			if len(memberDNF) == 0 {
				return nil
			}

			next := make(latticeDNF, 0, len(result)*len(memberDNF))
			for _, left := range result {
				for _, right := range memberDNF {
					next = append(next, mergeClauses(left, right))
				}
			}
			result = next
		}
		return result
	default:
		return latticeDNF{latticeClause{typ}}
	}
}

// clauseImplies reports whether conjunction left implies conjunction right.
// With nominally-incomparable atoms, this holds exactly when every atom
// required by right is already required by left.
func clauseImplies(left, right latticeClause) bool {
	for _, required := range right {
		if !clauseContains(left, required) {
			return false
		}
	}
	return true
}

// IsSubtype checks whether t1 <= t2 in Oak's semantic type lattice.
//
// Converting both sides to DNF makes all join/meet laws explicit:
//
//	A <= A | B
//	B <= A | B
//	A & B <= A
//	A & B <= B
//
// and the corresponding least-upper-bound / greatest-lower-bound rules.
func IsSubtype(t1, t2 Type) bool {
	left := latticeDNFOf(t1)
	right := latticeDNFOf(t2)

	// Every possible left clause must imply at least one right clause.
	// An empty left DNF is never/bottom, so this is vacuously true.
	for _, leftClause := range left {
		matched := false
		for _, rightClause := range right {
			if clauseImplies(leftClause, rightClause) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

// latticeSubtypeWithoutRepresentation reports the semantic lattice steps that
// are also valid at an ordinary value-flow boundary today. Semantic inclusion
// alone does not choose a runtime representation: in particular, `T <= any`
// and `T <= T | U` must not silently introduce boxing, tags, allocation, or
// RTTI. Exact types need no conversion, and never needs no representation
// because it produces no value. Feature-specific representation-preserving
// relations such as numeric widening, refinement erasure, record-shape
// satisfaction, and alignment are composed by TypeChecker.isAssignable.
func latticeSubtypeWithoutRepresentation(valueType, targetType Type) bool {
	if !IsSubtype(valueType, targetType) {
		return false
	}
	if _, isNever := valueType.(*NeverType); isNever {
		return true
	}
	return latticeAtomIdentical(valueType, targetType)
}

// Join computes the least upper bound (join) of types
// For union types: join(A, B) = A | B (when defined)
// For our minimal lattice:
// - join(T, T) = T
// - join(T, any) = any
// - join(T, never) = T
// - join(A, B) = A | B for union types
// - join(T1, T2) where T1 != T2 and neither is any/never = T1 | T2
// weakestAlignment is the join of structurally equal view or span types
// under the alignment fact's order (docs/spec/50-borrowing.md section 2a):
// a value from any arm must satisfy the fact, so the joined type carries
// the weakest one — none when any arm has none — never the first arm's.
func weakestAlignment(types []Type) Type {
	first, isArray := types[0].(*ArrayType)
	if !isArray || !(first.IsSlice || first.IsSpan) {
		return types[0]
	}
	align := first.Align
	for _, t := range types[1:] {
		if other, isOther := t.(*ArrayType); isOther && other.Align < align {
			align = other.Align
		}
	}
	if align == first.Align {
		return first
	}
	joined := *first
	joined.Align = align
	return &joined
}

func sameAlignmentShape(types []Type) bool {
	first, ok := types[0].(*ArrayType)
	if !ok || !(first.IsSlice || first.IsSpan) {
		return false
	}
	for _, typ := range types[1:] {
		other, ok := typ.(*ArrayType)
		if !ok || other.Length != first.Length || other.IsSlice != first.IsSlice ||
			other.IsSpan != first.IsSpan || !latticeAtomIdentical(other.ElementType, first.ElementType) {
			return false
		}
	}
	return true
}

// joinValueFlowTypes preserves the representation-free alignment weakening
// used when inferred match arms return the same view/span shape. Alignment is
// a separate fact order, not an atom relation in the proved free lattice, so
// the public lattice Join remains a true upper bound under IsSubtype.
func joinValueFlowTypes(types ...Type) Type {
	joined := Join(types...)
	nonNever := make([]Type, 0, len(types))
	for _, typ := range types {
		if _, isNever := typ.(*NeverType); !isNever {
			nonNever = append(nonNever, typ)
		}
	}
	if len(nonNever) != 0 && sameAlignmentShape(nonNever) {
		return weakestAlignment(nonNever)
	}
	return joined
}

func allLatticeTypesIdentical(types []Type) bool {
	for _, typ := range types[1:] {
		if !latticeAtomIdentical(types[0], typ) {
			return false
		}
	}
	return true
}

func Join(types ...Type) Type {
	if len(types) == 0 {
		return &NeverType{} // Empty join is bottom
	}

	if len(types) == 1 {
		return types[0]
	}

	// Filter out never types (they don't affect the join)
	nonNeverTypes := []Type{}
	for _, t := range types {
		if _, ok := t.(*NeverType); !ok {
			nonNeverTypes = append(nonNeverTypes, t)
		}
	}

	// If all were never, result is never
	if len(nonNeverTypes) == 0 {
		return &NeverType{}
	}

	// If any is any, result is any
	for _, t := range nonNeverTypes {
		if _, ok := t.(*AnyType); ok {
			return &AnyType{}
		}
	}

	// Collapse only strict atom identity, never the broader Type.Equals
	// compatibility relation. Representation facts such as alignment are
	// composed separately at value-flow boundaries.
	if allLatticeTypesIdentical(nonNeverTypes) {
		return nonNeverTypes[0]
	}

	// For two types, create a union type A | B
	if len(nonNeverTypes) == 2 {
		return &UnionType{Types: nonNeverTypes}
	}

	// For multiple types, create a union type
	// Flatten any existing union types
	flattened := []Type{}
	for _, t := range nonNeverTypes {
		if union, ok := t.(*UnionType); ok {
			flattened = append(flattened, union.Types...)
		} else {
			flattened = append(flattened, t)
		}
	}
	return &UnionType{Types: flattened}
}

// Meet computes the greatest lower bound (meet) of types
// For intersection types: meet(A, B) = A & B (when defined)
// For our minimal lattice:
// - meet(T, T) = T
// - meet(T, never) = never
// - meet(T, any) = T
// - meet(A, B) = A & B for intersection types
// - meet(T1, T2) where T1 != T2 and neither is never/any = T1 & T2
func Meet(types ...Type) Type {
	if len(types) == 0 {
		return &AnyType{} // Empty meet is top
	}

	if len(types) == 1 {
		return types[0]
	}

	// If any is never, result is never
	for _, t := range types {
		if _, ok := t.(*NeverType); ok {
			return &NeverType{}
		}
	}

	// If any is any, filter it out (any doesn't affect meet)
	nonAnyTypes := []Type{}
	for _, t := range types {
		if _, ok := t.(*AnyType); !ok {
			nonAnyTypes = append(nonAnyTypes, t)
		}
	}

	// If all were any, result is any
	if len(nonAnyTypes) == 0 {
		return &AnyType{}
	}

	// Compatible-but-distinct types remain a real intersection instead of
	// being collapsed by Equals.
	if allLatticeTypesIdentical(nonAnyTypes) {
		return nonAnyTypes[0]
	}

	// For two types, create an intersection type A & B
	if len(nonAnyTypes) == 2 {
		return &IntersectionType{Types: nonAnyTypes}
	}

	// For multiple types, create an intersection type
	// Flatten any existing intersection types
	flattened := []Type{}
	for _, t := range nonAnyTypes {
		if intersection, ok := t.(*IntersectionType); ok {
			flattened = append(flattened, intersection.Types...)
		} else {
			flattened = append(flattened, t)
		}
	}
	return &IntersectionType{Types: flattened}
}

// NarrowType narrows a type based on pattern matching
// For ADT variants, returns a narrowed variant type
// For literal patterns, returns the literal's type if it matches
// Otherwise returns the original type
func NarrowType(originalType Type, pattern ast.Pattern) Type {
	// For variant patterns, narrow to that specific variant
	if variantPattern, ok := pattern.(*ast.VariantPattern); ok {
		switch adtType := originalType.(type) {
		case *ADTType:
			return &NarrowedADTVariantType{
				ADTName:     adtType.Name,
				VariantName: variantPattern.Variant.Value,
			}
		case *GenericType:
			return &NarrowedADTVariantType{
				ADTName:     adtType.Name,
				VariantName: variantPattern.Variant.Value,
				TypeArgs:    append([]Type(nil), adtType.TypeArgs...),
			}
		}
	}

	// For literal patterns, if the literal type matches, we can narrow
	// (This is more advanced and can be expanded later)

	// For wildcard or binding patterns, no narrowing
	return originalType
}

// JoinNarrowedTypes joins narrowed types back to the original type
// Used to verify that pattern matching branches cover all cases
func JoinNarrowedTypes(narrowedTypes []Type) Type {
	// Convert narrowed variant types back to their ADT types
	adtTypes := []Type{}
	for _, nt := range narrowedTypes {
		if narrowed, ok := nt.(*NarrowedADTVariantType); ok {
			if len(narrowed.TypeArgs) > 0 {
				adtTypes = append(adtTypes, &GenericType{Name: narrowed.ADTName, TypeArgs: narrowed.TypeArgs})
			} else {
				adtTypes = append(adtTypes, &ADTType{Name: narrowed.ADTName})
			}
		} else {
			adtTypes = append(adtTypes, nt)
		}
	}

	// Join them
	return Join(adtTypes...)
}
