package typechecker

import (
	"github.com/SCKelemen/oak/ast"
)

// TypeLattice implements Oak's semantic lattice over nominal atomic types.
//
// never is bottom, any is top, UnionType is semantic join, and
// IntersectionType is semantic meet. Atomic types have no subtype relation
// beyond Type.Equals; nominal/structural feature-specific relations belong in
// their own checking rules rather than being smuggled into this lattice.

// A lattice clause is a conjunction of atomic types. A DNF is a disjunction
// of such clauses. This gives a small, complete decision procedure for the
// free distributive lattice generated by Oak's otherwise-incomparable atoms.
type latticeClause []Type
type latticeDNF []latticeClause

func clauseContains(clause latticeClause, typ Type) bool {
	for _, existing := range clause {
		if existing.Equals(typ) {
			return true
		}
	}
	return false
}

func mergeClauses(left, right latticeClause) latticeClause {
	merged := make(latticeClause, 0, len(left)+len(right))
	merged = append(merged, left...)
	for _, typ := range right {
		if !clauseContains(merged, typ) {
			merged = append(merged, typ)
		}
	}
	return merged
}

// latticeDNFOf normalizes only the semantic lattice constructors. All other
// Type implementations are opaque nominal atoms here.
func latticeDNFOf(typ Type) latticeDNF {
	switch t := typ.(type) {
	case *NeverType:
		// False: no satisfying clauses.
		return nil
	case *AnyType:
		// True: one empty conjunction.
		return latticeDNF{latticeClause{}}
	case *UnionType:
		var result latticeDNF
		for _, member := range t.Types {
			result = append(result, latticeDNFOf(member)...)
		}
		return result
	case *IntersectionType:
		// Empty meet is top. Intersections distribute over unions by taking
		// the cartesian product of their DNF clauses.
		result := latticeDNF{latticeClause{}}
		for _, member := range t.Types {
			memberDNF := latticeDNFOf(member)
			if len(memberDNF) == 0 {
				return nil
			}

			next := make(latticeDNF, 0, len(result)*len(memberDNF))
			for _, left := range result {
				for _, right := range memberDNF {
					next = append(next, mergeClauses(left, right))
				}
			}
			result = next
		}
		return result
	default:
		return latticeDNF{latticeClause{typ}}
	}
}

// clauseImplies reports whether conjunction left implies conjunction right.
// With nominally-incomparable atoms, this holds exactly when every atom
// required by right is already required by left.
func clauseImplies(left, right latticeClause) bool {
	for _, required := range right {
		if !clauseContains(left, required) {
			return false
		}
	}
	return true
}

// IsSubtype checks whether t1 <= t2 in Oak's semantic type lattice.
//
// Converting both sides to DNF makes all join/meet laws explicit:
//   A <= A | B
//   B <= A | B
//   A & B <= A
//   A & B <= B
// and the corresponding least-upper-bound / greatest-lower-bound rules.
func IsSubtype(t1, t2 Type) bool {
	left := latticeDNFOf(t1)
	right := latticeDNFOf(t2)

	// Every possible left clause must imply at least one right clause.
	// An empty left DNF is never/bottom, so this is vacuously true.
	for _, leftClause := range left {
		matched := false
		for _, rightClause := range right {
			if clauseImplies(leftClause, rightClause) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

// Join computes the least upper bound (join) of types
// For union types: join(A, B) = A | B (when defined)
// For our minimal lattice:
// - join(T, T) = T
// - join(T, any) = any
// - join(T, never) = T
// - join(A, B) = A | B for union types
// - join(T1, T2) where T1 != T2 and neither is any/never/union = any (incomparable)
func Join(types ...Type) Type {
	if len(types) == 0 {
		return &NeverType{} // Empty join is bottom
	}

	if len(types) == 1 {
		return types[0]
	}

	// Filter out never types (they don't affect the join)
	nonNeverTypes := []Type{}
	for _, t := range types {
		if _, ok := t.(*NeverType); !ok {
			nonNeverTypes = append(nonNeverTypes, t)
		}
	}

	// If all were never, result is never
	if len(nonNeverTypes) == 0 {
		return &NeverType{}
	}

	// If any is any, result is any
	for _, t := range nonNeverTypes {
		if _, ok := t.(*AnyType); ok {
			return &AnyType{}
		}
	}

	// Check if all types are equal
	firstType := nonNeverTypes[0]
	allEqual := true
	for i := 1; i < len(nonNeverTypes); i++ {
		if !nonNeverTypes[i].Equals(firstType) {
			allEqual = false
			break
		}
	}

	if allEqual {
		return firstType
	}

	// For two types, create a union type A | B
	if len(nonNeverTypes) == 2 {
		return &UnionType{Types: nonNeverTypes}
	}

	// For multiple types, create a union type
	// Flatten any existing union types
	flattened := []Type{}
	for _, t := range nonNeverTypes {
		if union, ok := t.(*UnionType); ok {
			flattened = append(flattened, union.Types...)
		} else {
			flattened = append(flattened, t)
		}
	}
	return &UnionType{Types: flattened}
}

// Meet computes the greatest lower bound (meet) of types
// For intersection types: meet(A, B) = A & B (when defined)
// For our minimal lattice:
// - meet(T, T) = T
// - meet(T, never) = never
// - meet(T, any) = T
// - meet(A, B) = A & B for intersection types
// - meet(T1, T2) where T1 != T2 and neither is never/any/intersection = never (incomparable)
func Meet(types ...Type) Type {
	if len(types) == 0 {
		return &AnyType{} // Empty meet is top
	}

	if len(types) == 1 {
		return types[0]
	}

	// If any is never, result is never
	for _, t := range types {
		if _, ok := t.(*NeverType); ok {
			return &NeverType{}
		}
	}

	// If any is any, filter it out (any doesn't affect meet)
	nonAnyTypes := []Type{}
	for _, t := range types {
		if _, ok := t.(*AnyType); !ok {
			nonAnyTypes = append(nonAnyTypes, t)
		}
	}

	// If all were any, result is any
	if len(nonAnyTypes) == 0 {
		return &AnyType{}
	}

	// Check if all types are equal
	firstType := nonAnyTypes[0]
	allEqual := true
	for i := 1; i < len(nonAnyTypes); i++ {
		if !nonAnyTypes[i].Equals(firstType) {
			allEqual = false
			break
		}
	}

	if allEqual {
		return firstType
	}

	// For two types, create an intersection type A & B
	if len(nonAnyTypes) == 2 {
		return &IntersectionType{Types: nonAnyTypes}
	}

	// For multiple types, create an intersection type
	// Flatten any existing intersection types
	flattened := []Type{}
	for _, t := range nonAnyTypes {
		if intersection, ok := t.(*IntersectionType); ok {
			flattened = append(flattened, intersection.Types...)
		} else {
			flattened = append(flattened, t)
		}
	}
	return &IntersectionType{Types: flattened}
}

// NarrowType narrows a type based on pattern matching
// For ADT variants, returns a narrowed variant type
// For literal patterns, returns the literal's type if it matches
// Otherwise returns the original type
func NarrowType(originalType Type, pattern ast.Pattern) Type {
	// For variant patterns, narrow to that specific variant
	if variantPattern, ok := pattern.(*ast.VariantPattern); ok {
		if adtType, ok := originalType.(*ADTType); ok {
			return &NarrowedADTVariantType{
				ADTName:     adtType.Name,
				VariantName: variantPattern.Variant.Value,
			}
		}
	}

	// For literal patterns, if the literal type matches, we can narrow
	// (This is more advanced and can be expanded later)

	// For wildcard or binding patterns, no narrowing
	return originalType
}

// JoinNarrowedTypes joins narrowed types back to the original type
// Used to verify that pattern matching branches cover all cases
func JoinNarrowedTypes(narrowedTypes []Type) Type {
	// Convert narrowed variant types back to their ADT types
	adtTypes := []Type{}
	for _, nt := range narrowedTypes {
		if narrowed, ok := nt.(*NarrowedADTVariantType); ok {
			adtTypes = append(adtTypes, &ADTType{Name: narrowed.ADTName})
		} else {
			adtTypes = append(adtTypes, nt)
		}
	}

	// Join them
	return Join(adtTypes...)
}
