package compiler

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// A record payload per protocol step (docs/spec/112-protocols.md section
// 1; the dbs pilot's ask 2): a declared record of command scalars is the
// step's payload, its fields read in guards and effects, quantified as a
// record set in the model-checker module, and generated by the
// typed-command derive.
const logProtocolSource = `
import(std)
Cmd: type = struct { slot: u8, value: u8 }
Log: protocol = {
  data { cells: [2]u8, writes: u32 }
  init { cells: [2]u8{ 0, 0 }, writes: u32(0) }
  initial Open
  write(cmd: Cmd): Open -> Open when u32(cmd.slot) < u32(2) && data.writes < u32(3) then { data.cells[u32(cmd.slot)] = cmd.value; data.writes = data.writes + u32(1) }
  seal: Open -> Sealed when data.writes > u32(0)
}
`

func TestE2EProtocolRecordPayload(t *testing.T) {
	// The typed-command derive generates and encodes the record payload
	// field by field (compiled with the testing host's externs, which only
	// `oak test` links).
	derived := logProtocolSource + `
import(testing)
step_generate: (choices: [*]TestChoices, data: []u8): LogStep = derive.test_generate
step_encode: (v: LogStep): TestCommand = derive.test_encode
step_decode: (command: TestCommand): Option[LogStep] = derive.test_decode
main: (): i32 = 0
`
	if _, err := New().WithSource("log_derive.oak", derived).EmitC().Get(); err != nil {
		t.Fatalf("typed commands over a record payload: %v", err)
	}
	src := logProtocolSource + `
is_sealed: (s: LogState): Bool = s ? | .Sealed => true | _ => false
main: (): i32 {
  store: [1]LogData
  data: [*]LogData = span(&store)
  data[0] = log_initial_data()
  s: LogState = log_initial()
  assert(!log_legal(s, data[0], .Seal))
  assert(!log_legal(s, data[0], .Write(Cmd { slot: u8(2), value: u8(7) })))
  assert(log_legal(s, data[0], .Write(Cmd { slot: u8(1), value: u8(7) })))
  s = log_next(s, data, .Write(Cmd { slot: u8(1), value: u8(7) }))
  s = log_next(s, data, .Write(Cmd { slot: u8(0), value: u8(3) }))
  assert(data[0].cells[u32(0)] == u8(3) && data[0].cells[u32(1)] == u8(7) && data[0].writes == u32(2))
  s = log_next(s, data, .Seal)
  is_sealed(s) ? 42 | 1
}
`
	code, abnormal := buildAndRun(t, "protocol_record_payload", src)
	if abnormal || code != 42 {
		t.Fatalf("exit=(%d,%v)", code, abnormal)
	}
	tree, err := New().WithSource("log.oak", logProtocolSource+"main: (): i32 = 0\n").Parse().Get()
	if err != nil {
		t.Fatal(err)
	}
	decl := Protocols(tree)[0]
	records := RecordDeclarations(tree.Root)
	module, err := ProtocolTLAWithRecords(decl, "log.oak", records)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"CONSTANTS CmdSlot, CmdValue",
		"Cmd == [slot: CmdSlot, value: CmdValue]",
		"Write(cmd) ==",
		"((cmd.slot < 2) /\\ (writes < 3))",
		"cells' = [cells EXCEPT ![cmd.slot] = cmd.value]",
		"(\\E cmd \\in Cmd : Write(cmd))",
	} {
		if !strings.Contains(module, want) {
			t.Fatalf("module lacks %q:\n%s", want, module)
		}
	}
	cfg := ProtocolTLCConfigWith(decl, records)
	if !strings.Contains(cfg, "    CmdSlot = {0, 1, 2, 3}\n    CmdValue = {0, 1, 2, 3}\n") {
		t.Fatalf("the record payload's fields each get a domain constant:\n%s", cfg)
	}
	// The projection agrees with itself: the domain definition is read as
	// a definition, not judged as an action.
	self, err := ProtocolConformance(decl, module, records)
	if err != nil {
		t.Fatal(err)
	}
	if !self.Conforms {
		t.Fatalf("self-conformance with a record payload:\n%s", FormatTLAConformance(self))
	}
	if _, _, reason := LocateTLC(); reason != "" {
		t.Skip(reason)
	}
	java, jar, _ := LocateTLC()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "Log.tla"), []byte(module), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "Log.cfg"), []byte(cfg), 0o644); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, java, "-cp", jar, "tlc2.TLC", "-deadlock", "-workers", "1", "Log.tla")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil || !strings.Contains(string(out), "No error has been found") {
		t.Fatalf("TLC: %v\n%s", err, out)
	}
}

// A record payload's fields are command scalars; anything else is a shape
// error naming the field.
func TestProtocolRecordPayloadRejections(t *testing.T) {
	cases := map[string]struct{ src, want string }{
		"array field": {`
Bad: type = struct { xs: [2]u8 }
P: protocol = {
  initial A
  go(cmd: Bad): A -> A
}
main: (): i32 = 0
`, "payload record Bad: field xs is"},
		"unknown type": {`
P: protocol = {
  initial A
  go(cmd: Mystery): A -> A
}
main: (): i32 = 0
`, "not one of u8, u16, u32, Bool, or a declared record"},
	}
	for name, c := range cases {
		_, err := New().WithSource("bad.oak", c.src).EmitC().Get()
		if err == nil || !strings.Contains(err.Error(), c.want) {
			t.Fatalf("%s: want %q, got %v", name, c.want, err)
		}
	}
}
