package compiler

// TLA+ projection of a protocol declaration (docs/spec/112-protocols.md):
// one VARIABLE per data field plus the control state, one action per step
// name — the disjunction of its lines, each `state = From /\ guard /\ state'
// = To /\ effects /\ UNCHANGED rest` — Next with payloads quantified over
// declared constant domains, TypeOK, Init from the declared initial data,
// and Spec. Guards and effects translate from the Oak subset a protocol
// line may use (field reads, the payload, literals, conversions, arithmetic,
// comparisons, Boolean connectives, field assignment); anything else stops
// the export with a message naming the line. The module is complete for
// what the declaration says; a scenario extends it for liveness and
// environment assumptions, so regeneration never overwrites them.

import (
	"fmt"
	"sort"
	"strings"

	"github.com/SCKelemen/oak/ast"
)

// ProtocolTLA renders the TLA+ module of one declaration, or the shape
// diagnostics that stop it.
func ProtocolTLA(decl *ast.ProtocolDeclaration, origin string) (string, error) {
	var problems []string
	m, ok := analyzeProtocol(decl, func(code string, node ast.Node, format string, args ...interface{}) {
		problems = append(problems, fmt.Sprintf(format, args...))
	})
	if !ok {
		return "", fmt.Errorf("protocol %s: %s", decl.Name.Value, strings.Join(problems, "; "))
	}
	var fields []ast.RecordField
	if decl.Data != nil {
		fields = decl.Data.FieldOrder
	}
	signed := false
	for _, f := range fields {
		if id, isIdent := f.Value.(*ast.Identifier); isIdent && strings.HasPrefix(id.Value, "i") {
			signed = true
		}
	}
	var b strings.Builder
	title := fmt.Sprintf(" MODULE %s ", m.name)
	pad := (77 - len(title)) / 2
	b.WriteString(strings.Repeat("-", pad) + title + strings.Repeat("-", 77-pad-len(title)) + "\n")
	fmt.Fprintf(&b, "\\* Generated by `oak protocol -tla %s` from %s. Do not edit: extend\n", m.name, origin)
	b.WriteString("\\* this module for liveness and environment assumptions, and regenerate.\n")
	if signed {
		b.WriteString("EXTENDS Integers\n\n")
	} else {
		b.WriteString("EXTENDS Naturals\n\n")
	}
	var constants []string
	seen := map[string]bool{}
	for _, step := range m.steps {
		if step.payload != nil {
			domain := domainName(step.payload.Name.Value)
			if !seen[domain] {
				seen[domain] = true
				constants = append(constants, domain)
			}
		}
	}
	if len(constants) > 0 {
		fmt.Fprintf(&b, "CONSTANTS %s\n\n", strings.Join(constants, ", "))
	}
	vars := []string{"state"}
	for _, f := range fields {
		vars = append(vars, f.Name)
	}
	fmt.Fprintf(&b, "VARIABLES %s\n\n", strings.Join(vars, ", "))
	fmt.Fprintf(&b, "vars == <<%s>>\n\n", strings.Join(vars, ", "))
	quoted := make([]string, len(m.states))
	for i, st := range m.states {
		quoted[i] = fmt.Sprintf("%q", st)
	}
	fmt.Fprintf(&b, "States == {%s}\n\n", strings.Join(quoted, ", "))
	initTerms := []string{fmt.Sprintf("state = %q", m.initial)}
	if decl.Init != nil {
		for _, f := range fields {
			value, err := tlaExpr(decl.Init.Fields[f.Name], "", true)
			if err != nil {
				return "", fmt.Errorf("protocol %s: init %s: %v", m.name, f.Name, err)
			}
			initTerms = append(initTerms, fmt.Sprintf("%s = %s", f.Name, value))
		}
	}
	fmt.Fprintf(&b, "Init ==\n    %s\n\n", strings.Join(initTerms, "\n    /\\ "))
	var nextTerms []string
	for _, step := range m.steps {
		head := variantName(step.name)
		payload := ""
		if step.payload != nil {
			payload = step.payload.Name.Value
			head = fmt.Sprintf("%s(%s)", variantName(step.name), payload)
			nextTerms = append(nextTerms, fmt.Sprintf("(\\E %s \\in %s : %s)", payload, domainName(payload), head))
		} else {
			nextTerms = append(nextTerms, variantName(step.name))
		}
		fmt.Fprintf(&b, "%s ==\n", head)
		for i, line := range step.lines {
			terms := []string{fmt.Sprintf("state = %q", line.From.Value)}
			if line.Guard != nil {
				guard, err := tlaExpr(line.Guard, payload, false)
				if err != nil {
					return "", fmt.Errorf("protocol %s: %s from %s: guard: %v", m.name, step.name, line.From.Value, err)
				}
				terms = append(terms, guard)
			}
			terms = append(terms, fmt.Sprintf("state' = %q", line.To.Value))
			assigned := map[string]bool{}
			if line.Effects != nil {
				for _, stmt := range line.Effects.Statements {
					store, isStore := stmt.(*ast.IndexAssignmentStatement)
					field, isField := dataField(store)
					if !isStore || !isField {
						return "", fmt.Errorf("protocol %s: %s from %s: effects: only `data.field = expr` translates", m.name, step.name, line.From.Value)
					}
					value, err := tlaExpr(store.Value, payload, false)
					if err != nil {
						return "", fmt.Errorf("protocol %s: %s from %s: effect %s: %v", m.name, step.name, line.From.Value, field, err)
					}
					terms = append(terms, fmt.Sprintf("%s' = %s", field, value))
					assigned[field] = true
				}
			}
			var unchanged []string
			for _, f := range fields {
				if !assigned[f.Name] {
					unchanged = append(unchanged, f.Name)
				}
			}
			if len(unchanged) > 0 {
				terms = append(terms, fmt.Sprintf("UNCHANGED <<%s>>", strings.Join(unchanged, ", ")))
			}
			connector := "    "
			if len(step.lines) > 1 {
				connector = "    \\/ "
			}
			_ = i
			fmt.Fprintf(&b, "%s%s\n", connector, strings.Join(terms, " /\\ "))
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "Next ==\n    %s\n\n", strings.Join(nextTerms, "\n    \\/ "))
	typeTerms := []string{"state \\in States"}
	for _, f := range fields {
		typeTerms = append(typeTerms, fmt.Sprintf("%s \\in %s", f.Name, tlaDomain(f.Value)))
	}
	fmt.Fprintf(&b, "TypeOK ==\n    %s\n\n", strings.Join(typeTerms, "\n    /\\ "))
	b.WriteString("Spec == Init /\\ [][Next]_vars\n")
	b.WriteString(strings.Repeat("=", 77) + "\n")
	return b.String(), nil
}

// domainName is the constant naming a payload's domain: compare -> Compare.
func domainName(param string) string {
	if param == "" {
		return "Payload"
	}
	return strings.ToUpper(param[:1]) + param[1:]
}

// tlaDomain maps a field's Oak type to its TLA+ set.
func tlaDomain(typ ast.Expression) string {
	id, ok := typ.(*ast.Identifier)
	if !ok {
		return "Nat"
	}
	switch id.Value {
	case "Bool":
		return "BOOLEAN"
	case "i8", "i16", "i32", "i64":
		return "Int"
	default:
		return "Nat"
	}
}

// dataField recognizes `data.field` as an assignment target.
func dataField(store *ast.IndexAssignmentStatement) (string, bool) {
	if store == nil || store.Target == nil || !store.Target.Dot {
		return "", false
	}
	base, okBase := store.Target.Left.(*ast.Identifier)
	field, okField := store.Target.Index.(*ast.Identifier)
	if !okBase || !okField || base.Value != "data" {
		return "", false
	}
	return field.Value, true
}

var tlaOperators = map[string]string{
	"&&": "/\\", "||": "\\/", "==": "=", "!=": "#", "<": "<", "<=": "<=", ">": ">", ">=": ">=",
	"+": "+", "-": "-", "*": "*", "/": "\\div", "%": "%",
}

var conversionNames = map[string]bool{"u8": true, "u16": true, "u32": true, "u64": true, "i8": true, "i16": true, "i32": true, "i64": true}

// tlaExpr translates the guard/effect expression subset. `payload` is the
// step's parameter name (or ""); `initial` marks init values, where only
// literals and conversions of literals are meaningful.
func tlaExpr(e ast.Expression, payload string, initial bool) (string, error) {
	switch n := e.(type) {
	case *ast.IntegerLiteral:
		return fmt.Sprintf("%d", n.Value), nil
	case *ast.Boolean:
		if n.Value {
			return "TRUE", nil
		}
		return "FALSE", nil
	case *ast.Identifier:
		if n.Value == payload && payload != "" {
			return n.Value, nil
		}
		return "", fmt.Errorf("identifier %s is not the payload or a data field", n.Value)
	case *ast.IndexExpression:
		base, okBase := n.Left.(*ast.Identifier)
		field, okField := n.Index.(*ast.Identifier)
		if n.Dot && okBase && okField && base.Value == "data" {
			return field.Value, nil
		}
		return "", fmt.Errorf("only data.field reads translate")
	case *ast.InvocationExpression:
		fn, ok := n.Function.(*ast.Identifier)
		if ok && conversionNames[fn.Value] && len(n.Arguments) == 1 {
			return tlaExpr(n.Arguments[0], payload, initial)
		}
		return "", fmt.Errorf("calls other than width conversions do not translate")
	case *ast.PrefixExpression:
		inner, err := tlaExpr(n.Right, payload, initial)
		if err != nil {
			return "", err
		}
		switch n.Operator {
		case "!":
			return "~(" + inner + ")", nil
		case "-":
			return "-(" + inner + ")", nil
		}
		return "", fmt.Errorf("prefix operator %s does not translate", n.Operator)
	case *ast.InfixExpression:
		op, ok := tlaOperators[n.Operator]
		if !ok {
			return "", fmt.Errorf("operator %s does not translate", n.Operator)
		}
		left, err := tlaExpr(n.Left, payload, initial)
		if err != nil {
			return "", err
		}
		right, err := tlaExpr(n.Right, payload, initial)
		if err != nil {
			return "", err
		}
		return "(" + left + " " + op + " " + right + ")", nil
	}
	return "", fmt.Errorf("expression %T does not translate", e)
}

// sortedFieldNames is a deterministic helper for diagnostics.
func sortedFieldNames(fields map[string]ast.Expression) []string {
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
