package compiler

// TLA+ projection of a protocol declaration (docs/spec/112-protocols.md):
// one VARIABLE for the control state, one action per transition line
// grouped by step name, Next as their disjunction with payloads quantified
// over declared constant domains, TypeOK, and Spec. The module is complete
// for the control graph; a scenario that needs data extends it in a module
// of its own, so regeneration never overwrites hand-written guards.

import (
	"fmt"
	"strings"

	"github.com/SCKelemen/oak/ast"
)

// ProtocolTLA renders the TLA+ module of one declaration, or the shape
// diagnostics that stop it.
func ProtocolTLA(decl *ast.ProtocolDeclaration, origin string) (string, error) {
	var problems []string
	m, ok := analyzeProtocol(decl, func(code string, node ast.Node, format string, args ...interface{}) {
		problems = append(problems, fmt.Sprintf(format, args...))
	})
	if !ok {
		return "", fmt.Errorf("protocol %s: %s", decl.Name.Value, strings.Join(problems, "; "))
	}
	var b strings.Builder
	title := fmt.Sprintf(" MODULE %s ", m.name)
	pad := (77 - len(title)) / 2
	b.WriteString(strings.Repeat("-", pad) + title + strings.Repeat("-", 77-pad-len(title)) + "\n")
	fmt.Fprintf(&b, "\\* Generated by `oak protocol -tla %s` from %s. Do not edit: extend\n", m.name, origin)
	b.WriteString("\\* this module for data, guards and liveness, and regenerate the control graph.\n")
	b.WriteString("EXTENDS Naturals\n\n")
	var constants []string
	seen := map[string]bool{}
	for _, step := range m.steps {
		if step.payload != nil {
			domain := domainName(step.payload.Name.Value)
			if !seen[domain] {
				seen[domain] = true
				constants = append(constants, domain)
			}
		}
	}
	if len(constants) > 0 {
		fmt.Fprintf(&b, "CONSTANTS %s\n\n", strings.Join(constants, ", "))
	}
	b.WriteString("VARIABLE state\n\n")
	quoted := make([]string, len(m.states))
	for i, st := range m.states {
		quoted[i] = fmt.Sprintf("%q", st)
	}
	fmt.Fprintf(&b, "States == {%s}\n\n", strings.Join(quoted, ", "))
	fmt.Fprintf(&b, "Init == state = %q\n\n", m.initial)
	var nextTerms []string
	for _, step := range m.steps {
		head := variantName(step.name)
		if step.payload != nil {
			head = fmt.Sprintf("%s(%s)", variantName(step.name), step.payload.Name.Value)
			nextTerms = append(nextTerms, fmt.Sprintf("(\\E %s \\in %s : %s)", step.payload.Name.Value, domainName(step.payload.Name.Value), head))
		} else {
			nextTerms = append(nextTerms, variantName(step.name))
		}
		fmt.Fprintf(&b, "%s ==\n", head)
		for i, from := range step.from {
			connector := "    \\/ "
			if len(step.from) == 1 {
				connector = "    "
			}
			fmt.Fprintf(&b, "%sstate = %q /\\ state' = %q\n", connector, from, step.to[i])
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "Next ==\n    %s\n\n", strings.Join(nextTerms, "\n    \\/ "))
	b.WriteString("TypeOK == state \\in States\n\n")
	b.WriteString("Spec == Init /\\ [][Next]_state\n")
	b.WriteString(strings.Repeat("=", 77) + "\n")
	return b.String(), nil
}

// domainName is the constant naming a payload's domain: compare -> Compare.
func domainName(param string) string {
	if param == "" {
		return "Payload"
	}
	return strings.ToUpper(param[:1]) + param[1:]
}
