// Package metal compiles Oak kernels (docs/spec/56-kernels.md) to Metal
// Shading Language. A kernel is a function declared with the `kernel`
// marker whose body lies in the kernel subset: fixed-width integers, f32
// and Bool; views and spans of those as buffers; canonical loops; Bool
// conditionals; calls to other functions in the subset. The emitter is the
// definition of the subset — a construct it cannot translate fails closed
// with a message naming it, and the compiler reports that as OAK-K0101
// whether or not Metal output was requested — so a kernel is exactly the
// Oak the C backend compiles, the interpreter runs, and the Lean
// extraction states theorems about.
//
// Semantics preserved from Oak: integer arithmetic wraps in the operand's
// width; division by zero, a shift count reaching the width, and an index
// past a buffer's length are traps — a GPU thread cannot trap, so each
// raises the launch's fault word and the host traps when the command buffer
// completes (section 3). Floating point is one rounding per operation with
// no contraction and no reassociation: the file pins Metal's safe math mode
// and the descriptor tells the host to compile it that way.
package metal

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/SCKelemen/oak/ast"
	"github.com/SCKelemen/oak/token"
	"github.com/SCKelemen/oak/typechecker"
)

// Param describes one kernel parameter in the launch descriptor.
type Param struct {
	Name string
	// Kind is "grid" (the u32 thread position), "view" (device const T*
	// plus a length), "span" (device T* plus a length), or "scalar".
	Kind string
	// Element is the Oak element or scalar type name.
	Element string
	// Buffers are the [[buffer(n)]] indices the parameter occupies: two for
	// a view or span (data, length), one for a scalar, none for the grid.
	Buffers []int
}

// Kernel is the launch descriptor of one emitted kernel: the buffer layout
// the host binds and the fault buffer index it checks after completion.
type Kernel struct {
	Name   string
	Params []Param
	Fault  int
	// Threadgroup is the threads per position of a group kernel — one that
	// calls reduce.group_tree — and 0 for an ordinary kernel whose
	// positions are single threads (docs/spec/56-kernels.md section 7).
	Threadgroup int64
	// Independence is the shape the checker discharged for the kernel's
	// span accesses (docs/spec/56-kernels.md section 6): "element" (every
	// access at the grid position) or "tile T" (accesses at gid * T + k,
	// k < T; the host keeps grid * T within the u32 index).
	Independence string
	// Reach lists the kernel and every helper function its body reaches,
	// the set the compiler holds to the kernel rules (loops, effects).
	Reach []string
}

// Result is the emitted Metal source and its kernel descriptors.
type Result struct {
	Source  string
	Kernels []Kernel
}

// Emit compiles every kernel in the program. Programs without kernels yield
// an empty source and no descriptors.
func Emit(program *ast.Program, tc *typechecker.TypeChecker) (*Result, error) {
	em := &emitter{
		tc:         tc,
		env:        tc.Env(),
		functions:  map[string]*ast.FunctionStatement{},
		helperDone: map[string]bool{},
		helperBusy: map[string]bool{},
		records:    map[string][]recordField{},
		structDone: map[string]bool{},
	}
	var kernels []*ast.FunctionStatement
	for _, stmt := range program.Statements {
		fn, ok := stmt.(*ast.FunctionStatement)
		if !ok || fn.Name == nil {
			continue
		}
		em.functions[fn.Name.Value] = fn
		if fn.Kernel {
			kernels = append(kernels, fn)
		}
	}
	result := &Result{}
	if len(kernels) == 0 {
		return result, nil
	}
	var bodies strings.Builder
	for _, fn := range kernels {
		desc, text, err := em.kernel(fn)
		if err != nil {
			return nil, err
		}
		desc.Reach = em.reachOrder(fn)
		result.Kernels = append(result.Kernels, *desc)
		bodies.WriteString(text)
		bodies.WriteString("\n")
	}
	var out strings.Builder
	out.WriteString("// Generated by the Oak compiler (codegen/metal): do not edit.\n")
	out.WriteString("// docs/spec/56-kernels.md states the translation. Compile with Metal's\n")
	out.WriteString("// safe math mode (MTLCompileOptions.mathMode = MTLMathModeSafe; on older\n")
	out.WriteString("// SDKs fastMathEnabled = NO): Oak floating point is one rounding per\n")
	out.WriteString("// operation, no contraction, no reassociation.\n//\n")
	out.WriteString("// Launch descriptors (one line per kernel; the host binds buffers by index\n")
	out.WriteString("// and checks the fault word after the command buffer completes — a nonzero\n")
	out.WriteString("// value is an Oak trap: the outputs are unspecified and the host traps):\n")
	for _, k := range result.Kernels {
		out.WriteString("// oak-kernel " + k.descriptorLine() + "\n")
	}
	out.WriteString("\n#include <metal_stdlib>\nusing namespace metal;\n")
	out.WriteString("#pragma METAL fp math_mode(safe)\n#pragma METAL fp contract(off)\n\n")
	out.WriteString(prelude)
	out.WriteString(em.structText.String())
	out.WriteString(em.helperText.String())
	out.WriteString(bodies.String())
	result.Source = out.String()
	return result, nil
}

func (k Kernel) descriptorLine() string {
	var parts []string
	for _, p := range k.Params {
		switch p.Kind {
		case "grid", "group":
			parts = append(parts, p.Name+" "+p.Kind)
		default:
			idx := make([]string, len(p.Buffers))
			for i, b := range p.Buffers {
				idx[i] = fmt.Sprint(b)
			}
			parts = append(parts, fmt.Sprintf("%s %s %s buffer %s", p.Name, p.Kind, p.Element, strings.Join(idx, ",")))
		}
	}
	parts = append(parts, fmt.Sprintf("fault buffer %d", k.Fault))
	parts = append(parts, "independence "+k.Independence)
	if k.Threadgroup > 0 {
		parts = append(parts, fmt.Sprintf("threadgroup %d", k.Threadgroup))
	}
	return k.Name + ": " + strings.Join(parts, "; ")
}

// prelude is the fixed runtime every emitted file carries: the fault word,
// the checked index, and the trapping integer operations. Unused functions
// cost nothing.
const prelude = `// Oak runtime for kernels: traps raise the fault word and yield zero.
static inline void oak_raise(device atomic_uint* fault, uint code) {
  atomic_store_explicit(fault, code, memory_order_relaxed);
}
static inline uint oak_check(uint index, uint len, device atomic_uint* fault) {
  if (index >= len) { oak_raise(fault, 1u); return 0u; }
  return index;
}
static inline uint oak_subslice(uint start, uint n, uint len, device atomic_uint* fault) {
  if ((ulong)start + (ulong)n > (ulong)len) { oak_raise(fault, 4u); return 0u; }
  return start;
}
#define OAK_DIV(T, U, W, MIN) \
static inline T oak_div_##T(T a, T b, device atomic_uint* fault) { \
  if (b == (T)0) { oak_raise(fault, 2u); return (T)0; } \
  if (MIN != (T)0 && a == (T)MIN && b == (T)-1) { return (T)MIN; } \
  return (T)(a / b); \
} \
static inline T oak_rem_##T(T a, T b, device atomic_uint* fault) { \
  if (b == (T)0) { oak_raise(fault, 2u); return (T)0; } \
  if (MIN != (T)0 && a == (T)MIN && b == (T)-1) { return (T)0; } \
  return (T)(a % b); \
} \
static inline T oak_shl_##T(T a, T n, device atomic_uint* fault) { \
  if ((U)n >= (U)W) { oak_raise(fault, 3u); return (T)0; } \
  return (T)((U)a << (U)n); \
} \
static inline T oak_shr_##T(T a, T n, device atomic_uint* fault) { \
  if ((U)n >= (U)W) { oak_raise(fault, 3u); return (T)0; } \
  return (T)(a >> n); \
}
OAK_DIV(uchar, uchar, 8, 0)
OAK_DIV(ushort, ushort, 16, 0)
OAK_DIV(uint, uint, 32, 0)
OAK_DIV(ulong, ulong, 64, 0)
OAK_DIV(char, uchar, 8, -128)
OAK_DIV(short, ushort, 16, -32768)
OAK_DIV(int, uint, 32, (-2147483647-1))
OAK_DIV(long, ulong, 64, (-9223372036854775807L-1L))
#undef OAK_DIV
static inline float oak_fmin(float a, float b) { return (isnan(a) || isnan(b)) ? NAN : fmin(a, b); }
static inline float oak_fmax(float a, float b) { return (isnan(a) || isnan(b)) ? NAN : fmax(a, b); }

`

type emitter struct {
	tc        *typechecker.TypeChecker
	env       *typechecker.TypeEnvironment
	functions map[string]*ast.FunctionStatement
	// helpers are emitted on demand, callee-first, under the name of their
	// instance: a helper with function-valued parameters is specialized
	// per call site to the named functions bound there (fnSubst).
	helperText strings.Builder
	helperDone map[string]bool
	helperBusy map[string]bool
	fnSubst    map[string]string
	// records maps a record's internal name to its fields in declaration
	// order; structText holds the MSL struct of each record used.
	records    map[string][]recordField
	structText strings.Builder
	structDone map[string]bool
	// currentRet is the result type of the function being emitted, for the
	// zero an assertion failure returns.
	currentRet oakType
	// groupSize is the threadgroup size of the group kernel being emitted
	// (0 otherwise); scratch counts its cooperative reductions; hoist is
	// where a statement's expression may place the lines it needs first.
	groupSize int64
	scratch   int
	hoist     *[]string
	inKernel  bool
	// per-function state
	current string
	locals  map[string]oakType
	indent  string
	// reach memo: function name -> callees in the subset, in first-use order
	reach map[string][]string
}

// oakType is the kernel subset's view of a type: a scalar name, or a view
// or span of a scalar.
type oakType struct {
	kind    string // "scalar", "view", "span", "array", "record", "func", "unit"
	element string // Oak scalar name: u8..u64, i8..i64, f32, Bool
	length  int64  // "array": the fixed length of a local [N]T
	record  string // "record": the declared record's internal name
}

// recordField is one field of a record in the subset: a scalar or a
// buffer (docs/spec/56-kernels.md section 2; nested records are outside).
type recordField struct {
	name string
	typ  oakType
}

func (t oakType) String() string {
	switch t.kind {
	case "view":
		return "[]" + t.element
	case "span":
		return "[*]" + t.element
	case "unit":
		return "()"
	case "array":
		return fmt.Sprintf("[%d]%s", t.length, t.element)
	case "func":
		return "a function value"
	case "record":
		return t.record
	}
	return t.element
}

// isBuffer reports a view or span.
func (t oakType) isBuffer() bool { return t.kind == "view" || t.kind == "span" }

var scalarMSL = map[string]string{
	"u8": "uchar", "u16": "ushort", "u32": "uint", "u64": "ulong",
	"i8": "char", "i16": "short", "i32": "int", "i64": "long",
	"f32": "float", "Bool": "bool",
}

var unsignedOf = map[string]string{
	"u8": "uchar", "u16": "ushort", "u32": "uint", "u64": "ulong",
	"i8": "uchar", "i16": "ushort", "i32": "uint", "i64": "ulong",
}

var intWidth = map[string]int{"u8": 8, "i8": 8, "u16": 16, "i16": 16, "u32": 32, "i32": 32, "u64": 64, "i64": 64}

func isInt(name string) bool    { _, ok := intWidth[name]; return ok }
func isSigned(name string) bool { return strings.HasPrefix(name, "i") }

// paramType is the type of a function's i-th parameter: the checker's
// recorded signature when it has one (records resolve only there), else
// the syntax.
func (em *emitter) paramType(fn *ast.FunctionStatement, i int) (oakType, error) {
	if scheme, ok := em.env.Get(fn.Name.Value); ok && scheme != nil {
		if ft, isFn := scheme.Type.(*typechecker.FunctionType); isFn && i < len(ft.Parameters) {
			if t, ok := em.fromChecker(ft.Parameters[i]); ok {
				return t, nil
			}
		}
	}
	return kernelTypeOf(fn.Parameters[i].Type)
}

// returnType is a function's result type, checker first.
func (em *emitter) returnType(fn *ast.FunctionStatement) (oakType, error) {
	if scheme, ok := em.env.Get(fn.Name.Value); ok && scheme != nil {
		if ft, isFn := scheme.Type.(*typechecker.FunctionType); isFn {
			if t, ok := em.fromChecker(ft.ReturnType); ok {
				return t, nil
			}
		}
	}
	return kernelTypeOf(fn.ReturnType)
}

// requireStruct emits the MSL struct of a record once: a buffer field is
// a pointer and its length, a scalar field its scalar.
func (em *emitter) requireStruct(t oakType) string {
	name := ident(t.record)
	if em.structDone[t.record] {
		return name
	}
	em.structDone[t.record] = true
	var b strings.Builder
	fmt.Fprintf(&b, "struct %s {\n", name)
	for _, f := range em.records[t.record] {
		msl := scalarMSL[f.typ.element]
		switch f.typ.kind {
		case "view":
			fmt.Fprintf(&b, "  device const %s* %s;\n  uint %s_len;\n", msl, f.name, f.name)
		case "span":
			fmt.Fprintf(&b, "  device %s* %s;\n  uint %s_len;\n", msl, f.name, f.name)
		default:
			fmt.Fprintf(&b, "  %s %s;\n", msl, f.name)
		}
	}
	b.WriteString("};\n\n")
	em.structText.WriteString(b.String())
	return name
}

// mslType renders a scalar or record type for a declaration or signature.
func (em *emitter) mslType(t oakType) string {
	if t.kind == "record" {
		return em.requireStruct(t)
	}
	return scalarMSL[t.element]
}

// kernelTypeOf reads a parameter or declaration type from syntax.
func kernelTypeOf(expr ast.Expression) (oakType, error) {
	switch t := expr.(type) {
	case nil:
		return oakType{kind: "unit"}, nil
	case *ast.Identifier:
		if t.Value == "()" {
			return oakType{kind: "unit"}, nil
		}
		if _, ok := scalarMSL[t.Value]; ok {
			return oakType{kind: "scalar", element: t.Value}, nil
		}
		if t.Value == "f64" {
			return oakType{}, fmt.Errorf("f64 is outside the kernel subset (Apple GPUs have no double precision; compute in f32)")
		}
		return oakType{}, fmt.Errorf("type %s is outside the kernel subset (scalars u8..u64, i8..i64, f32, Bool and their views and spans)", t.Value)
	case *ast.FunctionTypeExpression:
		return oakType{kind: "func"}, nil
	case *ast.IndexExpression:
		if length, isFixed := t.Index.(*ast.IntegerLiteral); isFixed {
			// A fixed array: a thread-private local (never a buffer).
			element, err := kernelTypeOf(t.Left)
			if err != nil {
				return oakType{}, err
			}
			if element.kind != "scalar" || length.Value <= 0 {
				return oakType{}, fmt.Errorf("type %s is outside the kernel subset (fixed arrays hold scalars)", expr.String())
			}
			return oakType{kind: "array", element: element.element, length: length.Value}, nil
		}
		marker, ok := t.Index.(*ast.Identifier)
		if !ok || (marker.Value != "" && marker.Value != "*") {
			return oakType{}, fmt.Errorf("type %s is outside the kernel subset", expr.String())
		}
		element, err := kernelTypeOf(t.Left)
		if err != nil {
			return oakType{}, err
		}
		if element.kind != "scalar" {
			return oakType{}, fmt.Errorf("type %s is outside the kernel subset (buffers hold scalars)", expr.String())
		}
		kind := "view"
		if marker.Value == "*" {
			kind = "span"
		}
		return oakType{kind: kind, element: element.element}, nil
	}
	return oakType{}, fmt.Errorf("type %s is outside the kernel subset", expr.String())
}

// checkedTypeOf reads the checker's recorded type of an expression.
func (em *emitter) checkedTypeOf(expr ast.Expression) (oakType, bool) {
	typ := em.env.CheckedExpressionType(expr)
	if typ == nil {
		return oakType{}, false
	}
	return em.fromChecker(typ)
}

func (em *emitter) fromChecker(typ typechecker.Type) (oakType, bool) {
	switch t := typ.(type) {
	case *typechecker.PrimitiveType:
		if _, ok := scalarMSL[t.Name]; ok {
			return oakType{kind: "scalar", element: t.Name}, true
		}
	case *typechecker.BoolType:
		return oakType{kind: "scalar", element: "Bool"}, true
	case *typechecker.UnitType:
		return oakType{kind: "unit"}, true
	case *typechecker.FunctionType:
		return oakType{kind: "func"}, true
	case *typechecker.RecordType:
		if t.Name == "" {
			return oakType{}, false
		}
		if _, known := em.records[t.Name]; !known {
			var fields []recordField
			for _, name := range t.Order {
				ft, ok := em.fromChecker(t.Fields[name])
				if !ok || (ft.kind != "scalar" && !ft.isBuffer()) {
					return oakType{}, false
				}
				fields = append(fields, recordField{name: name, typ: ft})
			}
			em.records[t.Name] = fields
		}
		return oakType{kind: "record", record: t.Name}, true
	case *typechecker.ArrayType:
		element, ok := em.fromChecker(t.ElementType)
		if !ok || element.kind != "scalar" {
			return oakType{}, false
		}
		switch {
		case t.IsSpan:
			return oakType{kind: "span", element: element.element}, true
		case t.IsSlice:
			return oakType{kind: "view", element: element.element}, true
		case t.Length > 0:
			return oakType{kind: "array", element: element.element, length: t.Length}, true
		}
	}
	return oakType{}, false
}

// typeOf is the type of an expression inside the current body: a local's
// declared type first, then the checker's record.
func (em *emitter) typeOf(expr ast.Expression) (oakType, bool) {
	if id, ok := expr.(*ast.Identifier); ok {
		if t, known := em.locals[id.Value]; known {
			return t, true
		}
	}
	return em.checkedTypeOf(expr)
}

// ---- signatures ----

func (em *emitter) fail(format string, args ...interface{}) error {
	return fmt.Errorf("metal: %s: %s", em.current, fmt.Sprintf(format, args...))
}

// kernel emits one compute kernel and its descriptor.
func (em *emitter) kernel(fn *ast.FunctionStatement) (*Kernel, string, error) {
	em.current = "kernel " + fn.Name.Value
	if err := em.shapeOK(fn); err != nil {
		return nil, "", err
	}
	ret, err := kernelTypeOf(fn.ReturnType)
	if err != nil {
		return nil, "", em.fail("%v", err)
	}
	if ret.kind != "unit" {
		return nil, "", em.fail("a kernel returns (), got %s; results leave through spans", ret)
	}
	if len(fn.Parameters) == 0 {
		return nil, "", em.fail("a kernel's first parameter is its grid position, a u32")
	}
	em.locals = map[string]oakType{}
	desc := &Kernel{Name: fn.Name.Value}
	var args []string
	next := 0
	var prologue []string
	groupSize, scratchTypes, err := em.groupShape(fn)
	if err != nil {
		return nil, "", err
	}
	em.groupSize, em.scratch, em.inKernel = groupSize, 0, true
	defer func() { em.groupSize, em.inKernel = 0, false }()
	desc.Threadgroup = groupSize
	for i, t := range scratchTypes {
		prologue = append(prologue, fmt.Sprintf("  threadgroup %s oak_scratch%d[%d];", scalarMSL[t], i+1, groupSize))
	}
	for i, p := range fn.Parameters {
		if p == nil || p.Name == nil || p.Variadic {
			return nil, "", em.fail("parameters are named and not variadic")
		}
		t, err := em.paramType(fn, i)
		if err != nil {
			return nil, "", em.fail("parameter %s: %v", p.Name.Value, err)
		}
		if t.kind == "array" || t.kind == "func" {
			return nil, "", em.fail("parameter %s: a kernel takes buffers, scalars, and records of those, got %s", p.Name.Value, t)
		}
		name := ident(p.Name.Value)
		if t.kind == "record" && i > 0 {
			// A record parameter is its fields, flattened into buffers, and
			// rebuilt as a struct local for the body.
			em.locals[p.Name.Value] = t
			structName := em.requireStruct(t)
			var init []string
			for _, f := range em.records[t.record] {
				fname := name + "__" + f.name
				msl := scalarMSL[f.typ.element]
				switch f.typ.kind {
				case "view":
					args = append(args, fmt.Sprintf("device const %s* %s [[buffer(%d)]]", msl, fname, next), fmt.Sprintf("constant uint& %s_len [[buffer(%d)]]", fname, next+1))
					desc.Params = append(desc.Params, Param{Name: p.Name.Value + "." + f.name, Kind: "view", Element: f.typ.element, Buffers: []int{next, next + 1}})
					init = append(init, fname, fname+"_len")
					next += 2
				case "span":
					args = append(args, fmt.Sprintf("device %s* %s [[buffer(%d)]]", msl, fname, next), fmt.Sprintf("constant uint& %s_len [[buffer(%d)]]", fname, next+1))
					desc.Params = append(desc.Params, Param{Name: p.Name.Value + "." + f.name, Kind: "span", Element: f.typ.element, Buffers: []int{next, next + 1}})
					init = append(init, fname, fname+"_len")
					next += 2
				default:
					args = append(args, fmt.Sprintf("constant %s& %s [[buffer(%d)]]", msl, fname, next))
					desc.Params = append(desc.Params, Param{Name: p.Name.Value + "." + f.name, Kind: "scalar", Element: f.typ.element, Buffers: []int{next}})
					init = append(init, fname)
					next++
				}
			}
			prologue = append(prologue, fmt.Sprintf("  %s %s = { %s };", structName, name, strings.Join(init, ", ")))
			continue
		}
		if i == 0 {
			if t.kind != "scalar" || t.element != "u32" {
				return nil, "", em.fail("the first parameter %s is the grid position and must be a u32, got %s", p.Name.Value, t)
			}
			em.locals[p.Name.Value] = t
			if groupSize > 0 {
				// A group kernel's position is its threadgroup; the
				// threads of the group are the cooperative reduction's.
				desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "group", Element: "u32"})
				args = append(args, fmt.Sprintf("uint %s [[threadgroup_position_in_grid]]", name), "uint oak_lid [[thread_position_in_threadgroup]]")
				continue
			}
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "grid", Element: "u32"})
			args = append(args, fmt.Sprintf("uint %s [[thread_position_in_grid]]", name))
			continue
		}
		em.locals[p.Name.Value] = t
		msl := scalarMSL[t.element]
		switch t.kind {
		case "view":
			args = append(args, fmt.Sprintf("device const %s* %s [[buffer(%d)]]", msl, name, next), fmt.Sprintf("constant uint& %s_len [[buffer(%d)]]", name, next+1))
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "view", Element: t.element, Buffers: []int{next, next + 1}})
			next += 2
		case "span":
			args = append(args, fmt.Sprintf("device %s* %s [[buffer(%d)]]", msl, name, next), fmt.Sprintf("constant uint& %s_len [[buffer(%d)]]", name, next+1))
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "span", Element: t.element, Buffers: []int{next, next + 1}})
			next += 2
		default:
			args = append(args, fmt.Sprintf("constant %s& %s [[buffer(%d)]]", msl, name, next))
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "scalar", Element: t.element, Buffers: []int{next}})
			next++
		}
	}
	desc.Fault = next
	args = append(args, fmt.Sprintf("device atomic_uint* oak_fault [[buffer(%d)]]", next))
	var out strings.Builder
	fmt.Fprintf(&out, "kernel void %s(%s) {\n", ident(fn.Name.Value), strings.Join(args, ", "))
	em.indent = "  "
	body, err := em.functionBody(fn, oakType{kind: "unit"})
	if err != nil {
		return nil, "", err
	}
	for _, line := range prologue {
		out.WriteString(line + "\n")
	}
	out.WriteString(body)
	out.WriteString("}\n")
	// Independence is judged once the body is known to be in the subset.
	shape, err := em.independence(fn)
	if err != nil {
		return nil, "", err
	}
	desc.Independence = shape
	return desc, out.String(), nil
}

// requireHelper emits the instance of a helper the current body calls —
// named by the helper and the functions bound to its function-valued
// parameters — once, callee-first, and returns its MSL name. The current
// function's emission state is saved around the nested emission.
func (em *emitter) requireHelper(fn *ast.FunctionStatement, subst map[string]string) (string, error) {
	name := fn.Name.Value
	keys := make([]string, 0, len(subst))
	for k := range subst {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		name += "__" + subst[k]
	}
	if em.helperDone[name] {
		return ident(name), nil
	}
	if em.helperBusy[name] {
		return "", em.fail("recursion through %s is outside the kernel subset", fn.Name.Value)
	}
	em.helperBusy[name] = true
	saved := struct {
		current string
		locals  map[string]oakType
		indent  string
		subst   map[string]string
	}{em.current, em.locals, em.indent, em.fnSubst}
	text, err := em.helper(fn, name, subst)
	em.current, em.locals, em.indent, em.fnSubst = saved.current, saved.locals, saved.indent, saved.subst
	delete(em.helperBusy, name)
	if err != nil {
		return "", err
	}
	em.helperDone[name] = true
	em.helperText.WriteString(text)
	em.helperText.WriteString("\n")
	return ident(name), nil
}

// helper emits a function the kernel calls as a static inline function
// taking each buffer as pointer and length, and the fault word last.
// Function-valued parameters are bound by subst to named functions and
// leave the signature.
func (em *emitter) helper(fn *ast.FunctionStatement, instance string, subst map[string]string) (string, error) {
	em.current = fn.Name.Value
	em.fnSubst = subst
	if err := em.shapeOK(fn); err != nil {
		return "", err
	}
	ret, err := em.returnType(fn)
	if err != nil {
		return "", em.fail("result: %v", err)
	}
	if ret.kind != "scalar" && ret.kind != "unit" && ret.kind != "record" {
		return "", em.fail("a helper returns a scalar, a record, or (), got %s", ret)
	}
	em.locals = map[string]oakType{}
	var args []string
	for i, p := range fn.Parameters {
		if p == nil || p.Name == nil || p.Variadic {
			return "", em.fail("parameters are named and not variadic")
		}
		t, err := em.paramType(fn, i)
		if err != nil {
			return "", em.fail("parameter %s: %v", p.Name.Value, err)
		}
		if t.kind == "func" {
			if _, bound := subst[p.Name.Value]; !bound {
				return "", em.fail("parameter %s: a function value is bound at the call site to a named function", p.Name.Value)
			}
			continue
		}
		if t.kind == "array" {
			return "", em.fail("parameter %s: fixed arrays are thread-private locals, not parameters; take a view", p.Name.Value)
		}
		em.locals[p.Name.Value] = t
		name := ident(p.Name.Value)
		msl := scalarMSL[t.element]
		switch t.kind {
		case "view":
			args = append(args, fmt.Sprintf("device const %s* %s, uint %s_len", msl, name, name))
		case "span":
			args = append(args, fmt.Sprintf("device %s* %s, uint %s_len", msl, name, name))
		case "record":
			args = append(args, fmt.Sprintf("%s %s", em.requireStruct(t), name))
		default:
			args = append(args, fmt.Sprintf("%s %s", msl, name))
		}
	}
	args = append(args, "device atomic_uint* oak_fault")
	retMSL := "void"
	if ret.kind == "scalar" || ret.kind == "record" {
		retMSL = em.mslType(ret)
	}
	var out strings.Builder
	fmt.Fprintf(&out, "static inline %s %s(%s) {\n", retMSL, ident(instance), strings.Join(args, ", "))
	em.indent = "  "
	body, err := em.functionBody(fn, ret)
	if err != nil {
		return "", err
	}
	out.WriteString(body)
	out.WriteString("}\n")
	return out.String(), nil
}

func (em *emitter) shapeOK(fn *ast.FunctionStatement) error {
	switch {
	case fn.Receiver != nil:
		return em.fail("methods are outside the kernel subset")
	case len(fn.TypeParams) != 0:
		return em.fail("generic functions are outside the kernel subset (call an instantiation)")
	case fn.ExternSymbol != "" || fn.AsmBacked:
		return em.fail("extern and asm-backed functions are outside the kernel subset")
	case fn.Body == nil:
		return em.fail("the function has no body")
	}
	return nil
}

// functionBody emits a body: a block, or an expression body returned (or
// evaluated, for unit).
func (em *emitter) functionBody(fn *ast.FunctionStatement, ret oakType) (string, error) {
	em.currentRet = ret
	var lines []string
	switch body := fn.Body.(type) {
	case *ast.BlockExpression:
		if body.Block != nil {
			if err := em.block(body.Block.Statements, &lines, ret); err != nil {
				return "", err
			}
		}
	default:
		if ret.kind == "unit" {
			if err := em.statement(&ast.ExpressionStatement{Expression: body}, &lines, ret, false); err != nil {
				return "", err
			}
		} else {
			term, err := em.expr(body, ret)
			if err != nil {
				return "", err
			}
			lines = append(lines, em.indent+"return "+term+";")
		}
	}
	return strings.Join(lines, "\n") + "\n", nil
}

// block emits statements; the last statement of a value-returning body is
// its result.
func (em *emitter) block(statements []ast.Statement, lines *[]string, ret oakType) error {
	for i, stmt := range statements {
		last := i == len(statements)-1 && (ret.kind == "scalar" || ret.kind == "record")
		if err := em.statement(stmt, lines, ret, last); err != nil {
			return err
		}
	}
	return nil
}

func (em *emitter) statement(stmt ast.Statement, lines *[]string, ret oakType, tail bool) error {
	emit := func(format string, args ...interface{}) {
		*lines = append(*lines, em.indent+fmt.Sprintf(format, args...))
	}
	// A cooperative reduction in a statement's expression places its
	// lines before the statement.
	savedHoist := em.hoist
	em.hoist = lines
	defer func() { em.hoist = savedHoist }()
	switch s := stmt.(type) {
	case *ast.VariableDeclaration:
		if s.Name == nil {
			return em.fail("a declaration without a name")
		}
		var t oakType
		resolved := false
		if declared := em.env.CheckedDeclarationType(s); declared != nil {
			if ct, ok := em.fromChecker(declared); ok {
				t, resolved = ct, true
			}
		}
		if !resolved && s.Type != nil {
			var err error
			if t, err = kernelTypeOf(s.Type); err != nil {
				return em.fail("declaration %s: %v", s.Name.Value, err)
			}
			resolved = true
		}
		if !resolved {
			return em.fail("declaration %s has no type in the kernel subset", s.Name.Value)
		}
		switch t.kind {
		case "record":
			if s.Value == nil {
				return em.fail("declaration %s: a record local needs a value", s.Name.Value)
			}
			term, err := em.expr(s.Value, t)
			if err != nil {
				return err
			}
			emit("%s %s = %s;", em.requireStruct(t), ident(s.Name.Value), term)
			em.locals[s.Name.Value] = t
			return nil
		case "view", "span":
			// A window on a buffer: subslice(buf, start, n) checks
			// start + n <= len (fault 4) and aliases the pointer; a bare
			// buffer name aliases it whole.
			if err := em.bufferLocal(s, t, emit); err != nil {
				return err
			}
			em.locals[s.Name.Value] = t
			return nil
		case "array":
			if err := em.arrayLocal(s, t, emit); err != nil {
				return err
			}
			em.locals[s.Name.Value] = t
			return nil
		case "scalar":
		default:
			return em.fail("declaration %s: a local is a scalar, a fixed array, or a window on a buffer", s.Name.Value)
		}
		if s.Value == nil {
			emit("%s %s = (%s)0;", scalarMSL[t.element], ident(s.Name.Value), scalarMSL[t.element])
		} else {
			term, err := em.expr(s.Value, t)
			if err != nil {
				return err
			}
			emit("%s %s = %s;", scalarMSL[t.element], ident(s.Name.Value), term)
		}
		em.locals[s.Name.Value] = t
		return nil
	case *ast.AssignmentStatement:
		t, ok := em.locals[s.Name.Value]
		if !ok {
			return em.fail("assignment to %s, which is not a local", s.Name.Value)
		}
		term, err := em.expr(s.Value, t)
		if err != nil {
			return err
		}
		emit("%s = %s;", ident(s.Name.Value), term)
		return nil
	case *ast.IndexAssignmentStatement:
		if s.Target.Dot {
			return em.fail("field assignment %s is outside the kernel subset", s.Target.String())
		}
		ref, t, ok := em.bufferRef(s.Target.Left)
		if !ok || (t.kind != "span" && t.kind != "array") {
			return em.fail("store into %s: not a span, a span field, or a local array", s.Target.Left.String())
		}
		index, err := em.expr(s.Target.Index, oakType{kind: "scalar", element: "u32"})
		if err != nil {
			return err
		}
		value, err := em.expr(s.Value, oakType{kind: "scalar", element: t.element})
		if err != nil {
			return err
		}
		if em.groupSize > 0 && em.inKernel && t.kind == "span" {
			// Every thread of the group computes the same value; one
			// writes it.
			emit("if (oak_lid == 0u) { %s = %s; }", em.elementRef(ref, t, index, s.Target.Token), value)
			return nil
		}
		emit("%s = %s;", em.elementRef(ref, t, index, s.Target.Token), value)
		return nil
	case *ast.WhileStatement:
		cond, err := em.expr(s.Condition, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return err
		}
		emit("while %s {", parens(cond))
		saved := em.indent
		em.indent += "  "
		if s.Body != nil {
			if err := em.block(s.Body.Statements, lines, oakType{kind: "unit"}); err != nil {
				return err
			}
		}
		em.indent = saved
		emit("}")
		return nil
	case *ast.BreakStatement:
		emit("break;")
		return nil
	case *ast.BlockStatement:
		return em.block(s.Statements, lines, ret)
	case *ast.ExpressionStatement:
		if match, ok := s.Expression.(*ast.MatchExpression); ok && !tail {
			return em.conditionalStatement(match, lines)
		}
		if tail {
			return em.returnValue(s.Expression, ret, lines)
		}
		if call, ok := s.Expression.(*ast.InvocationExpression); ok {
			if callee, isIdent := call.Function.(*ast.Identifier); isIdent && callee.Value == "assert" && len(call.Arguments) == 1 {
				// A failed assertion is a trap: fault 5, and the thread
				// leaves the function with a zero result.
				cond, err := em.expr(call.Arguments[0], oakType{kind: "scalar", element: "Bool"})
				if err != nil {
					return err
				}
				emit("if (!%s) { oak_raise(oak_fault, 5u); return %s; }", parens(cond), em.zeroOf(em.currentRet))
				return nil
			}
			term, err := em.call(call, oakType{kind: "unit"})
			if err != nil {
				return err
			}
			emit("%s;", term)
			return nil
		}
		if block, ok := s.Expression.(*ast.BlockExpression); ok && block.Block != nil {
			return em.block(block.Block.Statements, lines, oakType{kind: "unit"})
		}
		return em.fail("statement %s is outside the kernel subset", s.Expression.String())
	}
	return em.fail("statement %s is outside the kernel subset", stmt.String())
}

// returnValue emits a function's result: an expression is returned; a
// Bool conditional whose arms are blocks returns from each arm, its
// statements emitted in place, so the value-position conditional of a
// body's tail needs no temporaries.
func (em *emitter) returnValue(value ast.Expression, ret oakType, lines *[]string) error {
	switch v := value.(type) {
	case *ast.MatchExpression:
		trueBody, falseBody, ok := boolArms(v)
		if !ok || falseBody == nil {
			return em.fail("match %s in result position is outside the kernel subset (a Bool conditional with two arms)", v.String())
		}
		cond, err := em.expr(v.Scrutinee, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return err
		}
		*lines = append(*lines, em.indent+"if "+parens(cond)+" {")
		if err := em.returnArm(trueBody, ret, lines); err != nil {
			return err
		}
		*lines = append(*lines, em.indent+"} else {")
		if err := em.returnArm(falseBody, ret, lines); err != nil {
			return err
		}
		*lines = append(*lines, em.indent+"}")
		return nil
	case *ast.BlockExpression:
		if v.Block == nil || len(v.Block.Statements) == 0 {
			return em.fail("an empty block has no value")
		}
		stmts := v.Block.Statements
		if err := em.block(stmts[:len(stmts)-1], lines, oakType{kind: "unit"}); err != nil {
			return err
		}
		last, ok := stmts[len(stmts)-1].(*ast.ExpressionStatement)
		if !ok {
			return em.fail("the last statement of a value block is its result")
		}
		return em.returnValue(last.Expression, ret, lines)
	}
	term, err := em.expr(value, ret)
	if err != nil {
		return err
	}
	*lines = append(*lines, em.indent+"return "+term+";")
	return nil
}

func (em *emitter) returnArm(body ast.Expression, ret oakType, lines *[]string) error {
	saved := em.indent
	em.indent += "  "
	defer func() { em.indent = saved }()
	return em.returnValue(body, ret, lines)
}

// conditionalStatement emits a Bool conditional in statement position as
// if/else over its arms.
func (em *emitter) conditionalStatement(match *ast.MatchExpression, lines *[]string) error {
	trueBody, falseBody, ok := boolArms(match)
	if !ok {
		return em.fail("match %s is outside the kernel subset (Bool conditionals only)", match.String())
	}
	cond, err := em.expr(match.Scrutinee, oakType{kind: "scalar", element: "Bool"})
	if err != nil {
		return err
	}
	*lines = append(*lines, em.indent+"if "+parens(cond)+" {")
	if err := em.armBody(trueBody, lines); err != nil {
		return err
	}
	if !isEmptyArm(falseBody) {
		*lines = append(*lines, em.indent+"} else {")
		if err := em.armBody(falseBody, lines); err != nil {
			return err
		}
	}
	*lines = append(*lines, em.indent+"}")
	return nil
}

func (em *emitter) armBody(body ast.Expression, lines *[]string) error {
	saved := em.indent
	em.indent += "  "
	defer func() { em.indent = saved }()
	switch b := body.(type) {
	case *ast.BlockExpression:
		if b.Block == nil {
			return nil
		}
		return em.block(b.Block.Statements, lines, oakType{kind: "unit"})
	case *ast.MatchExpression:
		return em.conditionalStatement(b, lines)
	case *ast.InvocationExpression:
		term, err := em.call(b, oakType{kind: "unit"})
		if err != nil {
			return err
		}
		*lines = append(*lines, em.indent+term+";")
		return nil
	}
	if isUnitLiteral(body) {
		return nil
	}
	return em.fail("conditional arm %s is outside the kernel subset in statement position", body.String())
}

func isUnitLiteral(expr ast.Expression) bool {
	id, ok := expr.(*ast.Identifier)
	return ok && id.Value == "()"
}

// isEmptyArm reports an absent or empty conditional arm: the implicit unit
// else, or an empty block.
func isEmptyArm(expr ast.Expression) bool {
	if expr == nil || isUnitLiteral(expr) {
		return true
	}
	block, ok := expr.(*ast.BlockExpression)
	return ok && (block.Block == nil || len(block.Block.Statements) == 0)
}

// parens wraps a condition once: an already parenthesized term is used as is.
func parens(cond string) string {
	if strings.HasPrefix(cond, "(") && strings.HasSuffix(cond, ")") {
		depth := 0
		for i, r := range cond {
			switch r {
			case '(':
				depth++
			case ')':
				depth--
				if depth == 0 && i != len(cond)-1 {
					return "(" + cond + ")"
				}
			}
		}
		return cond
	}
	return "(" + cond + ")"
}

// boolArms decodes `cond ? a | b`: two arms with Bool literal patterns, or
// a literal true arm and a wildcard.
func boolArms(match *ast.MatchExpression) (ast.Expression, ast.Expression, bool) {
	if len(match.Arms) == 0 || len(match.Arms) > 2 {
		return nil, nil, false
	}
	var trueBody, falseBody ast.Expression
	for _, arm := range match.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			lit, ok := p.Value.(*ast.Boolean)
			if !ok {
				return nil, nil, false
			}
			if lit.Value {
				trueBody = arm.Body
			} else {
				falseBody = arm.Body
			}
		case *ast.WildcardPattern:
			if trueBody == nil {
				return nil, nil, false
			}
			falseBody = arm.Body
		default:
			return nil, nil, false
		}
	}
	if trueBody == nil {
		return nil, nil, false
	}
	return trueBody, falseBody, true
}

// ---- expressions ----

// expr emits an expression expected to have type want.
func (em *emitter) expr(expr ast.Expression, want oakType) (string, error) {
	switch e := expr.(type) {
	case *ast.IntegerLiteral:
		t := want
		if checked, ok := em.checkedTypeOf(e); ok && checked.kind == "scalar" {
			t = checked
		}
		if t.kind != "scalar" || !isInt(t.element) {
			if t.kind == "scalar" && t.element == "f32" {
				return fmt.Sprintf("%d.0f", e.Value), nil
			}
			return "", em.fail("integer literal %d has no integer type in context", e.Value)
		}
		return intLiteral(e.Value, t.element), nil
	case *ast.FloatLiteral:
		return floatLiteral(e.Text), nil
	case *ast.Boolean:
		if e.Value {
			return "true", nil
		}
		return "false", nil
	case *ast.Identifier:
		t, ok := em.locals[e.Value]
		if !ok {
			return "", em.fail("identifier %s is not a parameter or local (globals and constants are outside the kernel subset)", e.Value)
		}
		if t.kind != "scalar" && t.kind != "record" {
			return "", em.fail("%s is a buffer and can only be indexed, measured with len, or passed on", e.Value)
		}
		return ident(e.Value), nil
	case *ast.PrefixExpression:
		return em.prefix(e, want)
	case *ast.InfixExpression:
		return em.infix(e, want)
	case *ast.IndexExpression:
		if e.Dot {
			// A scalar field of a record local; buffer fields are read
			// only through indexing, len, windows, and calls.
			base, ok := e.Left.(*ast.Identifier)
			field, isField := e.Index.(*ast.Identifier)
			if !ok || !isField {
				return "", em.fail("field access %s is outside the kernel subset", e.String())
			}
			rt, known := em.locals[base.Value]
			if !known || rt.kind != "record" {
				return "", em.fail("%s is not a record local", base.Value)
			}
			for _, f := range em.records[rt.record] {
				if f.name == field.Value {
					if f.typ.kind != "scalar" {
						return "", em.fail("%s is a buffer field and can only be indexed, measured with len, windowed, or passed on", e.String())
					}
					return ident(base.Value) + "." + f.name, nil
				}
			}
			return "", em.fail("%s has no field %s", rt.record, field.Value)
		}
		ref, t, ok := em.bufferRef(e.Left)
		if !ok {
			return "", em.fail("%s is not a buffer (index a named buffer, a buffer field, or a local array)", e.Left.String())
		}
		index, err := em.expr(e.Index, oakType{kind: "scalar", element: "u32"})
		if err != nil {
			return "", err
		}
		return em.elementRef(ref, t, index, e.Token), nil
	case *ast.RecordLiteral:
		t, ok := em.checkedTypeOf(e)
		if !ok || t.kind != "record" {
			return "", em.fail("record literal %s has no record type in the kernel subset", e.String())
		}
		var terms []string
		for _, f := range em.records[t.record] {
			value, given := e.Fields[f.name]
			if !given {
				return "", em.fail("record literal %s lacks the field %s", e.String(), f.name)
			}
			if f.typ.isBuffer() {
				ref, src, ok := em.bufferRef(value)
				if !ok || !src.isBuffer() || (f.typ.kind == "span" && src.kind != "span") {
					return "", em.fail("record literal field %s: %s is not a matching buffer", f.name, value.String())
				}
				terms = append(terms, ref, em.lengthRef(ref, src))
				continue
			}
			term, err := em.expr(value, f.typ)
			if err != nil {
				return "", err
			}
			terms = append(terms, term)
		}
		return fmt.Sprintf("%s{ %s }", em.requireStruct(t), strings.Join(terms, ", ")), nil
	case *ast.InvocationExpression:
		return em.call(e, want)
	case *ast.MatchExpression:
		trueBody, falseBody, ok := boolArms(e)
		if !ok || falseBody == nil {
			return "", em.fail("match %s in value position is outside the kernel subset (a Bool conditional with two expression arms)", e.String())
		}
		cond, err := em.expr(e.Scrutinee, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return "", err
		}
		left, err := em.expr(trueBody, want)
		if err != nil {
			return "", err
		}
		right, err := em.expr(falseBody, want)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s ? %s : %s)", cond, left, right), nil
	case *ast.BlockExpression:
		if e.Block != nil && len(e.Block.Statements) == 1 {
			if es, ok := e.Block.Statements[0].(*ast.ExpressionStatement); ok {
				return em.expr(es.Expression, want)
			}
		}
		return "", em.fail("block %s in value position is outside the kernel subset", e.String())
	}
	return "", em.fail("expression %s is outside the kernel subset", expr.String())
}

// element renders buffer[index]: through the fault-raising check unless the
// checker proved the access in range (typechecker/extents.go, Oak.Extents)
// — a guard such as `gid < len(y)` or a canonical loop bound over a binding
// of `len(x)` discharges it, and the access is then the raw load or store.
func (em *emitter) element(buffer, index string, at token.Token) string {
	return em.elementRef(ident(buffer), em.locals[buffer], index, at)
}

// elementRef renders ref[index] for a rendered buffer reference.
func (em *emitter) elementRef(ref string, t oakType, index string, at token.Token) string {
	if em.tc != nil && em.tc.IndexProven(at) {
		return fmt.Sprintf("%s[%s]", ref, index)
	}
	return fmt.Sprintf("%s[oak_check(%s, %s, oak_fault)]", ref, index, em.lengthRef(ref, t))
}

// lengthOf is the length term of a named buffer or local array.
func (em *emitter) lengthOf(name string) string {
	return em.lengthRef(ident(name), em.locals[name])
}

// lengthRef is the length term of a rendered buffer reference.
func (em *emitter) lengthRef(ref string, t oakType) string {
	if t.kind == "array" {
		return fmt.Sprintf("%du", t.length)
	}
	return ref + "_len"
}

// bufferRef resolves an expression naming a buffer — a local, or a buffer
// field of a record local (`t.data`) — to its rendered reference and type.
func (em *emitter) bufferRef(e ast.Expression) (string, oakType, bool) {
	switch v := e.(type) {
	case *ast.Identifier:
		t, ok := em.locals[v.Value]
		if !ok || (!t.isBuffer() && t.kind != "array") {
			return "", oakType{}, false
		}
		return ident(v.Value), t, true
	case *ast.IndexExpression:
		if !v.Dot {
			return "", oakType{}, false
		}
		base, ok := v.Left.(*ast.Identifier)
		field, isField := v.Index.(*ast.Identifier)
		if !ok || !isField {
			return "", oakType{}, false
		}
		rt, known := em.locals[base.Value]
		if !known || rt.kind != "record" {
			return "", oakType{}, false
		}
		for _, f := range em.records[rt.record] {
			if f.name == field.Value && f.typ.isBuffer() {
				return ident(base.Value) + "." + f.name, f.typ, true
			}
		}
	}
	return "", oakType{}, false
}

// zeroOf is the value an aborted function returns.
func (em *emitter) zeroOf(t oakType) string {
	switch t.kind {
	case "scalar":
		return fmt.Sprintf("(%s)0", scalarMSL[t.element])
	case "record":
		return em.requireStruct(t) + "{}"
	}
	return ""
}

// bufferLocal emits a view or span local.
func (em *emitter) bufferLocal(s *ast.VariableDeclaration, t oakType, emit func(string, ...interface{})) error {
	qualifier := "device const"
	if t.kind == "span" {
		qualifier = "device"
	}
	msl := scalarMSL[t.element]
	name := ident(s.Name.Value)
	switch v := s.Value.(type) {
	case *ast.Identifier, *ast.IndexExpression:
		ref, src, ok := em.bufferRef(v)
		if !ok || !src.isBuffer() {
			return em.fail("declaration %s: %s is not a buffer", s.Name.Value, v.String())
		}
		if t.kind == "span" && src.kind != "span" {
			return em.fail("declaration %s: a span cannot alias the view %s", s.Name.Value, v.String())
		}
		emit("%s %s* %s = %s;", qualifier, msl, name, ref)
		emit("uint %s_len = %s;", name, em.lengthRef(ref, src))
		return nil
	case *ast.InvocationExpression:
		callee, ok := v.Function.(*ast.Identifier)
		if !ok || callee.Value != "subslice" || len(v.Arguments) != 3 {
			break
		}
		ref, src, ok := em.bufferRef(v.Arguments[0])
		if !ok || !src.isBuffer() {
			return em.fail("declaration %s: subslice takes a named buffer or a buffer field", s.Name.Value)
		}
		if t.kind == "span" && src.kind != "span" {
			return em.fail("declaration %s: a span cannot window the view %s", s.Name.Value, v.Arguments[0].String())
		}
		u32 := oakType{kind: "scalar", element: "u32"}
		start, err := em.expr(v.Arguments[1], u32)
		if err != nil {
			return err
		}
		count, err := em.expr(v.Arguments[2], u32)
		if err != nil {
			return err
		}
		emit("uint %s_len = %s;", name, count)
		emit("%s %s* %s = %s + oak_subslice(%s, %s_len, %s, oak_fault);", qualifier, msl, name, ref, start, name, em.lengthRef(ref, src))
		return nil
	}
	return em.fail("declaration %s: a buffer local is subslice(buf, start, n) or a buffer name", s.Name.Value)
}

// arrayLocal emits a fixed-size thread-private array.
func (em *emitter) arrayLocal(s *ast.VariableDeclaration, t oakType, emit func(string, ...interface{})) error {
	msl := scalarMSL[t.element]
	name := ident(s.Name.Value)
	if s.Value == nil {
		emit("%s %s[%d] = {0};", msl, name, t.length)
		return nil
	}
	literal, ok := s.Value.(*ast.ArrayLiteral)
	if !ok {
		return em.fail("declaration %s: a fixed array is initialized by a list literal", s.Name.Value)
	}
	if int64(len(literal.Elements)) != t.length {
		return em.fail("declaration %s: %d elements for [%d]%s", s.Name.Value, len(literal.Elements), t.length, t.element)
	}
	var terms []string
	for _, e := range literal.Elements {
		term, err := em.expr(e, oakType{kind: "scalar", element: t.element})
		if err != nil {
			return err
		}
		terms = append(terms, term)
	}
	emit("%s %s[%d] = { %s };", msl, name, t.length, strings.Join(terms, ", "))
	return nil
}

func (em *emitter) operandType(e ast.Expression, fallback oakType) oakType {
	if t, ok := em.typeOf(e); ok && t.kind == "scalar" {
		return t
	}
	return fallback
}

func (em *emitter) prefix(e *ast.PrefixExpression, want oakType) (string, error) {
	switch e.Operator {
	case "!":
		inner, err := em.expr(e.Right, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return "", err
		}
		return "(!" + inner + ")", nil
	case "-":
		t := em.operandType(e, em.operandType(e.Right, want))
		inner, err := em.expr(e.Right, t)
		if err != nil {
			return "", err
		}
		if t.element == "f32" {
			return "(-" + inner + ")", nil
		}
		if !isInt(t.element) {
			return "", em.fail("negation of %s is outside the kernel subset", t)
		}
		// Total negation in the operand's width: two's complement wraps.
		return fmt.Sprintf("(%s)(0u - (%s)%s)", scalarMSL[t.element], unsignedOf[t.element], inner), nil
	case "^":
		t := em.operandType(e, em.operandType(e.Right, want))
		inner, err := em.expr(e.Right, t)
		if err != nil {
			return "", err
		}
		if !isInt(t.element) {
			return "", em.fail("complement of %s is outside the kernel subset", t)
		}
		return fmt.Sprintf("(%s)(~%s)", scalarMSL[t.element], inner), nil
	}
	return "", em.fail("prefix operator %s is outside the kernel subset", e.Operator)
}

func (em *emitter) infix(e *ast.InfixExpression, want oakType) (string, error) {
	boolT := oakType{kind: "scalar", element: "Bool"}
	switch e.Operator {
	case "&&", "||":
		left, err := em.expr(e.Left, boolT)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, boolT)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	case "==", "!=", "<", "<=", ">", ">=":
		t := em.operandType(e.Left, oakType{})
		if t.kind == "" {
			t = em.operandType(e.Right, oakType{})
		}
		if t.kind == "" {
			return "", em.fail("comparison %s has no typed operand", e.String())
		}
		left, err := em.expr(e.Left, t)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, t)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	}
	// Arithmetic and bitwise: one width, the result's.
	t := em.operandType(e, oakType{})
	if t.kind == "" {
		t = em.operandType(e.Left, em.operandType(e.Right, want))
	}
	if t.kind != "scalar" {
		return "", em.fail("operator %s in %s has no scalar type", e.Operator, e.String())
	}
	left, err := em.expr(e.Left, t)
	if err != nil {
		return "", err
	}
	right, err := em.expr(e.Right, t)
	if err != nil {
		return "", err
	}
	msl := scalarMSL[t.element]
	if t.element == "f32" {
		switch e.Operator {
		case "+", "-", "*", "/":
			return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
		}
		return "", em.fail("operator %s over f32 is outside the kernel subset", e.Operator)
	}
	if !isInt(t.element) {
		return "", em.fail("operator %s over %s is outside the kernel subset", e.Operator, t)
	}
	u := unsignedOf[t.element]
	switch e.Operator {
	case "+", "-", "*":
		// Wrapping in the operand's width. uint and ulong wrap on their own;
		// narrow and signed types compute unsigned and cast back.
		if t.element == "u32" || t.element == "u64" {
			return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
		}
		return fmt.Sprintf("(%s)((%s)%s %s (%s)%s)", msl, u, left, e.Operator, u, right), nil
	case "/":
		return fmt.Sprintf("oak_div_%s(%s, %s, oak_fault)", msl, left, right), nil
	case "%":
		return fmt.Sprintf("oak_rem_%s(%s, %s, oak_fault)", msl, left, right), nil
	case "&", "|", "^":
		return fmt.Sprintf("(%s)(%s %s %s)", msl, left, e.Operator, right), nil
	case "<<":
		return fmt.Sprintf("oak_shl_%s(%s, %s, oak_fault)", msl, left, right), nil
	case ">>":
		return fmt.Sprintf("oak_shr_%s(%s, %s, oak_fault)", msl, left, right), nil
	}
	return "", em.fail("operator %s is outside the kernel subset", e.Operator)
}

var conversionRow = regexp.MustCompile(`^([ui](?:8|16|32|64)|f32)_(trunc|bits|round|saturating|checked|trapping)_([ui](?:8|16|32|64)|f32|f64)$`)

var floatIntrinsics = map[string]string{
	"fma": "fma", "sqrt": "precise::sqrt", "abs": "fabs", "copysign": "copysign",
	"floor": "floor", "ceil": "ceil", "trunc": "trunc", "round": "round", "round_even": "rint",
	"min": "oak_fmin", "max": "oak_fmax", "min_num": "fmin", "max_num": "fmax",
	"is_nan": "isnan", "is_finite": "isfinite", "is_infinite": "isinf", "is_normal": "isnormal",
}

func (em *emitter) call(call *ast.InvocationExpression, want oakType) (string, error) {
	callee, ok := call.Function.(*ast.Identifier)
	if !ok {
		return "", em.fail("call through %s is outside the kernel subset", call.Function.String())
	}
	name := callee.Value
	args := call.Arguments
	switch {
	case name == "len":
		if len(args) != 1 {
			return "", em.fail("len takes one argument")
		}
		ref, t, ok := em.bufferRef(args[0])
		if !ok {
			return "", em.fail("len of %s: not a buffer, a buffer field, or a local array", args[0].String())
		}
		return em.lengthRef(ref, t), nil
	case scalarMSL[name] != "" && name != "Bool":
		// Constructor conversions: widening and float constructors.
		if len(args) != 1 {
			return "", em.fail("%s takes one argument", name)
		}
		source := em.operandType(args[0], oakType{})
		if source.kind == "" {
			source = oakType{kind: "scalar", element: name}
		}
		inner, err := em.expr(args[0], source)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("((%s)%s)", scalarMSL[name], inner), nil
	case conversionRow.MatchString(name):
		m := conversionRow.FindStringSubmatch(name)
		target, op, source := m[1], m[2], m[3]
		if len(args) != 1 {
			return "", em.fail("%s takes one argument", name)
		}
		if source == "f64" {
			return "", em.fail("%s: f64 is outside the kernel subset", name)
		}
		inner, err := em.expr(args[0], oakType{kind: "scalar", element: source})
		if err != nil {
			return "", err
		}
		switch {
		case op == "trunc" && isInt(target) && isInt(source):
			return fmt.Sprintf("((%s)%s)", scalarMSL[target], inner), nil
		case op == "bits" && isInt(target) && isInt(source) && intWidth[target] == intWidth[source]:
			return fmt.Sprintf("((%s)%s)", scalarMSL[target], inner), nil
		case op == "bits" && (target == "f32" && source == "u32" || target == "u32" && source == "f32"):
			return fmt.Sprintf("as_type<%s>(%s)", scalarMSL[target], inner), nil
		case op == "round" && target == "f32" && isInt(source):
			// Integer to float rounds to nearest even in Metal, as in Oak.
			return fmt.Sprintf("((float)%s)", inner), nil
		}
		return "", em.fail("%s is outside the kernel subset (trunc and same-width bits between integers, bits between f32 and u32, round from an integer to f32)", name)
	case floatIntrinsics[name] != "":
		var rendered []string
		for _, a := range args {
			term, err := em.expr(a, oakType{kind: "scalar", element: "f32"})
			if err != nil {
				return "", err
			}
			rendered = append(rendered, term)
		}
		return fmt.Sprintf("%s(%s)", floatIntrinsics[name], strings.Join(rendered, ", ")), nil
	case name == "total_order" || name == "assert" || name == "subslice" || name == "view" || name == "span":
		return "", em.fail("%s is outside the kernel subset", name)
	}
	if bound, isValue := em.fnSubst[name]; isValue {
		// A call through a function-valued parameter, bound at the call
		// site of this helper instance to a named function.
		name = bound
	}
	if isGroupTree(name) {
		return em.groupTree(call)
	}
	target, known := em.functions[name]
	if !known {
		return "", em.fail("call to %s is outside the kernel subset (not a function of the program)", name)
	}
	if target.Kernel {
		return "", em.fail("a kernel does not call another kernel (%s); share a helper", name)
	}
	if len(args) != len(target.Parameters) {
		return "", em.fail("call to %s: %d arguments for %d parameters", name, len(args), len(target.Parameters))
	}
	var rendered []string
	subst := map[string]string{}
	for i, a := range args {
		pt, err := em.paramType(target, i)
		if err != nil {
			return "", em.fail("call to %s: parameter %s: %v", name, target.Parameters[i].Name.Value, err)
		}
		if pt.kind == "func" {
			// The argument names a function of the program; the helper is
			// specialized to it (docs/spec/56-kernels.md section 2).
			fnName, ok := a.(*ast.Identifier)
			if !ok {
				return "", em.fail("call to %s: the argument for %s must name a function of the program, got %s", name, target.Parameters[i].Name.Value, a.String())
			}
			resolved := fnName.Value
			if b, isValue := em.fnSubst[resolved]; isValue {
				resolved = b
			}
			if f := em.functions[resolved]; f == nil || f.Kernel {
				return "", em.fail("call to %s: %s is not a function of the program", name, fnName.Value)
			}
			subst[target.Parameters[i].Name.Value] = resolved
			continue
		}
		if pt.kind == "view" || pt.kind == "span" {
			ref, at, ok := em.bufferRef(a)
			if !ok || !at.isBuffer() {
				return "", em.fail("call to %s: a buffer argument is a named buffer or buffer field, got %s", name, a.String())
			}
			if pt.kind == "span" && at.kind != "span" {
				return "", em.fail("call to %s: %s is a view, the parameter wants a span", name, a.String())
			}
			rendered = append(rendered, ref, em.lengthRef(ref, at))
			continue
		}
		term, err := em.expr(a, pt)
		if err != nil {
			return "", err
		}
		rendered = append(rendered, term)
	}
	rendered = append(rendered, "oak_fault")
	instance, err := em.requireHelper(target, subst)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s(%s)", instance, strings.Join(rendered, ", ")), nil
}

// ---- cooperative reductions ----

// groupTreePrefix is the mangled name of the standard library's
// reduce.group_tree instances (`reduce__group_utree_<T>`).
const groupTreePrefix = "reduce__group_utree_"

func isGroupTree(name string) bool { return strings.HasPrefix(name, groupTreePrefix) }

// groupShape scans a kernel body for reduce.group_tree calls: their group
// argument is one integer literal, a power of two up to 1024, shared by
// every call; the element type of each call is recorded for its scratch.
func (em *emitter) groupShape(fn *ast.FunctionStatement) (int64, []string, error) {
	var size int64
	var types []string
	var failure error
	walk(fn.Body, func(n ast.Node) {
		call, ok := n.(*ast.InvocationExpression)
		if !ok || failure != nil {
			return
		}
		callee, ok := call.Function.(*ast.Identifier)
		if !ok || !isGroupTree(callee.Value) {
			return
		}
		if len(call.Arguments) != 6 {
			failure = em.fail("reduce.group_tree takes (group, xs, lo, m, zero, f)")
			return
		}
		literal, isLiteral := call.Arguments[0].(*ast.IntegerLiteral)
		if !isLiteral || literal.Value < 1 || literal.Value > 1024 || literal.Value&(literal.Value-1) != 0 {
			failure = em.fail("reduce.group_tree: the group is an integer literal, a power of two up to 1024 (the threadgroup size), got %s", call.Arguments[0].String())
			return
		}
		if size != 0 && size != literal.Value {
			failure = em.fail("reduce.group_tree: one kernel has one group size, got %d and %d", size, literal.Value)
			return
		}
		size = literal.Value
		element := strings.TrimPrefix(callee.Value, groupTreePrefix)
		if scalarMSL[element] == "" {
			failure = em.fail("reduce.group_tree over %s is outside the kernel subset", element)
			return
		}
		types = append(types, element)
	})
	return size, types, failure
}

// groupTree emits the cooperative reduction of a reduce.group_tree call
// (docs/spec/56-kernels.md section 7): the group's threads load the
// window into threadgroup scratch and combine pairwise-adjacent, partner
// present, doubling the stride — the binary-counter tree of reduce.tree
// (Oak.Reduce.coop_eq_tree) — and every thread reads the result. The call
// is a value; its lines go before the statement that holds it.
func (em *emitter) groupTree(call *ast.InvocationExpression) (string, error) {
	if em.groupSize == 0 || !em.inKernel || em.hoist == nil {
		return "", em.fail("reduce.group_tree is called from a kernel body, as a statement's value")
	}
	callee := call.Function.(*ast.Identifier)
	element := strings.TrimPrefix(callee.Value, groupTreePrefix)
	scalar := oakType{kind: "scalar", element: element}
	u32 := oakType{kind: "scalar", element: "u32"}
	xsRef, xsType, ok := em.bufferRef(call.Arguments[1])
	if !ok || !xsType.isBuffer() || xsType.element != element {
		return "", em.fail("reduce.group_tree: the second argument is a buffer of %s", element)
	}
	lo, err := em.expr(call.Arguments[2], u32)
	if err != nil {
		return "", err
	}
	m, err := em.expr(call.Arguments[3], u32)
	if err != nil {
		return "", err
	}
	zero, err := em.expr(call.Arguments[4], scalar)
	if err != nil {
		return "", err
	}
	fnName, isIdent := call.Arguments[5].(*ast.Identifier)
	if !isIdent || em.functions[fnName.Value] == nil || em.functions[fnName.Value].Kernel {
		return "", em.fail("reduce.group_tree: the combine names a function of the program")
	}
	combine, err := em.requireHelper(em.functions[fnName.Value], map[string]string{})
	if err != nil {
		return "", err
	}
	em.scratch++
	n := em.scratch
	msl := scalarMSL[element]
	ind := em.indent
	add := func(format string, args ...interface{}) {
		*em.hoist = append(*em.hoist, ind+fmt.Sprintf(format, args...))
	}
	add("%s oak_gt%d = %s;", msl, n, zero)
	add("{")
	add("  uint oak_lo%d = %s;", n, lo)
	add("  uint oak_m%d = %s;", n, m)
	add("  if ((ulong)oak_lo%d + (ulong)oak_m%d > (ulong)%s) { oak_raise(oak_fault, 4u); oak_m%d = 0u; }", n, n, em.lengthRef(xsRef, xsType), n)
	add("  if (oak_m%d > %du) { oak_raise(oak_fault, 5u); oak_m%d = 0u; }", n, em.groupSize, n)
	add("  oak_scratch%d[oak_lid] = (oak_lid < oak_m%d) ? %s[oak_lo%d + oak_lid] : oak_gt%d;", n, n, xsRef, n, n)
	add("  threadgroup_barrier(mem_flags::mem_threadgroup);")
	add("  for (uint oak_s = 1u; oak_s < %du; oak_s <<= 1u) {", em.groupSize)
	add("    if ((oak_lid %% (2u * oak_s)) == 0u && oak_lid + oak_s < oak_m%d) { oak_scratch%d[oak_lid] = %s(oak_scratch%d[oak_lid], oak_scratch%d[oak_lid + oak_s], oak_fault); }", n, n, combine, n, n)
	add("    threadgroup_barrier(mem_flags::mem_threadgroup);")
	add("  }")
	add("  if (oak_m%d > 0u) { oak_gt%d = oak_scratch%d[0]; }", n, n, n)
	add("}")
	return fmt.Sprintf("oak_gt%d", n), nil
}

// ---- reach ----

// reachOrder lists a function and every program function it reaches
// through calls, callees before callers, for emission and for the compiler
// to hold to the kernel rules. Recursion fails closed at emission time as an
// undeclared helper; the order here simply stops at a cycle.
func (em *emitter) reachOrder(fn *ast.FunctionStatement) []string {
	var order []string
	seen := map[string]bool{}
	var visit func(f *ast.FunctionStatement)
	visit = func(f *ast.FunctionStatement) {
		if f == nil || f.Name == nil || seen[f.Name.Value] {
			return
		}
		seen[f.Name.Value] = true
		var callees []string
		walk(f.Body, func(n ast.Node) {
			if call, ok := n.(*ast.InvocationExpression); ok {
				if id, ok := call.Function.(*ast.Identifier); ok {
					if _, known := em.functions[id.Value]; known {
						callees = append(callees, id.Value)
					}
				}
				for _, a := range call.Arguments {
					if id, ok := a.(*ast.Identifier); ok {
						if _, known := em.functions[id.Value]; known {
							callees = append(callees, id.Value)
						}
					}
				}
			}
		})
		sort.Strings(callees)
		for _, c := range callees {
			visit(em.functions[c])
		}
		order = append(order, f.Name.Value)
	}
	visit(fn)
	return order
}

// walk visits the expression and statement nodes under a body.
func walk(node ast.Node, visit func(ast.Node)) {
	if node == nil {
		return
	}
	visit(node)
	switch n := node.(type) {
	case *ast.BlockStatement:
		for _, s := range n.Statements {
			walk(s, visit)
		}
	case *ast.BlockExpression:
		if n.Block != nil {
			walk(n.Block, visit)
		}
	case *ast.ExpressionStatement:
		walk(n.Expression, visit)
	case *ast.VariableDeclaration:
		if n.Value != nil {
			walk(n.Value, visit)
		}
	case *ast.AssignmentStatement:
		walk(n.Value, visit)
	case *ast.IndexAssignmentStatement:
		walk(n.Target, visit)
		walk(n.Value, visit)
	case *ast.WhileStatement:
		walk(n.Condition, visit)
		if n.Body != nil {
			walk(n.Body, visit)
		}
	case *ast.PrefixExpression:
		walk(n.Right, visit)
	case *ast.InfixExpression:
		walk(n.Left, visit)
		walk(n.Right, visit)
	case *ast.IndexExpression:
		walk(n.Left, visit)
		walk(n.Index, visit)
	case *ast.InvocationExpression:
		walk(n.Function, visit)
		for _, a := range n.Arguments {
			walk(a, visit)
		}
	case *ast.MatchExpression:
		walk(n.Scrutinee, visit)
		for _, arm := range n.Arms {
			walk(arm.Body, visit)
		}
	case *ast.RecordLiteral:
		for _, f := range n.FieldOrder {
			walk(f.Value, visit)
		}
	}
}

// ---- literals and identifiers ----

func intLiteral(value int64, typ string) string {
	switch typ {
	case "u32":
		return fmt.Sprintf("%du", value)
	case "u64":
		return fmt.Sprintf("%duL", value)
	case "i64":
		return fmt.Sprintf("%dL", value)
	case "i32":
		return fmt.Sprintf("%d", value)
	}
	return fmt.Sprintf("((%s)%d)", scalarMSL[typ], value)
}

func floatLiteral(text string) string {
	t := strings.ReplaceAll(text, "_", "")
	if strings.HasSuffix(t, "f") || strings.HasSuffix(t, "F") {
		return t
	}
	return t + "f"
}

var mslReserved = map[string]bool{
	"kernel": true, "vertex": true, "fragment": true, "device": true, "constant": true, "thread": true,
	"threadgroup": true, "half": true, "float": true, "int": true, "uint": true, "char": true, "uchar": true,
	"short": true, "ushort": true, "long": true, "ulong": true, "bool": true, "void": true, "return": true,
	"if": true, "else": true, "while": true, "for": true, "do": true, "break": true, "continue": true,
	"switch": true, "case": true, "default": true, "struct": true, "class": true, "template": true,
	"typename": true, "using": true, "namespace": true, "static": true, "inline": true, "const": true,
	"auto": true, "new": true, "delete": true, "this": true, "true": true, "false": true, "metal": true,
	"main": true, "sizeof": true, "union": true, "enum": true, "typedef": true, "volatile": true,
	"operator": true, "private": true, "public": true, "protected": true, "virtual": true, "friend": true,
	"atomic_uint": true, "as_type": true, "min": true, "max": true, "abs": true, "sqrt": true, "fma": true,
	"floor": true, "ceil": true, "trunc": true, "round": true, "rint": true, "fmin": true, "fmax": true,
	"isnan": true, "isinf": true, "isfinite": true, "isnormal": true, "copysign": true, "fabs": true,
	"oak_fault": true, "oak_check": true, "oak_raise": true,
}

// ident renders an Oak name as an MSL identifier: reserved words and names
// ending in _len (which the buffer lengths use) get a suffix.
func ident(name string) string {
	if mslReserved[name] || strings.HasSuffix(name, "_len") || strings.HasPrefix(name, "oak_") {
		return name + "_"
	}
	return strings.ReplaceAll(name, ".", "__")
}
