// Package metal compiles Oak kernels (docs/spec/56-kernels.md) to Metal
// Shading Language. A kernel is a function declared with the `kernel`
// marker whose body lies in the kernel subset: fixed-width integers, f32
// and Bool; views and spans of those as buffers; canonical loops; Bool
// conditionals; calls to other functions in the subset. The emitter is the
// definition of the subset — a construct it cannot translate fails closed
// with a message naming it, and the compiler reports that as OAK-K0101
// whether or not Metal output was requested — so a kernel is exactly the
// Oak the C backend compiles, the interpreter runs, and the Lean
// extraction states theorems about.
//
// Semantics preserved from Oak: integer arithmetic wraps in the operand's
// width; division by zero, a shift count reaching the width, and an index
// past a buffer's length are traps — a GPU thread cannot trap, so each
// raises the launch's fault word and the host traps when the command buffer
// completes (section 3). Floating point is one rounding per operation with
// no contraction and no reassociation: the file pins Metal's safe math mode
// and the descriptor tells the host to compile it that way.
package metal

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/SCKelemen/oak/ast"
	"github.com/SCKelemen/oak/typechecker"
)

// Param describes one kernel parameter in the launch descriptor.
type Param struct {
	Name string
	// Kind is "grid" (the u32 thread position), "view" (device const T*
	// plus a length), "span" (device T* plus a length), or "scalar".
	Kind string
	// Element is the Oak element or scalar type name.
	Element string
	// Buffers are the [[buffer(n)]] indices the parameter occupies: two for
	// a view or span (data, length), one for a scalar, none for the grid.
	Buffers []int
}

// Kernel is the launch descriptor of one emitted kernel: the buffer layout
// the host binds and the fault buffer index it checks after completion.
type Kernel struct {
	Name   string
	Params []Param
	Fault  int
	// Reach lists the kernel and every helper function its body reaches,
	// the set the compiler holds to the kernel rules (loops, effects).
	Reach []string
}

// Result is the emitted Metal source and its kernel descriptors.
type Result struct {
	Source  string
	Kernels []Kernel
}

// Emit compiles every kernel in the program. Programs without kernels yield
// an empty source and no descriptors.
func Emit(program *ast.Program, tc *typechecker.TypeChecker) (*Result, error) {
	em := &emitter{
		env:       tc.Env(),
		functions: map[string]*ast.FunctionStatement{},
		helpers:   map[string]bool{},
	}
	var kernels []*ast.FunctionStatement
	for _, stmt := range program.Statements {
		fn, ok := stmt.(*ast.FunctionStatement)
		if !ok || fn.Name == nil {
			continue
		}
		em.functions[fn.Name.Value] = fn
		if fn.Kernel {
			kernels = append(kernels, fn)
		}
	}
	result := &Result{}
	if len(kernels) == 0 {
		return result, nil
	}
	var bodies strings.Builder
	var helperOrder []string
	for _, fn := range kernels {
		desc, text, err := em.kernel(fn)
		if err != nil {
			return nil, err
		}
		// Helpers the kernel reached, callee-first, each emitted once.
		for _, name := range em.reachOrder(fn) {
			if name == fn.Name.Value || em.helpers[name] {
				continue
			}
			em.helpers[name] = true
			helperOrder = append(helperOrder, name)
		}
		desc.Reach = em.reachOrder(fn)
		result.Kernels = append(result.Kernels, *desc)
		bodies.WriteString(text)
		bodies.WriteString("\n")
	}
	var helpers strings.Builder
	for _, name := range helperOrder {
		text, err := em.helper(em.functions[name])
		if err != nil {
			return nil, err
		}
		helpers.WriteString(text)
		helpers.WriteString("\n")
	}
	var out strings.Builder
	out.WriteString("// Generated by the Oak compiler (codegen/metal): do not edit.\n")
	out.WriteString("// docs/spec/56-kernels.md states the translation. Compile with Metal's\n")
	out.WriteString("// safe math mode (MTLCompileOptions.mathMode = MTLMathModeSafe; on older\n")
	out.WriteString("// SDKs fastMathEnabled = NO): Oak floating point is one rounding per\n")
	out.WriteString("// operation, no contraction, no reassociation.\n//\n")
	out.WriteString("// Launch descriptors (one line per kernel; the host binds buffers by index\n")
	out.WriteString("// and checks the fault word after the command buffer completes — a nonzero\n")
	out.WriteString("// value is an Oak trap: the outputs are unspecified and the host traps):\n")
	for _, k := range result.Kernels {
		out.WriteString("// oak-kernel " + k.descriptorLine() + "\n")
	}
	out.WriteString("\n#include <metal_stdlib>\nusing namespace metal;\n")
	out.WriteString("#pragma METAL fp math_mode(safe)\n#pragma METAL fp contract(off)\n\n")
	out.WriteString(prelude)
	out.WriteString(helpers.String())
	out.WriteString(bodies.String())
	result.Source = out.String()
	return result, nil
}

func (k Kernel) descriptorLine() string {
	var parts []string
	for _, p := range k.Params {
		switch p.Kind {
		case "grid":
			parts = append(parts, p.Name+" grid")
		default:
			idx := make([]string, len(p.Buffers))
			for i, b := range p.Buffers {
				idx[i] = fmt.Sprint(b)
			}
			parts = append(parts, fmt.Sprintf("%s %s %s buffer %s", p.Name, p.Kind, p.Element, strings.Join(idx, ",")))
		}
	}
	parts = append(parts, fmt.Sprintf("fault buffer %d", k.Fault))
	return k.Name + ": " + strings.Join(parts, "; ")
}

// prelude is the fixed runtime every emitted file carries: the fault word,
// the checked index, and the trapping integer operations. Unused functions
// cost nothing.
const prelude = `// Oak runtime for kernels: traps raise the fault word and yield zero.
static inline void oak_raise(device atomic_uint* fault, uint code) {
  atomic_store_explicit(fault, code, memory_order_relaxed);
}
static inline uint oak_check(uint index, uint len, device atomic_uint* fault) {
  if (index >= len) { oak_raise(fault, 1u); return 0u; }
  return index;
}
#define OAK_DIV(T, U, W, MIN) \
static inline T oak_div_##T(T a, T b, device atomic_uint* fault) { \
  if (b == (T)0) { oak_raise(fault, 2u); return (T)0; } \
  if (MIN != (T)0 && a == (T)MIN && b == (T)-1) { return (T)MIN; } \
  return (T)(a / b); \
} \
static inline T oak_rem_##T(T a, T b, device atomic_uint* fault) { \
  if (b == (T)0) { oak_raise(fault, 2u); return (T)0; } \
  if (MIN != (T)0 && a == (T)MIN && b == (T)-1) { return (T)0; } \
  return (T)(a % b); \
} \
static inline T oak_shl_##T(T a, T n, device atomic_uint* fault) { \
  if ((U)n >= (U)W) { oak_raise(fault, 3u); return (T)0; } \
  return (T)((U)a << (U)n); \
} \
static inline T oak_shr_##T(T a, T n, device atomic_uint* fault) { \
  if ((U)n >= (U)W) { oak_raise(fault, 3u); return (T)0; } \
  return (T)(a >> n); \
}
OAK_DIV(uchar, uchar, 8, 0)
OAK_DIV(ushort, ushort, 16, 0)
OAK_DIV(uint, uint, 32, 0)
OAK_DIV(ulong, ulong, 64, 0)
OAK_DIV(char, uchar, 8, -128)
OAK_DIV(short, ushort, 16, -32768)
OAK_DIV(int, uint, 32, (-2147483647-1))
OAK_DIV(long, ulong, 64, (-9223372036854775807L-1L))
#undef OAK_DIV
static inline float oak_fmin(float a, float b) { return (isnan(a) || isnan(b)) ? NAN : fmin(a, b); }
static inline float oak_fmax(float a, float b) { return (isnan(a) || isnan(b)) ? NAN : fmax(a, b); }

`

type emitter struct {
	env       *typechecker.TypeEnvironment
	functions map[string]*ast.FunctionStatement
	helpers   map[string]bool
	// per-function state
	current string
	locals  map[string]oakType
	indent  string
	// reach memo: function name -> callees in the subset, in first-use order
	reach map[string][]string
}

// oakType is the kernel subset's view of a type: a scalar name, or a view
// or span of a scalar.
type oakType struct {
	kind    string // "scalar", "view", "span", "unit"
	element string // Oak scalar name: u8..u64, i8..i64, f32, Bool
}

func (t oakType) String() string {
	switch t.kind {
	case "view":
		return "[]" + t.element
	case "span":
		return "[*]" + t.element
	case "unit":
		return "()"
	}
	return t.element
}

var scalarMSL = map[string]string{
	"u8": "uchar", "u16": "ushort", "u32": "uint", "u64": "ulong",
	"i8": "char", "i16": "short", "i32": "int", "i64": "long",
	"f32": "float", "Bool": "bool",
}

var unsignedOf = map[string]string{
	"u8": "uchar", "u16": "ushort", "u32": "uint", "u64": "ulong",
	"i8": "uchar", "i16": "ushort", "i32": "uint", "i64": "ulong",
}

var intWidth = map[string]int{"u8": 8, "i8": 8, "u16": 16, "i16": 16, "u32": 32, "i32": 32, "u64": 64, "i64": 64}

func isInt(name string) bool    { _, ok := intWidth[name]; return ok }
func isSigned(name string) bool { return strings.HasPrefix(name, "i") }

// kernelTypeOf reads a parameter or declaration type from syntax.
func kernelTypeOf(expr ast.Expression) (oakType, error) {
	switch t := expr.(type) {
	case nil:
		return oakType{kind: "unit"}, nil
	case *ast.Identifier:
		if t.Value == "()" {
			return oakType{kind: "unit"}, nil
		}
		if _, ok := scalarMSL[t.Value]; ok {
			return oakType{kind: "scalar", element: t.Value}, nil
		}
		if t.Value == "f64" {
			return oakType{}, fmt.Errorf("f64 is outside the kernel subset (Apple GPUs have no double precision; compute in f32)")
		}
		return oakType{}, fmt.Errorf("type %s is outside the kernel subset (scalars u8..u64, i8..i64, f32, Bool and their views and spans)", t.Value)
	case *ast.IndexExpression:
		marker, ok := t.Index.(*ast.Identifier)
		if !ok || (marker.Value != "" && marker.Value != "*") {
			return oakType{}, fmt.Errorf("type %s is outside the kernel subset (fixed arrays are not buffers; take a view or span)", expr.String())
		}
		element, err := kernelTypeOf(t.Left)
		if err != nil {
			return oakType{}, err
		}
		if element.kind != "scalar" {
			return oakType{}, fmt.Errorf("type %s is outside the kernel subset (buffers hold scalars)", expr.String())
		}
		kind := "view"
		if marker.Value == "*" {
			kind = "span"
		}
		return oakType{kind: kind, element: element.element}, nil
	}
	return oakType{}, fmt.Errorf("type %s is outside the kernel subset", expr.String())
}

// checkedTypeOf reads the checker's recorded type of an expression.
func (em *emitter) checkedTypeOf(expr ast.Expression) (oakType, bool) {
	typ := em.env.CheckedExpressionType(expr)
	if typ == nil {
		return oakType{}, false
	}
	return em.fromChecker(typ)
}

func (em *emitter) fromChecker(typ typechecker.Type) (oakType, bool) {
	switch t := typ.(type) {
	case *typechecker.PrimitiveType:
		if _, ok := scalarMSL[t.Name]; ok {
			return oakType{kind: "scalar", element: t.Name}, true
		}
	case *typechecker.BoolType:
		return oakType{kind: "scalar", element: "Bool"}, true
	case *typechecker.UnitType:
		return oakType{kind: "unit"}, true
	case *typechecker.ArrayType:
		element, ok := em.fromChecker(t.ElementType)
		if !ok || element.kind != "scalar" {
			return oakType{}, false
		}
		switch {
		case t.IsSpan:
			return oakType{kind: "span", element: element.element}, true
		case t.IsSlice:
			return oakType{kind: "view", element: element.element}, true
		}
	}
	return oakType{}, false
}

// typeOf is the type of an expression inside the current body: a local's
// declared type first, then the checker's record.
func (em *emitter) typeOf(expr ast.Expression) (oakType, bool) {
	if id, ok := expr.(*ast.Identifier); ok {
		if t, known := em.locals[id.Value]; known {
			return t, true
		}
	}
	return em.checkedTypeOf(expr)
}

// ---- signatures ----

func (em *emitter) fail(format string, args ...interface{}) error {
	return fmt.Errorf("metal: %s: %s", em.current, fmt.Sprintf(format, args...))
}

// kernel emits one compute kernel and its descriptor.
func (em *emitter) kernel(fn *ast.FunctionStatement) (*Kernel, string, error) {
	em.current = "kernel " + fn.Name.Value
	if err := em.shapeOK(fn); err != nil {
		return nil, "", err
	}
	ret, err := kernelTypeOf(fn.ReturnType)
	if err != nil {
		return nil, "", em.fail("%v", err)
	}
	if ret.kind != "unit" {
		return nil, "", em.fail("a kernel returns (), got %s; results leave through spans", ret)
	}
	if len(fn.Parameters) == 0 {
		return nil, "", em.fail("a kernel's first parameter is its grid position, a u32")
	}
	em.locals = map[string]oakType{}
	desc := &Kernel{Name: fn.Name.Value}
	var args []string
	next := 0
	for i, p := range fn.Parameters {
		if p == nil || p.Name == nil || p.Variadic {
			return nil, "", em.fail("parameters are named and not variadic")
		}
		t, err := kernelTypeOf(p.Type)
		if err != nil {
			return nil, "", em.fail("parameter %s: %v", p.Name.Value, err)
		}
		name := ident(p.Name.Value)
		if i == 0 {
			if t.kind != "scalar" || t.element != "u32" {
				return nil, "", em.fail("the first parameter %s is the grid position and must be a u32, got %s", p.Name.Value, t)
			}
			em.locals[p.Name.Value] = t
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "grid", Element: "u32"})
			args = append(args, fmt.Sprintf("uint %s [[thread_position_in_grid]]", name))
			continue
		}
		em.locals[p.Name.Value] = t
		msl := scalarMSL[t.element]
		switch t.kind {
		case "view":
			args = append(args, fmt.Sprintf("device const %s* %s [[buffer(%d)]]", msl, name, next), fmt.Sprintf("constant uint& %s_len [[buffer(%d)]]", name, next+1))
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "view", Element: t.element, Buffers: []int{next, next + 1}})
			next += 2
		case "span":
			args = append(args, fmt.Sprintf("device %s* %s [[buffer(%d)]]", msl, name, next), fmt.Sprintf("constant uint& %s_len [[buffer(%d)]]", name, next+1))
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "span", Element: t.element, Buffers: []int{next, next + 1}})
			next += 2
		default:
			args = append(args, fmt.Sprintf("constant %s& %s [[buffer(%d)]]", msl, name, next))
			desc.Params = append(desc.Params, Param{Name: p.Name.Value, Kind: "scalar", Element: t.element, Buffers: []int{next}})
			next++
		}
	}
	desc.Fault = next
	args = append(args, fmt.Sprintf("device atomic_uint* oak_fault [[buffer(%d)]]", next))
	var out strings.Builder
	fmt.Fprintf(&out, "kernel void %s(%s) {\n", ident(fn.Name.Value), strings.Join(args, ", "))
	em.indent = "  "
	body, err := em.functionBody(fn, oakType{kind: "unit"})
	if err != nil {
		return nil, "", err
	}
	out.WriteString(body)
	out.WriteString("}\n")
	return desc, out.String(), nil
}

// helper emits a function the kernel calls as a static inline function
// taking each buffer as pointer and length, and the fault word last.
func (em *emitter) helper(fn *ast.FunctionStatement) (string, error) {
	em.current = fn.Name.Value
	if err := em.shapeOK(fn); err != nil {
		return "", err
	}
	ret, err := kernelTypeOf(fn.ReturnType)
	if err != nil {
		return "", em.fail("result: %v", err)
	}
	if ret.kind != "scalar" && ret.kind != "unit" {
		return "", em.fail("a helper returns a scalar or (), got %s", ret)
	}
	em.locals = map[string]oakType{}
	var args []string
	for _, p := range fn.Parameters {
		if p == nil || p.Name == nil || p.Variadic {
			return "", em.fail("parameters are named and not variadic")
		}
		t, err := kernelTypeOf(p.Type)
		if err != nil {
			return "", em.fail("parameter %s: %v", p.Name.Value, err)
		}
		em.locals[p.Name.Value] = t
		name := ident(p.Name.Value)
		msl := scalarMSL[t.element]
		switch t.kind {
		case "view":
			args = append(args, fmt.Sprintf("device const %s* %s, uint %s_len", msl, name, name))
		case "span":
			args = append(args, fmt.Sprintf("device %s* %s, uint %s_len", msl, name, name))
		default:
			args = append(args, fmt.Sprintf("%s %s", msl, name))
		}
	}
	args = append(args, "device atomic_uint* oak_fault")
	retMSL := "void"
	if ret.kind == "scalar" {
		retMSL = scalarMSL[ret.element]
	}
	var out strings.Builder
	fmt.Fprintf(&out, "static inline %s %s(%s) {\n", retMSL, ident(fn.Name.Value), strings.Join(args, ", "))
	em.indent = "  "
	body, err := em.functionBody(fn, ret)
	if err != nil {
		return "", err
	}
	out.WriteString(body)
	out.WriteString("}\n")
	return out.String(), nil
}

func (em *emitter) shapeOK(fn *ast.FunctionStatement) error {
	switch {
	case fn.Receiver != nil:
		return em.fail("methods are outside the kernel subset")
	case len(fn.TypeParams) != 0:
		return em.fail("generic functions are outside the kernel subset (call an instantiation)")
	case fn.ExternSymbol != "" || fn.AsmBacked:
		return em.fail("extern and asm-backed functions are outside the kernel subset")
	case fn.Body == nil:
		return em.fail("the function has no body")
	}
	return nil
}

// functionBody emits a body: a block, or an expression body returned (or
// evaluated, for unit).
func (em *emitter) functionBody(fn *ast.FunctionStatement, ret oakType) (string, error) {
	var lines []string
	switch body := fn.Body.(type) {
	case *ast.BlockExpression:
		if body.Block != nil {
			if err := em.block(body.Block.Statements, &lines, ret); err != nil {
				return "", err
			}
		}
	default:
		if ret.kind == "unit" {
			if err := em.statement(&ast.ExpressionStatement{Expression: body}, &lines, ret, false); err != nil {
				return "", err
			}
		} else {
			term, err := em.expr(body, ret)
			if err != nil {
				return "", err
			}
			lines = append(lines, em.indent+"return "+term+";")
		}
	}
	return strings.Join(lines, "\n") + "\n", nil
}

// block emits statements; the last statement of a value-returning body is
// its result.
func (em *emitter) block(statements []ast.Statement, lines *[]string, ret oakType) error {
	for i, stmt := range statements {
		last := i == len(statements)-1 && ret.kind == "scalar"
		if err := em.statement(stmt, lines, ret, last); err != nil {
			return err
		}
	}
	return nil
}

func (em *emitter) statement(stmt ast.Statement, lines *[]string, ret oakType, tail bool) error {
	emit := func(format string, args ...interface{}) {
		*lines = append(*lines, em.indent+fmt.Sprintf(format, args...))
	}
	switch s := stmt.(type) {
	case *ast.VariableDeclaration:
		if s.Name == nil {
			return em.fail("a declaration without a name")
		}
		var t oakType
		if s.Type != nil {
			var err error
			if t, err = kernelTypeOf(s.Type); err != nil {
				return em.fail("declaration %s: %v", s.Name.Value, err)
			}
		} else if declared := em.env.CheckedDeclarationType(s); declared != nil {
			var ok bool
			if t, ok = em.fromChecker(declared); !ok {
				return em.fail("declaration %s has type %s, outside the kernel subset", s.Name.Value, declared.String())
			}
		} else {
			return em.fail("declaration %s has no recorded type", s.Name.Value)
		}
		if t.kind != "scalar" {
			return em.fail("declaration %s: locals are scalars; buffers are parameters", s.Name.Value)
		}
		if s.Value == nil {
			emit("%s %s = (%s)0;", scalarMSL[t.element], ident(s.Name.Value), scalarMSL[t.element])
		} else {
			term, err := em.expr(s.Value, t)
			if err != nil {
				return err
			}
			emit("%s %s = %s;", scalarMSL[t.element], ident(s.Name.Value), term)
		}
		em.locals[s.Name.Value] = t
		return nil
	case *ast.AssignmentStatement:
		t, ok := em.locals[s.Name.Value]
		if !ok {
			return em.fail("assignment to %s, which is not a local", s.Name.Value)
		}
		term, err := em.expr(s.Value, t)
		if err != nil {
			return err
		}
		emit("%s = %s;", ident(s.Name.Value), term)
		return nil
	case *ast.IndexAssignmentStatement:
		if s.Target.Dot {
			return em.fail("field assignment %s is outside the kernel subset", s.Target.String())
		}
		base, ok := s.Target.Left.(*ast.Identifier)
		if !ok {
			return em.fail("store into %s is outside the kernel subset (store through a named span)", s.Target.String())
		}
		t, known := em.locals[base.Value]
		if !known || t.kind != "span" {
			return em.fail("store into %s: not a span parameter", base.Value)
		}
		index, err := em.expr(s.Target.Index, oakType{kind: "scalar", element: "u32"})
		if err != nil {
			return err
		}
		value, err := em.expr(s.Value, oakType{kind: "scalar", element: t.element})
		if err != nil {
			return err
		}
		emit("%s[oak_check(%s, %s_len, oak_fault)] = %s;", ident(base.Value), index, ident(base.Value), value)
		return nil
	case *ast.WhileStatement:
		cond, err := em.expr(s.Condition, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return err
		}
		emit("while %s {", parens(cond))
		saved := em.indent
		em.indent += "  "
		if s.Body != nil {
			if err := em.block(s.Body.Statements, lines, oakType{kind: "unit"}); err != nil {
				return err
			}
		}
		em.indent = saved
		emit("}")
		return nil
	case *ast.BreakStatement:
		emit("break;")
		return nil
	case *ast.BlockStatement:
		return em.block(s.Statements, lines, ret)
	case *ast.ExpressionStatement:
		if match, ok := s.Expression.(*ast.MatchExpression); ok && !tail {
			return em.conditionalStatement(match, lines)
		}
		if tail {
			term, err := em.expr(s.Expression, ret)
			if err != nil {
				return err
			}
			emit("return %s;", term)
			return nil
		}
		if call, ok := s.Expression.(*ast.InvocationExpression); ok {
			term, err := em.call(call, oakType{kind: "unit"})
			if err != nil {
				return err
			}
			emit("%s;", term)
			return nil
		}
		if block, ok := s.Expression.(*ast.BlockExpression); ok && block.Block != nil {
			return em.block(block.Block.Statements, lines, oakType{kind: "unit"})
		}
		return em.fail("statement %s is outside the kernel subset", s.Expression.String())
	}
	return em.fail("statement %s is outside the kernel subset", stmt.String())
}

// conditionalStatement emits a Bool conditional in statement position as
// if/else over its arms.
func (em *emitter) conditionalStatement(match *ast.MatchExpression, lines *[]string) error {
	trueBody, falseBody, ok := boolArms(match)
	if !ok {
		return em.fail("match %s is outside the kernel subset (Bool conditionals only)", match.String())
	}
	cond, err := em.expr(match.Scrutinee, oakType{kind: "scalar", element: "Bool"})
	if err != nil {
		return err
	}
	*lines = append(*lines, em.indent+"if "+parens(cond)+" {")
	if err := em.armBody(trueBody, lines); err != nil {
		return err
	}
	if !isEmptyArm(falseBody) {
		*lines = append(*lines, em.indent+"} else {")
		if err := em.armBody(falseBody, lines); err != nil {
			return err
		}
	}
	*lines = append(*lines, em.indent+"}")
	return nil
}

func (em *emitter) armBody(body ast.Expression, lines *[]string) error {
	saved := em.indent
	em.indent += "  "
	defer func() { em.indent = saved }()
	switch b := body.(type) {
	case *ast.BlockExpression:
		if b.Block == nil {
			return nil
		}
		return em.block(b.Block.Statements, lines, oakType{kind: "unit"})
	case *ast.MatchExpression:
		return em.conditionalStatement(b, lines)
	case *ast.InvocationExpression:
		term, err := em.call(b, oakType{kind: "unit"})
		if err != nil {
			return err
		}
		*lines = append(*lines, em.indent+term+";")
		return nil
	}
	if isUnitLiteral(body) {
		return nil
	}
	return em.fail("conditional arm %s is outside the kernel subset in statement position", body.String())
}

func isUnitLiteral(expr ast.Expression) bool {
	id, ok := expr.(*ast.Identifier)
	return ok && id.Value == "()"
}

// isEmptyArm reports an absent or empty conditional arm: the implicit unit
// else, or an empty block.
func isEmptyArm(expr ast.Expression) bool {
	if expr == nil || isUnitLiteral(expr) {
		return true
	}
	block, ok := expr.(*ast.BlockExpression)
	return ok && (block.Block == nil || len(block.Block.Statements) == 0)
}

// parens wraps a condition once: an already parenthesized term is used as is.
func parens(cond string) string {
	if strings.HasPrefix(cond, "(") && strings.HasSuffix(cond, ")") {
		depth := 0
		for i, r := range cond {
			switch r {
			case '(':
				depth++
			case ')':
				depth--
				if depth == 0 && i != len(cond)-1 {
					return "(" + cond + ")"
				}
			}
		}
		return cond
	}
	return "(" + cond + ")"
}

// boolArms decodes `cond ? a | b`: two arms with Bool literal patterns, or
// a literal true arm and a wildcard.
func boolArms(match *ast.MatchExpression) (ast.Expression, ast.Expression, bool) {
	if len(match.Arms) == 0 || len(match.Arms) > 2 {
		return nil, nil, false
	}
	var trueBody, falseBody ast.Expression
	for _, arm := range match.Arms {
		switch p := arm.Pattern.(type) {
		case *ast.LiteralPattern:
			lit, ok := p.Value.(*ast.Boolean)
			if !ok {
				return nil, nil, false
			}
			if lit.Value {
				trueBody = arm.Body
			} else {
				falseBody = arm.Body
			}
		case *ast.WildcardPattern:
			if trueBody == nil {
				return nil, nil, false
			}
			falseBody = arm.Body
		default:
			return nil, nil, false
		}
	}
	if trueBody == nil {
		return nil, nil, false
	}
	return trueBody, falseBody, true
}

// ---- expressions ----

// expr emits an expression expected to have type want.
func (em *emitter) expr(expr ast.Expression, want oakType) (string, error) {
	switch e := expr.(type) {
	case *ast.IntegerLiteral:
		t := want
		if checked, ok := em.checkedTypeOf(e); ok && checked.kind == "scalar" {
			t = checked
		}
		if t.kind != "scalar" || !isInt(t.element) {
			if t.kind == "scalar" && t.element == "f32" {
				return fmt.Sprintf("%d.0f", e.Value), nil
			}
			return "", em.fail("integer literal %d has no integer type in context", e.Value)
		}
		return intLiteral(e.Value, t.element), nil
	case *ast.FloatLiteral:
		return floatLiteral(e.Text), nil
	case *ast.Boolean:
		if e.Value {
			return "true", nil
		}
		return "false", nil
	case *ast.Identifier:
		t, ok := em.locals[e.Value]
		if !ok {
			return "", em.fail("identifier %s is not a parameter or local (globals and constants are outside the kernel subset)", e.Value)
		}
		if t.kind != "scalar" {
			return "", em.fail("%s is a buffer and can only be indexed, measured with len, or passed on", e.Value)
		}
		return ident(e.Value), nil
	case *ast.PrefixExpression:
		return em.prefix(e, want)
	case *ast.InfixExpression:
		return em.infix(e, want)
	case *ast.IndexExpression:
		if e.Dot {
			return "", em.fail("field access %s is outside the kernel subset", e.String())
		}
		base, ok := e.Left.(*ast.Identifier)
		if !ok {
			return "", em.fail("index into %s is outside the kernel subset (index a named buffer)", e.Left.String())
		}
		t, known := em.locals[base.Value]
		if !known || t.kind == "scalar" {
			return "", em.fail("%s is not a buffer", base.Value)
		}
		index, err := em.expr(e.Index, oakType{kind: "scalar", element: "u32"})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s[oak_check(%s, %s_len, oak_fault)]", ident(base.Value), index, ident(base.Value)), nil
	case *ast.InvocationExpression:
		return em.call(e, want)
	case *ast.MatchExpression:
		trueBody, falseBody, ok := boolArms(e)
		if !ok || falseBody == nil {
			return "", em.fail("match %s in value position is outside the kernel subset (a Bool conditional with two expression arms)", e.String())
		}
		cond, err := em.expr(e.Scrutinee, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return "", err
		}
		left, err := em.expr(trueBody, want)
		if err != nil {
			return "", err
		}
		right, err := em.expr(falseBody, want)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s ? %s : %s)", cond, left, right), nil
	case *ast.BlockExpression:
		if e.Block != nil && len(e.Block.Statements) == 1 {
			if es, ok := e.Block.Statements[0].(*ast.ExpressionStatement); ok {
				return em.expr(es.Expression, want)
			}
		}
		return "", em.fail("block %s in value position is outside the kernel subset", e.String())
	}
	return "", em.fail("expression %s is outside the kernel subset", expr.String())
}

func (em *emitter) operandType(e ast.Expression, fallback oakType) oakType {
	if t, ok := em.typeOf(e); ok && t.kind == "scalar" {
		return t
	}
	return fallback
}

func (em *emitter) prefix(e *ast.PrefixExpression, want oakType) (string, error) {
	switch e.Operator {
	case "!":
		inner, err := em.expr(e.Right, oakType{kind: "scalar", element: "Bool"})
		if err != nil {
			return "", err
		}
		return "(!" + inner + ")", nil
	case "-":
		t := em.operandType(e, em.operandType(e.Right, want))
		inner, err := em.expr(e.Right, t)
		if err != nil {
			return "", err
		}
		if t.element == "f32" {
			return "(-" + inner + ")", nil
		}
		if !isInt(t.element) {
			return "", em.fail("negation of %s is outside the kernel subset", t)
		}
		// Total negation in the operand's width: two's complement wraps.
		return fmt.Sprintf("(%s)(0u - (%s)%s)", scalarMSL[t.element], unsignedOf[t.element], inner), nil
	case "^":
		t := em.operandType(e, em.operandType(e.Right, want))
		inner, err := em.expr(e.Right, t)
		if err != nil {
			return "", err
		}
		if !isInt(t.element) {
			return "", em.fail("complement of %s is outside the kernel subset", t)
		}
		return fmt.Sprintf("(%s)(~%s)", scalarMSL[t.element], inner), nil
	}
	return "", em.fail("prefix operator %s is outside the kernel subset", e.Operator)
}

func (em *emitter) infix(e *ast.InfixExpression, want oakType) (string, error) {
	boolT := oakType{kind: "scalar", element: "Bool"}
	switch e.Operator {
	case "&&", "||":
		left, err := em.expr(e.Left, boolT)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, boolT)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	case "==", "!=", "<", "<=", ">", ">=":
		t := em.operandType(e.Left, oakType{})
		if t.kind == "" {
			t = em.operandType(e.Right, oakType{})
		}
		if t.kind == "" {
			return "", em.fail("comparison %s has no typed operand", e.String())
		}
		left, err := em.expr(e.Left, t)
		if err != nil {
			return "", err
		}
		right, err := em.expr(e.Right, t)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
	}
	// Arithmetic and bitwise: one width, the result's.
	t := em.operandType(e, oakType{})
	if t.kind == "" {
		t = em.operandType(e.Left, em.operandType(e.Right, want))
	}
	if t.kind != "scalar" {
		return "", em.fail("operator %s in %s has no scalar type", e.Operator, e.String())
	}
	left, err := em.expr(e.Left, t)
	if err != nil {
		return "", err
	}
	right, err := em.expr(e.Right, t)
	if err != nil {
		return "", err
	}
	msl := scalarMSL[t.element]
	if t.element == "f32" {
		switch e.Operator {
		case "+", "-", "*", "/":
			return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
		}
		return "", em.fail("operator %s over f32 is outside the kernel subset", e.Operator)
	}
	if !isInt(t.element) {
		return "", em.fail("operator %s over %s is outside the kernel subset", e.Operator, t)
	}
	u := unsignedOf[t.element]
	switch e.Operator {
	case "+", "-", "*":
		// Wrapping in the operand's width. uint and ulong wrap on their own;
		// narrow and signed types compute unsigned and cast back.
		if t.element == "u32" || t.element == "u64" {
			return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil
		}
		return fmt.Sprintf("(%s)((%s)%s %s (%s)%s)", msl, u, left, e.Operator, u, right), nil
	case "/":
		return fmt.Sprintf("oak_div_%s(%s, %s, oak_fault)", msl, left, right), nil
	case "%":
		return fmt.Sprintf("oak_rem_%s(%s, %s, oak_fault)", msl, left, right), nil
	case "&", "|", "^":
		return fmt.Sprintf("(%s)(%s %s %s)", msl, left, e.Operator, right), nil
	case "<<":
		return fmt.Sprintf("oak_shl_%s(%s, %s, oak_fault)", msl, left, right), nil
	case ">>":
		return fmt.Sprintf("oak_shr_%s(%s, %s, oak_fault)", msl, left, right), nil
	}
	return "", em.fail("operator %s is outside the kernel subset", e.Operator)
}

var conversionRow = regexp.MustCompile(`^([ui](?:8|16|32|64)|f32)_(trunc|bits|round|saturating|checked|trapping)_([ui](?:8|16|32|64)|f32|f64)$`)

var floatIntrinsics = map[string]string{
	"fma": "fma", "sqrt": "precise::sqrt", "abs": "fabs", "copysign": "copysign",
	"floor": "floor", "ceil": "ceil", "trunc": "trunc", "round": "round", "round_even": "rint",
	"min": "oak_fmin", "max": "oak_fmax", "min_num": "fmin", "max_num": "fmax",
	"is_nan": "isnan", "is_finite": "isfinite", "is_infinite": "isinf", "is_normal": "isnormal",
}

func (em *emitter) call(call *ast.InvocationExpression, want oakType) (string, error) {
	callee, ok := call.Function.(*ast.Identifier)
	if !ok {
		return "", em.fail("call through %s is outside the kernel subset", call.Function.String())
	}
	name := callee.Value
	args := call.Arguments
	switch {
	case name == "len":
		if len(args) != 1 {
			return "", em.fail("len takes one argument")
		}
		base, ok := args[0].(*ast.Identifier)
		if !ok {
			return "", em.fail("len of %s is outside the kernel subset (measure a named buffer)", args[0].String())
		}
		if t, known := em.locals[base.Value]; !known || t.kind == "scalar" {
			return "", em.fail("len of %s: not a buffer", base.Value)
		}
		return ident(base.Value) + "_len", nil
	case scalarMSL[name] != "" && name != "Bool":
		// Constructor conversions: widening and float constructors.
		if len(args) != 1 {
			return "", em.fail("%s takes one argument", name)
		}
		source := em.operandType(args[0], oakType{})
		if source.kind == "" {
			source = oakType{kind: "scalar", element: name}
		}
		inner, err := em.expr(args[0], source)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("((%s)%s)", scalarMSL[name], inner), nil
	case conversionRow.MatchString(name):
		m := conversionRow.FindStringSubmatch(name)
		target, op, source := m[1], m[2], m[3]
		if len(args) != 1 {
			return "", em.fail("%s takes one argument", name)
		}
		if source == "f64" {
			return "", em.fail("%s: f64 is outside the kernel subset", name)
		}
		inner, err := em.expr(args[0], oakType{kind: "scalar", element: source})
		if err != nil {
			return "", err
		}
		switch {
		case op == "trunc" && isInt(target) && isInt(source):
			return fmt.Sprintf("((%s)%s)", scalarMSL[target], inner), nil
		case op == "bits" && isInt(target) && isInt(source) && intWidth[target] == intWidth[source]:
			return fmt.Sprintf("((%s)%s)", scalarMSL[target], inner), nil
		case op == "bits" && (target == "f32" && source == "u32" || target == "u32" && source == "f32"):
			return fmt.Sprintf("as_type<%s>(%s)", scalarMSL[target], inner), nil
		case op == "round" && target == "f32" && isInt(source):
			// Integer to float rounds to nearest even in Metal, as in Oak.
			return fmt.Sprintf("((float)%s)", inner), nil
		}
		return "", em.fail("%s is outside the kernel subset (trunc and same-width bits between integers, bits between f32 and u32, round from an integer to f32)", name)
	case floatIntrinsics[name] != "":
		var rendered []string
		for _, a := range args {
			term, err := em.expr(a, oakType{kind: "scalar", element: "f32"})
			if err != nil {
				return "", err
			}
			rendered = append(rendered, term)
		}
		return fmt.Sprintf("%s(%s)", floatIntrinsics[name], strings.Join(rendered, ", ")), nil
	case name == "total_order" || name == "assert" || name == "subslice" || name == "view" || name == "span":
		return "", em.fail("%s is outside the kernel subset", name)
	}
	target, known := em.functions[name]
	if !known {
		return "", em.fail("call to %s is outside the kernel subset (not a function of the program)", name)
	}
	if target.Kernel {
		return "", em.fail("a kernel does not call another kernel (%s); share a helper", name)
	}
	if len(args) != len(target.Parameters) {
		return "", em.fail("call to %s: %d arguments for %d parameters", name, len(args), len(target.Parameters))
	}
	var rendered []string
	for i, a := range args {
		pt, err := kernelTypeOf(target.Parameters[i].Type)
		if err != nil {
			return "", em.fail("call to %s: parameter %s: %v", name, target.Parameters[i].Name.Value, err)
		}
		if pt.kind == "view" || pt.kind == "span" {
			base, ok := a.(*ast.Identifier)
			if !ok {
				return "", em.fail("call to %s: a buffer argument is a named buffer, got %s", name, a.String())
			}
			at, known := em.locals[base.Value]
			if !known || at.kind == "scalar" {
				return "", em.fail("call to %s: %s is not a buffer", name, base.Value)
			}
			if pt.kind == "span" && at.kind != "span" {
				return "", em.fail("call to %s: %s is a view, the parameter wants a span", name, base.Value)
			}
			rendered = append(rendered, ident(base.Value), ident(base.Value)+"_len")
			continue
		}
		term, err := em.expr(a, pt)
		if err != nil {
			return "", err
		}
		rendered = append(rendered, term)
	}
	rendered = append(rendered, "oak_fault")
	return fmt.Sprintf("%s(%s)", ident(name), strings.Join(rendered, ", ")), nil
}

// ---- reach ----

// reachOrder lists a function and every program function it reaches
// through calls, callees before callers, for emission and for the compiler
// to hold to the kernel rules. Recursion fails closed at emission time as an
// undeclared helper; the order here simply stops at a cycle.
func (em *emitter) reachOrder(fn *ast.FunctionStatement) []string {
	var order []string
	seen := map[string]bool{}
	var visit func(f *ast.FunctionStatement)
	visit = func(f *ast.FunctionStatement) {
		if f == nil || f.Name == nil || seen[f.Name.Value] {
			return
		}
		seen[f.Name.Value] = true
		var callees []string
		walk(f.Body, func(n ast.Node) {
			if call, ok := n.(*ast.InvocationExpression); ok {
				if id, ok := call.Function.(*ast.Identifier); ok {
					if _, known := em.functions[id.Value]; known {
						callees = append(callees, id.Value)
					}
				}
			}
		})
		sort.Strings(callees)
		for _, c := range callees {
			visit(em.functions[c])
		}
		order = append(order, f.Name.Value)
	}
	visit(fn)
	return order
}

// walk visits the expression and statement nodes under a body.
func walk(node ast.Node, visit func(ast.Node)) {
	if node == nil {
		return
	}
	visit(node)
	switch n := node.(type) {
	case *ast.BlockStatement:
		for _, s := range n.Statements {
			walk(s, visit)
		}
	case *ast.BlockExpression:
		if n.Block != nil {
			walk(n.Block, visit)
		}
	case *ast.ExpressionStatement:
		walk(n.Expression, visit)
	case *ast.VariableDeclaration:
		if n.Value != nil {
			walk(n.Value, visit)
		}
	case *ast.AssignmentStatement:
		walk(n.Value, visit)
	case *ast.IndexAssignmentStatement:
		walk(n.Target, visit)
		walk(n.Value, visit)
	case *ast.WhileStatement:
		walk(n.Condition, visit)
		if n.Body != nil {
			walk(n.Body, visit)
		}
	case *ast.PrefixExpression:
		walk(n.Right, visit)
	case *ast.InfixExpression:
		walk(n.Left, visit)
		walk(n.Right, visit)
	case *ast.IndexExpression:
		walk(n.Left, visit)
		walk(n.Index, visit)
	case *ast.InvocationExpression:
		walk(n.Function, visit)
		for _, a := range n.Arguments {
			walk(a, visit)
		}
	case *ast.MatchExpression:
		walk(n.Scrutinee, visit)
		for _, arm := range n.Arms {
			walk(arm.Body, visit)
		}
	}
}

// ---- literals and identifiers ----

func intLiteral(value int64, typ string) string {
	switch typ {
	case "u32":
		return fmt.Sprintf("%du", value)
	case "u64":
		return fmt.Sprintf("%duL", value)
	case "i64":
		return fmt.Sprintf("%dL", value)
	case "i32":
		return fmt.Sprintf("%d", value)
	}
	return fmt.Sprintf("((%s)%d)", scalarMSL[typ], value)
}

func floatLiteral(text string) string {
	t := strings.ReplaceAll(text, "_", "")
	if strings.HasSuffix(t, "f") || strings.HasSuffix(t, "F") {
		return t
	}
	return t + "f"
}

var mslReserved = map[string]bool{
	"kernel": true, "vertex": true, "fragment": true, "device": true, "constant": true, "thread": true,
	"threadgroup": true, "half": true, "float": true, "int": true, "uint": true, "char": true, "uchar": true,
	"short": true, "ushort": true, "long": true, "ulong": true, "bool": true, "void": true, "return": true,
	"if": true, "else": true, "while": true, "for": true, "do": true, "break": true, "continue": true,
	"switch": true, "case": true, "default": true, "struct": true, "class": true, "template": true,
	"typename": true, "using": true, "namespace": true, "static": true, "inline": true, "const": true,
	"auto": true, "new": true, "delete": true, "this": true, "true": true, "false": true, "metal": true,
	"main": true, "sizeof": true, "union": true, "enum": true, "typedef": true, "volatile": true,
	"operator": true, "private": true, "public": true, "protected": true, "virtual": true, "friend": true,
	"atomic_uint": true, "as_type": true, "min": true, "max": true, "abs": true, "sqrt": true, "fma": true,
	"floor": true, "ceil": true, "trunc": true, "round": true, "rint": true, "fmin": true, "fmax": true,
	"isnan": true, "isinf": true, "isfinite": true, "isnormal": true, "copysign": true, "fabs": true,
	"oak_fault": true, "oak_check": true, "oak_raise": true,
}

// ident renders an Oak name as an MSL identifier: reserved words and names
// ending in _len (which the buffer lengths use) get a suffix.
func ident(name string) string {
	if mslReserved[name] || strings.HasSuffix(name, "_len") || strings.HasPrefix(name, "oak_") {
		return name + "_"
	}
	return strings.ReplaceAll(name, ".", "__")
}
