-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.LRATChecker

def LRAT_MAGIC : UInt32 := (1280459348 : UInt32)

def LRAT_HEADER_WORDS : UInt32 := (8 : UInt32)

def LRAT_ACCEPTED : UInt32 := (0 : UInt32)

def LRAT_MALFORMED : UInt32 := (1 : UInt32)

def LRAT_NOT_LIVE : UInt32 := (2 : UInt32)

def LRAT_NOT_UNIT : UInt32 := (3 : UInt32)

def LRAT_NO_CONFLICT : UInt32 := (4 : UInt32)

def LRAT_ID_ORDER : UInt32 := (5 : UInt32)

def LRAT_NO_EMPTY : UInt32 := (6 : UInt32)

def LRAT_CAPACITY : UInt32 := (7 : UInt32)

def LRAT_SATISFIED : UInt32 := (8 : UInt32)

def LRAT_UNASSIGNED : UInt8 := (0 : UInt8)

def lrat_fits (at_ : UInt32) (count : UInt32) (limit : UInt32) (fuel : Nat) : Option (Bool) := do
  pure ((decide (at_ <= limit)) && (decide (count <= (limit - at_))))

def lrat_false_value (lit : UInt32) (fuel : Nat) : Option (UInt8) := do
  pure (if ((lit % (2 : UInt32)) == (1 : UInt32)) then (1 : UInt8) else (2 : UInt8))

def lrat_true_value (lit : UInt32) (fuel : Nat) : Option (UInt8) := do
  pure (if ((lit % (2 : UInt32)) == (1 : UInt32)) then (2 : UInt8) else (1 : UInt8))

def lrat_undo.loop1 (assign : Array UInt8) (trail : Array UInt32) (used : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < used)) then do
      let assign := assign.setIfInBounds (trail.getD i.toNat (0 : UInt32)).toNat LRAT_UNASSIGNED
      let i := (i + (1 : UInt32))
      lrat_undo.loop1 assign trail used i fuel
    else pure (assign, i)

def lrat_undo (assign : Array UInt8) (trail : Array UInt32) (used : UInt32) (fuel : Nat) : Option (Unit × Array UInt8 × Array UInt32) := do
  let i : UInt32 := (0 : UInt32)
  let (assign, i) ← lrat_undo.loop1 assign trail used i fuel
  pure ((), assign, trail)

def lrat_rup.loop1 (words : Array UInt32) (target_at : UInt32) (target_n : UInt32) (assign : Array UInt8) (trail : Array UInt32) (variables : UInt32) (status : UInt32) (settled : Bool) (used : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × Bool × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < target_n)) && (status == LRAT_ACCEPTED)) then do
      let lit : UInt32 := (words.getD (target_at + i).toNat (0 : UInt32))
      let variable_ : UInt32 := (lit / (2 : UInt32))
      let status ← (if (decide (variable_ >= variables)) then (do
          let status := LRAT_MALFORMED
          pure status)
        else (do
          pure status))
      let (assign, trail, settled, used) ← (if ((status == LRAT_ACCEPTED) && (!settled)) then (do
          let r1 ← lrat_false_value lit fuel
          let wanted : UInt8 := r1
          let prior : UInt8 := (assign.getD variable_.toNat (0 : UInt8))
          let (assign, trail, settled, used) ← (if (prior == LRAT_UNASSIGNED) then (do
              let assign := assign.setIfInBounds variable_.toNat wanted
              let trail := trail.setIfInBounds used.toNat variable_
              let used := (used + (1 : UInt32))
              pure (assign, trail, settled, used))
            else (do
              let settled := (prior != wanted)
              pure (assign, trail, settled, used)))
          pure (assign, trail, settled, used))
        else (do
          pure (assign, trail, settled, used)))
      let i := (i + (1 : UInt32))
      lrat_rup.loop1 words target_at target_n assign trail variables status settled used i fuel
    else pure (assign, trail, status, settled, used, i)

def lrat_rup.loop3 (store : Array UInt32) (assign : Array UInt8) (status : UInt32) (start : UInt32) (count : UInt32) (remaining : UInt32) (unit : UInt32) (j : UInt32) : Nat → Option (UInt32 × UInt32 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (j < count)) && (status == LRAT_ACCEPTED)) then do
      let lit : UInt32 := (store.getD (start + j).toNat (0 : UInt32))
      let a : UInt8 := (assign.getD (lit / (2 : UInt32)).toNat (0 : UInt8))
      let r2 ← lrat_true_value lit fuel
      let (status, remaining, unit) ← (if (a == r2) then (do
          let status := LRAT_SATISFIED
          pure (status, remaining, unit))
        else (do
          let (remaining, unit) ← (if ((a == LRAT_UNASSIGNED) && ((remaining == (0 : UInt32)) || (unit != lit))) then (do
              let remaining := (remaining + (1 : UInt32))
              let unit := lit
              pure (remaining, unit))
            else (do
              pure (remaining, unit)))
          pure (status, remaining, unit)))
      let j := (j + (1 : UInt32))
      lrat_rup.loop3 store assign status start count remaining unit j fuel
    else pure (status, remaining, unit, j)

def lrat_rup.loop2 (words : Array UInt32) (hints_at : UInt32) (hints_n : UInt32) (starts : Array UInt32) (lengths : Array UInt32) (alive : Array UInt8) (store : Array UInt32) (assign : Array UInt8) (trail : Array UInt32) (max_id : UInt32) (status : UInt32) (settled : Bool) (used : UInt32) (h : UInt32) : Nat → Option (Array UInt8 × Array UInt32 × UInt32 × Bool × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (((decide (h < hints_n)) && (status == LRAT_ACCEPTED)) && (!settled)) then do
      let id_ : UInt32 := (words.getD (hints_at + h).toNat (0 : UInt32))
      let live : Bool := (((decide (id_ <= max_id)) && (decide (id_ > (0 : UInt32)))) && ((alive.getD id_.toNat (0 : UInt8)) != (0 : UInt8)))
      let (assign, trail, status, settled, used) ← (if live then (do
          let start : UInt32 := (starts.getD id_.toNat (0 : UInt32))
          let count : UInt32 := (lengths.getD id_.toNat (0 : UInt32))
          let remaining : UInt32 := (0 : UInt32)
          let unit : UInt32 := (0 : UInt32)
          let j : UInt32 := (0 : UInt32)
          let (status, remaining, unit, j) ← lrat_rup.loop3 store assign status start count remaining unit j fuel
          let (assign, trail, status, settled, used) ← (if (status == LRAT_ACCEPTED) then (do
              let (assign, trail, status, settled, used) ← (if (remaining == (0 : UInt32)) then (do
                  let (status, settled) ← (if ((h + (1 : UInt32)) == hints_n) then (do
                      let settled := true
                      pure (status, settled))
                    else (do
                      let status := LRAT_MALFORMED
                      pure (status, settled)))
                  pure (assign, trail, status, settled, used))
                else (do
                  let (assign, trail, status, used) ← (if (remaining == (1 : UInt32)) then (do
                      let r3 ← lrat_true_value unit fuel
                      let assign := assign.setIfInBounds (unit / (2 : UInt32)).toNat r3
                      let trail := trail.setIfInBounds used.toNat (unit / (2 : UInt32))
                      let used := (used + (1 : UInt32))
                      pure (assign, trail, status, used))
                    else (do
                      let status := LRAT_NOT_UNIT
                      pure (assign, trail, status, used)))
                  pure (assign, trail, status, settled, used)))
              pure (assign, trail, status, settled, used))
            else (do
              pure (assign, trail, status, settled, used)))
          pure (assign, trail, status, settled, used))
        else (do
          let status := LRAT_NOT_LIVE
          pure (assign, trail, status, settled, used)))
      let h := (h + (1 : UInt32))
      lrat_rup.loop2 words hints_at hints_n starts lengths alive store assign trail max_id status settled used h fuel
    else pure (assign, trail, status, settled, used, h)

def lrat_rup (words : Array UInt32) (target_at : UInt32) (target_n : UInt32) (hints_at : UInt32) (hints_n : UInt32) (starts : Array UInt32) (lengths : Array UInt32) (alive : Array UInt8) (store : Array UInt32) (assign : Array UInt8) (trail : Array UInt32) (variables : UInt32) (max_id : UInt32) (fuel : Nat) : Option (UInt32 × Array UInt32 × Array UInt32 × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32) := do
  let status : UInt32 := LRAT_ACCEPTED
  let settled : Bool := false
  let used : UInt32 := (0 : UInt32)
  let i : UInt32 := (0 : UInt32)
  let (assign, trail, status, settled, used, i) ← lrat_rup.loop1 words target_at target_n assign trail variables status settled used i fuel
  let h : UInt32 := (0 : UInt32)
  let (assign, trail, status, settled, used, h) ← lrat_rup.loop2 words hints_at hints_n starts lengths alive store assign trail max_id status settled used h fuel
  let status ← (if ((status == LRAT_ACCEPTED) && (!settled)) then (do
      let status := LRAT_NO_CONFLICT
      pure status)
    else (do
      pure status))
  let (r4, assign, trail) ← lrat_undo assign trail used fuel
  pure (status, starts, lengths, alive, store, assign, trail)

def lrat_check.loop1 (alive : Array UInt8) (ok : Bool) (max_id : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i <= max_id)) && ok) then do
      let alive := alive.setIfInBounds i.toNat (0 : UInt8)
      let i := (i + (1 : UInt32))
      lrat_check.loop1 alive ok max_id i fuel
    else pure (alive, i)

def lrat_check.loop2 (assign : Array UInt8) (ok : Bool) (variables : UInt32) (i : UInt32) : Nat → Option (Array UInt8 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < variables)) && ok) then do
      let assign := assign.setIfInBounds i.toNat LRAT_UNASSIGNED
      let i := (i + (1 : UInt32))
      lrat_check.loop2 assign ok variables i fuel
    else pure (assign, i)

def lrat_check.loop4 (words : Array UInt32) (store : Array UInt32) (status : UInt32) (variables : UInt32) (at_ : UInt32) (used : UInt32) (n : UInt32) (j : UInt32) : Nat → Option (Array UInt32 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (j < n)) && (status == LRAT_ACCEPTED)) then do
      let lit : UInt32 := (words.getD ((at_ + (1 : UInt32)) + j).toNat (0 : UInt32))
      let (store, status) ← (if (decide ((lit / (2 : UInt32)) < variables)) then (do
          let store := store.setIfInBounds (used + j).toNat lit
          pure (store, status))
        else (do
          let status := LRAT_MALFORMED
          pure (store, status)))
      let j := (j + (1 : UInt32))
      lrat_check.loop4 words store status variables at_ used n j fuel
    else pure (store, status, j)

def lrat_check.loop3 (words : Array UInt32) (starts : Array UInt32) (lengths : Array UInt32) (alive : Array UInt8) (store : Array UInt32) (status : UInt32) (variables : UInt32) (clause_count : UInt32) (store_words : UInt32) (at_ : UInt32) (end_ : UInt32) (used : UInt32) (empty : Bool) (c : UInt32) : Nat → Option (Array UInt32 × Array UInt32 × Array UInt8 × Array UInt32 × UInt32 × UInt32 × UInt32 × Bool × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (c <= clause_count)) && (status == LRAT_ACCEPTED)) then do
      let n : UInt32 := (if (decide (at_ < end_)) then (words.getD at_.toNat (0 : UInt32)) else (0 : UInt32))
      let r3 ← lrat_fits (at_ + (1 : UInt32)) n end_ fuel
      let r4 ← lrat_fits used n store_words fuel
      let fits : Bool := (((decide (at_ < end_)) && r3) && r4)
      let (starts, lengths, alive, store, status, at_, used, empty) ← (if fits then (do
          let starts := starts.setIfInBounds c.toNat used
          let lengths := lengths.setIfInBounds c.toNat n
          let j : UInt32 := (0 : UInt32)
          let (store, status, j) ← lrat_check.loop4 words store status variables at_ used n j fuel
          let used := (used + n)
          let at_ := ((at_ + (1 : UInt32)) + n)
          let alive := alive.setIfInBounds c.toNat (1 : UInt8)
          let empty := (empty || (n == (0 : UInt32)))
          pure (starts, lengths, alive, store, status, at_, used, empty))
        else (do
          let status := LRAT_MALFORMED
          pure (starts, lengths, alive, store, status, at_, used, empty)))
      let c := (c + (1 : UInt32))
      lrat_check.loop3 words starts lengths alive store status variables clause_count store_words at_ end_ used empty c fuel
    else pure (starts, lengths, alive, store, status, at_, used, empty, c)

def lrat_check.loop6 (words : Array UInt32) (alive : Array UInt8) (status : UInt32) (max_id : UInt32) (at_ : UInt32) (k : UInt32) (d : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (d < k)) && (status == LRAT_ACCEPTED)) then do
      let cid : UInt32 := (words.getD ((at_ + (3 : UInt32)) + d).toNat (0 : UInt32))
      let (alive, status) ← (if (((decide (cid <= max_id)) && (decide (cid > (0 : UInt32)))) && ((alive.getD cid.toNat (0 : UInt8)) != (0 : UInt8))) then (do
          let alive := alive.setIfInBounds cid.toNat (0 : UInt8)
          pure (alive, status))
        else (do
          let status := LRAT_NOT_LIVE
          pure (alive, status)))
      let d := (d + (1 : UInt32))
      lrat_check.loop6 words alive status max_id at_ k d fuel
    else pure (alive, status, d)

def lrat_check.loop7 (words : Array UInt32) (store : Array UInt32) (used : UInt32) (n : UInt32) (lits_at : UInt32) (j : UInt32) : Nat → Option (Array UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (j < n)) then do
      let store := store.setIfInBounds (used + j).toNat (words.getD (lits_at + j).toNat (0 : UInt32))
      let j := (j + (1 : UInt32))
      lrat_check.loop7 words store used n lits_at j fuel
    else pure (store, j)

def lrat_check.loop5 (words : Array UInt32) (starts : Array UInt32) (lengths : Array UInt32) (alive : Array UInt8) (store : Array UInt32) (assign : Array UInt8) (trail : Array UInt32) (status : UInt32) (additions : UInt32) (deletions : UInt32) (variables : UInt32) (max_id : UInt32) (store_words : UInt32) (at_ : UInt32) (end_ : UInt32) (used : UInt32) (empty : Bool) (last : UInt32) : Nat → Option (Array UInt32 × Array UInt32 × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32 × UInt32 × UInt32 × UInt32 × UInt32 × UInt32 × Bool × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (at_ < end_)) && (status == LRAT_ACCEPTED)) then do
      let kind : UInt32 := (words.getD at_.toNat (0 : UInt32))
      let (starts, lengths, alive, store, assign, trail, status, additions, deletions, at_, used, empty, last) ← (if (kind == (1 : UInt32)) then (do
          let r5 ← lrat_fits at_ (3 : UInt32) end_ fuel
          let (alive, status, deletions, at_) ← (if r5 then (do
              let id_ : UInt32 := (words.getD (at_ + (1 : UInt32)).toNat (0 : UInt32))
              let k : UInt32 := (words.getD (at_ + (2 : UInt32)).toNat (0 : UInt32))
              let r6 ← lrat_fits (at_ + (3 : UInt32)) k end_ fuel
              let (alive, status, deletions, at_) ← (if ((r6 && (decide (id_ > (0 : UInt32)))) && (decide (id_ >= last))) then (do
                  let d : UInt32 := (0 : UInt32)
                  let (alive, status, d) ← lrat_check.loop6 words alive status max_id at_ k d fuel
                  let deletions := (deletions + k)
                  let at_ := ((at_ + (3 : UInt32)) + k)
                  pure (alive, status, deletions, at_))
                else (do
                  let status := (if (decide (id_ >= last)) then LRAT_MALFORMED else LRAT_ID_ORDER)
                  pure (alive, status, deletions, at_)))
              pure (alive, status, deletions, at_))
            else (do
              let status := LRAT_MALFORMED
              pure (alive, status, deletions, at_)))
          pure (starts, lengths, alive, store, assign, trail, status, additions, deletions, at_, used, empty, last))
        else (do
          let (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last) ← (if (kind == (0 : UInt32)) then (do
              let r7 ← lrat_fits at_ (3 : UInt32) end_ fuel
              let (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last) ← (if r7 then (do
                  let id_ : UInt32 := (words.getD (at_ + (1 : UInt32)).toNat (0 : UInt32))
                  let n : UInt32 := (words.getD (at_ + (2 : UInt32)).toNat (0 : UInt32))
                  let lits_at : UInt32 := (at_ + (3 : UInt32))
                  let r8 ← lrat_fits lits_at n end_ fuel
                  let shape : Bool := (r8 && (decide ((lits_at + n) < end_)))
                  let m : UInt32 := (if shape then (words.getD (lits_at + n).toNat (0 : UInt32)) else (0 : UInt32))
                  let hints_at : UInt32 := (if shape then ((lits_at + n) + (1 : UInt32)) else (0 : UInt32))
                  let r9 ← lrat_fits hints_at m end_ fuel
                  let shape := (shape && r9)
                  let (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last) ← (if shape then (do
                      let (starts, lengths, alive, store, assign, trail, status, additions, used, empty, last) ← (if ((decide (id_ > last)) && (decide (id_ <= max_id))) then (do
                          let (r10, starts, lengths, alive, store, assign, trail) ← lrat_rup words lits_at n hints_at m starts lengths alive store assign trail variables max_id fuel
                          let status := r10
                          let (starts, lengths, alive, store, status, additions, used, empty, last) ← (if (status == LRAT_ACCEPTED) then (do
                              let r11 ← lrat_fits used n store_words fuel
                              let (starts, lengths, alive, store, status, additions, used, empty, last) ← (if r11 then (do
                                  let starts := starts.setIfInBounds id_.toNat used
                                  let lengths := lengths.setIfInBounds id_.toNat n
                                  let j : UInt32 := (0 : UInt32)
                                  let (store, j) ← lrat_check.loop7 words store used n lits_at j fuel
                                  let used := (used + n)
                                  let alive := alive.setIfInBounds id_.toNat (1 : UInt8)
                                  let last := id_
                                  let additions := (additions + (1 : UInt32))
                                  let empty := (empty || (n == (0 : UInt32)))
                                  pure (starts, lengths, alive, store, status, additions, used, empty, last))
                                else (do
                                  let status := LRAT_CAPACITY
                                  pure (starts, lengths, alive, store, status, additions, used, empty, last)))
                              pure (starts, lengths, alive, store, status, additions, used, empty, last))
                            else (do
                              pure (starts, lengths, alive, store, status, additions, used, empty, last)))
                          pure (starts, lengths, alive, store, assign, trail, status, additions, used, empty, last))
                        else (do
                          let status := LRAT_ID_ORDER
                          pure (starts, lengths, alive, store, assign, trail, status, additions, used, empty, last)))
                      let at_ := (hints_at + m)
                      pure (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last))
                    else (do
                      let status := LRAT_MALFORMED
                      pure (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last)))
                  pure (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last))
                else (do
                  let status := LRAT_MALFORMED
                  pure (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last)))
              pure (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last))
            else (do
              let status := LRAT_MALFORMED
              pure (starts, lengths, alive, store, assign, trail, status, additions, at_, used, empty, last)))
          pure (starts, lengths, alive, store, assign, trail, status, additions, deletions, at_, used, empty, last)))
      lrat_check.loop5 words starts lengths alive store assign trail status additions deletions variables max_id store_words at_ end_ used empty last fuel
    else pure (starts, lengths, alive, store, assign, trail, status, additions, deletions, at_, used, empty, last)

def lrat_check (words : Array UInt32) (starts : Array UInt32) (lengths : Array UInt32) (alive : Array UInt8) (store : Array UInt32) (assign : Array UInt8) (trail : Array UInt32) (out : Array UInt32) (fuel : Nat) : Option (UInt32 × Array UInt32 × Array UInt32 × Array UInt8 × Array UInt32 × Array UInt8 × Array UInt32 × Array UInt32) := do
  let status : UInt32 := LRAT_ACCEPTED
  let additions : UInt32 := (0 : UInt32)
  let deletions : UInt32 := (0 : UInt32)
  let ok : Bool := (((decide ((words.size.toUInt32) >= LRAT_HEADER_WORDS)) && ((words.getD (0 : UInt32).toNat (0 : UInt32)) == LRAT_MAGIC)) && (decide ((out.size.toUInt32) >= (3 : UInt32))))
  let variables : UInt32 := (if ok then (words.getD (1 : UInt32).toNat (0 : UInt32)) else (0 : UInt32))
  let clause_count : UInt32 := (if ok then (words.getD (2 : UInt32).toNat (0 : UInt32)) else (0 : UInt32))
  let literal_words : UInt32 := (if ok then (words.getD (3 : UInt32).toNat (0 : UInt32)) else (0 : UInt32))
  let step_words : UInt32 := (if ok then (words.getD (4 : UInt32).toNat (0 : UInt32)) else (0 : UInt32))
  let max_id : UInt32 := (if ok then (words.getD (5 : UInt32).toNat (0 : UInt32)) else (0 : UInt32))
  let store_words : UInt32 := (if ok then (words.getD (6 : UInt32).toNat (0 : UInt32)) else (0 : UInt32))
  let r1 ← lrat_fits LRAT_HEADER_WORDS literal_words (words.size.toUInt32) fuel
  let ok := (ok && r1)
  let literal_end : UInt32 := (if ok then (LRAT_HEADER_WORDS + literal_words) else (0 : UInt32))
  let r2 ← lrat_fits literal_end step_words (words.size.toUInt32) fuel
  let ok := (ok && r2)
  let ok := (ok && ((literal_end + step_words) == (words.size.toUInt32)))
  let ok := (((ok && (decide ((starts.size.toUInt32) > max_id))) && (decide ((lengths.size.toUInt32) > max_id))) && (decide ((alive.size.toUInt32) > max_id)))
  let ok := (((ok && (decide ((store.size.toUInt32) >= store_words))) && (decide ((assign.size.toUInt32) >= variables))) && (decide ((trail.size.toUInt32) >= variables)))
  let ok := (ok && (decide (clause_count <= max_id)))
  let status := (if ok then LRAT_ACCEPTED else LRAT_CAPACITY)
  let i : UInt32 := (0 : UInt32)
  let (alive, i) ← lrat_check.loop1 alive ok max_id i fuel
  let i := (0 : UInt32)
  let (assign, i) ← lrat_check.loop2 assign ok variables i fuel
  let at_ : UInt32 := LRAT_HEADER_WORDS
  let end_ : UInt32 := literal_end
  let used : UInt32 := (0 : UInt32)
  let empty : Bool := false
  let c : UInt32 := (1 : UInt32)
  let (starts, lengths, alive, store, status, at_, used, empty, c) ← lrat_check.loop3 words starts lengths alive store status variables clause_count store_words at_ end_ used empty c fuel
  let status ← (if ((status == LRAT_ACCEPTED) && (at_ != end_)) then (do
      let status := LRAT_MALFORMED
      pure status)
    else (do
      pure status))
  let last : UInt32 := clause_count
  let at_ := end_
  let end_ := (if ok then (end_ + step_words) else (0 : UInt32))
  let (starts, lengths, alive, store, assign, trail, status, additions, deletions, at_, used, empty, last) ← lrat_check.loop5 words starts lengths alive store assign trail status additions deletions variables max_id store_words at_ end_ used empty last fuel
  let status ← (if ((status == LRAT_ACCEPTED) && (!empty)) then (do
      let status := LRAT_NO_EMPTY
      pure status)
    else (do
      pure status))
  let out ← (if (decide ((out.size.toUInt32) >= (3 : UInt32))) then (do
      let out := out.setIfInBounds (0 : UInt32).toNat status
      let out := out.setIfInBounds (1 : UInt32).toNat additions
      let out := out.setIfInBounds (2 : UInt32).toNat deletions
      pure out)
    else (do
      pure out))
  pure (status, starts, lengths, alive, store, assign, trail, out)

end Oak.LRATChecker
