-- Generated by the Oak compiler (codegen/lean): do not edit.
-- Extracted from the type-checked program; docs/spec/95-extraction.md
-- states the translation and its modeling choices.

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxRecDepth 65536
set_option maxHeartbeats 4000000
namespace Oak.WasmAssembler

structure WasmInstruction where
  opcode : UInt32
  immediate : Int64
  deriving Repr, BEq, DecidableEq
instance : Inhabited WasmInstruction := ⟨{ opcode := (0 : UInt32), immediate := (0 : Int64) }⟩

structure WasmAssembly where
  status : UInt32
  size : UInt32
  deriving Repr, BEq, DecidableEq
instance : Inhabited WasmAssembly := ⟨{ status := (0 : UInt32), size := (0 : UInt32) }⟩

def wasm_signed_next (value : Int64) (fuel : Nat) : Option (Int64) := do
  let q : Int64 := (value / (128 : Int64))
  pure (if ((decide (value < (0 : Int64))) && ((value % (128 : Int64)) != (0 : Int64))) then (q - (1 : Int64)) else q)

def wasm_uleb_size.loop1 (v : UInt64) (size : UInt32) : Nat → Option (UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (v >= (128 : UInt64))) then do
      let v := (v >>> (7 : UInt64))
      let size := (size + (1 : UInt32))
      wasm_uleb_size.loop1 v size fuel
    else pure (v, size)

def wasm_uleb_size (value : UInt64) (fuel : Nat) : Option (UInt32) := do
  let v : UInt64 := value
  let size : UInt32 := (1 : UInt32)
  let (v, size) ← wasm_uleb_size.loop1 v size fuel
  pure size

def wasm_sleb_size.loop1 (v : Int64) (size : UInt32) : Nat → Option (Int64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if ((decide (v < (0 - (64 : Int64)))) || (decide (v >= (64 : Int64)))) then do
      let r1 ← wasm_signed_next v fuel
      let v := r1
      let size := (size + (1 : UInt32))
      wasm_sleb_size.loop1 v size fuel
    else pure (v, size)

def wasm_sleb_size (value : Int64) (fuel : Nat) : Option (UInt32) := do
  let v : Int64 := value
  let size : UInt32 := (1 : UInt32)
  let (v, size) ← wasm_sleb_size.loop1 v size fuel
  pure size

def wasm_write_uleb.loop1 (dst : Array UInt8) (offset : UInt32) (size : UInt32) (v : UInt64) (i : UInt32) : Nat → Option (Array UInt8 × UInt64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < size)) then do
      let b : UInt32 := ((v &&& (127 : UInt64)).toUInt32)
      let b ← (if (decide ((i + (1 : UInt32)) < size)) then (do
          let b := (b ||| (128 : UInt32))
          pure b)
        else (do
          pure b))
      let dst := dst.setIfInBounds (offset + i).toNat (b.toUInt8)
      let v := (v >>> (7 : UInt64))
      let i := (i + (1 : UInt32))
      wasm_write_uleb.loop1 dst offset size v i fuel
    else pure (dst, v, i)

def wasm_write_uleb (dst : Array UInt8) (offset : UInt32) (value : UInt64) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let r1 ← wasm_uleb_size value fuel
  let size : UInt32 := r1
  let result : UInt32 := (0 : UInt32)
  let (dst, result) ← (if ((decide (offset <= (dst.size.toUInt32))) && (decide (size <= ((dst.size.toUInt32) - offset)))) then (do
      let v : UInt64 := value
      let i : UInt32 := (0 : UInt32)
      let (dst, v, i) ← wasm_write_uleb.loop1 dst offset size v i fuel
      let result := size
      pure (dst, result))
    else (do
      pure (dst, result)))
  pure (result, dst)

def wasm_write_sleb.loop1 (dst : Array UInt8) (offset : UInt32) (size : UInt32) (v : Int64) (i : UInt32) : Nat → Option (Array UInt8 × Int64 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < size)) then do
      let b : UInt32 := (((v.toUInt64) &&& (127 : UInt64)).toUInt32)
      let b ← (if (decide ((i + (1 : UInt32)) < size)) then (do
          let b := (b ||| (128 : UInt32))
          pure b)
        else (do
          pure b))
      let dst := dst.setIfInBounds (offset + i).toNat (b.toUInt8)
      let r2 ← wasm_signed_next v fuel
      let v := r2
      let i := (i + (1 : UInt32))
      wasm_write_sleb.loop1 dst offset size v i fuel
    else pure (dst, v, i)

def wasm_write_sleb (dst : Array UInt8) (offset : UInt32) (value : Int64) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let r1 ← wasm_sleb_size value fuel
  let size : UInt32 := r1
  let result : UInt32 := (0 : UInt32)
  let (dst, result) ← (if ((decide (offset <= (dst.size.toUInt32))) && (decide (size <= ((dst.size.toUInt32) - offset)))) then (do
      let v : Int64 := value
      let i : UInt32 := (0 : UInt32)
      let (dst, v, i) ← wasm_write_sleb.loop1 dst offset size v i fuel
      let result := size
      pure (dst, result))
    else (do
      pure (dst, result)))
  pure (result, dst)

def wasm_instruction_kind (op : UInt32) (fuel : Nat) : Option (UInt32) := do
  let result : UInt32 := (0 : UInt32)
  let result ← (if (((op == (2 : UInt32)) || (op == (3 : UInt32))) || (op == (4 : UInt32))) then (do
      let result := (2 : UInt32)
      pure result)
    else (do
      let result ← (if ((((((op == (12 : UInt32)) || (op == (13 : UInt32))) || (op == (16 : UInt32))) || (op == (32 : UInt32))) || (op == (33 : UInt32))) || (op == (34 : UInt32))) then (do
          let result := (3 : UInt32)
          pure result)
        else (do
          let result ← (if (op == (65 : UInt32)) then (do
              let result := (4 : UInt32)
              pure result)
            else (do
              let result ← (if (op == (66 : UInt32)) then (do
                  let result := (5 : UInt32)
                  pure result)
                else (do
                  let result ← (if ((((((((((op == (0 : UInt32)) || (op == (1 : UInt32))) || (op == (5 : UInt32))) || (op == (11 : UInt32))) || (op == (15 : UInt32))) || (op == (26 : UInt32))) || ((decide (op >= (69 : UInt32))) && (decide (op <= (79 : UInt32))))) || ((decide (op >= (81 : UInt32))) && (decide (op <= (90 : UInt32))))) || ((decide (op >= (106 : UInt32))) && (decide (op <= (115 : UInt32))))) || ((decide (op >= (124 : UInt32))) && (decide (op <= (133 : UInt32))))) then (do
                      let result := (1 : UInt32)
                      pure result)
                    else (do
                      pure result))
                  pure result))
              pure result))
          pure result))
      pure result))
  pure result

def wasm_instruction_size (instruction : WasmInstruction) (fuel : Nat) : Option (UInt32) := do
  let r1 ← wasm_instruction_kind instruction.opcode fuel
  let kind : UInt32 := r1
  let v : Int64 := instruction.immediate
  let size : UInt32 := (0 : UInt32)
  let size ← (if ((kind == (1 : UInt32)) && (v == (0 : Int64))) then (do
      let size := (1 : UInt32)
      pure size)
    else (do
      pure size))
  let size ← (if ((kind == (2 : UInt32)) && (((v == (64 : Int64)) || (v == (127 : Int64))) || (v == (126 : Int64)))) then (do
      let size := (2 : UInt32)
      pure size)
    else (do
      pure size))
  let size ← (if (((kind == (3 : UInt32)) && (decide (v >= (0 : Int64)))) && (decide (v <= (4294967295 : Int64)))) then (do
      let r2 ← wasm_uleb_size (v.toUInt64) fuel
      let size := ((1 : UInt32) + r2)
      pure size)
    else (do
      pure size))
  let size ← (if ((((kind == (4 : UInt32)) && (decide (v >= (0 - (2147483648 : Int64))))) && (decide (v <= (2147483647 : Int64)))) || (kind == (5 : UInt32))) then (do
      let r3 ← wasm_sleb_size v fuel
      let size := ((1 : UInt32) + r3)
      pure size)
    else (do
      pure size))
  pure size

def wasm_write_instruction (dst : Array UInt8) (offset : UInt32) (instruction : WasmInstruction) (fuel : Nat) : Option (UInt32 × Array UInt8) := do
  let r1 ← wasm_instruction_size instruction fuel
  let size : UInt32 := r1
  let result : UInt32 := (0 : UInt32)
  let (dst, result) ← (if (((size != (0 : UInt32)) && (decide (offset <= (dst.size.toUInt32)))) && (decide (size <= ((dst.size.toUInt32) - offset)))) then (do
      let r2 ← wasm_instruction_kind instruction.opcode fuel
      let kind : UInt32 := r2
      let dst := dst.setIfInBounds offset.toNat (instruction.opcode.toUInt8)
      let dst ← (if (kind == (2 : UInt32)) then (do
          let dst := dst.setIfInBounds (offset + (1 : UInt32)).toNat (((instruction.immediate.toUInt64).toUInt32).toUInt8)
          pure dst)
        else (do
          pure dst))
      let dst ← (if (kind == (3 : UInt32)) then (do
          let (r3, dst) ← wasm_write_uleb dst (offset + (1 : UInt32)) (instruction.immediate.toUInt64) fuel
          pure dst)
        else (do
          pure dst))
      let dst ← (if ((kind == (4 : UInt32)) || (kind == (5 : UInt32))) then (do
          let (r4, dst) ← wasm_write_sleb dst (offset + (1 : UInt32)) instruction.immediate fuel
          pure dst)
        else (do
          pure dst))
      let result := size
      pure (dst, result))
    else (do
      pure (dst, result)))
  pure (result, dst)

def wasm_assemble.loop1 (dst : Array UInt8) (offset : UInt32) (plan : Array WasmInstruction) (total : UInt32) (i : UInt32) (ok : Bool) : Nat → Option (UInt32 × UInt32 × Bool)
  | 0 => none
  | fuel + 1 => do
    if ((decide (i < (plan.size.toUInt32))) && ok) then do
      let r1 ← wasm_instruction_size (plan.getD i.toNat (default : WasmInstruction)) fuel
      let size : UInt32 := r1
      let (total, ok) ← (if ((size != (0 : UInt32)) && (decide (size <= (((dst.size.toUInt32) - offset) - total)))) then (do
          let total := (total + size)
          pure (total, ok))
        else (do
          let ok := false
          pure (total, ok)))
      let i := (i + (1 : UInt32))
      wasm_assemble.loop1 dst offset plan total i ok fuel
    else pure (total, i, ok)

def wasm_assemble.loop2 (dst : Array UInt8) (plan : Array WasmInstruction) (i : UInt32) (pos : UInt32) : Nat → Option (Array UInt8 × UInt32 × UInt32)
  | 0 => none
  | fuel + 1 => do
    if (decide (i < (plan.size.toUInt32))) then do
      let (r3, dst) ← wasm_write_instruction dst pos (plan.getD i.toNat (default : WasmInstruction)) fuel
      let size : UInt32 := r3
      let pos := (pos + size)
      let i := (i + (1 : UInt32))
      wasm_assemble.loop2 dst plan i pos fuel
    else pure (dst, i, pos)

def wasm_assemble (dst : Array UInt8) (offset : UInt32) (plan : Array WasmInstruction) (fuel : Nat) : Option (WasmAssembly × Array UInt8) := do
  let total : UInt32 := (0 : UInt32)
  let i : UInt32 := (0 : UInt32)
  let ok : Bool := (decide (offset <= (dst.size.toUInt32)))
  let (total, i, ok) ← wasm_assemble.loop1 dst offset plan total i ok fuel
  let (r2, dst, i) ← (
    if ok then (do
      let i := (0 : UInt32)
      let pos : UInt32 := offset
      let (dst, i, pos) ← wasm_assemble.loop2 dst plan i pos fuel
      pure (({ status := (0 : UInt32), size := total } : WasmAssembly), dst, i))
    else (do
      pure (({ status := (1 : UInt32), size := (0 : UInt32) } : WasmAssembly), dst, i)))
  pure (r2, dst)

end Oak.WasmAssembler
