// Command riscvgen generates asm/rv64_encodings_gen.go from riscv-opcodes
// (docs/spec/94-assembler.md §9, the RISC-V lane): for every instruction of
// the RV64IM base the fixed bits, their values, and the argument fields by
// name from arg_lut.csv. Run from the repository root with the checkout
// under external/riscv-opcodes; only derived facts are written.
package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type field struct {
	Name   string
	Hi, Lo int
}

type encoding struct {
	Mnemonic string
	Mask     uint32
	Value    uint32
	Args     []field
	Source   string
}

func main() {
	root := "external/riscv-opcodes"
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	luts, err := readArgLut(filepath.Join(root, "arg_lut.csv"))
	if err != nil {
		fail(err)
	}
	var encodings []encoding
	for _, file := range []string{"rv_i", "rv64_i", "rv_m", "rv64_m", "rv_f", "rv64_f", "rv_d", "rv64_d"} {
		parsed, err := readExtension(filepath.Join(root, "extensions", file), file, luts)
		if err != nil {
			fail(err)
		}
		encodings = append(encodings, parsed...)
	}
	sort.SliceStable(encodings, func(i, j int) bool { return encodings[i].Mnemonic < encodings[j].Mnemonic })
	commit := "unknown"
	if out, err := exec.Command("git", "-C", root, "rev-parse", "--short", "HEAD").Output(); err == nil {
		commit = strings.TrimSpace(string(out))
	}
	var b strings.Builder
	b.WriteString("// Code generated by asm/internal/riscvgen from riscv-opcodes; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: riscv/riscv-opcodes %s, extensions rv_i, rv64_i, rv_m, rv64_m, rv_f, rv64_f, rv_d, rv64_d.\n\n", commit)
	b.WriteString("package asm\n\n")
	b.WriteString("var rv64Encodings = []rv64Encoding{\n")
	for _, e := range encodings {
		fmt.Fprintf(&b, "\t{Mnemonic: %q, Mask: 0x%08x, Value: 0x%08x, Args: []rv64Arg{", e.Mnemonic, e.Mask, e.Value)
		for i, a := range e.Args {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "{%q, %d, %d}", a.Name, a.Hi, a.Lo)
		}
		fmt.Fprintf(&b, "}, Source: %q},\n", e.Source)
	}
	b.WriteString("}\n")
	if err := os.WriteFile("asm/rv64_encodings_gen.go", []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %d encodings\n", len(encodings))
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "riscvgen:", err)
	os.Exit(1)
}

// readArgLut reads `"name", hi, lo` rows.
func readArgLut(path string) (map[string]field, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	out := map[string]field{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		parts := strings.Split(scanner.Text(), ",")
		if len(parts) != 3 {
			continue
		}
		name := strings.Trim(strings.TrimSpace(parts[0]), "\"")
		hi, err1 := strconv.Atoi(strings.TrimSpace(parts[1]))
		lo, err2 := strconv.Atoi(strings.TrimSpace(parts[2]))
		if err1 != nil || err2 != nil {
			continue
		}
		out[name] = field{Name: name, Hi: hi, Lo: lo}
	}
	return out, scanner.Err()
}

// readExtension reads one `extensions/rv_*` file: `mnemonic args... fixed`
// lines, where an argument names an arg_lut field and a fixed field is
// `hi..lo=value` or `bit=value`. `$pseudo_op` and `$import` lines are
// skipped: pseudo-instructions are the assembler's, spelled in asm/rv64.go.
func readExtension(path, source string, luts map[string]field) ([]encoding, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var out []encoding
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "$") {
			continue
		}
		fields := strings.Fields(line)
		e := encoding{Mnemonic: fields[0], Source: source}
		for _, tok := range fields[1:] {
			if strings.Contains(tok, "=") {
				lhs, rhs, _ := strings.Cut(tok, "=")
				value, err := strconv.ParseUint(strings.TrimPrefix(rhs, "0x"), map[bool]int{true: 16, false: 10}[strings.HasPrefix(rhs, "0x")], 64)
				if err != nil {
					return nil, fmt.Errorf("%s: %s: bad fixed field %q", path, fields[0], tok)
				}
				hi, lo := 0, 0
				if a, b, isRange := strings.Cut(lhs, ".."); isRange {
					hi, _ = strconv.Atoi(a)
					lo, _ = strconv.Atoi(b)
				} else {
					hi, _ = strconv.Atoi(lhs)
					lo = hi
				}
				width := hi - lo + 1
				mask := uint32((uint64(1)<<uint(width) - 1) << uint(lo))
				e.Mask |= mask
				e.Value |= uint32(value<<uint(lo)) & mask
				continue
			}
			lut, known := luts[tok]
			if !known {
				return nil, fmt.Errorf("%s: %s: unknown argument %q", path, fields[0], tok)
			}
			e.Args = append(e.Args, lut)
		}
		out = append(out, e)
	}
	return out, scanner.Err()
}
